Repository elastic/elastic-agent, pull requests merged in 2022-08, with the labels that each got.

#820 [automation] update elastic stack version for testing 8.4.0-d88c8a44
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#776 Fix unpacking of artifact config
  internal/pkg/agent/application/local_mode.go
  internal/pkg/artifact/config.go
  internal/pkg/artifact/config_test.go
  internal/pkg/artifact/download/snapshot/downloader.go
Labels: bug, Team:Elastic-Agent-Control-Plane, backport-skip, v8.5.0

#825 [automation] update elastic stack version for testing 8.4.0-5954f776
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#826 [automation] update elastic stack version for testing 8.5.0-c54c3404
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#827 [automation] update elastic stack version for testing 8.3.4-9c50d4cb
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#833 [automation] update elastic stack version for testing 8.5.0-7dbc10f8
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#805 [v2] Fix inspect command
  internal/pkg/agent/application/application.go
  internal/pkg/agent/application/once.go
  internal/pkg/agent/application/paths/common.go
  internal/pkg/agent/application/periodic.go
  internal/pkg/agent/cmd/diagnostics.go
  internal/pkg/agent/cmd/inspect.go
  internal/pkg/agent/cmd/inspect_test.go
  internal/pkg/agent/configuration/settings.go
  internal/pkg/agent/install/uninstall.go
  internal/pkg/composable/controller.go
  internal/pkg/config/discover.go
  internal/pkg/config/operations/inspector.go
  pkg/component/component.go
  pkg/component/error.go
  pkg/component/load.go
Labels: Team:Elastic-Agent-Control-Plane

#816 Fix RPM/DEB clean install
  dev-tools/packaging/templates/linux/postinstall.sh.tmpl
Labels: bug, Team:Elastic-Agent-Control-Plane, backport-v8.3.0, backport-v8.4.0

#844 [automation] update elastic stack version for testing 8.3.4-a15c6beb
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#852 [automation] update elastic stack version for testing 8.4.0-b5074ef3
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#853 [automation] update elastic stack version for testing 8.3.4-ce266bfe
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#859 fix path for auto generated spec file
  dev-tools/cmd/buildspec/buildspec.go
  internal/pkg/agent/program/supported.go
Labels: bug, backport-skip

#862 [automation] update elastic stack version for testing 8.4.0-43c061d1
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#863 [automation] update elastic stack version for testing 8.3.4-73c9af3c
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#848 Reload downloader client on config change
  internal/pkg/agent/application/local_mode.go
  internal/pkg/agent/application/managed_mode.go
  internal/pkg/agent/application/pipeline/emitter/controller.go
  internal/pkg/agent/application/pipeline/emitter/emitter.go
  internal/pkg/agent/application/pipeline/router/router.go
  internal/pkg/agent/application/pipeline/stream/operator_stream.go
  internal/pkg/agent/operation/operator.go
  internal/pkg/artifact/config.go
  internal/pkg/artifact/download/composed/downloader.go
  internal/pkg/artifact/download/composed/verifier.go
  internal/pkg/artifact/download/http/downloader.go
  internal/pkg/artifact/download/http/verifier.go
  internal/pkg/artifact/download/reloadable.go
  internal/pkg/artifact/download/snapshot/downloader.go
  internal/pkg/artifact/download/snapshot/verifier.go
Labels: bug, Team:Elastic-Agent-Control-Plane, backport-v8.4.0, backport-v8.5.0

#874 [automation] update elastic stack version for testing 8.3.4-9c6c318b
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#873 [automation] update elastic stack version for testing 8.4.0-4b3e8f6e
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#714 Bundle elastic-agent.app for MacOS, needed to be able to enable the …
  dev-tools/packaging/files/darwin/PkgInfo
  dev-tools/packaging/packages.yml
  dev-tools/packaging/templates/darwin/Info.plist.tmpl
  internal/pkg/agent/application/info/state.go
  internal/pkg/agent/application/info/state_test.go
  internal/pkg/agent/application/paths/common.go
  internal/pkg/agent/install/install.go
Labels: enhancement, Team:Elastic-Agent-Control-Plane, Team:Asset Mgt, 8.5-candidate, v8.5.0, backport-v8.5.0

#880 [automation] update elastic stack version for testing 8.3.4-fd43be48
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#881 [automation] update elastic stack version for testing 8.4.0-96568c7b
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#868 [8.4](backport #848) Reload downloader client on config change
  internal/pkg/agent/application/local_mode.go
  internal/pkg/agent/application/managed_mode.go
  internal/pkg/agent/application/pipeline/emitter/controller.go
  internal/pkg/agent/application/pipeline/emitter/emitter.go
  internal/pkg/agent/application/pipeline/router/router.go
  internal/pkg/agent/application/pipeline/stream/operator_stream.go
  internal/pkg/agent/operation/operator.go
  internal/pkg/artifact/config.go
  internal/pkg/artifact/config_test.go
  internal/pkg/artifact/download/composed/downloader.go
  internal/pkg/artifact/download/composed/verifier.go
  internal/pkg/artifact/download/http/downloader.go
  internal/pkg/artifact/download/http/verifier.go
  internal/pkg/artifact/download/reloadable.go
  internal/pkg/artifact/download/snapshot/downloader.go
  internal/pkg/artifact/download/snapshot/verifier.go
Labels: Team:Elastic-Agent-Control-Plane, v8.4.0, backport

#856 crossbuild: add fix to set ulimit for debian images
  dev-tools/mage/crossbuild.go
Labels: bug, Team:Elastic-Agent-Data-Plane, backport, backport-v8.4.0, backport-v8.5.0

#764 [Heartbeat] Cleanup docker install / always add playwright deps
  dev-tools/packaging/templates/docker/Dockerfile.elastic-agent.tmpl
Labels: enhancement, Team:Uptime, backport-skip

#888 [automation] update elastic stack version for testing 8.4.0-9adc8090
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#889 [automation] update elastic stack version for testing 8.5.0-41aadc32
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#890 [automation] update elastic stack version for testing 8.3.4-b4aa6143
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#823 Fix/panic with composable renderer
  CHANGELOG.next.asciidoc
  internal/pkg/agent/install/uninstall.go
Labels: Team:Elastic-Agent-Control-Plane, ci:end-to-end, backport-v8.4.0, backport-v8.5.0

#832 [automation] Update go release version 1.18.5
  .go-version
  Dockerfile
  version/docs/version.asciidoc
Labels: automation, dependency, backport-skip

#900 [automation] update elastic stack version for testing 8.4.0-c17572db
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#899 [automation] update elastic stack version for testing 8.5.0-60a4c029
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#901 [automation] update elastic stack version for testing 8.3.4-a5e24e15
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#864 Add control-plane toleration to Agent K8S manifests.
  deploy/kubernetes/elastic-agent-managed-kubernetes.yaml
  deploy/kubernetes/elastic-agent-managed/elastic-agent-managed-daemonset.yaml
  deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml
  deploy/kubernetes/elastic-agent-standalone/elastic-agent-standalone-daemonset.yaml
Labels: bug, backport-v8.3.0, backport-v8.4.0, backport-v8.5.0

#912 [automation] update elastic stack version for testing 8.3.4-adc3e57f
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#920 [automation] update elastic stack version for testing 8.4.0-fea9abbe
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#919 [automation] update elastic stack version for testing 8.3.4-6d6eaf28
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#928 [automation] update elastic stack version for testing 8.3.4-58ddca7b
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#927 [automation] update elastic stack version for testing 8.4.0-9bd354a1
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#916 Expand check-in payload for V2
  internal/pkg/agent/application/gateway/fleet/fleet_gateway.go
  internal/pkg/fleetapi/checkin_cmd.go
Labels: enhancement

#934 [automation] update elastic stack version for testing 8.4.0-aff0df12
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#936 install mage with go install
  Makefile
Labels: backport-v8.4.0

#837 Cloudnative ci automation
  .ci/Jenkinsfile
  deploy/kubernetes/Makefile
  deploy/kubernetes/creator_k8s_manifest.sh
  deploy/kubernetes/elastic-agent-managed-kubernetes.yaml
  deploy/kubernetes/elastic-agent-managed/elastic-agent-managed-daemonset.yaml
  deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml
  deploy/kubernetes/elastic-agent-standalone/elastic-agent-standalone-daemonset-configmap.yaml
  deploy/kubernetes/elastic-agent-standalone/elastic-agent-standalone-daemonset.yaml
Labels: backport-skip

#804 Reduce memory footprint by reordering struct elements
  internal/pkg/agent/application/pipeline/actions/handlers/handler_action_unenroll.go
  internal/pkg/agent/application/upgrade/upgrade.go
  internal/pkg/agent/operation/operation_retryable.go
  internal/pkg/agent/stateresolver/resolve.go
  internal/pkg/composable/providers/kubernetes/pod.go
  internal/pkg/composable/providers/kubernetesleaderelection/config.go
  internal/pkg/core/plugin/process/app.go
  internal/pkg/core/state/state.go
  internal/pkg/core/status/reporter.go
  internal/pkg/crypto/io.go
  internal/pkg/fleetapi/acker/retrier/retrier.go
  internal/pkg/reporter/fleet/reporter.go
Labels: enhancement, Team:Elastic-Agent, backport-v8.5.0

#947 [automation] update elastic stack version for testing 8.3.4-e23a59c6
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#948 [automation] update elastic stack version for testing 8.5.0-6b9f92c0
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#946 [automation] update elastic stack version for testing 8.4.0-b95305c2
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#850 [v2] Update protocol to use new UnitExpectedConfig.
  NOTICE.txt
  go.mod
  go.sum
  internal/pkg/agent/application/actions/handlers/handler_action_application.go
  pkg/component/component.go
  pkg/component/component_test.go
  pkg/component/config.go
  pkg/component/config_test.go
  pkg/component/fake/main.go
  pkg/component/runtime/command.go
  pkg/component/runtime/manager_test.go
  pkg/component/runtime/runtime.go
  pkg/component/runtime/state.go
Labels: Team:Elastic-Agent-Control-Plane

#964 [automation] update elastic stack version for testing 8.4.0-910fe5e1
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#962 [automation] update elastic stack version for testing 8.3.4-70c0b53c
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#963 [automation] update elastic stack version for testing 8.5.0-0616acda
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#969 Clarify that this repo is not only docs
  README.md
Labels: backport-skip, docs

#959 Add Filebeat lumberjack input to spec
  CHANGELOG.next.asciidoc
  internal/pkg/agent/program/supported.go
  internal/spec/filebeat.yml
Labels: backport-skip

#977 [automation] update elastic stack version for testing 8.4.0-7f4eb04b
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#979 [automation] update elastic stack version for testing 8.3.4-45336fec
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#978 [automation] update elastic stack version for testing 8.5.0-dd6f2bb0
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#987 [automation] update elastic stack version for testing 8.4.0-fa661330
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#988 [automation] update elastic stack version for testing 8.5.0-feb644de
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#986 [automation] update elastic stack version for testing 8.3.4-97a7bb79
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#785 [Release] Update version to 8.4.1
  version/version.go
Labels: Team:Automation, release

#973 Fix action dispatching that was using ActionType instead of InputType as before
  internal/pkg/agent/application/actions/handlers/handler_action_application.go
Labels: bug, Team:Elastic-Agent-Control-Plane

#786 [Release] Update test environments for 8.4.1
  testing/environments/latest.yml
Labels: Team:Automation, release

#1004 [automation] update elastic stack version for testing 8.5.0-7783a03c
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1003 [automation] update elastic stack version for testing 8.3.4-5621f166
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1015 [automation] update elastic stack version for testing 8.4.1-74c5d538
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1013 [automation] update elastic stack version for testing 8.3.4-22a90cba
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1014 [automation] update elastic stack version for testing 8.5.0-17b8a62d
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1009 update ironbank image product name
  dev-tools/packaging/templates/ironbank/hardening_manifest.yaml.tmpl
Labels: backport-v8.4.0

#683 ci: add extended support for windows
  .ci/Jenkinsfile
Labels: Team:Automation, automation, backport-v8.4.0, ci:extended-windows

#1030 [automation] update elastic stack version for testing 8.5.0-9aed3b11
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1010 Fix bootstrapping a Fleet Server with v2.
  internal/pkg/agent/application/application.go
  internal/pkg/agent/application/coordinator/coordinator.go
  internal/pkg/agent/application/fleet_server_bootstrap.go
  internal/pkg/agent/application/fleet_server_bootstrap_test.go
  internal/pkg/agent/application/managed_mode.go
  internal/pkg/agent/cmd/run.go
  internal/pkg/testutils/testutils.go
  pkg/component/component_test.go
  pkg/component/runtime/manager.go
  pkg/component/runtime/manager_test.go
  pkg/component/runtime/runtime.go
  pkg/component/runtime/runtime_comm.go
  pkg/component/runtime/state.go
  specs/fleet-server.spec.yml
Labels: Team:Elastic-Agent-Control-Plane

#1042 [automation] update elastic stack version for testing 8.4.1-b72ec52c
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1035 Cloudnative ci utomation
  .ci/Jenkinsfile
  deploy/kubernetes/Makefile
  deploy/kubernetes/creator_k8s_manifest.sh
  deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml
  deploy/kubernetes/elastic-agent-standalone/elastic-agent-standalone-daemonset-configmap.yaml
Labels: backport-skip

#1045 Query just related files on build
  magefile.go
Labels: bug, Team:Elastic-Agent-Control-Plane, V2-Architecture

#998 docs: update docs versions 8.4.1
  deploy/kubernetes/elastic-agent-managed-kubernetes.yaml
  deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml
  version/docs/version.asciidoc
Labels: Team:Automation, release, docs, in progress

#1054 [automation] update elastic stack version for testing 8.5.0-fedc3e60
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1049 Testing PR creation for 706
  deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml
  deploy/kubernetes/elastic-agent-standalone/elastic-agent-standalone-daemonset-configmap.yaml
  deploy/kubernetes/elastic-agent-standalone/elastic-agent-standalone-daemonset.yaml
Labels: backport-skip

#840 Fix lookup issues with inputs.d fragment yml
  CHANGELOG.next.asciidoc
  internal/pkg/agent/application/local_mode.go
  internal/pkg/agent/application/paths/files.go
  internal/pkg/agent/configuration/settings.go
Labels: Team:Elastic-Agent-Control-Plane, backport-v8.5.0

#1000 [Release] Update test environments for 8.4.2
  testing/environments/latest.yml
Labels: Team:Automation, release
