Repository elastic/elastic-agent, pull requests merged in 2022-05, with the labels that each got.

#395 [automation] update elastic stack version for testing 8.2.0-e7ad9ef0
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#400 [automation] update elastic stack version for testing 8.2.0-56396fd0
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#399 [automation] update elastic stack version for testing 8.3.0-0b6ea9f2
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#401 [automation] update elastic stack version for testing 8.3.0-7f585873
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#267 update 8.2.1
  version/version.go
Labels: Team:Elastic-Agent-Control-Plane

#406 [automation] update elastic stack version for testing 8.3.0-a1c5cfff
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#410 [automation] update elastic stack version for testing 8.3.0-6ba9f710
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#413 [automation] update elastic stack version for testing 8.3.0-5c1ff35f
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#414 [automation] update elastic stack version for testing 8.3.0-d380914f
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#397 Create snyk-scan.yml
  .github/workflows/snyk-scan.yml
Labels: backport-skip

#381 add missing kube-api resources from managed agent manifest
  deploy/kubernetes/elastic-agent-managed-kubernetes.yaml
  deploy/kubernetes/elastic-agent-managed/elastic-agent-managed-role.yaml
  deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml
  deploy/kubernetes/elastic-agent-standalone/elastic-agent-standalone-role.yaml
Labels: Team:Elastic-Agent-Control-Plane, backport-skip

#417 validate kubernetes templates in .CI
  Makefile
  deploy/kubernetes/Makefile
  deploy/kubernetes/elastic-agent-managed-kubernetes.yaml
  deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml
  version/docs/version.asciidoc
Labels: Team:Elastic-Agent-Control-Plane, backport-v8.2.0

#336 Add tags option during enroll/install
  internal/pkg/agent/cmd/container.go
  internal/pkg/agent/cmd/enroll.go
  internal/pkg/agent/cmd/enroll_cmd.go
  internal/pkg/agent/cmd/enroll_cmd_test.go
  internal/pkg/fleetapi/enroll_cmd.go
Labels: Team:Elastic-Agent-Control-Plane, v8.3.0, ci:end-to-end, backport-skip

#421 [automation] update elastic stack version for testing 8.3.0-53513548
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#420 [automation] update elastic stack version for testing 8.2.1-2eb01953
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#422 [automation] update elastic stack version for testing 8.3.0-8ee1196f
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#423 [automation] update elastic stack version for testing 8.2.1-91d7a53f
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#430 [automation] update elastic stack version for testing 8.3.0-19aba912
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#429 [automation] update elastic stack version for testing 8.2.1-3d12787c
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#435 [automation] update elastic stack version for testing 8.3.0-4149272f
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#434 [automation] update elastic stack version for testing 8.2.1-736d131e
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#439 [automation] update elastic stack version for testing 8.2.1-8d9ffca9
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#432 [automation] Update go release version 1.17.10
  .go-version
  Dockerfile
  version/docs/version.asciidoc
Labels: automation, dependency, backport-skip

#447 [automation] update elastic stack version for testing 8.3.0-a55286cc
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#448 [automation] update elastic stack version for testing 8.2.1-93582d09
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#441 Revert changes requiring CGO and disable CGO for linting on darwin
  .github/workflows/golangci-lint.yml
  .github/workflows/macos.yml
  NOTICE.txt
  go.mod
  go.sum
  internal/pkg/agent/cmd/metrics.go
  internal/pkg/agent/cmd/platformcheck_test.go
  internal/pkg/agent/cmd/run.go
  internal/pkg/agent/cmd/watch.go
Labels: backport-skip

#433 Initialize logger directory to allow group access
  internal/pkg/agent/cmd/container.go
  pkg/core/logger/logger.go
Labels: bug, Team:Uptime, backport-v8.2.0

#453 [automation] update elastic stack version for testing 8.2.1-54274789
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#438 Fix disable optimizations and inlining for debug
  dev-tools/mage/build.go
Labels: enhancement, v8.3.0, 8.3-candidate, backport-v8.2.0

#450 Incorrect use of errors.As
  internal/pkg/fleetapi/enroll_cmd.go
Labels: Team:Elastic-Agent-Control-Plane, ci:end-to-end, backport-skip

#444 ci: use orka workers
  .ci/Jenkinsfile
  .github/workflows/macos.yml
Labels: Team:Automation, automation, backport-v8.2.0, backport-v8.3.0

#446 Update agent-complete node version to 16.15.0
  CHANGELOG.next.asciidoc
  dev-tools/packaging/templates/docker/Dockerfile.elastic-agent.tmpl
  dev-tools/packaging/templates/docker/Dockerfile.tmpl
Labels: enhancement, backport-skip

#462 [automation] update elastic stack version for testing 8.3.0-3a5a0cd2
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#463 [automation] update elastic stack version for testing 8.2.1-539cf6f5
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#455 Collect process (beats) stdout and stderr
  CHANGELOG.next.asciidoc
  internal/pkg/agent/control/client/client.go
  internal/pkg/core/plugin/process/configure.go
  internal/pkg/core/plugin/process/start.go
  internal/pkg/core/plugin/process/stdlogger.go
  internal/pkg/core/plugin/process/stdlogger_test.go
  pkg/core/logger/logger_test.go
  pkg/core/logger/testing.go
Labels: bug, 8.3-candidate, backport-skip

#398 Agent configuration encryption
  CHANGELOG.next.asciidoc
  Makefile
  NOTICE.txt
  dev-tools/notice/NOTICE.txt.append
  go.mod
  go.sum
  internal/pkg/agent/application/application.go
  internal/pkg/agent/application/application_test.go
  internal/pkg/agent/application/info/agent_id.go
  internal/pkg/agent/application/paths/files.go
  internal/pkg/agent/application/paths/paths_darwin.go
  internal/pkg/agent/application/paths/paths_linux.go
  internal/pkg/agent/application/paths/paths_windows.go
  internal/pkg/agent/application/pipeline/emitter/modifiers/monitoring_decorator_test.go
  internal/pkg/agent/application/secret/secret.go
  internal/pkg/agent/application/secret/secret_test.go
  internal/pkg/agent/application/upgrade/step_mark.go
  internal/pkg/agent/application/upgrade/upgrade.go
  internal/pkg/agent/cmd/enroll_cmd.go
  internal/pkg/agent/cmd/enroll_cmd_test.go
  internal/pkg/agent/cmd/run.go
  internal/pkg/agent/configuration/configuration.go
  internal/pkg/agent/operation/monitoring_test.go
  internal/pkg/agent/storage/encrypted_disk_storage_windows_linux_test.go
  internal/pkg/agent/storage/encrypted_disk_store.go
  internal/pkg/agent/storage/storage.go
  internal/pkg/agent/storage/store/state_store.go
  internal/pkg/agent/vault/aesgcm.go
  internal/pkg/agent/vault/aesgcm_test.go
  internal/pkg/agent/vault/seed.go
  internal/pkg/agent/vault/seed_darwin.go
  internal/pkg/agent/vault/seed_test.go
  internal/pkg/agent/vault/vault_darwin.c
  internal/pkg/agent/vault/vault_darwin.go
  internal/pkg/agent/vault/vault_linux.go
  internal/pkg/agent/vault/vault_test.go
  internal/pkg/agent/vault/vault_windows.go
  internal/pkg/composable/providers/agent/agent_test.go
  internal/pkg/config/operations/inspector.go
  internal/pkg/testutils/testutils.go
Labels: Team:Elastic-Agent-Control-Plane, backport-skip, blocked

#466 [automation] update elastic stack version for testing 8.3.0-bf0ad929
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#465 [automation] update elastic stack version for testing 8.2.1-e97da867
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#419 Support scheduled actions and cancellation
  .golangci.yml
  CHANGELOG.next.asciidoc
  NOTICE.txt
  go.mod
  go.sum
  internal/pkg/agent/application/gateway/fleet/fleet_gateway.go
  internal/pkg/agent/application/gateway/fleet/fleet_gateway_test.go
  internal/pkg/agent/application/managed_mode.go
  internal/pkg/agent/application/pipeline/actions/handlers/handler_action_cancel.go
  internal/pkg/agent/application/pipeline/dispatcher/dispatcher_test.go
  internal/pkg/agent/errors/error.go
  internal/pkg/agent/storage/store/state_store.go
  internal/pkg/agent/storage/store/state_store_test.go
  internal/pkg/fleetapi/action.go
  internal/pkg/fleetapi/action_test.go
  internal/pkg/queue/actionqueue.go
  internal/pkg/queue/actionqueue_test.go
Labels: enhancement, Team:Elastic-Agent-Control-Plane, backport-skip

#468 Update 8.2.2
  version/version.go
Labels: Team:Elastic-Agent-Control-Plane

#470 [automation] update elastic stack version for testing 8.3.0-a2430aec
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#471 [automation] update elastic stack version for testing 8.2.1-f86dca4c
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#476 Update main to 8.4.0
  version/version.go
Labels: backport-skip

#477 Remove redis dockerfile
  testing/environments/docker/redis/Dockerfile
Labels: Team:Elastic-Agent-Control-Plane, backport-skip

#479 Up 8.2.3
  version/version.go
Labels: Team:Elastic-Agent-Control-Plane
