Repository elastic/elastic-agent, pull requests merged in 2022-04, with the labels that each got.

#278 [automation] update elastic stack version for testing 8.2.0-5d1042d1
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#277 [automation] update elastic stack version for testing 8.3.0-1ecd9720
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#279 Update deploy/kube elastic agent templates (add cronjob)
  CHANGELOG.next.asciidoc
  deploy/kubernetes/elastic-agent-managed-kubernetes.yaml
  deploy/kubernetes/elastic-agent-managed/elastic-agent-managed-role.yaml
  deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml
  deploy/kubernetes/elastic-agent-standalone/elastic-agent-standalone-role.yaml
Labels: Team:Elastic-Agent-Control-Plane, backport-v8.2.0

#282 Revert "Remove flags for policy defaulting (#226)"
  CHANGELOG.next.asciidoc
  docs/fleet-server-bootstrap.asciidoc
  internal/pkg/agent/cmd/container.go
  internal/pkg/agent/cmd/container_test.go
  internal/pkg/agent/cmd/setup_config.go
Labels: Team:Elastic-Agent-Control-Plane, backport-v8.2.0, backport-v8.3.0

#286 [automation] update elastic stack version for testing 8.2.0-f531236e
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#287 [automation] update elastic stack version for testing 8.3.0-4cd86339
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#288 cloudbeat artifact path fix
  internal/pkg/agent/program/supported.go
  internal/spec/cloudbeat.yml
Labels: bug, backport-v8.2.0, backport-v8.3.0

#298 [automation] update elastic stack version for testing 8.2.0-12b59372
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#297 [automation] update elastic stack version for testing 8.3.0-657f2d50
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#305 [automation] update elastic stack version for testing 8.3.0-00f4f855
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#306 [automation] update elastic stack version for testing 8.2.0-fdfc79e3
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#309 [automation] update elastic stack version for testing 8.3.0-5bb6f468
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#310 [automation] update elastic stack version for testing 8.2.0-c56d8262
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#317 [automation] update elastic stack version for testing 8.2.0-4df380a5
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#316 [automation] update elastic stack version for testing 8.3.0-76e0128f
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#319 [automation] update elastic stack version for testing 8.2.0-bcbc1a13
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#318 [automation] update elastic stack version for testing 8.3.0-8d19ff01
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#322 [automation] update elastic stack version for testing 8.3.0-2c8f9574
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#315 Misspell
  dev-tools/mage/crossbuild.go
  dev-tools/mage/target/common/package.go
  internal/pkg/agent/application/gateway/fleet/fleet_gateway_test.go
  internal/pkg/agent/application/pipeline/actions/handlers/handler_action_unenroll.go
  internal/pkg/agent/application/pipeline/actions/handlers/handler_unknown.go
  internal/pkg/agent/cmd/diagnostics.go
  internal/pkg/agent/errors/generators.go
  internal/pkg/agent/install/install_unix.go
  internal/pkg/agent/transpiler/ast.go
  internal/pkg/agent/transpiler/rules.go
  internal/pkg/artifact/download/http/verifier.go
  internal/pkg/capabilities/input_test.go
  internal/pkg/capabilities/output_test.go
  internal/pkg/core/composable/providers.go
  internal/pkg/crypto/io.go
  internal/pkg/eql/methods_array.go
  internal/pkg/eql/methods_dict.go
  internal/pkg/eql/methods_length.go
  internal/pkg/eql/methods_math.go
  internal/pkg/eql/methods_str.go
  internal/pkg/reporter/fleet/reporter.go
  pkg/core/server/server_test.go
Labels: bug, Team:Elastic-Agent-Control-Plane, backport-skip

#326 [automation] update elastic stack version for testing 8.2.0-a99722cc
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#312 Improve sync handling and errors
  NOTICE.txt
  go.mod
  go.sum
  internal/pkg/agent/storage/disk_store.go
  internal/pkg/agent/storage/replace_store.go
Labels: Team:Elastic-Agent-Control-Plane, ci:end-to-end, backport-v8.2.0

#329 Create CODEOWNERS
  .github/CODEOWNERS
Labels: Team:Elastic-Agent-Control-Plane, backport-skip

#332 [automation] update elastic stack version for testing 8.2.0-39d3fe7f
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#333 [automation] update elastic stack version for testing 8.3.0-4be61f32
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#308 Add download progress reporter to HTTP downloader.
  .golangci.yml
  CHANGELOG.next.asciidoc
  NOTICE.txt
  go.mod
  internal/pkg/agent/application/upgrade/step_download.go
  internal/pkg/artifact/config.go
  internal/pkg/artifact/download/http/downloader.go
  internal/pkg/artifact/download/http/downloader_test.go
  internal/pkg/artifact/download/http/elastic_test.go
  internal/pkg/artifact/download/localremote/downloader.go
  internal/pkg/artifact/download/snapshot/downloader.go
Labels: Team:Elastic-Agent-Control-Plane, backport-skip

#338 [automation] update elastic stack version for testing 8.3.0-55ba6f37
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#339 [automation] update elastic stack version for testing 8.2.0-edf55ea1
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#341 [automation] update elastic stack version for testing 8.2.0-c65cb8e3
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#343 [automation] update elastic stack version for testing 8.2.0-3a7e2f99
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#342 [automation] update elastic stack version for testing 8.3.0-b671393e
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#345 Fix: uses Debian 10 for mips, ppc and s390x
  dev-tools/mage/crossbuild.go
Labels: Team:Elastic-Agent-Control-Plane, backport-skip, backport-v8.2.0

#349 [automation] update elastic stack version for testing 8.2.0-a7e9513d
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#355 [Flaky Test] Fix TestDownloadBodyError
  internal/pkg/artifact/download/http/downloader_test.go
Labels: Team:Elastic-Agent-Control-Plane, backport-skip

#351 Use local `github.com/elastic/elastic-agent/internal/pkg/agent/cmd/proc` package instead of the one from libbeat
  internal/pkg/core/process/process.go
Labels: backport-skip

#356 [automation] update elastic stack version for testing 8.3.0-55bd5fae
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#357 [automation] update elastic stack version for testing 8.2.0-000e1c18
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#331 Update Go to 1.17.9
  .go-version
  Dockerfile
  version/docs/version.asciidoc
Labels: Team:Elastic-Agent-Control-Plane, backport-v8.2.0

#362 [automation] update elastic stack version for testing 8.2.0-c47183cf
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#361 [automation] update elastic stack version for testing 8.3.0-04455a76
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#365 [automation] update elastic stack version for testing 8.3.0-99e29e67
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#364 [automation] update elastic stack version for testing 8.2.0-14a8abdc
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#363 ci: enable junit reporting
  .ci/Jenkinsfile
Labels: Team:Automation, backport-v8.2.0, backport-v8.3.0

#372 [automation] update elastic stack version for testing 8.3.0-ed7759bd
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#373 [automation] update elastic stack version for testing 8.2.0-63f66f47
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#368 [Heartbeat] Fix umask on docker entrypoint
  dev-tools/packaging/templates/docker/docker-entrypoint.elastic-agent.tmpl
Labels: bug, Team:Uptime, backport-v8.2.0

#367 Decrease dependency on libbeat: use common target for checking for uncommitted changes
  NOTICE.txt
  dev-tools/mage/check.go
  go.mod
  go.sum
Labels: backport-skip

#378 [automation] update elastic stack version for testing 8.3.0-6b041601
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#379 [automation] update elastic stack version for testing 8.2.0-bdd1c93d
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#370 use crypto.rand in generate id with ulid.
  internal/pkg/id/generate.go
Labels: Team:Elastic-Agent-Control-Plane, backport-skip

#360 Fix a bunch of errorlint errors from our linters
  Makefile
  dev-tools/mage/common.go
  dev-tools/mage/dockerbuilder.go
  dev-tools/mage/gotest.go
  dev-tools/mage/pkgtypes.go
  dev-tools/packaging/package_test.go
  internal/pkg/agent/application/info/agent_id.go
  internal/pkg/agent/application/upgrade/step_unpack.go
  internal/pkg/agent/application/upgrade/upgrade.go
  internal/pkg/agent/cmd/container.go
  internal/pkg/agent/cmd/enroll_cmd.go
  internal/pkg/agent/cmd/install.go
  internal/pkg/agent/cmd/status.go
  internal/pkg/agent/cmd/uninstall.go
  internal/pkg/agent/cmd/watch.go
  internal/pkg/agent/errors/error.go
  internal/pkg/agent/errors/error_test.go
  internal/pkg/agent/operation/operator.go
  internal/pkg/agent/storage/store/action_store.go
  internal/pkg/agent/storage/store/state_store.go
  internal/pkg/agent/transpiler/ast.go
  internal/pkg/agent/transpiler/steps.go
  internal/pkg/agent/transpiler/utils.go
  internal/pkg/agent/transpiler/vars.go
  internal/pkg/artifact/install/tar/tar_installer.go
  internal/pkg/composable/controller.go
  internal/pkg/composable/providers/host/host.go
  internal/pkg/composable/providers/kubernetes/service.go
  internal/pkg/composable/providers/local/local.go
  internal/pkg/composable/providers/localdynamic/localdynamic.go
  internal/pkg/core/monitoring/server/handler.go
  internal/pkg/core/monitoring/server/process.go
  internal/pkg/core/monitoring/server/process_test.go
  internal/pkg/core/plugin/service/app.go
  internal/pkg/core/retry/retrystrategy.go
  internal/pkg/crypto/io.go
  internal/pkg/eql/methods_str.go
  internal/pkg/fleetapi/enroll_cmd.go
  pkg/core/logger/logger.go
  pkg/core/server/server.go
  pkg/core/server/server_test.go
Labels: Team:Elastic-Agent-Control-Plane, ci:package, ci:end-to-end, backport-v8.3.0

#383 [automation] update elastic stack version for testing 8.3.0-cb2ce38c
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#384 [automation] update elastic stack version for testing 8.2.0-8b4cfac3
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#344 Remove dependency on libbeat
  .github/workflows/golangci-lint.yml
  .github/workflows/macos.yml
  .golangci.yml
  NOTICE.txt
  go.mod
  go.sum
  internal/pkg/agent/cmd/common.go
  internal/pkg/agent/cmd/container.go
  internal/pkg/agent/cmd/enroll.go
  internal/pkg/agent/cmd/enroll_cmd.go
  internal/pkg/agent/cmd/inspect.go
  internal/pkg/agent/cmd/install.go
  internal/pkg/agent/cmd/metrics.go
  internal/pkg/agent/cmd/platformcheck_test.go
  internal/pkg/agent/cmd/run.go
  internal/pkg/agent/cmd/uninstall.go
  internal/pkg/agent/cmd/watch.go
  internal/pkg/agent/configuration/fleet_server.go
  internal/pkg/agent/control/client/dial_windows.go
  internal/pkg/agent/control/control_test.go
  internal/pkg/agent/control/server/listener_windows.go
  internal/pkg/agent/install/uninstall.go
  internal/pkg/agent/operation/common_test.go
  internal/pkg/agent/transpiler/vars.go
  internal/pkg/agent/transpiler/vars_test.go
  internal/pkg/artifact/config.go
  internal/pkg/artifact/download/fs/verifier_test.go
  internal/pkg/artifact/download/http/downloader.go
  internal/pkg/artifact/download/http/downloader_test.go
  internal/pkg/artifact/download/http/elastic_test.go
  internal/pkg/artifact/download/http/verifier.go
  internal/pkg/artifact/download/snapshot/downloader.go
  internal/pkg/basecmd/version/cmd_test.go
  internal/pkg/capabilities/capabilities_test.go
  internal/pkg/composable/controller.go
  internal/pkg/composable/providers/docker/config.go
  internal/pkg/composable/providers/docker/docker.go
  internal/pkg/composable/providers/docker/docker_test.go
  internal/pkg/composable/providers/kubernetes/config.go
  internal/pkg/composable/providers/kubernetes/kubernetes.go
  internal/pkg/composable/providers/kubernetes/node.go
  internal/pkg/composable/providers/kubernetes/node_test.go
  internal/pkg/composable/providers/kubernetes/pod.go
  internal/pkg/composable/providers/kubernetes/pod_test.go
  internal/pkg/composable/providers/kubernetes/service.go
  internal/pkg/composable/providers/kubernetes/service_test.go
  internal/pkg/composable/providers/kubernetesleaderelection/config.go
  internal/pkg/composable/providers/kubernetesleaderelection/kubernetes_leaderelection.go
  internal/pkg/composable/providers/kubernetessecrets/config.go
  internal/pkg/composable/providers/kubernetessecrets/kubernetes_secrets.go
  internal/pkg/composable/providers/kubernetessecrets/kubernetes_secrets_test.go
  internal/pkg/composable/registry.go
  internal/pkg/config/operations/inspector.go
  internal/pkg/core/monitoring/server/server.go
  internal/pkg/core/monitoring/server/stats.go
  internal/pkg/remote/client.go
  internal/pkg/remote/config.go
  internal/pkg/remote/config_test.go
  pkg/core/logger/logger.go
  pkg/core/server/server_test.go
Labels: Team:Elastic-Agent-Control-Plane, ci:end-to-end, backport-skip

#387 Remove last dependencies on beats repo
  NOTICE.txt
  go.mod
  go.sum
  internal/pkg/core/monitoring/config/config_test.go
  internal/pkg/core/monitoring/server/process.go
  internal/pkg/core/monitoring/server/url.go
Labels: ci:end-to-end, backport-skip

#377 ci: enable coverage
  .ci/Jenkinsfile
  dev-tools/mage/gotest.go
Labels: backport-v8.2.0, backport-v8.3.0

#391 [automation] update elastic stack version for testing 8.2.0-2c25c9de
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip
