Repository elastic/elastic-agent, pull requests merged in 2022-10, with the labels that each got.

#1382 Mount /etc directory in Kubernetes DaemonSet manifests.
  deploy/kubernetes/elastic-agent-managed-kubernetes.yaml
  deploy/kubernetes/elastic-agent-managed/elastic-agent-managed-daemonset.yaml
  deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml
  deploy/kubernetes/elastic-agent-standalone/elastic-agent-standalone-daemonset.yaml
Labels: bug, backport-v8.5.0

#1392 Fix: Agent failed to upgrade from 8.4.2 to 8.5.0 BC1 for MAC 12 agent using agent binary.
  dev-tools/packaging/files/darwin/PkgInfo
  dev-tools/packaging/packages.yml
  dev-tools/packaging/templates/darwin/Info.plist.tmpl
  dev-tools/packaging/templates/darwin/elastic-agent.tmpl
  internal/pkg/agent/application/info/state.go
  internal/pkg/agent/application/info/state_test.go
  internal/pkg/agent/application/paths/common.go
  internal/pkg/agent/application/upgrade/service_darwin.go
  internal/pkg/agent/application/upgrade/step_relink.go
  internal/pkg/agent/install/install.go
Labels: bug

#1403 [automation] update elastic stack version for testing 8.4.3-5e0dd488
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1405 [automation] update elastic stack version for testing 8.6.0-aea1c645
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1404 [automation] update elastic stack version for testing 8.5.0-49b2dce3
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1413 [automation] update elastic stack version for testing 8.4.3-ff95b7c5
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1412 [automation] update elastic stack version for testing 8.6.0-0fca2953
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1417 ci: 7.17 is not available for the daily run
  .ci/schedule-daily.groovy
Labels: backport-skip

#1425 [automation] update elastic stack version for testing 8.6.0-e4c15f15
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1424 [automation] update elastic stack version for testing 8.5.0-58624073
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1325 [Release] Update version to 8.4.4
  version/version.go
Labels: Team:Automation, release

#1401 [backport main] Fix: Agent failed to upgrade from 8.4.2 to 8.5.0 BC1 for MAC 12 agent using agent binary.
  dev-tools/packaging/packages.yml
  dev-tools/packaging/templates/darwin/elastic-agent.tmpl
  internal/pkg/agent/application/info/state.go
  internal/pkg/agent/application/info/state_test.go
  internal/pkg/agent/application/paths/common.go
  internal/pkg/agent/application/paths/common_test.go
  internal/pkg/agent/application/upgrade/service_darwin.go
  internal/pkg/agent/application/upgrade/step_relink.go
  internal/pkg/agent/application/upgrade/step_unpack.go
  internal/pkg/agent/application/upgrade/upgrade.go
  internal/pkg/agent/install/install.go
Labels: bug, backport-skip

#1420 Fix docker provider add_fields processors
  changelog/fragments/1664989867-fix-docker-provider-processors.yaml
  internal/pkg/composable/providers/docker/docker.go
  internal/pkg/composable/providers/docker/docker_test.go
Labels: bug, Team:Elastic-Agent-Control-Plane, backport-v8.5.0

#1437 [automation] update elastic stack version for testing 8.4.4-ac374c4b
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1436 [automation] update elastic stack version for testing 8.6.0-d939cfde
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1438 [automation] update elastic stack version for testing 8.5.0-c52257ee
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1447 [automation] update elastic stack version for testing 8.4.4-17ce02d0
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1448 [automation] update elastic stack version for testing 8.5.0-7d416dc4
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1446 [automation] update elastic stack version for testing 8.6.0-7c9f25a9
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1456 Enable integration only when datastreams are not defined
  internal/pkg/composable/providers/kubernetes/hints.go
  internal/pkg/composable/providers/kubernetes/hints_test.go
Labels: Team:Cloudnative-Monitoring, backport-v8.5.0

#1398 Add not dedoted k8s pod labels in autodiscover provider to be used for templating, exactly like annotations
  CHANGELOG.next.asciidoc
  internal/pkg/composable/providers/kubernetes/pod.go
Labels: backport-skip

#1463 [automation] update elastic stack version for testing 8.4.4-221d2ff4
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1465 [automation] update elastic stack version for testing 8.5.0-4f4df9f4
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1464 [automation] update elastic stack version for testing 8.6.0-c49fac70
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1470 Add storageclass permissions in agent clusterrole
  CHANGELOG.next.asciidoc
  deploy/kubernetes/elastic-agent-managed-kubernetes.yaml
  deploy/kubernetes/elastic-agent-managed/elastic-agent-managed-role.yaml
Labels: backport-skip

#1455 Remote QA-labels automation
  .github/workflows/qa-labels.yml
Labels: backport-skip

#1444 [automation] Update go release version 1.18.7
  .go-version
  Dockerfile
  version/docs/version.asciidoc
Labels: automation, dependency, backport-v8.5.0

#1481 [automation] update elastic stack version for testing 8.4.4-5fbb5bd0
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1480 [automation] update elastic stack version for testing 8.6.0-5a8d757d
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1482 [automation] update elastic stack version for testing 8.5.0-09886b6e
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1477 Improve logging around agent checkins.
  CHANGELOG.next.asciidoc
  changelog/fragments/1665517984-improve-checkin-error-logging.yaml
  internal/pkg/agent/application/gateway/fleet/fleet_gateway.go
  internal/pkg/agent/application/gateway/fleet/fleet_gateway_test.go
  internal/pkg/core/backoff/backoff.go
  internal/pkg/core/backoff/backoff_test.go
  internal/pkg/core/backoff/equal_jitter.go
  internal/pkg/core/backoff/exponential.go
  internal/pkg/fleetapi/checkin_cmd.go
  internal/pkg/fleetapi/checkin_cmd_test.go
Labels: backport-v8.5.0

#1498 [automation] update elastic stack version for testing 8.4.4-1129f33b
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1496 [automation] update elastic stack version for testing 8.6.0-40086bc7
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1490 Fixing makefile check
  deploy/kubernetes/Makefile
Labels: backport-skip

#1488 action: validate changelog fragment
  .github/workflows/changelog.yml
Labels: Team:Automation, automation, backport-skip, backport

#1500 Allign managed with standalone role
  deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml
  deploy/kubernetes/elastic-agent-standalone/elastic-agent-standalone-role.yaml
Labels: backport-skip

#1504 Fix k8s template link versioning
  deploy/kubernetes/Makefile
  deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml
  deploy/kubernetes/elastic-agent-standalone/elastic-agent-standalone-daemonset.yaml
Labels: Team:Cloudnative-Monitoring, v8.5.0, backport, backport-v8.5.0

#1507 Allighningmanifests
  deploy/kubernetes/Makefile
  deploy/kubernetes/elastic-agent-managed-kubernetes.yaml
  deploy/kubernetes/elastic-agent-managed/elastic-agent-managed-daemonset.yaml
  deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml
  deploy/kubernetes/elastic-agent-standalone/elastic-agent-standalone-daemonset-configmap.yaml
Labels: backport-skip

#1517 [automation] update elastic stack version for testing 8.4.4-fdf1902b
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1515 [automation] update elastic stack version for testing 8.6.0-233dc5d4
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1516 [automation] update elastic stack version for testing 8.5.0-976bca07
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1244 Convert CHANGELOG.next to fragments
  CHANGELOG.next.asciidoc
  README.md
  changelog/fragments/1660139385-Fix-a-panic-caused-by-a-race-condition-when-installing-the-Elastic-Agent.yaml
  changelog/fragments/1660158319-Upgrade-to-Go-118-Certificates-signed-with-SHA-1-are-now-rejected-See-the-Go-118.yaml
  changelog/fragments/1661188787-Add-lumberjack-input-type-to-the-Filebeat-spec.yaml
  changelog/fragments/1663143487-Add-support-for-hints-based-autodiscovery-in-kubernetes-provider.yaml
  changelog/fragments/1664177394-Fix-unintended-reset-of-source-URI-when-downloading-components.yaml
  changelog/fragments/1664212969-Create-separate-status-reporter-for-local-only-events-so-that-degraded-fleet-che.yaml
  changelog/fragments/1664230732-Improve-logging-during-upgrades.yaml
  changelog/fragments/1664360554-Add-success-log-message-after-previous-checkin-failures.yaml
Labels: backport-v8.5.0

#1219 [v2] Add upgrade action retry
  CHANGELOG.next.asciidoc
  internal/pkg/agent/application/coordinator/coordinator.go
  internal/pkg/agent/application/dispatcher/dispatcher.go
  internal/pkg/agent/application/dispatcher/dispatcher_test.go
  internal/pkg/agent/application/dispatcher/retryconfig.go
  internal/pkg/agent/application/dispatcher/retryconfig_test.go
  internal/pkg/agent/application/gateway/fleet/fleet_gateway.go
  internal/pkg/agent/application/gateway/fleet/fleet_gateway_test.go
  internal/pkg/agent/application/gateway/gateway.go
  internal/pkg/agent/application/managed_mode.go
  internal/pkg/agent/application/upgrade/upgrade.go
  internal/pkg/agent/storage/store/state_store.go
  internal/pkg/agent/storage/store/state_store_test.go
  internal/pkg/fleetapi/ack_cmd.go
  internal/pkg/fleetapi/acker/fleet/fleet_acker.go
  internal/pkg/fleetapi/acker/fleet/fleet_acker_test.go
  internal/pkg/fleetapi/action.go
  internal/pkg/fleetapi/action_test.go
  internal/pkg/queue/actionqueue.go
  internal/pkg/queue/actionqueue_test.go
Labels: enhancement, Team:Elastic-Agent-Control-Plane, v8.6.0

#1533 [automation] update elastic stack version for testing 8.4.4-2db0c963
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1531 [automation] update elastic stack version for testing 8.6.0-54a302f0
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1532 [automation] update elastic stack version for testing 8.5.0-f8c98e5d
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1478 Update the linter configuration.
  .github/workflows/golangci-lint.yml
  .golangci.yml
Labels: backport-v8.4.0, backport-v8.5.0

#1528 Elastic agent counterpart of https://github.com/elastic/beats/pull/33362
  changelog/fragments/1665784342-use-stack-version-npm-synthetics.yaml
  dev-tools/packaging/templates/docker/Dockerfile.elastic-agent.tmpl
  dev-tools/packaging/templates/docker/Dockerfile.tmpl
Labels: enhancement, Team:Uptime, backport-skip

#1547 [automation] update elastic stack version for testing 8.4.4-93b2bfdf
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1546 [automation] update elastic stack version for testing 8.5.0-7c74e950
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1545 [automation] update elastic stack version for testing 8.6.0-cae815eb
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1552 Fix admin permission check on localized windows
  changelog/fragments/1666088774-Fix-admin-permission-check-on-localized-windows.yaml
  internal/pkg/agent/control/server/listener_windows.go
Labels: bug, Team:Elastic-Agent-Control-Plane, backport-v8.5.0

#1563 [automation] update elastic stack version for testing 8.4.4-e97ba82f
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1561 [automation] update elastic stack version for testing 8.6.0-6545f2df
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1562 [automation] update elastic stack version for testing 8.5.0-792499b4
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1487 V1 metrics monitoring for V2
  NOTICE.txt
  go.mod
  go.sum
  internal/pkg/agent/application/application.go
  internal/pkg/agent/application/coordinator/coordinator.go
  internal/pkg/agent/application/monitoring/handler.go
  internal/pkg/agent/application/monitoring/server.go
  internal/pkg/agent/application/monitoring/stats.go
  internal/pkg/agent/application/monitoring/v1_monitor.go
  internal/pkg/agent/cmd/inspect.go
  internal/pkg/agent/cmd/run.go
  internal/pkg/agent/configuration/settings.go
  internal/pkg/agent/install/uninstall.go
  internal/pkg/agent/vars/vars.go
  internal/pkg/core/monitoring/config/config.go
  pkg/component/component.go
  pkg/component/component_test.go
  pkg/component/runtime/command.go
  pkg/component/runtime/manager.go
  pkg/component/runtime/manager_test.go
  pkg/component/runtime/runtime.go
  specs/metricbeat.spec.yml
  version/version.go
Labels: enhancement, Team:Elastic-Agent-Control-Plane, V2-Architecture

#1491 [Heartbeat] Only support elasticsearch output for synthetics integration
  changelog/fragments/1665780486-heartbeat-es-output-only.yaml
  internal/pkg/agent/program/program_test.go
  internal/pkg/agent/program/supported.go
  internal/pkg/agent/program/testdata/logstash_config-heartbeat.yml
  internal/spec/heartbeat.yml
Labels: bug, Team:Uptime, backport-skip

#1571 [automation] update elastic stack version for testing 8.4.4-51bbfe53
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1570 [automation] update elastic stack version for testing 8.5.0-7e528e3e
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1329 make policy change handler try all fleet hosts before failing
  changelog/fragments/1666281194-Fix-how-multiple-Fleet-Server-hosts-are-handled.yaml
  internal/pkg/agent/application/pipeline/actions/handlers/handler_action_policy_change.go
  internal/pkg/fleetapi/client/client.go
  internal/pkg/remote/client.go
  internal/pkg/remote/client_test.go
Labels: bug, 8.6-candidate, backport-v8.5.0

#1581 [automation] update elastic stack version for testing 8.4.4-4edb5c6b
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1579 [automation] update elastic stack version for testing 8.6.0-baf193e8
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1580 [automation] update elastic stack version for testing 8.5.0-754ef325
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1589 [automation] update elastic stack version for testing 8.4.4-9b801d60
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1587 [automation] update elastic stack version for testing 8.6.0-22d60ec9
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1588 [automation] update elastic stack version for testing 8.5.0-d7b01592
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1594 Update kubernetes templates for elastic-agent [templates.d]
  deploy/kubernetes/elastic-agent-standalone/templates.d/activemq.yml
  deploy/kubernetes/elastic-agent-standalone/templates.d/apache.yml
  deploy/kubernetes/elastic-agent-standalone/templates.d/cassandra.yml
  deploy/kubernetes/elastic-agent-standalone/templates.d/cockroachdb.yml
  deploy/kubernetes/elastic-agent-standalone/templates.d/elasticsearch.yml
  deploy/kubernetes/elastic-agent-standalone/templates.d/endpoint.yml
  deploy/kubernetes/elastic-agent-standalone/templates.d/haproxy.yml
  deploy/kubernetes/elastic-agent-standalone/templates.d/hashicorp_vault.yml
  deploy/kubernetes/elastic-agent-standalone/templates.d/hid_bravura_monitor.yml
  deploy/kubernetes/elastic-agent-standalone/templates.d/iis.yml
  deploy/kubernetes/elastic-agent-standalone/templates.d/iptables.yml
  deploy/kubernetes/elastic-agent-standalone/templates.d/kafka.yml
  deploy/kubernetes/elastic-agent-standalone/templates.d/kibana.yml
  deploy/kubernetes/elastic-agent-standalone/templates.d/logstash.yml
  deploy/kubernetes/elastic-agent-standalone/templates.d/microsoft_sqlserver.yml
  deploy/kubernetes/elastic-agent-standalone/templates.d/mimecast.yml
  deploy/kubernetes/elastic-agent-standalone/templates.d/mongodb.yml
  deploy/kubernetes/elastic-agent-standalone/templates.d/mysql.yml
  deploy/kubernetes/elastic-agent-standalone/templates.d/nats.yml
  deploy/kubernetes/elastic-agent-standalone/templates.d/netflow.yml
  deploy/kubernetes/elastic-agent-standalone/templates.d/nginx.yml
  deploy/kubernetes/elastic-agent-standalone/templates.d/oracle.yml
  deploy/kubernetes/elastic-agent-standalone/templates.d/panw.yml
  deploy/kubernetes/elastic-agent-standalone/templates.d/panw_cortex_xdr.yml
  deploy/kubernetes/elastic-agent-standalone/templates.d/pfsense.yml
  deploy/kubernetes/elastic-agent-standalone/templates.d/postgresql.yml
  deploy/kubernetes/elastic-agent-standalone/templates.d/prometheus.yml
  deploy/kubernetes/elastic-agent-standalone/templates.d/qnap_nas.yml
  deploy/kubernetes/elastic-agent-standalone/templates.d/rabbitmq.yml
  deploy/kubernetes/elastic-agent-standalone/templates.d/redis.yml
  deploy/kubernetes/elastic-agent-standalone/templates.d/security_detection_engine.yml
  deploy/kubernetes/elastic-agent-standalone/templates.d/sentinel_one.yml
  deploy/kubernetes/elastic-agent-standalone/templates.d/snyk.yml
  deploy/kubernetes/elastic-agent-standalone/templates.d/stan.yml
  deploy/kubernetes/elastic-agent-standalone/templates.d/symantec_endpoint.yml
  deploy/kubernetes/elastic-agent-standalone/templates.d/synthetics.yml
  deploy/kubernetes/elastic-agent-standalone/templates.d/tcp.yml
  deploy/kubernetes/elastic-agent-standalone/templates.d/traefik.yml
  deploy/kubernetes/elastic-agent-standalone/templates.d/udp.yml
  deploy/kubernetes/elastic-agent-standalone/templates.d/zookeeper.yml
Labels: automation, backport-skip

#1286 Fix: Windows Agent Left Unhealthy After Removing Endpoint Integration
  changelog/fragments/1666611696-fix_service_stop_timeout.yaml
  internal/pkg/agent/operation/monitoring.go
  internal/pkg/agent/operation/monitoring_test.go
  internal/pkg/agent/program/spec.go
  internal/pkg/agent/program/spec_test.go
  internal/pkg/agent/program/supported.go
  internal/pkg/core/plugin/service/app.go
  internal/spec/endpoint.yml
Labels: bug, Team:Elastic-Agent-Control-Plane, backport-v8.4.0, backport-v8.5.0

#1596 Add input name alias for cloudbeat integrations
  specs/cloudbeat.spec.yml
Labels: skip-changelog

#1603 [automation] update elastic stack version for testing 8.4.4-46f2f222
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1602 [automation] update elastic stack version for testing 8.6.0-b8b35931
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1529 Service runtime V2
  NOTICE.txt
  changelog/fragments/1666095433-service_runtime_v2.yaml
  go.mod
  go.sum
  internal/pkg/agent/application/application.go
  internal/pkg/agent/application/coordinator/coordinator.go
  internal/pkg/agent/application/fleet_server_bootstrap.go
  internal/pkg/agent/application/info/inject_config.go
  internal/pkg/agent/cmd/container.go
  internal/pkg/agent/cmd/enroll_cmd.go
  internal/pkg/agent/configuration/settings.go
  internal/pkg/agent/install/uninstall.go
  internal/pkg/agent/storage/store/state_store.go
  pkg/component/component.go
  pkg/component/runtime/README.md
  pkg/component/runtime/command.go
  pkg/component/runtime/conn_info_server.go
  pkg/component/runtime/conn_info_server_test.go
  pkg/component/runtime/runtime.go
  pkg/component/runtime/service.go
  pkg/component/runtime/service_command.go
  pkg/component/runtime/service_command_test.go
  pkg/component/runtime/state.go
  pkg/component/spec.go
  pkg/component/spec_test.go
  pkg/core/process/process.go
  specs/endpoint-security.spec.yml
Labels: V2-Architecture

#1613 [automation] update elastic stack version for testing 8.5.0-bdb74671
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1612 [automation] update elastic stack version for testing 8.4.4-1ee39d03
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1607 Create stale config
  .github/stale.yml
Labels: backport-skip

#1622 [automation] update elastic stack version for testing 8.4.4-d66e996a
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1620 [automation] update elastic stack version for testing 8.5.0-eb17cbd2
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1621 [automation] update elastic stack version for testing 8.6.0-a892f234
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1618 Improve shutdown logs
  NOTICE.txt
  changelog/fragments/1666789812-Improve-shutdown-logs.yaml
  go.mod
  go.sum
  internal/pkg/agent/application/pipeline/actions/handlers/handler_action_settings.go
  internal/pkg/agent/application/upgrade/upgrade.go
  internal/pkg/agent/cmd/common.go
  internal/pkg/agent/cmd/run.go
Labels: enhancement, 8.6-candidate, backport-v8.5.0

#1634 [automation] update elastic stack version for testing 8.4.4-6eb63640
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1635 [automation] update elastic stack version for testing 8.5.0-4028b295
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1633 [automation] update elastic stack version for testing 8.6.0-89d224d2
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1629 [Automation] Add GH action to add issues to ingest board
  .github/workflows/add-issues-to-ingest-board.yml
Labels: backport-skip, skip-changelog

#1646 [automation] update elastic stack version for testing 8.4.4-f3b8851a
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1647 [automation] update elastic stack version for testing 8.6.0-949a38d2
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1645 [automation] update elastic stack version for testing 8.5.0-f48cdca0
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1657 Update node version to 18.12.0 on complete image
  changelog/fragments/1667243040-Upgrade-node-to-18.12.0.yaml
  dev-tools/packaging/templates/docker/Dockerfile.elastic-agent.tmpl
  dev-tools/packaging/templates/docker/Dockerfile.tmpl
Labels: enhancement, Team:Uptime, backport-skip
