Repository elastic/elastic-agent, pull requests merged in 2022-12, with the labels that each got.

#1858 [automation] update elastic stack version for testing 8.6.0-87c26073
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1857 [automation] update elastic stack version for testing 8.5.3-268167d7
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1856 Add agent logging level to fleet configuration
  changelog/fragments/1669845868-add-agent-logging-level-to-fleet-configuration.yaml
  internal/pkg/agent/application/application.go
  internal/pkg/agent/application/fleet_server_bootstrap.go
  internal/pkg/agent/application/fleet_server_bootstrap_test.go
Labels: bug, backport-v8.6.0

#1859 Allow empty redirect for processes endpoint
  internal/pkg/agent/application/monitoring/process.go
  internal/pkg/agent/application/monitoring/processes_cloud.go
  internal/pkg/agent/application/monitoring/processes_cloud_test.go
Labels: bug, Team:Elastic-Agent, ci:end-to-end, skip-changelog, backport-v8.6.0

#1872 [automation] update elastic stack version for testing 8.5.3-1625ae9f
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1871 [automation] update elastic stack version for testing 8.6.0-f96862e0
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1873 [automation] update elastic stack version for testing 8.7.0-1b0dc867
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1866 Ensure unique ID for dynamic variable replacement.
  changelog/fragments/1669928791-Ensure-unique-input-ID-when-variable-substition-occurs-from-a-dynamic-provider.yaml
  internal/pkg/agent/transpiler/ast_test.go
  internal/pkg/agent/transpiler/utils.go
  internal/pkg/agent/transpiler/utils_test.go
  internal/pkg/agent/transpiler/vars.go
  internal/pkg/agent/transpiler/vars_test.go
  internal/pkg/composable/controller.go
  pkg/component/component.go
Labels: Team:Elastic-Agent, backport-v8.6.0

#1875 Add pre-hook to load paths overrides in container
  internal/pkg/agent/cmd/common.go
  internal/pkg/agent/cmd/diagnostics.go
  internal/pkg/agent/cmd/inspect.go
  internal/pkg/agent/cmd/status.go
Labels: bug, Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent, skip-changelog, backport-v8.6.0

#1869 Remove inputs when all streams are removed
  changelog/fragments/1669940990-Remove-inputs-when-all-streams-are-removed.yaml
  internal/pkg/agent/transpiler/utils.go
  internal/pkg/agent/transpiler/utils_test.go
Labels: Team:Elastic-Agent, backport-v8.6.0

#1879 Clean up 8.5 changelog fragements
  changelog/8.5.1.yaml
  changelog/8.5.2.yaml
  changelog/fragments/1665784342-use-stack-version-npm-synthetics.yaml
  changelog/fragments/1666281194-Fix-how-multiple-Fleet-Server-hosts-are-handled.yaml
  changelog/fragments/1666611696-fix_service_stop_timeout.yaml
  changelog/fragments/1666789812-Improve-shutdown-logs.yaml
Labels: Team:Elastic-Agent, docs, backport-v8.6.0, forwardport-main

#1884 [automation] update elastic stack version for testing 8.6.0-368aeeae
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1885 [automation] update elastic stack version for testing 8.5.3-0a7c209d
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1883 [automation] update elastic stack version for testing 8.7.0-1fff43d4
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1791 snapshot/downloader: fix fetching snapshot URI
  internal/pkg/agent/application/upgrade/artifact/download/snapshot/downloader.go
Labels: Team:Elastic-Agent-Data-Plane, backport-v8.6.0

#1870 add container platforms to endpoint spec
  pkg/component/component_test.go
  pkg/component/load_test.go
  specs/endpoint-security.spec.yml
Labels: bug, v8.6.0

#1878 Fix how apm is started in cloud legacy mode
  internal/pkg/agent/cmd/container.go
Labels: bug, Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent, skip-changelog, backport-v8.6.0

#1892 [automation] update elastic stack version for testing 8.7.0-7fe23b13
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1893 [automation] update elastic stack version for testing 8.5.3-55d94167
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1763 Cloudbeat args v2 alignment
  specs/cloudbeat.spec.yml
Labels: skip-changelog, backport-v8.6.0

#1902 [automation] update elastic stack version for testing 8.6.0-57f16700
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1901 [automation] update elastic stack version for testing 8.7.0-2c7c2bad
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1903 [automation] update elastic stack version for testing 8.5.3-e63a0e72
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1909 [automation] update elastic stack version for testing 8.7.0-188e6a3a
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1911 [automation] update elastic stack version for testing 8.5.3-ec242734
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1910 [automation] update elastic stack version for testing 8.6.0-7c9fd7a8
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1838 [Release] Update version to 8.5.4
  version/version.go
Labels: Team:Automation, release

#1867 Change local fleet-server connection to localhost:8221
  changelog/fragments/1669929902-fix-local-fleet-server-port.yaml
  internal/pkg/agent/cmd/enroll_cmd.go
  internal/pkg/remote/client.go
Labels: bug, Team:Elastic-Agent-Control-Plane, backport-v8.5.0, backport-v8.6.0

#1917 [automation] update elastic stack version for testing 8.7.0-59d5589a
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1918 [automation] update elastic stack version for testing 8.6.0-3bb8e729
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1919 [automation] update elastic stack version for testing 8.5.3-91bdfab4
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1921 [automation] update elastic stack version for testing 8.7.0-e9833f49
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1922 [automation] update elastic stack version for testing 8.6.0-febebae1
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1923 Disable monitoring in bootstrap mode
  internal/pkg/agent/application/application.go
  internal/pkg/agent/application/monitoring/v1_monitor.go
  internal/pkg/agent/cmd/run.go
Labels: bug, Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent, skip-changelog, backport-v8.6.0

#1935 [automation] update elastic stack version for testing 8.6.0-6538107d
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1934 [automation] update elastic stack version for testing 8.7.0-08cd8ac3
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1936 Fixed Monitoring.Prepare for IDs exceeding filepath length limit
  internal/pkg/agent/application/monitoring/v1_monitor.go
  pkg/component/runtime/command.go
  pkg/component/runtime/manager_test.go
Labels: bug, Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent, skip-changelog, backport-v8.6.0

#1941 [automation] update elastic stack version for testing 8.7.0-04d5f080
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1914 Fix log level support to adjust components and remove need for re-exec
  changelog/fragments/1670518841-No-longer-restart-Elastic-Agent-on-log-level-change.yaml
  internal/pkg/agent/application/actions/handlers/handler_action_settings.go
  internal/pkg/agent/application/application.go
  internal/pkg/agent/application/coordinator/coordinator.go
  internal/pkg/agent/application/monitoring/processes_cloud.go
  internal/pkg/agent/application/monitoring/processes_cloud_test.go
  internal/pkg/agent/cmd/inspect.go
  internal/pkg/agent/cmd/run.go
  internal/pkg/agent/control/cproto/control.pb.go
  internal/pkg/agent/control/cproto/control_grpc.pb.go
  internal/pkg/agent/install/uninstall.go
  pkg/component/component.go
  pkg/component/component_test.go
  pkg/component/runtime/command.go
  pkg/component/runtime/log_writer.go
  pkg/component/runtime/log_writer_test.go
  pkg/core/logger/logger.go
  specs/apm-server.spec.yml
  specs/auditbeat.spec.yml
  specs/cloudbeat.spec.yml
  specs/filebeat.spec.yml
  specs/fleet-server.spec.yml
  specs/heartbeat.spec.yml
  specs/metricbeat.spec.yml
  specs/osquerybeat.spec.yml
  specs/packetbeat.spec.yml
Labels: Team:Elastic-Agent, backport-v8.6.0

#1948 [automation] update elastic stack version for testing 8.7.0-4441fcfd
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1947 [automation] update elastic stack version for testing 8.6.0-919399a0
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1958 [automation] update elastic stack version for testing 8.7.0-319a9bee
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1963 [automation] update elastic stack version for testing 8.6.0-d5c0a6be
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1962 [O11y] Add cometd filebeat input to elastic-agent
  specs/filebeat.spec.yml
Labels: backport-skip

#1968 [automation] update elastic stack version for testing 8.6.0-a85d8f17
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1966 [automation] update elastic stack version for testing 8.7.0-bb19a9d1
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1970 Integration input name updated for new cloud-defend service
  specs/cloud-defend.spec.yml
Labels: bug, backport-skip, Team: Cloud Native Integrations

#1973 [automation] update elastic stack version for testing 8.7.0-19f30181
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1972 [automation] update elastic stack version for testing 8.6.0-734df845
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1964 runtime/manager: make error message human readable
  pkg/component/runtime/manager.go
Labels: backport-skip, Cleanup

#1950 Lazy Acker print actions as string so indeed prints them
  internal/pkg/fleetapi/acker/lazy/lazy_acker.go
  internal/pkg/fleetapi/acker/lazy/lazy_acker_test.go
Labels: enhancement, Team:Elastic-Agent, 8.7-candidate, backport-v8.6.0

#1908 Filter binaries by platform when EXTERNAL=true
  NOTICE.txt
  dev-tools/mage/platforms.go
  go.mod
  go.sum
  magefile.go
Labels: Team:Elastic-Agent, backport-v8.6.0

#1974 Introducing V1 grpc control protocol for backward compatibility with older agents
  control_v1.proto
  control_v2.proto
  internal/pkg/agent/application/coordinator/coordinator.go
  internal/pkg/agent/application/coordinator/handler.go
  internal/pkg/agent/application/gateway/fleet/fleet_gateway.go
  internal/pkg/agent/application/upgrade/error_checker.go
  internal/pkg/agent/application/upgrade/rollback.go
  internal/pkg/agent/cmd/diagnostics.go
  internal/pkg/agent/cmd/enroll_cmd.go
  internal/pkg/agent/cmd/run.go
  internal/pkg/agent/cmd/status.go
  internal/pkg/agent/cmd/upgrade.go
  internal/pkg/agent/control/v1/client/client.go
  internal/pkg/agent/control/v1/client/dial.go
  internal/pkg/agent/control/v1/client/dial_windows.go
  internal/pkg/agent/control/v1/proto/control_v1.pb.go
  internal/pkg/agent/control/v1/proto/control_v1_grpc.pb.go
  internal/pkg/agent/control/v1/server/server.go
  internal/pkg/agent/control/v2/client/client.go
  internal/pkg/agent/control/v2/client/dial.go
  internal/pkg/agent/control/v2/client/dial_windows.go
  internal/pkg/agent/control/v2/control_test.go
  internal/pkg/agent/control/v2/cproto/control_v2.pb.go
  internal/pkg/agent/control/v2/cproto/control_v2_grpc.pb.go
  internal/pkg/agent/control/v2/server/listener.go
  internal/pkg/agent/control/v2/server/listener_windows.go
  internal/pkg/agent/control/v2/server/server.go
  internal/pkg/basecmd/restart/cmd.go
  internal/pkg/basecmd/version/cmd.go
  internal/pkg/basecmd/version/cmd_test.go
  magefile.go
Labels: bug, Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent, skip-changelog, backport-v8.6.0

#1978 Do not persist action error with new action batch
  internal/pkg/agent/application/dispatcher/dispatcher.go
  internal/pkg/agent/application/dispatcher/dispatcher_test.go
Labels: Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent, skip-changelog, backport-v8.6.0

#1985 [automation] update elastic stack version for testing 8.6.0-55d181cf
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1984 [automation] update elastic stack version for testing 8.5.4-880022a5
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1986 Fix logging of service based components (aka. endpoint)
  internal/pkg/agent/application/coordinator/coordinator.go
  internal/pkg/agent/application/monitoring/v1_monitor.go
  internal/pkg/agent/cmd/inspect.go
  pkg/component/component.go
Labels: Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent, backport-v8.6.0

#1983 Update the beats specifications for log level and output change.
  specs/apm-server.spec.yml
  specs/auditbeat.spec.yml
  specs/cloudbeat.spec.yml
  specs/filebeat.spec.yml
  specs/heartbeat.spec.yml
  specs/metricbeat.spec.yml
  specs/osquerybeat.spec.yml
  specs/packetbeat.spec.yml
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog, backport-v8.6.0

#1995 [automation] update elastic stack version for testing 8.5.4-9612e66a
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1998 [V2] Do not collect endpoint metrics on /stats endpoint
  internal/pkg/agent/application/monitoring/v1_monitor.go
Labels: bug, Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent, skip-changelog, backport-v8.6.0

#2001 Improve state change messages
  internal/pkg/agent/application/coordinator/coordinator.go
Labels: Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent, skip-changelog, backport-v8.6.0

#2010 [automation] update elastic stack version for testing 8.6.0-f6d7d537
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#2009 [automation] update elastic stack version for testing 8.7.0-0f74a2e9
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#2011 [automation] update elastic stack version for testing 8.5.4-09ced402
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#2015 [automation] update elastic stack version for testing 8.6.0-a026c2fe
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#2014 [automation] update elastic stack version for testing 8.5.4-53cae6e0
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#2020 [automation] update elastic stack version for testing 8.6.0-7e55dcb1
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#2021 [automation] update elastic stack version for testing 8.7.0-b3da67ae
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#2019 [automation] update elastic stack version for testing 8.5.4-b44284e8
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1994 All inputs in an agent policy must have a unique ID
  _meta/config/common.p2.yml.tmpl
  _meta/config/common.reference.p2.yml.tmpl
  _meta/config/elastic-agent.docker.yml.tmpl
  _meta/elastic-agent.yml
  changelog/fragments/1671748292-input-ids-are-required.yaml
  deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml
  deploy/kubernetes/elastic-agent-standalone/elastic-agent-standalone-daemonset-configmap.yaml
  elastic-agent.docker.yml
  elastic-agent.reference.yml
  elastic-agent.yml
  pkg/component/component.go
  pkg/component/component_test.go
Labels: Team:Elastic-Agent, backport-v8.6.0

#2023 [automation] update elastic stack version for testing 8.6.0-08909b84
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#2024 [automation] update elastic stack version for testing 8.5.4-63dd32c9
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#2003 Add configurable numbness for component restarts
  NOTICE.txt
  go.mod
  go.sum
  pkg/component/runtime/command.go
  pkg/component/runtime/command_test.go
  pkg/component/spec.go
  specs/auditbeat.spec.yml
  specs/cloudbeat.spec.yml
  specs/filebeat.spec.yml
  specs/heartbeat.spec.yml
  specs/metricbeat.spec.yml
  specs/osquerybeat.spec.yml
  specs/packetbeat.spec.yml
Labels: bug, Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent, skip-changelog, backport-v8.6.0

#2031 [automation] update elastic stack version for testing 8.6.0-2d1af9b1
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#2030 [automation] update elastic stack version for testing 8.7.0-d6e7f5ec
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#2032 [automation] update elastic stack version for testing 8.5.4-2ce7df52
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#2034 Normalise dataset name for service logs monitor
  internal/pkg/agent/application/monitoring/v1_monitor.go
Labels: Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent, skip-changelog, backport-v8.6.0
