Repository elastic/elastic-agent, pull requests merged in 2022-07, with the labels that each got.

#656 [automation] update elastic stack version for testing 8.4.0-3d206b5d
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#661 [automation] update elastic stack version for testing 8.4.0-3ad82aa8
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#658 jjbb: exclude allowed branches, tags and PRs
  .ci/jobs/elastic-agent-mbp.yml
Labels: Team:Automation, automation, backport-skip

#649 Update elastic-agent-project-board.yml
  .github/workflows/elastic-agent-project-board.yml
Labels: backport-skip

#659 ci: fix labels that clashes with the Orka workers
  .ci/Jenkinsfile
Labels: backport-v8.3.0, backport-v8.4.0

#668 [automation] update elastic stack version for testing 8.4.0-03bd6f3f
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#667 [automation] update elastic stack version for testing 8.3.2-d34285fd
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#671 [Release] Update test environments for 8.3.2
  testing/environments/latest.yml
Labels: Team:Automation, release

#670 docs: update docs versions 8.3.2
  deploy/kubernetes/elastic-agent-managed-kubernetes.yaml
  deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml
  version/docs/version.asciidoc
Labels: Team:Automation, release, docs, in progress

#675 [automation] update elastic stack version for testing 8.4.0-533f1e30
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#676 [automation] update elastic stack version for testing 8.3.2-56253b46
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#674 Osquerybeat: Fix osquerybeat is not running with logstash output
  internal/pkg/agent/program/supported.go
  internal/spec/osquerybeat.yml
Labels: bug, Team:Asset Mgt, backport-v8.3.0

#684 [automation] update elastic stack version for testing 8.4.0-d0a4da44
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#672 [Release] Update version to 8.3.3
  version/version.go
Labels: Team:Automation, release

#703 [automation] update elastic stack version for testing 8.4.0-dd98ded4
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#702 [automation] update elastic stack version for testing 8.3.3-385d4fdb
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#704 [automation] update elastic stack version for testing 8.3.3-46b07667
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#705 [automation] update elastic stack version for testing 8.4.0-164d9a10
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#711 Add missing license headers
  internal/pkg/core/status/handler.go
  internal/pkg/testutils/status_reporter.go
Labels: Team:Elastic-Agent-Control-Plane, backport-skip, Cleanup

#713 [automation] update elastic stack version for testing 8.4.0-00048b66
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#680 Fix transpiler to allow : in dynamic variables.
  CHANGELOG.next.asciidoc
  internal/pkg/agent/transpiler/vars.go
  internal/pkg/agent/transpiler/vars_test.go
Labels: bug, Team:Elastic-Agent-Control-Plane, backport-v8.3.0

#645 V2 Runtime Component Manager
  .gitignore
  internal/pkg/agent/cmd/container.go
  internal/pkg/agent/cmd/enroll_cmd.go
  internal/pkg/agent/configuration/settings.go
  internal/pkg/agent/operation/common_test.go
  internal/pkg/agent/operation/monitoring_test.go
  internal/pkg/agent/storage/encrypted_disk_storage_windows_linux_test.go
  internal/pkg/artifact/install/atomic/atomic_installer.go
  internal/pkg/core/monitoring/server/processes_test.go
  internal/pkg/core/plugin/process/app.go
  internal/pkg/core/plugin/process/start.go
  internal/pkg/core/plugin/process/status.go
  internal/pkg/core/plugin/service/app.go
  internal/pkg/core/process/process.go
  internal/pkg/core/state/state.go
  magefile.go
  main.go
  pkg/component/fake/README.md
  pkg/component/fake/main.go
  pkg/component/runtime/command.go
  pkg/component/runtime/failed.go
  pkg/component/runtime/manager.go
  pkg/component/runtime/manager_test.go
  pkg/component/runtime/runtime.go
  pkg/component/runtime/runtime_comm.go
  pkg/component/runtime/subscription.go
  pkg/component/spec.go
  pkg/core/process/cmd.go
  pkg/core/process/cmd_darwin.go
  pkg/core/process/cmd_linux.go
  pkg/core/process/config.go
  pkg/core/process/external_unix.go
  pkg/core/process/external_windows.go
  pkg/core/process/job_unix.go
  pkg/core/process/job_windows.go
  pkg/core/process/process.go
Labels: Team:Elastic-Agent-Control-Plane, V2-Architecture

#720 [automation] update elastic stack version for testing 8.3.3-fba30f71
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#700 Fix for the filebeat spec file picking up packetbeat inputs
  CHANGELOG.next.asciidoc
  internal/pkg/agent/program/supported.go
  internal/pkg/agent/program/testdata/single_config-packetbeat.yml
  internal/pkg/agent/program/testdata/single_config.yml
  internal/spec/filebeat.yml
Labels: bug, Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent-Data-Plane, backport-v8.3.0

#724 [automation] update elastic stack version for testing 8.4.0-3cd57abb
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#727 [automation] update elastic stack version for testing 8.4.0-a324b98b
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#728 [automation] update elastic stack version for testing 8.3.3-99553f72
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#696 ci: run on MacOS12
  .ci/Jenkinsfile
Labels: Team:Automation, automation, backport-v8.3.0, backport-v8.4.0

#732 [automation] update elastic stack version for testing 8.4.0-31315ca3
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#733 [automation] update elastic stack version for testing 8.3.3-302be7c1
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#734 fix typo on package command
  README.md
Labels: backport-v8.3.0

#718 Allow / to be used in variable names
  CHANGELOG.next.asciidoc
  internal/pkg/agent/transpiler/vars.go
  internal/pkg/agent/transpiler/vars_test.go
  internal/pkg/composable/providers/kubernetes/node_test.go
  internal/pkg/composable/providers/kubernetes/pod_test.go
  internal/pkg/composable/providers/kubernetes/service_test.go
  internal/pkg/eql/Eql.g4
  internal/pkg/eql/eql_test.go
  internal/pkg/eql/parser/EqlLexer.interp
  internal/pkg/eql/parser/eql_lexer.go
Labels: bug, Team:Elastic-Agent-Control-Plane, backport-v8.3.0

#746 [automation] update elastic stack version for testing 8.4.0-31269fd2
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#747 [automation] update elastic stack version for testing 8.3.3-e5bc7e69
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#743 Wrap errors and fix some docs typo and convention
  internal/pkg/agent/application/info/agent_id.go
  internal/pkg/agent/application/info/agent_metadata.go
  internal/pkg/agent/storage/encrypted_disk_store.go
  internal/pkg/agent/vault/vault_darwin.go
  internal/pkg/agent/vault/vault_linux.go
Labels: enhancement, backport-skip

#679 automate the ironbank docker context generation
  .ci/Jenkinsfile
  .gitignore
  dev-tools/packaging/files/ironbank/LICENSE
  dev-tools/packaging/files/ironbank/config/docker-entrypoint
  dev-tools/packaging/templates/ironbank/Dockerfile.tmpl
  dev-tools/packaging/templates/ironbank/README.md.tmpl
  dev-tools/packaging/templates/ironbank/hardening_manifest.yaml.tmpl
  magefile.go
Labels: Team:Automation, automation, backport-v8.3.0, backport-v8.4.0

#730 fix flaky test TestDownloadBodyError
  internal/pkg/artifact/download/http/downloader_test.go
Labels: Team:Elastic-Agent-Control-Plane, backport-v8.3.0

#739 docs: update docs versions 8.3.3
  deploy/kubernetes/elastic-agent-managed-kubernetes.yaml
  deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml
  version/docs/version.asciidoc
Labels: Team:Automation, release, docs, in progress

#765 [automation] update elastic stack version for testing 8.3.3-bb633b08
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#742 Add filestream ID on standalone kubernetes manifest
  CHANGELOG.next.asciidoc
  deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml
  deploy/kubernetes/elastic-agent-standalone/elastic-agent-standalone-daemonset-configmap.yaml
Labels: bug, Team:Elastic-Agent-Data-Plane, backport-v8.3.0

#769 Alter github action to run on different OSs
  .github/workflows/golangci-lint.yml
  internal/pkg/agent/application/secret/secret.go
Labels: Team:Elastic-Agent-Control-Plane, backport-skip, Cleanup

#771 [automation] update elastic stack version for testing 8.4.0-d058e92f
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#708 elastic-agent manifests: add comments; add cloudnative team as a codeowner for the k8s manifests
  .github/CODEOWNERS
  deploy/kubernetes/elastic-agent-managed-kubernetes.yaml
  deploy/kubernetes/elastic-agent-managed/elastic-agent-managed-daemonset.yaml
  deploy/kubernetes/elastic-agent-managed/elastic-agent-managed-role.yaml
  deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml
  deploy/kubernetes/elastic-agent-standalone/elastic-agent-standalone-daemonset-configmap.yaml
  deploy/kubernetes/elastic-agent-standalone/elastic-agent-standalone-daemonset.yaml
  deploy/kubernetes/elastic-agent-standalone/elastic-agent-standalone-role.yaml
Labels: enhancement, backport-skip

#774 [automation] update elastic stack version for testing 8.3.3-d520d440
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#686 [Elastic-Agent] Added source uri reloading
  internal/pkg/agent/application/managed_mode.go
  internal/pkg/agent/application/pipeline/actions/handlers/handler_action_policy_change.go
  internal/pkg/agent/application/pipeline/actions/handlers/handler_action_policy_change_test.go
  internal/pkg/artifact/config.go
Labels: enhancement, Team:Elastic-Agent-Control-Plane, backport-skip, v8.5.0

#752 Update will cleanup unneeded artifacts.
  CHANGELOG.next.asciidoc
  internal/pkg/agent/application/upgrade/cleanup.go
  internal/pkg/agent/application/upgrade/cleanup_test.go
  internal/pkg/agent/application/upgrade/upgrade.go
Labels: bug, Team:Elastic-Agent-Control-Plane, backport-skip

#784 backport: Add 8.4 branch
  .mergify.yml
Labels: Team:Automation, impact:critical, backport-skip, release

#793 Update main to 8.5.0
  version/version.go
Labels: Team:Elastic-Agent-Control-Plane, backport-skip

#726 [automation] Update go release version 1.17.12
  .go-version
  Dockerfile
  version/docs/version.asciidoc
Labels: automation, dependency, backport-v8.4.0

#800 [automation] update elastic stack version for testing 8.3.3-8631d33c
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#799 [automation] update elastic stack version for testing 8.4.0-60171339
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#740 [Release] Update version to 8.3.4
  version/version.go
Labels: Team:Automation, release

#741 [Release] Update test environments for 8.3.4
  testing/environments/latest.yml
Labels: Team:Automation, release

#802 update dependency elastic/go-structform from v0.0.9 to v0.0.10
  NOTICE.txt
  go.mod
  go.sum
Labels: enhancement, Team:Elastic-Agent, Team:Elastic-Agent-Data-Plane, backport-skip
