Repository elastic/elastic-agent, pull requests merged in 2022-06, with the labels that each got.

#489 [automation] update elastic stack version for testing 8.3.0-4644f7c7
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#490 [automation] update elastic stack version for testing 8.4.0-481759a3
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#497 [automation] update elastic stack version for testing 8.4.0-df27a645
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#485 Fix linter issues with doc strings
  internal/pkg/agent/application/secret/secret.go
  internal/pkg/agent/storage/encrypted_disk_store.go
  internal/pkg/agent/storage/storage.go
  internal/pkg/agent/vault/aesgcm.go
  internal/pkg/agent/vault/vault_darwin.go
  internal/pkg/testutils/testutils.go
Labels: Team:Elastic-Agent-Control-Plane, backport-skip, Cleanup

#504 [backport 8.3]: Fix Agent failing to run in standalone mode (#501)
  internal/pkg/agent/cmd/run.go
Labels: bug, v8.3.0, backport

#506 [automation] update elastic stack version for testing 8.3.0-378ebcca
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#505 [automation] update elastic stack version for testing 8.4.0-3525aaf7
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#510 [v2] Add component spec command to validate component specifications
  internal/pkg/agent/cmd/common.go
  internal/pkg/agent/cmd/component.go
  internal/pkg/agent/cmd/component_spec.go
Labels: Team:Elastic-Agent-Control-Plane

#516 [automation] update elastic stack version for testing 8.4.0-42ce0eef
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#519 [automation] update elastic stack version for testing 8.3.0-f530a93f
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#518 [automation] update elastic stack version for testing 8.4.0-b8fce3f8
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#531 [automation] update elastic stack version for testing 8.3.0-3c22a7f7
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#538 [automation] update elastic stack version for testing 8.4.0-a27cbcfa
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#543 [automation] update elastic stack version for testing 8.3.0-db012561
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#541 [automation] update elastic stack version for testing 8.4.0-3bedeef4
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#537 added cloudbeat to packages.yml
  dev-tools/packaging/packages.yml
Labels: backport-v8.3.0

#529 Config encryption: Fix the vault possible race conditions, harden the code for concurrent access
  NOTICE.txt
  go.mod
  internal/pkg/agent/application/secret/secret.go
  internal/pkg/agent/storage/encrypted_disk_storage_windows_linux_test.go
  internal/pkg/agent/vault/seed.go
  internal/pkg/agent/vault/seed_test.go
  internal/pkg/agent/vault/vault_darwin.go
  internal/pkg/agent/vault/vault_key.go
  internal/pkg/agent/vault/vault_linux.go
  internal/pkg/agent/vault/vault_test.go
  internal/pkg/agent/vault/vault_windows.go
  internal/pkg/core/plugin/process/stdlogger.go
  internal/pkg/core/plugin/process/stdlogger_test.go
  pkg/core/logger/testing.go
Labels: bug, v8.3.0, backport-v8.3.0

#546 [backport 8.3] Config encryption: Fix the vault possible race conditions, harden the code for concurrent access (#529)
  NOTICE.txt
  go.mod
  internal/pkg/agent/application/secret/secret.go
  internal/pkg/agent/storage/encrypted_disk_storage_windows_linux_test.go
  internal/pkg/agent/vault/seed.go
  internal/pkg/agent/vault/seed_test.go
  internal/pkg/agent/vault/vault_darwin.go
  internal/pkg/agent/vault/vault_key.go
  internal/pkg/agent/vault/vault_linux.go
  internal/pkg/agent/vault/vault_test.go
  internal/pkg/agent/vault/vault_windows.go
  internal/pkg/core/plugin/process/stdlogger.go
  internal/pkg/core/plugin/process/stdlogger_test.go
  pkg/core/logger/testing.go
Labels: bug, v8.3.0, backport

#551 [automation] update elastic stack version for testing 8.3.0-e4e76686
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#552 [automation] update elastic stack version for testing 8.4.0-7e67f5d9
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#557 [automation] update elastic stack version for testing 8.4.0-40cff009
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#558 [automation] update elastic stack version for testing 8.3.0-460dc667
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#550 [v2] Calculate the expected runtime components from policy
  NOTICE.txt
  control.proto
  go.mod
  go.sum
  internal/pkg/agent/cmd/diagnostics.go
  internal/pkg/agent/cmd/enroll_cmd.go
  internal/pkg/agent/control/client/client.go
  internal/pkg/agent/control/cproto/control.pb.go
  internal/pkg/agent/control/cproto/control_grpc.pb.go
  internal/pkg/agent/control/server/server.go
  internal/pkg/agent/operation/tests/scripts/serviceable-1.0-darwin-x86_64/main.go
  magefile.go
  pkg/component/component.go
  pkg/component/component_test.go
  pkg/component/load.go
  pkg/component/load_test.go
  pkg/component/platforms.go
  pkg/component/spec.go
  pkg/component/spec_test.go
  pkg/core/server/server.go
  specs/apm-server.spec.yml
  specs/auditbeat.spec.yml
  specs/cloudbeat.spec.yml
  specs/endpoint-security.spec.yml
  specs/filebeat.spec.yml
  specs/fleet-server.spec.yml
  specs/heartbeat.spec.yml
  specs/metricbeat.spec.yml
  specs/osquerybeat.spec.yml
  specs/packetbeat.spec.yml
Labels: Team:Elastic-Agent-Control-Plane

#559 Update to 8.2.4
  version/version.go
Labels: Team:Elastic-Agent-Control-Plane

#562 [automation] update elastic stack version for testing 8.3.0-fe62331f
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#564 [automation] update elastic stack version for testing 8.4.0-5e6770b1
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#565 [automation] update elastic stack version for testing 8.2.4-4cc4fbfd
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#560 Fix regression and use comma separated values
  .ci/Jenkinsfile
Labels: Team:Elastic-Agent-Control-Plane, backport-v8.4.0

#568 Change in Jenkinsfile will trigger k8s run
  .ci/Jenkinsfile
Labels: Team:Elastic-Agent-Control-Plane, backport-skip, backport-v8.3.0, backport-v8.4.0

#573 [automation] update elastic stack version for testing 8.4.0-da5a1c6d
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#574 [automation] update elastic stack version for testing 8.2.4-01ccaf06
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#527 Add `@metadata.input_id` and `@metadata.stream_id` when injecting streams
  CHANGELOG.next.asciidoc
  internal/pkg/agent/program/testdata/audit_config-auditbeat.yml
  internal/pkg/agent/program/testdata/logstash_config-metricbeat.yml
  internal/pkg/agent/program/testdata/namespace-metricbeat.yml
  internal/pkg/agent/program/testdata/single_config-metricbeat.yml
  internal/pkg/agent/program/testdata/usecases/generated/namespace.metricbeat.golden.yml
  internal/pkg/agent/program/testdata/usecases/generated/single_config.filebeat.golden.yml
  internal/pkg/agent/program/testdata/usecases/generated/single_config.metricbeat.golden.yml
  internal/pkg/agent/transpiler/rules.go
  internal/pkg/agent/transpiler/rules_test.go
Labels: enhancement, backport-skip, v8.4.0

#570 Add filemod times to contents of diagnostics collect command
  CHANGELOG.next.asciidoc
  internal/pkg/agent/cmd/diagnostics.go
Labels: bug, Team:Elastic-Agent-Control-Plane, backport-skip

#579 [automation] update elastic stack version for testing 8.3.0-75d7500e
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#581 [automation] update elastic stack version for testing 8.4.0-b13123ee
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#580 [automation] update elastic stack version for testing 8.2.4-698e06ec
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#578 Fix Agent upgrade 8.2->8.3
  internal/pkg/agent/application/upgrade/step_mark.go
  internal/pkg/agent/application/upgrade/upgrade.go
  internal/pkg/agent/cleaner/cleaner.go
  internal/pkg/agent/cleaner/cleaner_test.go
  internal/pkg/agent/cmd/run.go
  internal/pkg/fileutil/fileutil.go
Labels: bug, v8.3.0, backport-v8.3.0

#584 [automation] update elastic stack version for testing 8.3.0-6d4bb852
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#585 [automation] update elastic stack version for testing 8.2.4-b657c8f5
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#588 [automation] update elastic stack version for testing 8.2.4-589bdf37
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#589 [automation] update elastic stack version for testing 8.3.0-e0057e17
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#590 [automation] update elastic stack version for testing 8.2.4-a34570b4
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#591 [automation] update elastic stack version for testing 8.4.0-4fe26f2a
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#594 Set explicit ExitTimeOut for MacOS agent launchd plist
  internal/pkg/agent/install/svc.go
Labels: bug, v8.3.0, v8.4.0, backport-v8.3.0

#598 [automation] update elastic stack version for testing 8.3.0-47d97929
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#599 [automation] update elastic stack version for testing 8.4.0-2e32a640
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#597 [automation] update elastic stack version for testing 8.2.4-b5aa40e4
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#595 ci: enable build notifications as GitHub issues
  .ci/Jenkinsfile
Labels: Team:Automation, automation, backport-v8.3.0, backport-v8.4.0

#569 status identifies failing component, fleet gateway may report degraded, liveness endpoint added
  CHANGELOG.next.asciidoc
  internal/pkg/agent/application/gateway/fleet/fleet_gateway.go
  internal/pkg/agent/application/gateway/fleet/fleet_gateway_test.go
  internal/pkg/agent/application/gateway/fleet/noop_status_controller_test.go
  internal/pkg/agent/cmd/run.go
  internal/pkg/core/monitoring/server/server.go
  internal/pkg/core/status/handler.go
  internal/pkg/core/status/reporter.go
  internal/pkg/core/status/reporter_test.go
  internal/pkg/testutils/status_reporter.go
Labels: enhancement, Team:Elastic-Agent-Control-Plane, backport-skip

#561 V1 controller with agent
  dev-tools/packaging/packages.yml
  internal/pkg/agent/program/supported.go
  internal/spec/elastic-agent-shipper.spec.yml
  magefile.go
Labels: Team:Elastic-Agent-Data-Plane, v8.4.0, backport-v8.4.0

#608 [automation] update elastic stack version for testing 8.3.0-3b390c7b
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#607 [automation] update elastic stack version for testing 8.4.0-722a7d79
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#609 [automation] update elastic stack version for testing 8.2.4-32b57cbe
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#605 ci: enable flaky test detector
  .ci/Jenkinsfile
Labels: backport-v8.3.0, backport-v8.4.0

#620 [automation] update elastic stack version for testing 8.4.0-210dd487
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#619 [automation] update elastic stack version for testing 8.3.0-fdf97a2e
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#618 [automation] update elastic stack version for testing 8.2.4-b7bb3a0c
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#615 mergify: remove backport automation for non active branches
  .mergify.yml
Labels: Team:Automation, automation, backport-skip

#631 [automation] update elastic stack version for testing 8.4.0-a6aa9f3b
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#630 [automation] update elastic stack version for testing 8.2.4-9b981623
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#632 update to 8.3.1
  version/version.go
Labels: Team:Elastic-Agent-Control-Plane

#458 Add macros pointing to new agent's repo. Fix necessary macro calls
  CHANGELOG.asciidoc
  CHANGELOG.next.asciidoc
Labels: documentation, v8.3.0, backport-skip

#528 Set hostPID=true for managed agent in k8s
  deploy/kubernetes/elastic-agent-managed-kubernetes.yaml
  deploy/kubernetes/elastic-agent-managed/elastic-agent-managed-daemonset.yaml
Labels: enhancement, backport-skip, v8.4.0

#648 [automation] update elastic stack version for testing 8.4.0-86cc80f3
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#646 [automation] update elastic stack version for testing 8.3.1-b95de5e6
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#647 [automation] update elastic stack version for testing 8.2.4-e7c42e26
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#521 Update elastic-agent-libs version: includes restriction on default VerificationMode to `full`
  CHANGELOG.next.asciidoc
  NOTICE.txt
  go.mod
  go.sum
Labels: Team:Elastic-Agent-Control-Plane, ci:end-to-end, backport-skip, v8.4.0

#566 Redact sensitive information in diagnostics collect command
  CHANGELOG.next.asciidoc
  internal/pkg/agent/cmd/diagnostics.go
  internal/pkg/agent/cmd/diagnostics_test.go
Labels: enhancement, backport-skip, v8.4.0

#638 Support Cloudbeat regex input type
  internal/pkg/agent/program/supported.go
  internal/spec/cloudbeat.yml
Labels: enhancement, 8.4-candidate, backport-v8.4.0

#641 Disable flaky test download test
  internal/pkg/artifact/download/http/downloader_test.go
Labels: Team:Elastic-Agent-Control-Plane, backport-skip
