Repository elastic/elastic-agent, pull requests merged in 2022-11, with the labels that each got.

#1661 [automation] update elastic stack version for testing 8.4.4-55734bd7
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1660 [automation] update elastic stack version for testing 8.6.0-26dc1164
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1255 [Release] Update version to 8.5.1
  version/version.go
Labels: Team:Automation, release

#1256 [Release] Update test environments for 8.5.1
  testing/environments/latest.yml
Labels: Team:Automation, release, skip-changelog

#1642 Generate the consolidated 8.5.0 changelog.
  README.md
  changelog/8.5.0.yaml
  changelog/fragments/1660139385-Fix-a-panic-caused-by-a-race-condition-when-installing-the-Elastic-Agent.yaml
  changelog/fragments/1660158319-Upgrade-to-Go-118-Certificates-signed-with-SHA-1-are-now-rejected-See-the-Go-118.yaml
  changelog/fragments/1661188787-Add-lumberjack-input-type-to-the-Filebeat-spec.yaml
  changelog/fragments/1663143487-Add-support-for-hints-based-autodiscovery-in-kubernetes-provider.yaml
  changelog/fragments/1664177394-Fix-unintended-reset-of-source-URI-when-downloading-components.yaml
  changelog/fragments/1664212969-Create-separate-status-reporter-for-local-only-events-so-that-degraded-fleet-che.yaml
  changelog/fragments/1664230732-Improve-logging-during-upgrades.yaml
  changelog/fragments/1664360554-Add-success-log-message-after-previous-checkin-failures.yaml
  changelog/fragments/1664989867-fix-docker-provider-processors.yaml
  changelog/fragments/1665517984-improve-checkin-error-logging.yaml
  changelog/fragments/1666088774-Fix-admin-permission-check-on-localized-windows.yaml
Labels: Team:Elastic-Agent, skip-changelog

#1670 Forward port: Generate the consolidated 8.5.0 changelog. (#1642)
  README.md
  changelog/8.5.0.yaml
  changelog/fragments/1660139385-Fix-a-panic-caused-by-a-race-condition-when-installing-the-Elastic-Agent.yaml
  changelog/fragments/1660158319-Upgrade-to-Go-118-Certificates-signed-with-SHA-1-are-now-rejected-See-the-Go-118.yaml
  changelog/fragments/1661188787-Add-lumberjack-input-type-to-the-Filebeat-spec.yaml
  changelog/fragments/1663143487-Add-support-for-hints-based-autodiscovery-in-kubernetes-provider.yaml
  changelog/fragments/1664177394-Fix-unintended-reset-of-source-URI-when-downloading-components.yaml
  changelog/fragments/1664212969-Create-separate-status-reporter-for-local-only-events-so-that-degraded-fleet-che.yaml
  changelog/fragments/1664230732-Improve-logging-during-upgrades.yaml
  changelog/fragments/1664360554-Add-success-log-message-after-previous-checkin-failures.yaml
  changelog/fragments/1664989867-fix-docker-provider-processors.yaml
  changelog/fragments/1665517984-improve-checkin-error-logging.yaml
  changelog/fragments/1666088774-Fix-admin-permission-check-on-localized-windows.yaml
Labels: backport-skip, skip-changelog

#1674 [automation] update elastic stack version for testing 8.6.0-4765d2b0
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1682 [automation] update elastic stack version for testing 8.6.0-8a615646
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1653 Sync components with state during container start
  internal/pkg/agent/application/paths/common.go
  internal/pkg/agent/cmd/container.go
Labels: bug, Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent, skip-changelog

#1686 [automation] update elastic stack version for testing 8.5.1-7fd6ffae
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1685 [automation] update elastic stack version for testing 8.6.0-3f5f98b7
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1539 Remove non-agent Dockerfile templates.
  dev-tools/packaging/templates/docker/Dockerfile.tmpl
  dev-tools/packaging/templates/docker/docker-entrypoint.tmpl
Labels: backport-skip, Cleanup, skip-changelog

#1693 [automation] update elastic stack version for testing 8.5.1-2ceb7fad
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1692 [automation] update elastic stack version for testing 8.6.0-f20b7179
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1691 [automation] Update go release version 1.18.8
  .go-version
  Dockerfile
  version/docs/version.asciidoc
Labels: automation, dependency, backport-skip

#1696 [automation] update elastic stack version for testing 8.6.0-da453972
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1695 [automation] update elastic stack version for testing 8.5.1-2041424b
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1326 [Release] Update test environments for 8.4.4
  testing/environments/latest.yml
Labels: Team:Automation, release

#1711 [automation] update elastic stack version for testing 8.5.1-1f91140d
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1714 [automation] update elastic stack version for testing 8.5.1-d7343c55
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1716 Fix components permissions on build
  dev-tools/packaging/templates/docker/Dockerfile.elastic-agent.tmpl
  magefile.go
Labels: bug, backport-skip, skip-changelog

#1717 Remove released changelog fragments.
  changelog/fragments/1660139385-Fix-a-panic-caused-by-a-race-condition-when-installing-the-Elastic-Agent.yaml
  changelog/fragments/1660158319-Upgrade-to-Go-118-Certificates-signed-with-SHA-1-are-now-rejected-See-the-Go-118.yaml
  changelog/fragments/1661188787-Add-lumberjack-input-type-to-the-Filebeat-spec.yaml
  changelog/fragments/1663143487-Add-support-for-hints-based-autodiscovery-in-kubernetes-provider.yaml
  changelog/fragments/1664177394-Fix-unintended-reset-of-source-URI-when-downloading-components.yaml
  changelog/fragments/1664212969-Create-separate-status-reporter-for-local-only-events-so-that-degraded-fleet-che.yaml
  changelog/fragments/1664230732-Improve-logging-during-upgrades.yaml
  changelog/fragments/1664360554-Add-success-log-message-after-previous-checkin-failures.yaml
  changelog/fragments/1664989867-fix-docker-provider-processors.yaml
  changelog/fragments/1665517984-improve-checkin-error-logging.yaml
  changelog/fragments/1666088774-Fix-admin-permission-check-on-localized-windows.yaml
Labels: Team:Elastic-Agent, backport-skip, Cleanup

#1720 [automation] update elastic stack version for testing 8.5.1-49e04c16
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1719 filebeat.spec: make Common Expression Languate input available
  changelog/fragments/1668483030-common-expression-language.yaml
  specs/filebeat.spec.yml
Labels: enhancement, Team:Security-External Integrations, backport-skip, 8.6-candidate

#1699 [Release] Update version to 8.5.2
  version/version.go
Labels: Team:Automation, release

#1698 docs: update docs versions 8.5.1
  deploy/kubernetes/elastic-agent-managed-kubernetes.yaml
  deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml
  version/docs/version.asciidoc
Labels: Team:Automation, release, docs, in progress

#1723 Sort config source for TestToComponents
  pkg/component/component_test.go
Labels: bug, Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent, backport-skip, skip-changelog

#1718 Use protocmp instead of assert.Equal in component test
  pkg/component/component_test.go
Labels: Team:Elastic-Agent, backport-skip, v8.6.0, skip-changelog

#1730 [automation] update elastic stack version for testing 8.6.0-9a0f87a9
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1732 backport: Add 8.6 branch
  .mergify.yml
Labels: Team:Automation, impact:critical, backport-skip, release

#1745 V2: Provide fleet configuration to APM server
  changelog/fragments/1668645651-apm-fleet-config.yaml
  internal/pkg/agent/application/application.go
  internal/pkg/agent/application/fleet_server_bootstrap.go
Labels: bug, backport-v8.6.0

#1735 monitoring: fix JSON logs parsing for Beats
  changelog/fragments/1668591286-fix-beats-logs.yaml
  internal/pkg/agent/application/monitoring/v1_monitor.go
Labels: Team:Elastic-Agent-Control-Plane, backport-v8.6.0

#1752 Github action clean up
  .github/workflows/elastic-agent-project-board.yml
Labels: backport-skip

#1748 V2: fix monitoring for APM Server
  changelog/fragments/1668679987-apm-monitoring.yaml
  internal/pkg/agent/application/monitoring/v1_monitor.go
Labels: bug, backport-v8.6.0

#1755 [automation] update elastic stack version for testing 8.5.2-733d317b
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1754 [automation] update elastic stack version for testing 8.7.0-eb092238
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1758 [automation] update elastic stack version for testing 8.7.0-84b6e00d
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1759 [automation] update elastic stack version for testing 8.5.2-13a22054
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1767 Inject input.policy.revision without overwriting.
  pkg/component/component.go
  pkg/component/component_test.go
Labels: skip-changelog, backport-v8.6.0

#1770 [automation] update elastic stack version for testing 8.5.2-c2e5a3f4
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1769 [automation] update elastic stack version for testing 8.6.0-e72cd235
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1742 [Release] Update version to 8.5.3
  version/version.go
Labels: Team:Automation, release

#1740 docs: update docs versions 8.5.2
  deploy/kubernetes/elastic-agent-managed-kubernetes.yaml
  deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml
  version/docs/version.asciidoc
Labels: Team:Automation, release, docs, in progress

#1741 [Release] Update test environments for 8.5.2
  testing/environments/latest.yml
Labels: Team:Automation, release

#1743 [Release] Update test environments for 8.5.3
  testing/environments/latest.yml
Labels: Team:Automation, release

#1775 [automation] update elastic stack version for testing 8.5.2-98bdbc90
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1776 [automation] update elastic stack version for testing 8.6.0-3747fc18
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1774 [automation] update elastic stack version for testing 8.7.0-c5c709bf
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1773 Re-implement processes route to restore compatibility with the current cloud health checks
  changelog/fragments/1669159455-reimplement-processes-route.yaml
  internal/pkg/agent/application/monitoring/error.go
  internal/pkg/agent/application/monitoring/process.go
  internal/pkg/agent/application/monitoring/processes.go
  internal/pkg/agent/application/monitoring/server.go
  internal/pkg/agent/cmd/run.go
  pkg/component/runtime/manager.go
Labels: bug, enhancement, skip-changelog, backport-v8.6.0

#1781 Fix APM server not being available in cloud.
  internal/pkg/agent/application/monitoring/processes.go
Labels: skip-changelog, backport-v8.6.0

#1784 [automation] update elastic stack version for testing 8.6.0-742fd135
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1783 [automation] update elastic stack version for testing 8.7.0-11ac5926
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1785 [automation] update elastic stack version for testing 8.5.3-760caed9
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1779 Fix upgrade under V2
  internal/pkg/agent/application/coordinator/coordinator.go
Labels: Team:Elastic-Agent-Control-Plane, backport-v8.6.0

#1792 Handle requests for /processes/apm-server.
  internal/pkg/agent/application/monitoring/process.go
  internal/pkg/agent/application/monitoring/processes.go
  internal/pkg/agent/application/monitoring/processes_cloud.go
  internal/pkg/agent/application/monitoring/processes_cloud_test.go
Labels: Team:Elastic-Agent, v8.6.0, skip-changelog, backport-v8.6.0

#1795 [automation] update elastic stack version for testing 8.6.0-94ebec53
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1796 [automation] update elastic stack version for testing 8.5.3-c0681f01
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1798 [automation] update elastic stack version for testing 8.6.0-3e06249e
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1799 [automation] update elastic stack version for testing 8.5.3-a0b682b9
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1777 Fix diagnostics failures on max message size limit
  _meta/config/common.p2.yml.tmpl
  _meta/config/common.reference.p2.yml.tmpl
  _meta/config/elastic-agent.docker.yml.tmpl
  control.proto
  elastic-agent.docker.yml
  elastic-agent.reference.yml
  elastic-agent.yml
  internal/pkg/agent/application/application.go
  internal/pkg/agent/cmd/run.go
  internal/pkg/agent/configuration/grpc.go
  internal/pkg/agent/control/client/client.go
  internal/pkg/agent/control/client/dial.go
  internal/pkg/agent/control/client/dial_windows.go
  internal/pkg/agent/control/control_test.go
  internal/pkg/agent/control/cproto/control.pb.go
  internal/pkg/agent/control/cproto/control_grpc.pb.go
  internal/pkg/agent/control/server/server.go
  internal/pkg/basecmd/version/cmd_test.go
  pkg/component/runtime/manager.go
  pkg/component/runtime/manager_test.go
Labels: bug, Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent, backport-skip, v8.6.0, skip-changelog

#1787 Support 'processes/stats' for agent, apm and fleet server
  internal/pkg/agent/application/monitoring/process.go
  internal/pkg/agent/application/monitoring/server.go
  internal/pkg/agent/application/monitoring/url.go
  internal/pkg/agent/application/monitoring/v1_monitor.go
  internal/pkg/agent/cmd/run.go
Labels: enhancement, Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent, backport-skip, skip-changelog

#1802 Include host in hosts
  internal/pkg/agent/application/fleet_server_bootstrap.go
  internal/pkg/agent/application/fleet_server_bootstrap_test.go
Labels: bug, Team:Elastic-Agent, backport-skip, skip-changelog

#1702 Capture stdout/stderr of spawned components
  .gitignore
  NOTICE.txt
  changelog/fragments/1669236059-Capture-stdout-stderr-of-all-spawned-components-to-simplify-logging.yaml
  go.mod
  go.sum
  internal/pkg/agent/application/monitoring/v1_monitor.go
  pkg/component/runtime/command.go
  pkg/component/runtime/log_writer.go
  pkg/component/runtime/log_writer_test.go
  pkg/component/runtime/runtime.go
  pkg/component/spec.go
  pkg/core/logger/logger.go
  specs/apm-server.spec.yml
  specs/auditbeat.spec.yml
  specs/cloudbeat.spec.yml
  specs/filebeat.spec.yml
  specs/heartbeat.spec.yml
  specs/metricbeat.spec.yml
  specs/osquerybeat.spec.yml
  specs/packetbeat.spec.yml
Labels: Team:Elastic-Agent-Control-Plane, v8.6.0, backport-v8.6.0

#1766 change syncExpected to use proto.Equal
  changelog/fragments/1669066497-struct-compare-unit-update.yaml
  pkg/component/runtime/state.go
Labels: bug, Team:Elastic-Agent, backport-v8.6.0

#1817 [automation] update elastic stack version for testing 8.5.3-770e9287
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1812 [Synthetics] Fix synthetics-browser integration name
  specs/heartbeat.spec.yml
Labels: bug, Team:Uptime, skip-changelog, backport-v8.6.0

#1805 Fix: Elastic-Agent fails to re-start during upgrade
  changelog/fragments/1669665017-fix-nil-action-ack-crash-after-local-upgrade.yaml
  internal/pkg/agent/application/upgrade/upgrade.go
Labels: enhancement, backport-v8.6.0

#1811 Fix erroneously created http url directory path for monitoring
  changelog/fragments/1669668741-fix-erroneous-http-url-directory-created-for-monitoring.yaml
  internal/pkg/agent/application/monitoring/server.go
  internal/pkg/agent/application/monitoring/server_test.go
Labels: bug, backport-v8.6.0

#1813 Drop events from monitoring components
  internal/pkg/agent/application/monitoring/v1_monitor.go
Labels: Team:Elastic-Agent-Control-Plane, backport-v8.6.0

#1827 Report uppercase Unit State
  NOTICE.txt
  go.mod
  go.sum
  internal/pkg/agent/application/coordinator/coordinator.go
  internal/pkg/agent/application/gateway/fleet/fleet_gateway.go
Labels: bug, Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent, skip-changelog, backport-v8.6.0

#1829 Fix osqueryd and osquery-extension.ext permissions
  changelog/fragments/1669739947-fix-osqueryd-and-osquery-extension.ext-permissions.yaml
  dev-tools/packaging/templates/docker/Dockerfile.elastic-agent.tmpl
Labels: bug, backport-v8.6.0

#1764 Added a spec for new cloud_defend integration input
  changelog/fragments/1669049916-CHANGELOG.asciidoc.yaml
  internal/pkg/agent/application/monitoring/v1_monitor.go
  pkg/component/load_test.go
  specs/cloud-defend.spec.yml
Labels: enhancement, backport-skip, v8.7.0

#1835 [automation] update elastic stack version for testing 8.5.3-a46b25ec
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1836 [automation] update elastic stack version for testing 8.6.0-ecfefdaf
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1837 docs: update docs versions 8.5.3
  deploy/kubernetes/elastic-agent-managed-kubernetes.yaml
  deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml
  version/docs/version.asciidoc
Labels: Team:Automation, release, docs, in progress

#1841 actions: use go-version-file: .go-version
  .github/workflows/changelog.yml
  .github/workflows/golangci-lint.yml
  .github/workflows/macos.yml
Labels: backport-v8.5.0, skip-changelog, backport-v8.6.0

#1845 [8.6] Use v1 data stream names for log shipping
  pkg/component/runtime/command.go
Labels: Team:Elastic-Agent-Control-Plane

#1848 Fix data_stream.dataset for metrics monitoring
  internal/pkg/agent/application/monitoring/v1_monitor.go
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog, backport-v8.6.0

#1834 Remove the changelog github action check.
  .github/workflows/changelog.yml
Labels: Team:Elastic-Agent, backport-v8.5.0, skip-changelog, backport-v8.6.0

#1854 [8.6] Use v1 data stream names for metric shipping
  internal/pkg/agent/application/monitoring/v1_monitor.go
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog
