Repository elastic/elastic-agent, pull requests merged in 2022-03, with the labels that each got.

#63 [automation] update elastic stack version for testing 8.2.0-43df679f
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#62 ci: enable windows-2022 support
  .ci/Jenkinsfile
Labels: backport-skip

#65 Move integration tests order
  .ci/Jenkinsfile
Labels: Team:Elastic-Agent-Control-Plane, backport-skip

#66 ci: windows os matrix and e2e/ITs for branches/tags
  .ci/Jenkinsfile
Labels: backport-skip

#71 [automation] update elastic stack version for testing 8.2.0-190af159
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#74 [automation] update elastic stack version for testing 8.2.0-a12f7069
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#76 Update github action workflow for board management
  .github/workflows/elastic-agent-project-board.yml
Labels: backport-skip

#73 [automation] Update go release version 1.17.8
  .go-version
  Dockerfile
  version/docs/version.asciidoc
Labels: automation, dependency, backport-skip

#194 Check errors in buildspec cmd and fix conflicting -out flag
  dev-tools/cmd/buildspec/buildspec.go
  internal/pkg/agent/program/supported.go
  internal/spec/filebeat.yml
Labels: backport-v8.2.0

#198 [automation] update elastic stack version for testing 8.2.0-63265ec9
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#201 [automation] update elastic stack version for testing 8.2.0-d02c907a
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#197 Add a base set of issues templates
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/ISSUE_TEMPLATE/flaky-test.md
  .github/ISSUE_TEMPLATE/question.md
Labels: Team:Elastic-Agent-Control-Plane, backport-skip

#199 Enable logstash output for endpoint, adding logstash/multioutput test
  internal/pkg/agent/program/program_test.go
  internal/pkg/agent/program/supported.go
  internal/pkg/agent/program/testdata/logstash_config-endpoint-security.yml
  internal/pkg/agent/program/testdata/logstash_config-filebeat-elasticsearch.yml
  internal/pkg/agent/program/testdata/logstash_config-filebeat.yml
  internal/pkg/agent/program/testdata/logstash_config-fleet-server.yml
  internal/pkg/agent/program/testdata/logstash_config-heartbeat.yml
  internal/pkg/agent/program/testdata/logstash_config-metricbeat.yml
  internal/pkg/agent/program/testdata/logstash_config-packetbeat.yml
  internal/pkg/agent/program/testdata/logstash_config.yml
  internal/spec/endpoint.yml
  magefile.go
Labels: enhancement, Team:Elastic-Agent-Control-Plane, backport-v8.2.0

#205 [automation] update elastic stack version for testing 8.2.0-fee3b8d2
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#206 [automation] update elastic stack version for testing 8.2.0-9bac538c
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#202 [Heartbeat] Unpack beats at build time on docker
  dev-tools/packaging/packages.yml
  dev-tools/packaging/templates/docker/Dockerfile.elastic-agent.tmpl
Labels: bug, Team:Elastic-Agent, Team:Uptime, v8.2.0, backport-skip

#187 Move the `context cancelled` error message into a debug statement
  CHANGELOG.next.asciidoc
  internal/pkg/agent/application/gateway/fleet/fleet_gateway.go
Labels: Team:Elastic-Agent-Control-Plane, ci:end-to-end, backport-v8.2.0

#209 [automation] update elastic stack version for testing 8.2.0-ff67d7b8
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#223 [automation] update elastic stack version for testing 8.2.0-82b803a1
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#225 Enhance process start errors and error logs
  CHANGELOG.next.asciidoc
  internal/pkg/core/plugin/process/start.go
Labels: Team:Elastic-Agent-Control-Plane, backport-v8.2.0

#228 [automation] update elastic stack version for testing 8.2.0-5cc993c1
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#229 [automation] update elastic stack version for testing 8.2.0-63942b4d
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#180 Instrumentation
  NOTICE.txt
  go.mod
  go.sum
  internal/pkg/agent/application/application.go
  internal/pkg/agent/application/fleet_server_bootstrap.go
  internal/pkg/agent/application/gateway/fleet/fleet_gateway.go
  internal/pkg/agent/application/gateway/fleet/fleet_gateway_test.go
  internal/pkg/agent/application/gateway/fleetserver/fleet_gateway_local.go
  internal/pkg/agent/application/local_mode.go
  internal/pkg/agent/application/managed_mode.go
  internal/pkg/agent/application/managed_mode_test.go
  internal/pkg/agent/application/once.go
  internal/pkg/agent/application/pipeline/actions/handlers/handler_action_policy_change.go
  internal/pkg/agent/application/pipeline/actions/handlers/handler_action_policy_change_test.go
  internal/pkg/agent/application/pipeline/actions/handlers/handler_action_unenroll.go
  internal/pkg/agent/application/pipeline/dispatcher/dispatcher.go
  internal/pkg/agent/application/pipeline/dispatcher/dispatcher_test.go
  internal/pkg/agent/application/pipeline/emitter/controller.go
  internal/pkg/agent/application/pipeline/emitter/emitter.go
  internal/pkg/agent/application/pipeline/pipeline.go
  internal/pkg/agent/application/pipeline/router/router.go
  internal/pkg/agent/application/pipeline/router/router_test.go
  internal/pkg/agent/application/pipeline/stream/operator_stream.go
  internal/pkg/agent/application/upgrade/step_download.go
  internal/pkg/agent/application/upgrade/upgrade.go
  internal/pkg/agent/cmd/diagnostics.go
  internal/pkg/agent/cmd/enroll_cmd.go
  internal/pkg/agent/cmd/inspect.go
  internal/pkg/agent/cmd/run.go
  internal/pkg/agent/control/client/client.go
  internal/pkg/agent/control/control_test.go
  internal/pkg/agent/control/proto/control.pb.go
  internal/pkg/agent/control/server/server.go
  internal/pkg/agent/operation/common_test.go
  internal/pkg/agent/operation/monitoring_test.go
  internal/pkg/agent/operation/operator.go
  internal/pkg/agent/storage/store/state_store.go
  internal/pkg/artifact/download/composed/downloader.go
  internal/pkg/artifact/download/fs/downloader.go
  internal/pkg/basecmd/version/cmd_test.go
  internal/pkg/core/monitoring/beats/beats_monitor.go
  internal/pkg/core/monitoring/config/config.go
  internal/pkg/core/monitoring/config/config_test.go
  internal/pkg/core/monitoring/server/server.go
  internal/pkg/core/server/config.go
  internal/pkg/core/server/config_test.go
  internal/pkg/core/server/server.go
  internal/pkg/core/server/server_test.go
  internal/pkg/fleetapi/ack_cmd.go
  internal/pkg/fleetapi/acker/fleet/fleet_acker.go
  internal/pkg/fleetapi/acker/lazy/lazy_acker.go
Labels: Team:Elastic-Agent-Control-Plane, ci:end-to-end, backport-skip

#232 Add apm instrumentation to changelog
  CHANGELOG.next.asciidoc
Labels: Team:Elastic-Agent-Control-Plane, v8.2.0, backport-skip

#200 Updated ack response schema and processing, add retrier for acks
  CHANGELOG.next.asciidoc
  internal/pkg/agent/application/managed_mode.go
  internal/pkg/fleetapi/ack_cmd.go
  internal/pkg/fleetapi/ack_cmd_test.go
  internal/pkg/fleetapi/acker/fleet/fleet_acker.go
  internal/pkg/fleetapi/acker/fleet/fleet_acker_test.go
  internal/pkg/fleetapi/acker/lazy/lazy_acker.go
  internal/pkg/fleetapi/acker/lazy/lazy_acker_test.go
  internal/pkg/fleetapi/acker/retrier/retrier.go
  internal/pkg/fleetapi/acker/retrier/retrier_test.go
Labels: Team:Elastic-Agent-Control-Plane, backport-skip

#236 [automation] update elastic stack version for testing 8.2.0-4509f321
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#203 Build darwin/aarch64 and universal binary
  .ci/Jenkinsfile
  CHANGELOG.next.asciidoc
  dev-tools/mage/common.go
  dev-tools/mage/crossbuild.go
  dev-tools/mage/pkg.go
  dev-tools/mage/pkgtypes.go
  dev-tools/mage/platforms.go
  dev-tools/mage/settings.go
  internal/pkg/artifact/artifact.go
  internal/pkg/artifact/config.go
  magefile.go
Labels: Team:Elastic-Agent-Control-Plane, ci:end-to-end, backport-skip

#182 Add non-interactive support
  internal/pkg/agent/cmd/install.go
Labels: Team:Elastic-Agent-Control-Plane, ci:end-to-end, backport-v8.2.0

#234 Force golangci-lint to run on every supported Os
  .github/workflows/golangci-lint.yml
Labels: Team:Elastic-Agent-Control-Plane, backport-v8.2.0

#211 Enable monitoring buffer for elastic-agent (#30471)
  CHANGELOG.next.asciidoc
  _meta/config/common.p2.yml.tmpl
  _meta/config/common.reference.p2.yml.tmpl
  _meta/config/elastic-agent.docker.yml.tmpl
  _meta/elastic-agent.yml
  control.proto
  elastic-agent.docker.yml
  elastic-agent.reference.yml
  elastic-agent.yml
  internal/pkg/agent/cmd/diagnostics.go
Labels: Team:Elastic-Agent-Control-Plane, ci:end-to-end, backport-skip

#244 Add the missing PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: backport-v8.2.0

#251 Not assemble darwin universal binary
  dev-tools/mage/crossbuild.go
  dev-tools/mage/pkg.go
  dev-tools/mage/pkgtypes.go
Labels: Team:Elastic-Agent-Control-Plane, v8.2.0, backport-skip

#243 Add fleet-server to elastic-agent inspect output
  CHANGELOG.next.asciidoc
  internal/pkg/agent/cmd/inspect.go
  internal/pkg/agent/cmd/inspect_test.go
Labels: debugging, backport-v8.2.0

#254 [automation] update elastic stack version for testing 8.2.0-dcff22d7
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#261 github actions: enable for branches
  .github/workflows/macos.yml
Labels: automation, backport-v8.2.0

#253 Change kibana api paths used in container command
  CHANGELOG.next.asciidoc
  internal/pkg/agent/cmd/container.go
Labels: Team:Elastic-Agent-Control-Plane, backport-v8.2.0, Cleanup

#226 Remove flags for policy defaulting
  CHANGELOG.next.asciidoc
  docs/fleet-server-bootstrap.asciidoc
  internal/pkg/agent/cmd/container.go
  internal/pkg/agent/cmd/container_test.go
  internal/pkg/agent/cmd/setup_config.go
Labels: enhancement, Team:Elastic-Agent-Control-Plane, v8.2.0, backport-v8.2.0

#183 Use `file` package from `github.com/elastic/elastic-agent-libs`
  NOTICE.txt
  dev-tools/mage/crossbuild.go
  go.mod
  go.sum
  internal/pkg/agent/application/upgrade/step_relink.go
  internal/pkg/agent/storage/disk_store.go
  internal/pkg/agent/storage/replace_store.go
  internal/pkg/core/logger/logger.go
Labels: Team:Elastic-Agent-Control-Plane, ci:end-to-end, backport-skip

#258 Move `platformcheck` and `common/proc` from libbeat
  NOTICE.txt
  go.mod
  internal/pkg/agent/cmd/platformcheck.go
  internal/pkg/agent/cmd/platformcheck_other.go
  internal/pkg/agent/cmd/platformcheck_test.go
  internal/pkg/agent/cmd/proc/job_unix.go
  internal/pkg/agent/cmd/proc/job_windows.go
  main.go
Labels: Team:Elastic-Agent-Control-Plane, backport-skip

#262 Simple fixes for the diagnostics command
  CHANGELOG.next.asciidoc
  internal/pkg/agent/cmd/diagnostics.go
  internal/pkg/agent/cmd/diagnostics_test.go
Labels: bug, Team:Elastic-Agent-Control-Plane, backport-v8.2.0

#255 Fix download verification in snapshot builds
  internal/pkg/agent/application/upgrade/step_download.go
  internal/pkg/agent/operation/common_test.go
  internal/pkg/agent/operation/operation_verify.go
  internal/pkg/artifact/download/composed/verifier.go
  internal/pkg/artifact/download/composed/verifier_test.go
  internal/pkg/artifact/download/fs/verifier.go
  internal/pkg/artifact/download/fs/verifier_test.go
  internal/pkg/artifact/download/http/elastic_test.go
  internal/pkg/artifact/download/http/verifier.go
  internal/pkg/artifact/download/verifier.go
Labels: Team:Elastic-Agent-Control-Plane, backport-v8.2.0

#249 Use `--whole-files` as golangci-lint argument
  .github/workflows/golangci-lint.yml
Labels: bug, Team:Elastic-Agent-Control-Plane, backport-v8.2.0

#259 no e2e if only docs
  .ci/Jenkinsfile
Labels: Team:Elastic-Agent-Control-Plane, backport-skip

#265 Update mage version in `makefile`
  Makefile
Labels: Team:Elastic-Agent-Control-Plane, backport-v8.2.0

#270 remove `-d` flag ad it only gets the package, does not install
  Makefile
  magefile.go
Labels: Team:Elastic-Agent-Control-Plane, backport-v8.2.0

#266 Update to 8.3.0
  version/version.go
Labels: Team:Elastic-Agent-Control-Plane, backport-skip

#268 Adjust mergify with the 8.2 branch
  .mergify.yml
Labels: Team:Elastic-Agent-Control-Plane, backport-skip

#263 Add changelog entry for Cloudbeat and the verifier
  CHANGELOG.next.asciidoc
Labels: Team:Elastic-Agent-Control-Plane, backport-v8.2.0
