Repository elastic/elastic-agent, pull requests merged in 2022-09, with the labels that each got.

#1065 [automation] update elastic stack version for testing 8.4.2-30e0a703
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1064 [automation] update elastic stack version for testing 8.5.0-b5001a6d
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1076 [automation] update elastic stack version for testing 8.4.2-48cedf17
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1082 [automation] update elastic stack version for testing 8.5.0-1bd77fc1
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1091 [automation] update elastic stack version for testing 8.5.0-167dfc80
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1044 Adding support for v1.25.0 k8s
  .ci/Jenkinsfile
Labels: backport-skip

#1102 [automation] update elastic stack version for testing 8.4.2-b244ddfa
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1101 [automation] update elastic stack version for testing 8.5.0-6b7dda2d
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1105 fixed docker build
  magefile.go
Labels: bug, V2-Architecture

#1061 V2 command work dir
  internal/pkg/agent/application/paths/common.go
  internal/pkg/agent/application/periodic.go
  internal/pkg/agent/cmd/install.go
  internal/pkg/agent/cmd/run.go
  internal/pkg/agent/cmd/uninstall.go
  internal/pkg/agent/transpiler/merge_strategy.go
  internal/pkg/agent/transpiler/rules.go
  internal/pkg/agent/transpiler/rules_test.go
  internal/pkg/agent/transpiler/steps.go
  internal/pkg/agent/transpiler/steps_test.go
  internal/pkg/agent/transpiler/tests/exec-1.0-darwin-x86_64/main.go
  magefile.go
  pkg/component/component.go
  pkg/component/component_test.go
  pkg/component/runtime/command.go
  pkg/component/runtime/manager_test.go
  pkg/component/spec.go
  pkg/utils/perm_unix.go
  pkg/utils/perm_windows.go
  pkg/utils/root_unix.go
  pkg/utils/root_windows.go
  pkg/utils/root_windows_test.go
  specs/endpoint-security.spec.yml
Labels: Team:Elastic-Agent-Control-Plane

#1114 [automation] update elastic stack version for testing 8.5.0-4140365c
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1106 Remove experimental warning log in upgrade command
  internal/pkg/agent/cmd/upgrade.go
Labels: bug, backport-v8.4.0

#1120 Update go.mod to Go 1.18, update notice.
  NOTICE.txt
  go.mod
  go.sum
Labels: backport-skip

#1134 [automation] update elastic stack version for testing 8.4.2-7c2154f4
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1130 Remove the fleet reporter
  CHANGELOG.next.asciidoc
  internal/pkg/agent/application/gateway/fleet/fleet_gateway.go
  internal/pkg/agent/application/gateway/fleet/fleet_gateway_test.go
  internal/pkg/agent/application/managed_mode.go
  internal/pkg/agent/configuration/fleet.go
  internal/pkg/fleetapi/checkin_cmd.go
  internal/pkg/reporter/fleet/config/config.go
  internal/pkg/reporter/fleet/reporter.go
  internal/pkg/reporter/fleet/reporter_test.go
Labels: bug, Team:Elastic-Agent-Control-Plane, backport-v8.4.0

#1147 [automation] update elastic stack version for testing 8.5.0-589a4a10
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1152 Avoid reporting `Unhealthy` on fleet connectivity issues
  internal/pkg/agent/application/gateway/fleet/fleet_gateway.go
  internal/pkg/agent/application/gateway/fleet/fleet_gateway_test.go
Labels: bug, Team:Elastic-Agent-Control-Plane, v8.5.0, backport-v8.4.0, backport-v8.5.0

#1123 ci: enable MacOS M1 stages
  .ci/Jenkinsfile
Labels: backport-v8.4.0, ci:extended-m1

#1143 [automation] Update go release version 1.18.6
  .go-version
  Dockerfile
  version/docs/version.asciidoc
Labels: automation, dependency, backport-skip

#1165 [automation] update elastic stack version for testing 8.5.0-37418cf3
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1164 [automation] update elastic stack version for testing 8.4.2-fda47f6e
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1108 Remove mage notice in favour of make notice
  README.md
  magefile.go
Labels: bug, backport-skip

#1169 ci: run e2e-testing at the end
  .ci/Jenkinsfile
Labels: backport-v8.4.0

#1175 ci: move macos to github actions
  .ci/Jenkinsfile
  .github/workflows/macos.yml
Labels: Team:Automation, automation, backport-v8.4.0, backport-v8.5.0

#1184 [automation] update elastic stack version for testing 8.4.2-4457f478
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1183 [automation] update elastic stack version for testing 8.5.0-fcf3d4c2
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#698 Add support for hints' based autodiscovery in kubernetes provider
  CHANGELOG.next.asciidoc
  NOTICE.txt
  go.mod
  go.sum
  internal/pkg/agent/application/local_mode.go
  internal/pkg/agent/application/managed_mode.go
  internal/pkg/agent/application/managed_mode_test.go
  internal/pkg/agent/cmd/inspect.go
  internal/pkg/agent/install/uninstall.go
  internal/pkg/composable/context.go
  internal/pkg/composable/controller.go
  internal/pkg/composable/controller_test.go
  internal/pkg/composable/dynamic.go
  internal/pkg/composable/providers/agent/agent.go
  internal/pkg/composable/providers/agent/agent_test.go
  internal/pkg/composable/providers/docker/docker.go
  internal/pkg/composable/providers/env/env.go
  internal/pkg/composable/providers/env/env_test.go
  internal/pkg/composable/providers/host/host.go
  internal/pkg/composable/providers/host/host_test.go
  internal/pkg/composable/providers/kubernetes/config.go
  internal/pkg/composable/providers/kubernetes/hints.go
  internal/pkg/composable/providers/kubernetes/hints_test.go
  internal/pkg/composable/providers/kubernetes/kubernetes.go
  internal/pkg/composable/providers/kubernetes/node.go
  internal/pkg/composable/providers/kubernetes/node_test.go
  internal/pkg/composable/providers/kubernetes/pod.go
  internal/pkg/composable/providers/kubernetes/pod_test.go
  internal/pkg/composable/providers/kubernetes/service.go
  internal/pkg/composable/providers/kubernetes/service_test.go
  internal/pkg/composable/providers/kubernetesleaderelection/kubernetes_leaderelection.go
  internal/pkg/composable/providers/kubernetessecrets/kubernetes_secrets.go
  internal/pkg/composable/providers/kubernetessecrets/kubernetes_secrets_test.go
  internal/pkg/composable/providers/local/local.go
  internal/pkg/composable/providers/local/local_test.go
  internal/pkg/composable/providers/localdynamic/localdynamic.go
  internal/pkg/composable/providers/localdynamic/localdynamic_test.go
  internal/pkg/composable/providers/path/path.go
  internal/pkg/composable/providers/path/path_test.go
  internal/pkg/composable/testing/dynamic.go
Labels: Team:Cloudnative-Monitoring, backport-skip, 8.5-candidate

#1188 Fixing condition for PR creation
  deploy/kubernetes/Makefile
Labels: backport-skip

#1194 Fix leftover log level
  internal/pkg/composable/providers/kubernetes/pod.go
Labels: backport-skip

#1192 Update kubernetes templates for elastic-agent [templates.d]
  deploy/kubernetes/elastic-agent-standalone/templates.d/activemq.yml
  deploy/kubernetes/elastic-agent-standalone/templates.d/apache.yml
  deploy/kubernetes/elastic-agent-standalone/templates.d/cassandra.yml
  deploy/kubernetes/elastic-agent-standalone/templates.d/cef.yml
  deploy/kubernetes/elastic-agent-standalone/templates.d/checkpoint.yml
  deploy/kubernetes/elastic-agent-standalone/templates.d/cloud_security_posture.yml
  deploy/kubernetes/elastic-agent-standalone/templates.d/cockroachdb.yml
  deploy/kubernetes/elastic-agent-standalone/templates.d/crowdstrike.yml
  deploy/kubernetes/elastic-agent-standalone/templates.d/cyberarkpas.yml
  deploy/kubernetes/elastic-agent-standalone/templates.d/elasticsearch.yml
  deploy/kubernetes/elastic-agent-standalone/templates.d/endpoint.yml
  deploy/kubernetes/elastic-agent-standalone/templates.d/fireeye.yml
  deploy/kubernetes/elastic-agent-standalone/templates.d/haproxy.yml
  deploy/kubernetes/elastic-agent-standalone/templates.d/hashicorp_vault.yml
  deploy/kubernetes/elastic-agent-standalone/templates.d/hid_bravura_monitor.yml
  deploy/kubernetes/elastic-agent-standalone/templates.d/iis.yml
  deploy/kubernetes/elastic-agent-standalone/templates.d/infoblox_nios.yml
  deploy/kubernetes/elastic-agent-standalone/templates.d/iptables.yml
  deploy/kubernetes/elastic-agent-standalone/templates.d/kafka.yml
  deploy/kubernetes/elastic-agent-standalone/templates.d/keycloak.yml
  deploy/kubernetes/elastic-agent-standalone/templates.d/kibana.yml
  deploy/kubernetes/elastic-agent-standalone/templates.d/log.yml
  deploy/kubernetes/elastic-agent-standalone/templates.d/logstash.yml
  deploy/kubernetes/elastic-agent-standalone/templates.d/mattermost.yml
  deploy/kubernetes/elastic-agent-standalone/templates.d/microsoft_sqlserver.yml
  deploy/kubernetes/elastic-agent-standalone/templates.d/mimecast.yml
  deploy/kubernetes/elastic-agent-standalone/templates.d/modsecurity.yml
  deploy/kubernetes/elastic-agent-standalone/templates.d/mongodb.yml
  deploy/kubernetes/elastic-agent-standalone/templates.d/mysql.yml
  deploy/kubernetes/elastic-agent-standalone/templates.d/mysql_enterprise.yml
  deploy/kubernetes/elastic-agent-standalone/templates.d/nats.yml
  deploy/kubernetes/elastic-agent-standalone/templates.d/netflow.yml
  deploy/kubernetes/elastic-agent-standalone/templates.d/nginx.yml
  deploy/kubernetes/elastic-agent-standalone/templates.d/nginx_ingress_controller.yml
  deploy/kubernetes/elastic-agent-standalone/templates.d/oracle.yml
  deploy/kubernetes/elastic-agent-standalone/templates.d/osquery.yml
  deploy/kubernetes/elastic-agent-standalone/templates.d/osquery_manager.yml
  deploy/kubernetes/elastic-agent-standalone/templates.d/panw.yml
  deploy/kubernetes/elastic-agent-standalone/templates.d/panw_cortex_xdr.yml
  deploy/kubernetes/elastic-agent-standalone/templates.d/pfsense.yml
  deploy/kubernetes/elastic-agent-standalone/templates.d/postgresql.yml
  deploy/kubernetes/elastic-agent-standalone/templates.d/prometheus.yml
  deploy/kubernetes/elastic-agent-standalone/templates.d/qnap_nas.yml
  deploy/kubernetes/elastic-agent-standalone/templates.d/rabbitmq.yml
  deploy/kubernetes/elastic-agent-standalone/templates.d/redis.yml
  deploy/kubernetes/elastic-agent-standalone/templates.d/santa.yml
  deploy/kubernetes/elastic-agent-standalone/templates.d/security_detection_engine.yml
  deploy/kubernetes/elastic-agent-standalone/templates.d/sentinel_one.yml
  deploy/kubernetes/elastic-agent-standalone/templates.d/snort.yml
  deploy/kubernetes/elastic-agent-standalone/templates.d/snyk.yml
  deploy/kubernetes/elastic-agent-standalone/templates.d/stan.yml
  deploy/kubernetes/elastic-agent-standalone/templates.d/suricata.yml
  deploy/kubernetes/elastic-agent-standalone/templates.d/symantec_endpoint.yml
  deploy/kubernetes/elastic-agent-standalone/templates.d/synthetics.yml
  deploy/kubernetes/elastic-agent-standalone/templates.d/tcp.yml
  deploy/kubernetes/elastic-agent-standalone/templates.d/tomcat.yml
  deploy/kubernetes/elastic-agent-standalone/templates.d/traefik.yml
  deploy/kubernetes/elastic-agent-standalone/templates.d/udp.yml
  deploy/kubernetes/elastic-agent-standalone/templates.d/zeek.yml
  deploy/kubernetes/elastic-agent-standalone/templates.d/zookeeper.yml
Labels: automation, backport-skip

#1204 ci: force GO_VERSION
  .ci/Jenkinsfile
Labels: Team:Automation, automation, backport-v8.4.0

#1206 Fix whitespaces in vault_darwin.c
  internal/pkg/agent/vault/vault_darwin.c
Labels: Team:Elastic-Agent-Control-Plane, backport-skip, Cleanup

#1212 [automation] update elastic stack version for testing 8.4.2-36096067
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1109 [v2] Move queue management to dispatcher
  internal/pkg/agent/application/dispatcher/dispatcher.go
  internal/pkg/agent/application/dispatcher/dispatcher_test.go
  internal/pkg/agent/application/gateway/fleet/fleet_gateway.go
  internal/pkg/agent/application/gateway/fleet/fleet_gateway_test.go
  internal/pkg/agent/application/managed_mode.go
  internal/pkg/queue/actionqueue.go
  internal/pkg/queue/actionqueue_test.go
Labels: Team:Elastic-Agent-Control-Plane, Cleanup

#1228 [automation] update elastic stack version for testing 8.4.2-b98b12f1
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1231 Update kubernetes templates for elastic-agent [templates.d]
  deploy/kubernetes/elastic-agent-standalone/templates.d/activemq.yml
  deploy/kubernetes/elastic-agent-standalone/templates.d/apache.yml
  deploy/kubernetes/elastic-agent-standalone/templates.d/cassandra.yml
  deploy/kubernetes/elastic-agent-standalone/templates.d/cloud_security_posture.yml
  deploy/kubernetes/elastic-agent-standalone/templates.d/cockroachdb.yml
  deploy/kubernetes/elastic-agent-standalone/templates.d/cyberarkpas.yml
  deploy/kubernetes/elastic-agent-standalone/templates.d/fireeye.yml
  deploy/kubernetes/elastic-agent-standalone/templates.d/haproxy.yml
  deploy/kubernetes/elastic-agent-standalone/templates.d/infoblox_nios.yml
  deploy/kubernetes/elastic-agent-standalone/templates.d/kafka.yml
  deploy/kubernetes/elastic-agent-standalone/templates.d/mongodb.yml
  deploy/kubernetes/elastic-agent-standalone/templates.d/nginx.yml
  deploy/kubernetes/elastic-agent-standalone/templates.d/osquery.yml
  deploy/kubernetes/elastic-agent-standalone/templates.d/osquery_manager.yml
  deploy/kubernetes/elastic-agent-standalone/templates.d/qnap_nas.yml
  deploy/kubernetes/elastic-agent-standalone/templates.d/sentinel_one.yml
  deploy/kubernetes/elastic-agent-standalone/templates.d/symantec_endpoint.yml
Labels: automation, backport-skip

#1218 Use at least warning level for all status logs
  CHANGELOG.next.asciidoc
  internal/pkg/core/status/reporter.go
Labels: bug, v8.5.0, backport-v8.4.0

#1202 Update k8s manifests to leverage hints
  deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml
  deploy/kubernetes/elastic-agent-standalone/elastic-agent-standalone-daemonset-configmap.yaml
  deploy/kubernetes/elastic-agent-standalone/elastic-agent-standalone-daemonset.yaml
Labels: backport-skip

#1216 Add Go 1.18 upgrade to breaking changes section.
  CHANGELOG.next.asciidoc
Labels: backport-skip, v8.5.0

#1222 docs: update docs versions 8.4.2
  deploy/kubernetes/elastic-agent-managed-kubernetes.yaml
  deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml
  version/docs/version.asciidoc
Labels: Team:Automation, release, docs, in progress

#1224 [Release] Update version to 8.4.3
  version/version.go
Labels: Team:Automation, release

#1225 [Release] Update test environments for 8.4.3
  testing/environments/latest.yml
Labels: Team:Automation, release

#1254 backport: Add 8.5 branch
  .mergify.yml
Labels: Team:Automation, impact:critical, backport-skip, release

#1259 Bump version to 8.6.0.
  version/version.go
Labels: backport-skip

#1248 [automation] update elastic stack version for testing 8.5.0-7dc445a0
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1266 [automation] update elastic stack version for testing 8.4.3-72a0900d
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1279 [automation] update elastic stack version for testing 8.4.3-24191b6e
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1240 internal/pkg/agent/cmd: don't format error message with nil errors
  internal/pkg/agent/cmd/container.go
Labels: backport-skip

#1292 [automation] update elastic stack version for testing 8.5.0-d04a8a8e
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1291 [automation] update elastic stack version for testing 8.4.3-f2e1ac46
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1290 [automation] update elastic stack version for testing 8.6.0-21651da3
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1252 Fixed: source uri reload for download/verify components
  CHANGELOG.next.asciidoc
  internal/pkg/agent/operation/operator.go
  internal/pkg/agent/operation/operator_test.go
  internal/pkg/artifact/config.go
Labels: bug, Team:Elastic-Agent-Control-Plane, backport-v8.4.0, backport-v8.5.0

#1285 Expand status reporter/controller interfaces to allow local reporters
  CHANGELOG.next.asciidoc
  internal/pkg/agent/application/gateway/fleet/fleet_gateway.go
  internal/pkg/agent/application/gateway/fleet/fleet_gateway_test.go
  internal/pkg/agent/application/gateway/fleet/noop_status_controller_test.go
  internal/pkg/core/status/handler.go
  internal/pkg/core/status/reporter.go
  internal/pkg/testutils/status_reporter.go
Labels: bug, Team:Elastic-Agent-Control-Plane, backport-v8.5.0

#1287 Improve logging for agent upgrades.
  CHANGELOG.next.asciidoc
  internal/pkg/agent/application/pipeline/actions/handlers/handler_action_upgrade.go
  internal/pkg/agent/application/upgrade/cleanup.go
  internal/pkg/agent/application/upgrade/cleanup_test.go
  internal/pkg/agent/application/upgrade/rollback.go
  internal/pkg/agent/application/upgrade/step_download.go
  internal/pkg/agent/application/upgrade/step_mark.go
  internal/pkg/agent/application/upgrade/step_relink.go
  internal/pkg/agent/application/upgrade/step_unpack.go
  internal/pkg/agent/application/upgrade/upgrade.go
  internal/pkg/agent/cmd/watch.go
  internal/pkg/agent/control/server/server.go
Labels: backport-v8.4.0, backport-v8.5.0

#1320 [automation] update elastic stack version for testing 8.4.3-3f1f47b9
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1318 [automation] update elastic stack version for testing 8.6.0-326f84b0
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1319 [automation] update elastic stack version for testing 8.5.0-d6bc1fd7
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1336 [automation] update elastic stack version for testing 8.4.3-e8645b30
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1335 [automation] update elastic stack version for testing 8.5.0-a415b54b
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1334 [automation] update elastic stack version for testing 8.6.0-df00693f
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1327 Add success log message after previous checkin failures
  CHANGELOG.next.asciidoc
  internal/pkg/agent/application/gateway/fleet/fleet_gateway.go
Labels: bug, backport-v8.4.0, backport-v8.5.0

#1341 Fix status reporter initialization
  internal/pkg/core/status/reporter.go
  internal/pkg/core/status/reporter_test.go
Labels: bug, v8.6.0, backport-v8.4.0, backport-v8.5.0

#1331 Fix [V2]: Elastic Agent Install is broken.
  internal/pkg/agent/cmd/inspect.go
  internal/pkg/agent/install/uninstall.go
  internal/pkg/agent/vars/vars.go
Labels: bug, Team:Elastic-Agent-Control-Plane, V2-Architecture

#1258 Fix agent shutdown on SIGINT
  NOTICE.txt
  go.mod
  go.sum
  internal/pkg/agent/application/managed_mode.go
  internal/pkg/fleetapi/acker/retrier/retrier.go
  internal/pkg/runner/runner.go
  internal/pkg/runner/runner_test.go
  pkg/component/runtime/manager.go
  pkg/component/runtime/runtime.go
  pkg/component/runtime/runtime_comm.go
Labels: bug, Team:Elastic-Agent-Control-Plane

#1364 [automation] update elastic stack version for testing 8.4.3-d0e42d08
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1362 [automation] update elastic stack version for testing 8.6.0-a2f4f140
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1363 [automation] update elastic stack version for testing 8.5.0-dbc138b6
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1369 Added status message to CheckinRequest
  CHANGELOG.next.asciidoc
  internal/pkg/agent/application/gateway/fleet/fleet_gateway.go
  internal/pkg/agent/application/gateway/fleet/fleet_gateway_test.go
  internal/pkg/fleetapi/checkin_cmd.go
Labels: enhancement, backport-skip, v8.6.0

#1140 [v2] Re-enable diagnostics for Elastic Agent and all components
  control.proto
  internal/pkg/agent/application/coordinator/coordinator.go
  internal/pkg/agent/cmd/diagnostics.go
  internal/pkg/agent/cmd/diagnostics_test.go
  internal/pkg/agent/cmd/run.go
  internal/pkg/agent/control/client/client.go
  internal/pkg/agent/control/control_test.go
  internal/pkg/agent/control/cproto/control.pb.go
  internal/pkg/agent/control/cproto/control_grpc.pb.go
  internal/pkg/agent/control/server/server.go
  internal/pkg/agent/transpiler/vars.go
  internal/pkg/basecmd/version/cmd_test.go
  internal/pkg/diagnostics/diagnostics.go
  pkg/component/load.go
  pkg/component/runtime/manager.go
  pkg/component/runtime/state.go
  pkg/component/spec.go
  specs/endpoint-security.spec.yml
Labels: Team:Elastic-Agent-Control-Plane, v8.6.0

#1371 Fix failures when using npipe monitoring endpoints
  internal/pkg/core/monitoring/beats/sidecar_monitor.go
Labels: bug, Team:Elastic-Agent-Control-Plane, backport-v8.4.0, backport-v8.5.0

#1380 [automation] update elastic stack version for testing 8.4.3-0900b129
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1378 [automation] update elastic stack version for testing 8.5.0-b22c068f
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1379 [automation] update elastic stack version for testing 8.6.0-158a13db
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1387 Revert: Bundle elastic-agent.app for MacOS… #714
  dev-tools/packaging/files/darwin/PkgInfo
  dev-tools/packaging/packages.yml
  dev-tools/packaging/templates/darwin/Info.plist.tmpl
  internal/pkg/agent/application/info/state.go
  internal/pkg/agent/application/info/state_test.go
  internal/pkg/agent/application/paths/common.go
  internal/pkg/agent/install/install.go
Labels: bug, Team:Elastic-Agent-Control-Plane
