Repository elastic/elastic-agent, pull requests merged in 2023-03, with the labels that each got.

#2234 [updatecli][githubrelease] Bump version to 1.19.5
  .github/workflows/golangci-lint.yml
  .go-version
  .golangci.yml
  Dockerfile
  go.mod
  version/docs/version.asciidoc
Labels: backport-skip

#2338 Fix formatting of system metricsets in example elastic-agent config
  _meta/config/common.p2.yml.tmpl
  _meta/config/common.reference.p2.yml.tmpl
  _meta/config/elastic-agent.docker.yml.tmpl
  _meta/elastic-agent.yml
  changelog/fragments/1677711770-fix-standalone-system-config.yaml
  elastic-agent.docker.yml
  elastic-agent.reference.yml
  elastic-agent.yml
Labels: bug, Team:Elastic-Agent, backport-skip

#2341 Link to ARCHITECTURE.md from README.md
  README.md
Labels: Team:Elastic-Agent, backport-skip

#2344 managed-agent will periodically call dispatcher.Dispatch
  changelog/fragments/1677797191-dispatch-periodic-flush.yaml
  internal/pkg/agent/application/managed_mode.go
  internal/pkg/agent/application/managed_mode_test.go
Labels: bug, Team:Elastic-Agent-Control-Plane, Team:Fleet, backport-v8.6.0, backport-v8.7.0

#2346 [updatecli][githubrelease] Bump version to 1.19.6
  .go-version
  .golangci.yml
  Dockerfile
  version/docs/version.asciidoc
Labels: backport-v8.7.0

#2356 fix checkout under windows for golangci-lint
  .gitattributes
Labels: backport-skip

#1727 Pre-create `state/` directory inside Docker image to allow writes to named volumes
  changelog/fragments/1675352435-Pre-create-state-directory-inside-Docker-image-to-allow-writes-to-named-volumes.yaml
  dev-tools/packaging/templates/docker/Dockerfile.elastic-agent.tmpl
Labels: Team:Elastic-Agent, backport-skip

#2283 Enhancement: Adding required mounts and capabilities for `Defend for containers`
  deploy/kubernetes/elastic-agent-managed-kubernetes.yaml
  deploy/kubernetes/elastic-agent-managed/elastic-agent-managed-daemonset.yaml
  deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml
  deploy/kubernetes/elastic-agent-standalone/elastic-agent-standalone-daemonset.yaml
Labels: backport-skip

#2252 Add support for testing mode operation
  changelog/fragments/1676571093-control-state-watch.yaml
  control_v2.proto
  internal/pkg/agent/application/actions/handlers/handler_action_application.go
  internal/pkg/agent/application/actions/handlers/handler_action_diagnostics.go
  internal/pkg/agent/application/application.go
  internal/pkg/agent/application/coordinator/coordinator.go
  internal/pkg/agent/application/coordinator/coordinator_test.go
  internal/pkg/agent/application/coordinator/handler.go
  internal/pkg/agent/application/coordinator/state/state.go
  internal/pkg/agent/application/gateway/fleet/fleet_gateway.go
  internal/pkg/agent/application/gateway/fleet/fleet_gateway_test.go
  internal/pkg/agent/application/monitoring/process.go
  internal/pkg/agent/application/monitoring/processes.go
  internal/pkg/agent/application/testing_mode.go
  internal/pkg/agent/application/upgrade/error_checker.go
  internal/pkg/agent/application/upgrade/rollback.go
  internal/pkg/agent/cmd/container.go
  internal/pkg/agent/cmd/diagnostics.go
  internal/pkg/agent/cmd/enroll_cmd.go
  internal/pkg/agent/cmd/run.go
  internal/pkg/agent/cmd/status.go
  internal/pkg/agent/cmd/upgrade.go
  internal/pkg/basecmd/restart/cmd.go
  internal/pkg/basecmd/version/cmd.go
  internal/pkg/basecmd/version/cmd_test.go
  internal/pkg/diagnostics/diagnostics.go
  magefile.go
  pkg/component/load.go
  pkg/control/addr.go
  pkg/control/addr_windows.go
  pkg/control/time.go
  pkg/control/v1/client/client.go
  pkg/control/v1/client/dial.go
  pkg/control/v1/client/dial_windows.go
  pkg/control/v1/proto/control_v1.pb.go
  pkg/control/v1/proto/control_v1_grpc.pb.go
  pkg/control/v1/server/server.go
  pkg/control/v2/client/client.go
  pkg/control/v2/client/dial.go
  pkg/control/v2/client/dial_windows.go
  pkg/control/v2/control_test.go
  pkg/control/v2/cproto/control_v2.pb.go
  pkg/control/v2/cproto/control_v2_grpc.pb.go
  pkg/control/v2/server/listener.go
  pkg/control/v2/server/listener_windows.go
  pkg/control/v2/server/server.go
Labels: Team:Elastic-Agent, backport-skip

#2361 Code cleanup
  dev-tools/mage/gotest_test.go
  dev-tools/mage/keychain.go
  internal/pkg/agent/application/actions/handlers/handler_action_application.go
  internal/pkg/agent/application/actions/handlers/handler_action_settings.go
  internal/pkg/agent/application/application.go
  internal/pkg/agent/application/coordinator/coordinator.go
  internal/pkg/agent/application/filters/stream_checker.go
  internal/pkg/agent/application/managed_mode_test.go
  internal/pkg/agent/application/monitoring/v1_monitor.go
  internal/pkg/agent/application/reexec/reexec_windows.go
  internal/pkg/agent/errors/error.go
  internal/pkg/composable/context.go
  internal/pkg/composable/dynamic.go
  internal/pkg/composable/testing/dynamic.go
  internal/pkg/fleetapi/ack_cmd.go
  internal/pkg/fleetapi/enroll_cmd.go
  internal/pkg/remote/client.go
  pkg/component/component.go
  pkg/component/config.go
  pkg/component/runtime/command.go
  pkg/component/runtime/manager.go
  pkg/component/runtime/manager_test.go
  pkg/component/runtime/runtime.go
  pkg/component/runtime/runtime_comm.go
  pkg/component/runtime/state.go
  pkg/control/v2/server/server.go
Labels: Cleanup, backport-v8.7.0

#2363 [updatecli][githubrelease] Bump version to 1.19.7
  .go-version
  .golangci.yml
  Dockerfile
  version/docs/version.asciidoc
Labels: Team:Elastic-Agent, backport-v8.7.0

#2349 Reduce deadlock in controller
  changelog/fragments/1678178226-Reduced-deadlocks-in-controller.yaml
  internal/pkg/composable/controller.go
Labels: bug, Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent, backport-v8.6.0, backport-v8.7.0

#2314 Ventura Permissions Issue
  changelog/fragments/1678553750-ventura-permission-issue.yaml
  internal/pkg/agent/cmd/enroll.go
Labels: bug, Team:Elastic-Agent, backport-v8.6.0, backport-v8.7.0

#2352 Fix deadlocks in agent startup process
  changelog/fragments/1678471725-coordinator_deadlock_fix.yaml
  internal/pkg/agent/application/coordinator/coordinator.go
  internal/pkg/agent/application/periodic.go
  pkg/component/runtime/manager.go
Labels: bug, Team:Elastic-Agent, backport-v8.7.0

#2378 Refactoring fake component and shipper codebases
  magefile.go
  pkg/component/fake/component/comp/actions.go
  pkg/component/fake/component/comp/component.go
  pkg/component/fake/component/comp/dialer.go
  pkg/component/fake/component/comp/dialer_windows.go
  pkg/component/fake/component/main.go
  pkg/component/fake/shipper/actions.go
  pkg/component/fake/shipper/main.go
Labels: Cleanup, backport-v8.7.0

#2382 [Fleet] Fix backticks in k8's manifests
  deploy/kubernetes/elastic-agent-managed-kubernetes.yaml
  deploy/kubernetes/elastic-agent-managed/elastic-agent-managed-daemonset.yaml
Labels: Cleanup, backport-v8.7.0

#2381 Adding Label in CI of cloudnative automation for autoapprove
  deploy/kubernetes/Makefile
Labels: backport-skip, cloudnative-observability

#2384 Minor code cleanup
  Vagrantfile
  internal/pkg/agent/application/coordinator/coordinator.go
  pkg/component/runtime/command.go
  pkg/component/runtime/manager.go
  pkg/component/runtime/runtime_comm.go
Labels: backport-skip, Cleanup

#2387 [Fleet] Remove more K8's manifest backticks that break Kibana's build
  deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml
  deploy/kubernetes/elastic-agent-standalone/elastic-agent-standalone-daemonset-configmap.yaml
  deploy/kubernetes/elastic-agent-standalone/elastic-agent-standalone-daemonset.yaml
Labels: backport-skip, Cleanup

#2396 Fix timeout in coordinator shutdown loop
  internal/pkg/agent/application/coordinator/coordinator.go
  internal/pkg/agent/application/coordinator/coordinator_test.go
Labels: bug, Team:Elastic-Agent, backport-v8.7.0

#2348 Agent actions signature validation
  changelog/fragments/1678136865-Agent-actions-signature-validation.yaml
  internal/pkg/agent/application/actions/handlers/handler_action_application.go
  internal/pkg/agent/application/actions/handlers/handler_action_policy_change.go
  internal/pkg/agent/application/application.go
  internal/pkg/agent/application/coordinator/coordinator.go
  internal/pkg/agent/application/endpoint_signed_component_modifier.go
  internal/pkg/agent/application/endpoint_signed_component_modifier_test.go
  internal/pkg/agent/application/managed_mode.go
  internal/pkg/agent/protection/action.go
  internal/pkg/agent/protection/action_test.go
  internal/pkg/agent/protection/config.go
  internal/pkg/agent/protection/config_test.go
  internal/pkg/agent/protection/match_policy.go
  internal/pkg/agent/protection/match_policy_test.go
  internal/pkg/agent/protection/overlay_policy.go
  internal/pkg/agent/protection/overlay_policy_test.go
  internal/pkg/agent/protection/policy.go
  internal/pkg/agent/protection/policy_test.go
  internal/pkg/agent/protection/signature.go
  internal/pkg/agent/protection/signature_test.go
  internal/pkg/agent/storage/store/state_store.go
  internal/pkg/conv/map.go
  internal/pkg/conv/map_test.go
  internal/pkg/fleetapi/action.go
  internal/pkg/fleetapi/checkin_cmd.go
Labels: enhancement, backport-skip, v8.8.0, 8.8-candidate

#2395 Generate 8.7.0 release note summary
  changelog/8.7.0.yaml
  changelog/fragments/1669049916-CHANGELOG.asciidoc.yaml
  changelog/fragments/1674757194-entity-analytics-input.yaml
  changelog/fragments/1674785407-add-diagnostics-action-handler.yaml
  changelog/fragments/1674822835-Enhance-agent-monitoring-config-to-support-filebeat-inputs-endpoint
  changelog/fragments/1675085396-preserve-state-on-upgrade.yaml
  changelog/fragments/1675151497-Add-Universal-Profiling-Agent.yaml
  changelog/fragments/1675379107-heartbeat-engine-strict-validation.yaml
  changelog/fragments/1676358802-migrate-unencrypted-config.yaml
  changelog/fragments/1677000534-Restore-support-for-memcached-metrics-inputs.yaml
  changelog/fragments/1677048898-render-config-for-inspect-with-variable-wait.yaml
  changelog/fragments/1677255543-upgrade-watcher-fix-log.yaml
  changelog/fragments/1677572502-add-fleet-checkin-starting-state.yaml
  changelog/fragments/1677599609-fix-container-state-dirs-perms.yaml
  changelog/fragments/1677797191-dispatch-periodic-flush.yaml
  changelog/fragments/1678178226-Reduced-deadlocks-in-controller.yaml
  changelog/fragments/1678471725-coordinator_deadlock_fix.yaml
  changelog/fragments/1678553750-ventura-permission-issue.yaml
Labels: Team:Elastic-Agent, forwardport-main

#2401 Add spec for Universal Profiling Symbolizer
  changelog/fragments/1679899362-pf-elastic-symbolizer.yaml
  dev-tools/packaging/templates/docker/Dockerfile.elastic-agent.tmpl
  magefile.go
  pkg/component/load_test.go
  specs/pf-elastic-symbolizer.spec.yml
Labels: enhancement, backport-skip

#2386 Fix log collection with hints when missing container ports or annotations
  deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml
  deploy/kubernetes/elastic-agent-standalone/elastic-agent-standalone-daemonset-configmap.yaml
  internal/pkg/composable/providers/kubernetes/config.go
  internal/pkg/composable/providers/kubernetes/kubernetes.go
  internal/pkg/composable/providers/kubernetes/pod.go
Labels: backport-skip, v8.8.0, 8.8-candidate

#2407 Add spec for Universal Profiling Collector
  changelog/fragments/1679986811-pf-elastic-collector.yaml
  dev-tools/packaging/templates/docker/Dockerfile.elastic-agent.tmpl
  magefile.go
  pkg/component/load_test.go
  specs/pf-elastic-collector.spec.yml
Labels: enhancement, backport-skip

#2406 Fix actions acks delay
  changelog/fragments/1680101776-Fix-actions-acks-delay.yaml
  internal/pkg/remote/client.go
  internal/pkg/remote/client_test.go
Labels: bug, 8.8-candidate, backport-v8.7.0

#2243 [Release] Update version to 8.7.1
  version/version.go
Labels: Team:Automation, release

#2389 Add new integration testing framework
  .gitignore
  internal/pkg/agent/application/coordinator/mocks/capability.go
  internal/pkg/agent/application/coordinator/mocks/components_modifier.go
  internal/pkg/agent/application/coordinator/mocks/config_change.go
  internal/pkg/agent/application/coordinator/mocks/config_manager.go
  internal/pkg/agent/application/coordinator/mocks/fetch_context_provider.go
  internal/pkg/agent/application/coordinator/mocks/monitor_manager.go
  internal/pkg/agent/application/coordinator/mocks/re_exec_manager.go
  internal/pkg/agent/application/coordinator/mocks/runtime_manager.go
  internal/pkg/agent/application/coordinator/mocks/upgrade_manager.go
  internal/pkg/agent/application/coordinator/mocks/vars_manager.go
  internal/pkg/agent/application/coordinator/testdata/simple_config/expected/components-actual.yaml
  internal/pkg/agent/application/coordinator/testdata/simple_config/expected/components-expected.yaml
  internal/pkg/agent/application/testing_mode.go
  internal/pkg/agent/cmd/enroll.go
  internal/pkg/agent/cmd/run.go
  pkg/component/fake/component/comp/component.go
  pkg/component/input_spec.go
  pkg/component/shipper_spec.go
  pkg/component/spec.go
  pkg/control/addr_common.go
  pkg/control/v2/client/client.go
  pkg/control/v2/client/dial.go
  pkg/control/v2/client/dial_windows.go
  pkg/testing/fetcher.go
  pkg/testing/fetcher_artifact.go
  pkg/testing/fetcher_artifact_test.go
  pkg/testing/fetcher_local.go
  pkg/testing/fetcher_local_test.go
  pkg/testing/fixture.go
  pkg/testing/log.go
  pkg/testing/machine.go
  pkg/testing/machine_test.go
  pkg/testing/use.go
  testing/integration/fake_test.go
Labels: backport-skip, skip-changelog

#2422 Fix typos in PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: backport-skip

#2421 Un-harcode config file path
  internal/pkg/agent/application/coordinator/diagnostics_test.go
Labels: enhancement, Team:Elastic-Agent, backport-skip

#2437 Correct api-key to api_key in example configurations
  _meta/config/common.p2.yml.tmpl
  _meta/config/common.reference.p2.yml.tmpl
  elastic-agent.reference.yml
  elastic-agent.yml
  internal/pkg/config/loader_test.go
  internal/pkg/config/testdata/standalone-with-inputs.yml
  internal/pkg/config/testdata/standalone1.yml
Labels: Team:Elastic-Agent, backport-v8.7.0
