Repository elastic/elastic-agent, pull requests merged in 2023-05, with the labels that each got.

#2577 Fix up 8.7.1 release notes
  changelog/8.7.1.yaml
  changelog/fragments/1681942680-fix-diag-zip-file.yaml
Labels: Team:Elastic-Agent

#2586 Skip flaky dispatch test on Windows.
  internal/pkg/agent/application/managed_mode_test.go
Labels: Team:Elastic-Agent, backport-v8.7.0, backport-v8.8.0

#2576 Fix issue with service token path in fleet-server bootstrap of container
  changelog/fragments/1682953274-Fix-container-service-token-path-issue.yaml
  internal/pkg/agent/cmd/container.go
  internal/pkg/agent/cmd/container_test.go
Labels: bug, Team:Elastic-Agent-Control-Plane, Team:Fleet, backport-v8.8.0

#2567 Validate install base path
  internal/pkg/agent/cmd/install.go
  internal/pkg/agent/cmd/install_test.go
  internal/pkg/agent/cmd/install_windows_test.go
Labels: bug, Team:Elastic-Agent, backport-skip

#2492 [Release] Update version to 8.7.2
  version/version.go
Labels: Team:Automation, release

#2571 Test/create integration test for diagnostics cmd
  pkg/core/process/process.go
  pkg/testing/fixture.go
  testing/integration/diagnostics_test.go
  testing/integration/fake_test.go
Labels: Team:Elastic-Agent, backport-skip, Testing

#2592 Hide `--base-path` flag for `install` sub-command
  internal/pkg/agent/cmd/install.go
Labels: Team:Elastic-Agent, backport-skip

#2574 Add documentation around inputs.d to config file
  _meta/config/common.p2.yml.tmpl
  elastic-agent.yml
Labels: Team:Elastic-Agent, backport-skip

#2589 Minimal ESS API client for integration/E2E testing framework
  pkg/testing/ess/client.go
  pkg/testing/ess/client_test.go
  pkg/testing/ess/config.go
  pkg/testing/ess/deployment.go
  pkg/testing/ess/deployment_test.go
  pkg/testing/ess/doc.go
Labels: backport-skip, Testing

#2593 Address flakey dispatcher flush test
  internal/pkg/agent/application/managed_mode_test.go
Labels: Team:Elastic-Agent-Control-Plane, flaky-test, backport-skip

#2550 Add hostPath to store elastic-agent state
  deploy/kubernetes/elastic-agent-managed-kubernetes.yaml
  deploy/kubernetes/elastic-agent-managed/elastic-agent-managed-daemonset.yaml
  deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml
  deploy/kubernetes/elastic-agent-standalone/elastic-agent-standalone-daemonset.yaml
Labels: backport-v8.8.0

#1961 Autopilot GKE documentation for Elastic Agent
  docs/elastic-agent-gke-autopilot.md
  docs/images/1.png
  docs/images/2.png
  docs/images/3.png
  docs/images/4.png
  docs/images/5.png
  docs/images/6.png
  docs/images/cloudid.png
  docs/manifests/elastic-agent-managed-gke-autopilot.yaml
  docs/manifests/elastic-agent-standalone-gke-autopilot.yaml
  docs/scripts/autopilot-tests.sh
Labels: backport-skip

#2604 Update PULL_REQUEST_TEMPLATE.md
  .github/ISSUE_TEMPLATE/feature-request.md
Labels: backport-skip

#2591 Add testing/define module that allows test runtime requirements
  NOTICE.txt
  go.mod
  go.sum
  magefile.go
  pkg/testing/define/batch.go
  pkg/testing/define/batch_test.go
  pkg/testing/define/define.go
  pkg/testing/define/define_all.go
  pkg/testing/define/define_define.go
  pkg/testing/define/define_local.go
  pkg/testing/define/parser.go
  pkg/testing/define/parser_test.go
  pkg/testing/define/requirements.go
  pkg/testing/define/testdata/sample_test.go
  pkg/testing/fixture.go
  testing/integration/diagnostics_test.go
  testing/integration/fake_test.go
Labels: Team:Elastic-Agent, backport-skip, Testing

#2600 Delete Kibana client and Fleet API code from E2E testing framework
  NOTICE.txt
  go.mod
  go.sum
  testing/e2e/tests/upgrade_test.go
  testing/e2e/tools/agents.go
  testing/e2e/tools/fleet_tools.go
  testing/e2e/tools/kibana_client.go
Labels: Team:Elastic-Agent, backport-v8.8.0

#2620 [Automation] Bump Golang version to 1.19.9
  .go-version
  .golangci.yml
  Dockerfile
  version/docs/version.asciidoc
Labels: backport-skip, backport-v8.8.0

#2626 Comment out cloud-defend caps
  deploy/kubernetes/elastic-agent-managed-kubernetes.yaml
  deploy/kubernetes/elastic-agent-managed/elastic-agent-managed-daemonset.yaml
  deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml
  deploy/kubernetes/elastic-agent-standalone/elastic-agent-standalone-daemonset.yaml
Labels: backport-v8.8.0

#2631 Set the build settings for the elastc-agent
  catalog-info.yaml
Labels: backport-skip, Packaging

#2642 Add PR bot and update CI settings
  .buildkite/pull-requests.json
  catalog-info.yaml
Labels: backport-skip

#2646 Create build.yml
  .github/workflows/build.yml
  sonar-project.properties
Labels: backport-skip

#2649 Adding code coverage badge
  README.md
Labels: backport-skip

#2611 Test/add logs to diagnostic command
  internal/pkg/agent/application/actions/handlers/handler_action_diagnostics.go
  internal/pkg/agent/application/actions/handlers/handler_action_diagnostics_test.go
  internal/pkg/agent/application/actions/handlers/mocks/acker.go
  internal/pkg/agent/application/actions/handlers/mocks/diagnostics_provider.go
  internal/pkg/agent/application/actions/handlers/mocks/uploader.go
Labels: Team:Elastic-Agent, backport-skip, skip-changelog

#2653 Add the sonarqube project key
  catalog-info.yaml
Labels: backport-skip

#2633 Monitoring: add Universal Profiling components to supportedBeatsCompo…
  internal/pkg/agent/application/monitoring/process.go
  internal/pkg/agent/application/monitoring/v1_monitor.go
Labels: enhancement, Team:Elastic-Agent, backport-v8.8.0

#2648 Changelog fragment Github Action
  .github/workflows/fragment-in-pr.yml
Labels: Team:Elastic-Agent, backport-skip

#2619 Adding `integration:auth` target
  magefile.go
  pkg/testing/ess/users.go
Labels: Team:Elastic-Agent, backport-v8.7.0

#2660 Update backstage catalog-info
  catalog-info.yaml
Labels: backport-skip, skip-changelog

#2652 Split GH workflows
  .github/workflows/build.yml
  .github/workflows/sonarcloud.yml
Labels: backport-skip, skip-changelog

#2657 [Cleanup] Remove some unused AST helpers
  internal/pkg/agent/transpiler/ast.go
  internal/pkg/agent/transpiler/ast_test.go
Labels: Team:Elastic-Agent, backport-skip, Cleanup

#2637 Fix EQL parser definitions for variable names
  NOTICE.txt
  go.mod
  go.sum
  internal/pkg/eql/Eql.g4
  internal/pkg/eql/eql_test.go
  internal/pkg/eql/expression.go
  internal/pkg/eql/parser/Eql.interp
  internal/pkg/eql/parser/EqlLexer.interp
  internal/pkg/eql/parser/eql_base_listener.go
  internal/pkg/eql/parser/eql_base_visitor.go
  internal/pkg/eql/parser/eql_lexer.go
  internal/pkg/eql/parser/eql_listener.go
  internal/pkg/eql/parser/eql_parser.go
  internal/pkg/eql/parser/eql_visitor.go
  internal/pkg/eql/visitor.go
Labels: bug, Team:Elastic-Agent, backport-skip

#2643 Fix mapping of Fleet status and message in protobuf StateResponse
  pkg/control/v2/server/server.go
  pkg/control/v2/server/server_test.go
Labels: bug, Team:Elastic-Agent, skip-changelog, backport-v8.8.0

#2655 Create installation marker on upgrade from versions < 8.8.0
  changelog/fragments/1683748237-upgrade-install-marker.yaml
  internal/pkg/agent/application/info/state.go
  internal/pkg/agent/cmd/install.go
  internal/pkg/agent/cmd/run.go
Labels: Team:Elastic-Agent, QA:Needs Validation, backport-v8.8.0

#2669 Add link to ESS QA API keys page
  magefile.go
Labels: Team:Elastic-Agent, skip-changelog, backport-v8.8.0

#2618 Port over Agent Upgrade test
  NOTICE.txt
  go.mod
  go.sum
  pkg/testing/tools/agents.go
  pkg/testing/tools/arch.go
  pkg/testing/tools/artifacts_darwin.go
  pkg/testing/tools/artifacts_linux.go
  pkg/testing/tools/cmd.go
  pkg/testing/tools/cmd_darwin.go
  pkg/testing/tools/cmd_linux.go
  pkg/testing/tools/config.go
  pkg/testing/tools/download.go
  testing/e2e/tests/upgrade_test.go
  testing/integration/upgrade_test.go
Labels: Team:Elastic-Agent, skip-changelog, backport-v8.8.0, Testing

#2684 Adjust the workflows for SonarCloud
  .github/workflows/build.yml
  .github/workflows/sonarcloud.yml
Labels: backport-skip, skip-changelog

#2686 Add a new job for Sonar only on push on main
  .github/workflows/sonarcloud.yml
Labels: backport-skip, skip-changelog

#2688 Update README with the badge
  README.md
Labels: backport-skip, skip-changelog

#2623 Reintroduce TestManager_FakeInput_OutputChange
  pkg/component/fake/component/main.go
  pkg/component/runtime/manager.go
  pkg/component/runtime/manager_test.go
Labels: flaky-test, backport-skip, skip-changelog

#2677 E2E test for FQDN feature flag
  NOTICE.txt
  go.mod
  go.sum
  pkg/testing/tools/agents.go
  pkg/testing/tools/tools.go
  testing/integration/fqdn_test.go
  testing/integration/upgrade_test.go
Labels: Team:Elastic-Agent, skip-changelog, backport-v8.8.0

#2678 Allow optional strict checking of variable names in EQL expressions
  docs/component-specs.md
  internal/pkg/agent/transpiler/ast.go
  internal/pkg/capabilities/upgrade.go
  internal/pkg/eql/eql.go
  internal/pkg/eql/eql_test.go
  internal/pkg/eql/expression.go
  internal/pkg/eql/visitor.go
  pkg/component/component.go
  pkg/component/component_test.go
  pkg/component/load.go
  specs/README.md
  specs/cloud-defend.spec.yml
  specs/endpoint-security.spec.yml
  specs/pf-host-agent.spec.yml
Labels: bug, Team:Elastic-Agent, backport-skip, skip-changelog

#2638 Add linting rules for `replace` directives in go.mod
  .golangci.yml
Labels: Team:Elastic-Agent, backport-v8.8.0

#2700 Add `mage integration:test` target
  .gitignore
  NOTICE.txt
  go.mod
  go.sum
  internal/pkg/agent/application/actions/handlers/mocks/acker.go
  internal/pkg/agent/application/actions/handlers/mocks/diagnostics_provider.go
  internal/pkg/agent/application/actions/handlers/mocks/uploader.go
  magefile.go
  pkg/testing/define/define.go
  pkg/testing/ess/deployment.go
  pkg/testing/runner/archiver.go
  pkg/testing/runner/config.go
  pkg/testing/runner/debian.go
  pkg/testing/runner/json.go
  pkg/testing/runner/junit.go
  pkg/testing/runner/layout.go
  pkg/testing/runner/ogc.go
  pkg/testing/runner/prefix_output.go
  pkg/testing/runner/runner.go
  pkg/testing/runner/ssh.go
  pkg/testing/runner/supported.go
  testing/integration/fqdn_test.go
Labels: skip-changelog, backport-v8.8.0

#2707 Adding developer guide for integration and E2E testing framework
  docs/test-framework-dev-guide.md
Labels: Team:Elastic-Agent, skip-changelog, backport-v8.8.0, Testing

#2687 Add specs to Sonar exclusions
  sonar-project.properties
Labels: backport-skip, skip-changelog

#2725 Add a new packaging pipeline
  .buildkite/hooks/post-checkout
  .buildkite/pipeline.elastic-agent-package.yml
  .buildkite/pull-requests.json
  catalog-info.yaml
Labels: backport-skip, skip-changelog, ci

#2564 [Release] Update version to 8.8.1
  version/version.go
Labels: release

#2729 Fix deadlock in RuntimeManager
  changelog/fragments/1685029627-Fix-deadlock-condition-in-RuntimeManager.yaml
  pkg/component/fake/component/comp/component.go
  pkg/component/runtime/command.go
  pkg/component/runtime/manager.go
  pkg/component/runtime/manager_test.go
  pkg/component/runtime/runtime.go
  pkg/component/runtime/runtime_comm.go
  pkg/component/runtime/service.go
Labels: Team:Elastic-Agent, backport-v8.6.0, backport-v8.7.0, backport-v8.8.0

#2696 Update synthetics deps
  changelog/fragments/1684175757-bump-node-deps.yaml
  dev-tools/packaging/templates/docker/Dockerfile.elastic-agent.tmpl
  dev-tools/packaging/templates/docker/Dockerfile.tmpl
Labels: bug, Team:Uptime, v8.8.0, backport-v8.8.0

#2741 Avoid SEGFAULT when cleaning up installation in integration tests fixture
  pkg/testing/fixture_install.go
Labels: bug, Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent, backport-skip, skip-changelog

#2744 Enable auto-updates of github.com/elastic/* dependencies.
  .github/dependabot.yml
  .github/workflows/post-dependabot.yml
Labels: Team:Elastic-Agent, backport-skip, skip-changelog

#2755 Update sonar-project.properties
  sonar-project.properties
Labels: backport-skip

#2745 Add the `logs` subcommand to the CLI
  changelog/fragments/1685442237-add-logs-subcommand.yaml
  internal/pkg/agent/cmd/common.go
  internal/pkg/agent/cmd/logs.go
  internal/pkg/agent/cmd/logs_test.go
Labels: enhancement, Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent, backport-skip
