Repository elastic/elastic-agent, pull requests merged in 2023-01, with the labels that each got.

#2036 Fix stale checkin expected messages being sent on process restart
  pkg/component/runtime/command.go
  pkg/component/runtime/conn_info_server_test.go
  pkg/component/runtime/runtime_comm.go
  pkg/component/runtime/service.go
Labels: v8.6.0, forwardport-main

#2045 Update copyright year to 2023.
  NOTICE.txt
Labels: Team:Elastic-Agent, backport-v8.6.0

#2047 Use full filename for component diagnostic files.
  internal/pkg/agent/cmd/diagnostics.go
Labels: Team:Elastic-Agent, forwardport-main

#2005 Add generic diagnostic redactor back to v2
  internal/pkg/agent/cmd/diagnostics.go
Labels: bug, V2-Architecture, skip-changelog, backport-v8.6.0

#2055 Add osquery and endpoint security logstash output support
  pkg/component/component_test.go
  specs/endpoint-security.spec.yml
  specs/osquerybeat.spec.yml
Labels: v8.6.0, forwardport-main

#2016 Update ironbank base image to ubi 8.7
  dev-tools/packaging/templates/ironbank/Dockerfile.tmpl
  dev-tools/packaging/templates/ironbank/hardening_manifest.yaml.tmpl
Labels: backport-skip

#2069 [automation] update elastic stack version for testing 8.6.0-08ebeaf7
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#2071 [automation] update elastic stack version for testing 8.7.0-df9bb536
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#2077 [automation] update elastic stack version for testing 8.7.0-61c35791
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#1733 [Release] Update version to 8.6.1
  version/version.go
Labels: Team:Automation, release

#2076 V2 Changelog: adding fragments for visible changes
  changelog/8.6.0.yaml
  changelog/fragments/1665780486-heartbeat-es-output-only.yaml
  changelog/fragments/1666095433-service_runtime_v2.yaml
  changelog/fragments/1667243040-Upgrade-node-to-18.12.0.yaml
  changelog/fragments/1667571017-Add-support-for-running-the-elastic-agent-shipper.yaml
  changelog/fragments/1668483030-common-expression-language.yaml
  changelog/fragments/1668591286-fix-beats-logs.yaml
  changelog/fragments/1668645651-apm-fleet-config.yaml
  changelog/fragments/1668679987-apm-monitoring.yaml
  changelog/fragments/1669066497-struct-compare-unit-update.yaml
  changelog/fragments/1669159455-reimplement-processes-route.yaml
  changelog/fragments/1669236059-Capture-stdout-stderr-of-all-spawned-components-to-simplify-logging.yaml
  changelog/fragments/1669665017-fix-nil-action-ack-crash-after-local-upgrade.yaml
  changelog/fragments/1669668741-fix-erroneous-http-url-directory-created-for-monitoring.yaml
  changelog/fragments/1669739947-fix-osqueryd-and-osquery-extension.ext-permissions.yaml
  changelog/fragments/1669845868-add-agent-logging-level-to-fleet-configuration.yaml
  changelog/fragments/1669928791-Ensure-unique-input-ID-when-variable-substition-occurs-from-a-dynamic-provider.yaml
  changelog/fragments/1669929902-fix-local-fleet-server-port.yaml
  changelog/fragments/1669940990-Remove-inputs-when-all-streams-are-removed.yaml
  changelog/fragments/1670518841-No-longer-restart-Elastic-Agent-on-log-level-change.yaml
  changelog/fragments/1671748292-input-ids-are-required.yaml
Labels: Team:Elastic-Agent, V2-Architecture, docs

#2013 Add statsd metricbeat input.
  specs/metricbeat.spec.yml
Labels: enhancement, Team:Elastic-Agent, backport-skip

#2093 Add agent directory into git safe dirs
  dev-tools/mage/build.go
Labels: bug, Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent, backport-v8.6.0

#2082 Upgrade elastic-agent-libs to v0.2.16.
  NOTICE.txt
  go.mod
  go.sum
Labels: Team:Elastic-Agent, backport-v8.6.0

#2100 [automation] Update go release version 1.18.10
  .go-version
  .golangci.yml
  Dockerfile
  version/docs/version.asciidoc
Labels: automation, dependency, backport-skip, backport-v8.6.0

#2112 [automation] update elastic stack version for testing 8.6.1-cc0796ca
  testing/environments/snapshot.yml
Labels: automation, dependency, backport-skip

#2116 action: use opentelemetry composite action
  .github/workflows/opentelemetry.yml
Labels: Team:Automation, automation, backport-v8.5.0, backport-v8.6.0

#2105 [Kubernetes] Add support to 1.26 k8s version
  .ci/Jenkinsfile
Labels: Team:Cloudnative-Monitoring, backport-skip

#2104 Use Kustomize to build elastic-agent manifests for both managed and standalone more
  dev-tools/kubernetes/.gitignore
  dev-tools/kubernetes/Taskfile.yaml
  dev-tools/kubernetes/base/common/cluster-role-binding.yaml
  dev-tools/kubernetes/base/common/cluster-role.yaml
  dev-tools/kubernetes/base/common/kustomization.yml
  dev-tools/kubernetes/base/common/role-binding-leases.yaml
  dev-tools/kubernetes/base/common/role-leases.yaml
  dev-tools/kubernetes/base/common/service-account.yaml
  dev-tools/kubernetes/base/elastic-agent-managed/.env
  dev-tools/kubernetes/base/elastic-agent-managed/daemonset.yaml
  dev-tools/kubernetes/base/elastic-agent-managed/kustomization.yml
  dev-tools/kubernetes/base/elastic-agent-standalone/.env
  dev-tools/kubernetes/base/elastic-agent-standalone/config-map.yaml
  dev-tools/kubernetes/base/elastic-agent-standalone/daemonset.yaml
  dev-tools/kubernetes/base/elastic-agent-standalone/kustomization.yml
  dev-tools/kubernetes/base/elastic-agent-standalone/role-binding-kubeadm-config.yaml
  dev-tools/kubernetes/base/elastic-agent-standalone/role-kubeadm-config.yaml
  dev-tools/kubernetes/overlays/elastic-agent-managed/kustomization.yml
  dev-tools/kubernetes/overlays/elastic-agent-standalone/kustomization.yml
Labels: enhancement, backport-skip, draft

#2108 Remove unused testing environments.
  testing/environments/Dockerfile
  testing/environments/Makefile
  testing/environments/README.md
  testing/environments/docker/README.md
  testing/environments/docker/elasticsearch/kerberos/init.sh
  testing/environments/docker/elasticsearch/kerberos/installkdc.sh
  testing/environments/docker/elasticsearch/pki/ca/ca.crt
  testing/environments/docker/elasticsearch/pki/ca/ca.key
  testing/environments/docker/elasticsearch/pki/elasticsearchssl/elasticsearchssl.crt
  testing/environments/docker/elasticsearch/pki/elasticsearchssl/elasticsearchssl.key
  testing/environments/docker/elasticsearch/pki/generate_pki.sh
  testing/environments/docker/elasticsearch/roles.yml
  testing/environments/docker/elasticsearch/users
  testing/environments/docker/elasticsearch/users_roles
  testing/environments/docker/elasticsearch_kerberos/Dockerfile
  testing/environments/docker/elasticsearch_kerberos/config/kdc.conf.template
  testing/environments/docker/elasticsearch_kerberos/config/krb5.conf
  testing/environments/docker/elasticsearch_kerberos/config/krb5.conf.template
  testing/environments/docker/elasticsearch_kerberos/healthcheck.sh
  testing/environments/docker/elasticsearch_kerberos/init.sh
  testing/environments/docker/elasticsearch_kerberos/scripts/addprinc.sh
  testing/environments/docker/elasticsearch_kerberos/scripts/addprincs.sh
  testing/environments/docker/elasticsearch_kerberos/scripts/installkdc.sh
  testing/environments/docker/elasticsearch_kerberos/start.sh
  testing/environments/docker/kafka/Dockerfile
  testing/environments/docker/kafka/README.md
  testing/environments/docker/kafka/certs/broker-cert
  testing/environments/docker/kafka/certs/broker-cert-signed
  testing/environments/docker/kafka/certs/broker.keystore.jks
  testing/environments/docker/kafka/certs/ca-cert
  testing/environments/docker/kafka/certs/ca-cert.srl
  testing/environments/docker/kafka/certs/ca-key
  testing/environments/docker/kafka/certs/client.truststore.jks
  testing/environments/docker/kafka/healthcheck.sh
  testing/environments/docker/kafka/run.sh
  testing/environments/docker/kerberos_kdc/Dockerfile
  testing/environments/docker/logstash/gencerts.sh
  testing/environments/docker/logstash/pipeline-xpack/default.conf
  testing/environments/docker/logstash/pipeline/default.conf
  testing/environments/docker/logstash/pki/tls/certs/logstash.crt
  testing/environments/docker/logstash/pki/tls/private/logstash.key
  testing/environments/docker/logstash/ssl.conf
  testing/environments/docker/mosquitto/Dockerfile
  testing/environments/docker/sredis/Dockerfile
  testing/environments/docker/sredis/gencerts.sh
  testing/environments/docker/sredis/pki/tls/certs/sredis.crt
  testing/environments/docker/sredis/pki/tls/private/sredis.key
  testing/environments/docker/sredis/stunnel.conf
  testing/environments/docker/test.env
  testing/environments/latest.yml
  testing/environments/local.yml
  testing/environments/prev-minor.yml
  testing/environments/snapshot.yml
Labels: Team:Elastic-Agent, backport-v8.6.0

#2121 add enterprisesearch input to metricbeat spec
  specs/metricbeat.spec.yml
Labels: enhancement, Team:Elastic-Agent, backport-skip

#2132 change code owners of dev-tools/kubernetes
  .github/CODEOWNERS
Labels: backport-skip

#2130 Accept spec files already present in artifact
  magefile.go
  specs/shipper.spec.yml
Labels: Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent, skip-changelog, backport-v8.6.0

#2138 Fix issue where its possible for a component to receive a unit without a config
  changelog/fragments/1674071325-Fix-issue-where-its-possible-for-a-component-to-receive-a-unit-without-a-config.yaml
  internal/pkg/agent/control/v1/proto/control_v1.pb.go
  internal/pkg/agent/control/v1/proto/control_v1_grpc.pb.go
  internal/pkg/agent/control/v2/cproto/control_v2.pb.go
  internal/pkg/agent/control/v2/cproto/control_v2_grpc.pb.go
  pkg/component/fake/component/main.go
  pkg/component/fake/shipper/listener.go
  pkg/component/runtime/command.go
  pkg/component/runtime/conn_info_server_test.go
  pkg/component/runtime/manager_test.go
  pkg/component/runtime/runtime_comm.go
  pkg/component/runtime/service.go
Labels: Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent, backport-v8.6.0

#2154 Increase timeouts in TestManager_FakeShipper for slower CI nodes
  pkg/component/runtime/manager_test.go
Labels: Team:Elastic-Agent, skip-changelog, backport-v8.6.0

#2144 ci: use ubuntu:22 workers
  .ci/Jenkinsfile
Labels: backport-v8.6.0

#2044 Tag agent logs with 'service.name'
  internal/pkg/agent/application/application.go
  internal/pkg/agent/application/monitoring/v1_monitor.go
  internal/pkg/agent/cmd/run.go
  pkg/component/runtime/command.go
  pkg/component/runtime/manager.go
  pkg/component/runtime/manager_test.go
  pkg/component/runtime/runtime.go
Labels: Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent, skip-changelog, backport-v8.6.0

#2158 Inject custom headers defined during enroll
  internal/pkg/agent/application/coordinator/coordinator.go
  internal/pkg/agent/cmd/inspect.go
  internal/pkg/agent/install/uninstall.go
  pkg/component/component.go
  pkg/component/component_test.go
Labels: bug, Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent, skip-changelog, backport-v8.6.0

#2160 pull out env vars from daemonset and document them
  dev-tools/kubernetes/base/elastic-agent-managed/.env
  dev-tools/kubernetes/base/elastic-agent-managed/daemonset.yaml
  dev-tools/kubernetes/base/elastic-agent-standalone/.env
  dev-tools/kubernetes/base/elastic-agent-standalone/daemonset.yaml
Labels: enhancement, Team:Cloudnative-Monitoring, backport-skip

#2172 Accept `fleet.proxy_url` policy options
  internal/pkg/agent/application/actions/handlers/handler_action_policy_change.go
Labels: bug, Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent, skip-changelog, backport-v8.6.0

#2186 Upgrade golang/x/crypto to latest.
  NOTICE.txt
  go.mod
  go.sum
Labels: Team:Elastic-Agent, backport-v8.6.0

#2173 Prevent losing Headers
  internal/pkg/agent/application/actions/handlers/handler_action_policy_change.go
  internal/pkg/agent/cmd/enroll_cmd.go
Labels: Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent, skip-changelog, backport-v8.6.0

#2199 Update kubernetes templates for elastic-agent [templates.d]
  deploy/kubernetes/elastic-agent-standalone/templates.d/apache.yml
  deploy/kubernetes/elastic-agent-standalone/templates.d/crowdstrike.yml
  deploy/kubernetes/elastic-agent-standalone/templates.d/cyberarkpas.yml
  deploy/kubernetes/elastic-agent-standalone/templates.d/hid_bravura_monitor.yml
  deploy/kubernetes/elastic-agent-standalone/templates.d/infoblox_nios.yml
  deploy/kubernetes/elastic-agent-standalone/templates.d/iptables.yml
  deploy/kubernetes/elastic-agent-standalone/templates.d/microsoft_sqlserver.yml
  deploy/kubernetes/elastic-agent-standalone/templates.d/mimecast.yml
  deploy/kubernetes/elastic-agent-standalone/templates.d/mongodb.yml
  deploy/kubernetes/elastic-agent-standalone/templates.d/nginx_ingress_controller.yml
  deploy/kubernetes/elastic-agent-standalone/templates.d/panw.yml
  deploy/kubernetes/elastic-agent-standalone/templates.d/sentinel_one.yml
  deploy/kubernetes/elastic-agent-standalone/templates.d/snort.yml
  deploy/kubernetes/elastic-agent-standalone/templates.d/symantec_endpoint.yml
  deploy/kubernetes/elastic-agent-standalone/templates.d/synthetics.yml
  deploy/kubernetes/elastic-agent-standalone/templates.d/udp.yml
Labels: automation, backport-skip

#2164 docs: update docs versions 8.6.1
  deploy/kubernetes/elastic-agent-managed-kubernetes.yaml
  deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml
  version/docs/version.asciidoc
Labels: Team:Automation, release, docs, in progress

#2188 [Anduril] Defend for containers (cloud-defend) spec updates
  deploy/kubernetes/elastic-agent-managed-kubernetes.yaml
  deploy/kubernetes/elastic-agent-managed/elastic-agent-managed-daemonset.yaml
  deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml
  deploy/kubernetes/elastic-agent-standalone/elastic-agent-standalone-daemonset.yaml
  internal/pkg/agent/application/monitoring/v1_monitor.go
  specs/cloud-defend.spec.yml
Labels: bug, backport-skip, Team: Cloud Native Integrations

#2204 Fix TestAddToBucket flakiness on Windows
  pkg/component/runtime/command.go
  pkg/component/runtime/command_test.go
Labels: bug, backport-v8.6.0

#2210 Add spec for Universal Profiling Agent
  changelog/fragments/1675151497-Add-Universal-Profiling-Agent.yaml
  dev-tools/packaging/templates/docker/Dockerfile.elastic-agent.tmpl
  magefile.go
  pkg/component/load_test.go
  specs/pf-host-agent.spec.yml
Labels: enhancement, backport-skip

#1703 Add agent diagnostics action
  _meta/config/common.p2.yml.tmpl
  _meta/config/common.reference.p2.yml.tmpl
  changelog/fragments/1674785407-add-diagnostics-action-handler.yaml
  elastic-agent.reference.yml
  elastic-agent.yml
  internal/pkg/agent/application/actions/handlers/handler_action_diagnostics.go
  internal/pkg/agent/application/coordinator/coordinator.go
  internal/pkg/agent/application/dispatcher/dispatcher_test.go
  internal/pkg/agent/application/managed_mode.go
  internal/pkg/agent/cmd/diagnostics.go
  internal/pkg/core/monitoring/config/config.go
  internal/pkg/diagnostics/diagnostics.go
  internal/pkg/fleetapi/ack_cmd.go
  internal/pkg/fleetapi/acker/fleet/fleet_acker.go
  internal/pkg/fleetapi/acker/fleet/fleet_acker_test.go
  internal/pkg/fleetapi/action.go
  internal/pkg/fleetapi/uploader/uploader.go
  internal/pkg/fleetapi/uploader/uploader_test.go
  internal/pkg/queue/actionqueue_test.go
Labels: enhancement, Team:Elastic-Agent-Control-Plane, Team:Fleet, backport-skip
