Repository elastic/elastic-agent, pull requests merged in 2023-08, with the labels that each got.

#3136 Improve test runner to re-use instances and make provisioners pluggable
  .buildkite/scripts/steps/integration_tests.sh
  .gitignore
  NOTICE.txt
  docs/test-framework-dev-guide.md
  go.mod
  go.sum
  magefile.go
  pkg/testing/ess/provisioner.go
  pkg/testing/ogc/api.go
  pkg/testing/ogc/config.go
  pkg/testing/ogc/provisioner.go
  pkg/testing/ogc/supported.go
  pkg/testing/runner/config.go
  pkg/testing/runner/debian.go
  pkg/testing/runner/layout.go
  pkg/testing/runner/provisioner.go
  pkg/testing/runner/runner.go
  pkg/testing/runner/supported.go
  pkg/testing/runner/utils.go
  testing/.gitignore
  testing/integration/endpoint_security_test.go
Labels: Team:Elastic-Agent, skip-changelog, backport-v8.9.0

#1891 Adding cloudbeat to EXTERNAL flow
  magefile.go
Labels: enhancement, backport-skip, skip-changelog

#3150 Clean up runtime manager test initialization
  pkg/component/runtime/manager.go
  pkg/component/runtime/manager_test.go
Labels: Team:Elastic-Agent, backport-skip, Cleanup, skip-changelog

#3164 Disable proxy tests while flakiness is addressed.
  testing/integration/proxy_url_test.go
Labels: Team:Elastic-Agent, backport-skip, skip-changelog

#3153 Add Kafka to osquerybeat+endpoint spec files.
  specs/endpoint-security.spec.yml
  specs/osquerybeat.spec.yml
Labels: Team:Elastic-Agent, backport-skip, skip-changelog

#2955 Introduce upgrade tests from released versions
  pkg/testing/fixture.go
  testing/integration/upgrade_test.go
Labels: Team:Elastic-Agent-Control-Plane, backport-skip, skip-changelog, Testing

#3142 Add new install checker that stops the watcher when Elastic Agent is uninstalled
  internal/pkg/agent/application/upgrade/crash_checker.go
  internal/pkg/agent/application/upgrade/install_checker.go
  internal/pkg/agent/cmd/watch.go
  internal/pkg/agent/configuration/upgrade.go
Labels: Team:Elastic-Agent, backport-skip, skip-changelog

#3163 Add auto diagnostic collection on test failure and ability to skip uninstall for inspection of installed agent
  .buildkite/pipeline.yml
  docs/test-framework-dev-guide.md
  magefile.go
  pkg/testing/fixture.go
  pkg/testing/fixture_install.go
  pkg/testing/runner/config.go
  pkg/testing/runner/debian.go
  pkg/testing/runner/runner.go
  pkg/testing/runner/ssh.go
Labels: Team:Elastic-Agent, skip-changelog, backport-v8.9.0

#3169 Skip versions newer than version under test for upgrade tests
  testing/integration/upgrade_test.go
Labels: Team:Elastic-Agent, skip-changelog, Testing, backport-v8.9.0

#3175 Fix typo in artifact verification error log
  internal/pkg/agent/application/upgrade/artifact/download/http/verifier.go
Labels: debugging, skip-changelog, backport-v8.9.0

#3177 [Automation] Bump Golang version to 1.20.7
  .github/workflows/govulncheck.yml
  .go-version
  .golangci.yml
  Dockerfile
  Dockerfile.skaffold
  changelog/fragments/1691070305-Upgrade-to-Go-1.20.7.yaml
  version/docs/version.asciidoc
Labels: backport-v8.9.0

#3160 [heartbeat] Add default timezone to complete image
  changelog/fragments/1690896259-synthetics-default-timezone.yaml
  dev-tools/packaging/templates/docker/Dockerfile.elastic-agent.tmpl
Labels: bug, Team:Uptime, backport-v8.9.0

#3186 [updatecli][githubrelease] Bump version to 1.19.12 on 8.9
  .go-version
  .golangci.yml
  Dockerfile
  changelog/fragments/1691091834-Upgrade-to-Go-1.19.12.yaml
  version/docs/version.asciidoc
Labels: Team:Elastic-Agent, backport-skip

#3101 [Integration Test] Upgrade failed default verification test
  control_v2.proto
  internal/pkg/agent/application/actions/handlers/handler_action_upgrade.go
  internal/pkg/agent/application/actions/handlers/handler_action_upgrade_test.go
  internal/pkg/agent/application/actions/handlers/handler_helpers.go
  internal/pkg/agent/application/coordinator/coordinator.go
  internal/pkg/agent/application/coordinator/coordinator_test.go
  internal/pkg/agent/application/coordinator/coordinator_unit_test.go
  internal/pkg/agent/application/upgrade/artifact/download/composed/verifier.go
  internal/pkg/agent/application/upgrade/artifact/download/composed/verifier_test.go
  internal/pkg/agent/application/upgrade/artifact/download/fs/verifier.go
  internal/pkg/agent/application/upgrade/artifact/download/fs/verifier_test.go
  internal/pkg/agent/application/upgrade/artifact/download/http/elastic_test.go
  internal/pkg/agent/application/upgrade/artifact/download/http/verifier.go
  internal/pkg/agent/application/upgrade/artifact/download/snapshot/verifier.go
  internal/pkg/agent/application/upgrade/artifact/download/verifier.go
  internal/pkg/agent/application/upgrade/step_download.go
  internal/pkg/agent/application/upgrade/upgrade.go
  internal/pkg/agent/cmd/upgrade.go
  pkg/control/v1/proto/control_v1.pb.go
  pkg/control/v1/proto/control_v1_grpc.pb.go
  pkg/control/v2/client/client.go
  pkg/control/v2/cproto/control_v2.pb.go
  pkg/control/v2/cproto/control_v2_grpc.pb.go
  pkg/control/v2/server/server.go
  pkg/testing/tools/agents.go
  pkg/testing/tools/artifacts_api.go
  testing/integration/upgrade_test.go
Labels: Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent, skip-changelog, Testing, backport-v8.9.0

#3181 Add ability to filter runner by TEST_PLATFORM
  docs/test-framework-dev-guide.md
  magefile.go
  pkg/testing/runner/config.go
  pkg/testing/runner/config_test.go
  pkg/testing/runner/runner.go
  pkg/testing/runner/supported.go
  pkg/testing/runner/supported_test.go
Labels: Team:Elastic-Agent, skip-changelog, backport-v8.9.0

#3151 add permissions for release-eng to trigger package pipeline
  catalog-info.yaml
Labels: backport-skip, skip-changelog

#3183 Add TEST_RUN_UNTIL_FAILURE option to integration suite
  docs/test-framework-dev-guide.md
  magefile.go
Labels: Team:Elastic-Agent, skip-changelog, backport-v8.9.0

#3189 [Developer Documentation] Add details of Upgrade Watcher interactions with Agent and upgrade marker file
  docs/upgrades.md
Labels: documentation, Team:Elastic-Agent, skip-changelog, backport-v8.9.0

#3205 [Flaky test] skip FQDN integration test
  testing/integration/fqdn_test.go
Labels: Team:Elastic-Agent, flaky-test, backport-skip, skip-changelog

#3199 Remove 8.9 schedule for DRA artifacts
  catalog-info.yaml
Labels: backport-skip, skip-changelog

#3190 Add complete flag environment variable to agent metadata
  changelog/fragments/1691141314-complete-image-metadata.yaml
  dev-tools/packaging/templates/docker/Dockerfile.elastic-agent.tmpl
  internal/pkg/agent/application/info/agent_metadata.go
  internal/pkg/release/version.go
  testing/fleetservertest/fleetserver_test.go
Labels: enhancement, Team:Uptime, backport-skip

#3204 Vagrantfile: increase dev box resources
  Vagrantfile
Labels: enhancement, backport-skip, skip-changelog

#3165 Fix diagnostic scrubbing errors
  NOTICE.txt
  changelog/fragments/1690916478-fix-cred-scrubbing.yaml
  go.mod
  internal/pkg/agent/cmd/diagnostics.go
  internal/pkg/diagnostics/diagnostics.go
  internal/pkg/diagnostics/diagnostics_test.go
  pkg/component/runtime/state.go
Labels: bug, Team:Elastic-Agent, backport-skip

#3187 Serverless integration tests
  magefile.go
  pkg/testing/ess/config.go
  pkg/testing/ess/serverless.go
  pkg/testing/ess/serverless_provision.go
  pkg/testing/ess/serverless_test.go
Labels: Team:Elastic-Agent, backport-skip, skip-changelog

#3215 Revert "Add new install checker that stops the watcher when Elastic Agent is uninstalled"
  internal/pkg/agent/application/upgrade/crash_checker.go
  internal/pkg/agent/application/upgrade/install_checker.go
  internal/pkg/agent/cmd/watch.go
  internal/pkg/agent/configuration/upgrade.go
Labels: Team:Elastic-Agent, backport-skip, skip-changelog

#3182 Remove cloud-defend spec file from this repo
  pkg/component/load_test.go
  specs/cloud-defend.spec.yml
Labels: enhancement, backport-skip, skip-changelog, v8.10.0

#3216 Fix Coordinator log formatting strings
  internal/pkg/agent/application/coordinator/coordinator.go
Labels: bug, Team:Elastic-Agent, backport-skip, skip-changelog

#3217 Fix character on changelog filename
  changelog/fragments/1688657261-Dont-trigger-IOC-alert-on-Windows-uninstall.yaml
Labels: bug, Team:Elastic-Agent, backport-skip, skip-changelog

#3201 Fix `mage integration:clean` to actually delete instances and stacks
  .buildkite/scripts/steps/integration_tests.sh
  magefile.go
  pkg/testing/ogc/provisioner.go
  pkg/testing/runner/config.go
  pkg/testing/runner/provisioner.go
  pkg/testing/runner/runner.go
  pkg/testing/runner/runner_test.go
Labels: Team:Elastic-Agent, skip-changelog, backport-v8.9.0

#3224 Fix spawning upgrade watcher on darwin platform
  internal/pkg/agent/application/paths/common.go
Labels: Team:Elastic-Agent, backport-skip, skip-changelog

#3226 Add deployment ID to ESS stack create console output
  pkg/testing/ess/provisioner.go
Labels: Team:Elastic-Agent, skip-changelog, backport-v8.9.0

#3203 Fix Elastic Defend removal for tamper protected Agent. Add E2E test coverage for tamper protection.
  NOTICE.txt
  go.mod
  go.sum
  pkg/component/runtime/service.go
  pkg/testing/ess/deployment.go
  pkg/testing/fixture.go
  pkg/testing/fixture_install.go
  pkg/testing/tools/agents.go
  pkg/testing/tools/fleet_package_policy_api.go
  pkg/testing/tools/tools.go
  testing/integration/endpoint_security_test.go
  testing/integration/enroll_test.go
  testing/integration/fqdn_test.go
  testing/integration/upgrade_test.go
Labels: bug, enhancement, backport-skip, skip-changelog, v8.10.0

#3227 Fix mapping the upgrading state to degraded.
  changelog/fragments/1691694963-Stop-translating-the-Upgrading-agent-state-to-Degraded.yaml
  internal/pkg/agent/application/gateway/fleet/fleet_gateway.go
  internal/pkg/agent/application/gateway/fleet/fleet_gateway_test.go
Labels: Team:Elastic-Agent, backport-v8.9.0

#3222 increase internal/pkg/agent/install.RemovePath arbitrary timeout
  internal/pkg/agent/install/uninstall.go
Labels: Team:Elastic-Agent, flaky-test, skip-changelog, backport-v8.9.0

#3202 Adds an instance provisioner for multipass for integration testing locally
  docs/test-framework-dev-guide.md
  magefile.go
  pkg/testing/multipass/provisioner.go
Labels: Team:Elastic-Agent, skip-changelog, backport-v8.9.0

#3179 Add support for setting GOMAXPROCS for components started by the agent and the agent itself
  NOTICE.txt
  _meta/config/common.reference.p2.yml.tmpl
  changelog/fragments/1691160301-gomaxprocs-config-option.yaml
  elastic-agent.reference.yml
  go.mod
  go.sum
  internal/pkg/agent/application/application.go
  internal/pkg/agent/application/application_test.go
  internal/pkg/agent/application/coordinator/coordinator.go
  internal/pkg/agent/application/coordinator/diagnostics_test.go
  pkg/component/component.go
  pkg/component/config.go
  pkg/component/runtime/failed.go
  pkg/component/runtime/manager_test.go
  pkg/component/runtime/state.go
  pkg/limits/limits.go
  pkg/limits/limits_test.go
Labels: enhancement, Team:Elastic-Agent, backport-skip

#3220 Prevent `systemd` from killing the Upgrade Watcher process after the main Agent process has crashed
  NOTICE.txt
  changelog/fragments/1691647276-systemd-increase-upg-watcher-kill-timeout.yaml
  dev-tools/packaging/templates/linux/elastic-agent.unit.tmpl
  go.mod
  go.sum
  internal/pkg/agent/application/upgrade/service_update.go
  internal/pkg/agent/application/upgrade/service_update_linux.go
  internal/pkg/agent/application/upgrade/service_update_linux_test.go
  internal/pkg/agent/cmd/run.go
  internal/pkg/agent/install/svc.go
Labels: bug, Team:Elastic-Agent, backport-skip

#3248 8.9.1 changelog generation
  changelog/8.9.1.asciidoc
  changelog/8.9.1.yaml
  changelog/fragments/1689622778-upgrade-watcher-fix-error-message.yaml
  changelog/fragments/1690896259-synthetics-default-timezone.yaml
  changelog/fragments/1691091834-Upgrade-to-Go-1.19.12.yaml
  changelog/fragments/1691694963-Stop-translating-the-Upgrading-agent-state-to-Degraded.yaml
Labels: Team:Elastic-Agent, skip-changelog, forwardport-main

#3250 Bump the version on main to 8.10
  version/version.go
Labels: backport-skip, skip-changelog

#3266 Fix branch version number
  deploy/kubernetes/elastic-agent-managed-kubernetes.yaml
  deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml
  version/docs/version.asciidoc
  version/version.go
Labels: Team:Elastic-Agent, backport-skip, skip-changelog

#3246 docs: update docs versions 8.9.1
  deploy/kubernetes/elastic-agent-kustomize/default/elastic-agent-managed/base/elastic-agent-managed-daemonset.yaml
  deploy/kubernetes/elastic-agent-kustomize/default/elastic-agent-standalone/base/elastic-agent-standalone-daemonset.yaml
  deploy/kubernetes/elastic-agent-kustomize/ksm-autosharding/elastic-agent-managed/base/elastic-agent-managed-daemonset.yaml
  deploy/kubernetes/elastic-agent-kustomize/ksm-autosharding/elastic-agent-managed/extra/elastic-agent-managed-statefulset.yaml
  deploy/kubernetes/elastic-agent-kustomize/ksm-autosharding/elastic-agent-standalone/base/elastic-agent-standalone-daemonset.yaml
  deploy/kubernetes/elastic-agent-kustomize/ksm-autosharding/elastic-agent-standalone/extra/elastic-agent-standalone-statefulset.yaml
  deploy/kubernetes/elastic-agent-managed-kubernetes.yaml
  deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml
  deploy/kubernetes/elastic-agent-standalone/elastic-agent-standalone-daemonset.yaml
  version/docs/version.asciidoc
Labels: Team:Automation, release, docs, in progress, skip-changelog

#3247 [Release] Update version to 8.9.2
  version/version.go
Labels: Team:Automation, release, skip-changelog

#3256 Fix versioning in K8s makefile
  deploy/kubernetes/Makefile
  deploy/kubernetes/elastic-agent-standalone/elastic-agent-standalone-daemonset.yaml
Labels: Team:Elastic-Agent, release, skip-changelog

#3273 Update the e2e-testing dependency and unblock 8.11 buiilds
  NOTICE.txt
  go.mod
  go.sum
  magefile.go
Labels: Team:Elastic-Agent, backport-skip, skip-changelog

#3281 Change BK machine type in integration pipeline
  .buildkite/pipeline.yml
Labels: bug, skip-changelog, backport-v8.8.0, ci, backport-v8.9.0

#3293 skip downgrade test when only one snapshot version is available
  pkg/testing/tools/artifacts_api.go
  testing/integration/upgrade_test.go
Labels: Team:Elastic-Agent, flaky-test, skip-changelog, backport-v8.9.0, backport-v8.10.0

#3271 Add cnative team as codeowner for k8s provider
  .github/CODEOWNERS
Labels: backport-skip, skip-changelog

#3295 Fix components in diag collection from Kibana
  changelog/fragments/1691647290-kibana-diag-collection.yaml
  internal/pkg/agent/application/actions/handlers/handler_action_diagnostics.go
  internal/pkg/agent/application/actions/handlers/handler_action_diagnostics_test.go
  internal/pkg/agent/application/actions/handlers/mocks/diagnostics_provider.go
Labels: bug, Team:Elastic-Agent, backport-v8.9.0, backport-v8.10.0

#3245 [Upgrade Watcher] Add logging to rollback restart step
  changelog/fragments/1692141038-upgrade-watcher-logging.yaml
  internal/pkg/agent/application/upgrade/rollback.go
  internal/pkg/agent/cmd/run.go
  internal/pkg/agent/cmd/watch.go
Labels: enhancement, Team:Elastic-Agent, backport-v8.9.0, backport-v8.10.0

#3291 Fix Endpoint teardown handling while tamper protection is enabled
  pkg/component/runtime/service.go
Labels: bug, Team:Elastic-Agent, skip-changelog, backport-v8.10.0

#3268 [Upgrade Watcher] Try restarting Agent in multiple ways during rollback
  changelog/fragments/1692323065-bugfix-rollback-restart-agent-no-process.yaml
  internal/pkg/agent/application/upgrade/rollback.go
  internal/pkg/agent/install/install.go
Labels: bug, Team:Elastic-Agent, backport-v8.10.0

#3238 Daily BK job deleting stale GCE instances
  .buildkite/hooks/pre-exit
  .buildkite/misc/gce-cleanup.yml
  .buildkite/pipeline.elastic-agent-gce-cleanup.yml
  .buildkite/scripts/steps/gce-cleanup.sh
  .buildkite/scripts/unset-secrets.sh
  catalog-info.yaml
Labels: backport-skip, skip-changelog

#3312 Rename package version file so it's not hidden anymore
  dev-tools/packaging/packages.yml
  internal/pkg/diagnostics/diagnostics.go
  testing/integration/diagnostics_test.go
  version/helper.go
Labels: bug, skip-changelog, backport-v8.10.0

#3314 Skip test while snapshot downloader cannot handle downgrades
  internal/pkg/agent/application/upgrade/upgrade.go
  testing/integration/upgrade_test.go
Labels: flaky-test, backport-skip, skip-changelog

#3235 Fix flakiness on enrollment integration test and rename it
  pkg/testing/tools/check/check.go
  testing/integration/monitoring_logs_test.go
  testing/integration/proxy_url_test.go
Labels: Team:Elastic-Agent, flaky-test, skip-changelog, backport-v8.9.0, backport-v8.10.0

#3317 Properly check if and error matches a windows/syscall error
  changelog/fragments/1693319952-Change-error-handling-o-Windows-when-uninstalling-the-Elastic-Agent.yaml
  internal/pkg/agent/install/uninstall.go
  internal/pkg/agent/install/uninstall_unix.go
  internal/pkg/agent/install/uninstall_windows.go
Labels: bug, flaky-test, backport-v8.9.0, backport-v8.10.0

#3300 Update elastic-agent-libs to v0.3.13
  NOTICE.txt
  go.mod
  go.sum
Labels: Team:Elastic-Agent, skip-changelog, backport-v8.9.0, backport-v8.10.0

#3335 move the package version file outside of app directory for MacOS
  dev-tools/packaging/packages.yml
  version/helper.go
Labels: bug, Team:Elastic-Agent, skip-changelog, backport-v8.10.0
