Repository elastic/elastic-agent, pull requests merged in 2023-09, with the labels that each got.

#3340 Diagnostics creates the necessary folder for -f argument
  changelog/fragments/1693544911-Diagnostics-command-creates-necessary-folders-for--f-flag.yaml
  internal/pkg/agent/cmd/diagnostics.go
  internal/pkg/agent/cmd/diagnostics_test.go
  internal/pkg/agent/cmd/logs_test.go
Labels: bug, Team:Elastic-Agent, backport-v8.10.0

#3107 Add support for processors in hints based k8s autodiscover
  changelog/fragments/1691060806-Processor-support-for-hints-autodiscover.yaml
  internal/pkg/composable/providers/kubernetes/hints.go
  internal/pkg/composable/providers/kubernetes/hints_test.go
  internal/pkg/composable/providers/kubernetes/pod.go
Labels: backport-skip, 8.10-candidate

#3267 Updating variable %BRANCH% to repalce hardcoded value main
  deploy/kubernetes/Makefile
  deploy/kubernetes/elastic-agent-standalone/elastic-agent-standalone-daemonset.yaml
Labels: backport-skip, skip-changelog

#3265 Small improvements on integration tests
  pkg/testing/tools/testcontext/testcontext.go
  pkg/testing/tools/tools.go
  testing/integration/endpoint_security_test.go
  testing/integration/install_test.go
  testing/integration/upgrade_test.go
Labels: Team:Elastic-Agent, flaky-test, skip-changelog, backport-v8.10.0

#3108 Sonarqube buildkite integration
  .buildkite/hooks/post-checkout
  .buildkite/pipeline.yml
  .buildkite/scripts/common.sh
  .buildkite/scripts/steps/unit-tests.sh
  .github/workflows/build.yml
  .github/workflows/sonarcloud.yml
  sonar-project.properties
Labels: Team:Elastic-Agent, backport-skip, skip-changelog

#3214 [Tests] Update K8s and Kind version
  .ci/Jenkinsfile
Labels: backport-skip, skip-changelog

#3351 Changelog creation for 8.9.2 release
  changelog/8.9.2.asciidoc
  changelog/8.9.2.yaml
  changelog/fragments/1692141038-upgrade-watcher-logging.yaml
  changelog/fragments/1693319952-Change-error-handling-o-Windows-when-uninstalling-the-Elastic-Agent.yaml
Labels: Team:Elastic-Agent, skip-changelog, forwardport-main

#3330 [Release] Update version to 8.9.3
  version/version.go
Labels: Team:Automation, release, skip-changelog

#3310 [crossbuild] Fix path separators
  dev-tools/mage/crossbuild.go
Labels: Team:Elastic-Agent, backport-skip, Packaging, skip-changelog

#3356 Revert changes to RemovePath
  changelog/fragments/1693319952-Change-error-handling-o-Windows-when-uninstalling-the-Elastic-Agent.yaml
  internal/pkg/agent/install/uninstall.go
  internal/pkg/agent/install/uninstall_unix.go
  internal/pkg/agent/install/uninstall_windows.go
Labels: Team:Elastic-Agent, skip-changelog, backport-v8.10.0

#3360 exclude fake components from sonar analysis
  sonar-project.properties
Labels: Team:Elastic-Agent, backport-skip, skip-changelog, Testing

#3361 Don't create a stack on a single run that doesn't require a stack
  pkg/testing/define/batch.go
  pkg/testing/define/batch_test.go
  pkg/testing/ogc/provisioner.go
  pkg/testing/runner/debian.go
  pkg/testing/runner/runner.go
Labels: Team:Elastic-Agent, skip-changelog, Testing, backport-v8.9.0, backport-v8.10.0

#3338 Show installation progress
  NOTICE.txt
  changelog/fragments/1693427183-install-progress.yaml
  go.mod
  internal/pkg/agent/cmd/install.go
  internal/pkg/agent/install/install.go
  internal/pkg/agent/install/progress.go
  internal/pkg/agent/install/progress_test.go
Labels: enhancement, Team:Elastic-Agent, backport-skip

#3348 Ignore AGENT_KEEP_INSTALLED if test succeeds
  docs/test-framework-dev-guide.md
  pkg/testing/fixture_install.go
Labels: enhancement, Team:Elastic-Agent, skip-changelog, backport-v8.10.0

#3370 Fix integration tests by waiting for the watcher to finish during upgrade tests
  testing/integration/upgrade_test.go
Labels: Team:Elastic-Agent, skip-changelog, backport-v8.10.0

#3166 [Upgrade Watcher][Crash Checker] Consider Agent process as crashed if its PID remains 0
  changelog/fragments/1690917883-crash-checker-pid-zero.yaml
  internal/pkg/agent/application/upgrade/crash_checker.go
  internal/pkg/agent/application/upgrade/crash_checker_test.go
  internal/pkg/agent/cmd/watch.go
Labels: bug, Team:Elastic-Agent, backport-v8.10.0

#3274 Adding upgrade test for unhealthy upgraded Agent
  pkg/testing/fixture_install.go
  testing/integration/upgrade_test.go
Labels: Team:Elastic-Agent, skip-changelog, backport-v8.10.0

#3380 Fix when fixture.Install logs 'ignoring AGENT_KEEP_INSTALLED...'
  pkg/testing/fixture_install.go
Labels: enhancement, Team:Elastic-Agent, skip-changelog, backport-v8.10.0

#3345 Add colors for log messages based on their level
  NOTICE.txt
  changelog/fragments/1693813219-log-command-colors.yaml
  go.mod
  internal/pkg/agent/cmd/logs.go
  internal/pkg/agent/cmd/logs_test.go
Labels: enhancement, Team:Elastic-Agent, backport-skip

#3279 Improve the coordinator logging correctness
  internal/pkg/agent/application/coordinator/coordinator.go
  pkg/core/logger/logger.go
Labels: enhancement, Team:Elastic-Agent, backport-skip, Cleanup, skip-changelog

#3385 Revert "skip test while snapshot downloader cannot handle downgrades (#3314)"
  internal/pkg/agent/application/upgrade/upgrade.go
  testing/integration/upgrade_test.go
Labels: Team:Elastic-Agent, backport-skip, skip-changelog

#3354 Updating Elastic Manifests with NETINFO variable
  changelog/fragments/1693920861-netinfo-manifests.yaml
  deploy/kubernetes/elastic-agent-kustomize/default/elastic-agent-managed/base/elastic-agent-managed-daemonset.yaml
  deploy/kubernetes/elastic-agent-kustomize/default/elastic-agent-standalone/base/elastic-agent-standalone-daemonset.yaml
  deploy/kubernetes/elastic-agent-kustomize/ksm-autosharding/elastic-agent-managed/base/elastic-agent-managed-daemonset.yaml
  deploy/kubernetes/elastic-agent-kustomize/ksm-autosharding/elastic-agent-managed/extra/elastic-agent-managed-statefulset.yaml
  deploy/kubernetes/elastic-agent-kustomize/ksm-autosharding/elastic-agent-standalone/base/elastic-agent-standalone-daemonset.yaml
  deploy/kubernetes/elastic-agent-kustomize/ksm-autosharding/elastic-agent-standalone/extra/elastic-agent-standalone-statefulset.yaml
  deploy/kubernetes/elastic-agent-managed-kubernetes.yaml
  deploy/kubernetes/elastic-agent-managed/elastic-agent-managed-daemonset.yaml
  deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml
  deploy/kubernetes/elastic-agent-standalone/elastic-agent-standalone-daemonset.yaml
Labels: backport-skip

#3394 Bump elastic-agent-libs to get the new kibana client
  NOTICE.txt
  go.mod
  go.sum
Labels: bug, Team:Elastic-Agent, backport-skip, skip-changelog

#3398 Changelog for 8.10.0
  changelog/8.10.0.asciidoc
  changelog/8.10.0.yaml
  changelog/fragments/1687529573-Report-the-version-from-the-elastic-agent-package-instead-of-agent-binary.yaml
  changelog/fragments/1688069371-Tamper-protected-Endpoint-uninstall.yaml
  changelog/fragments/1688572070-Upgrade-Go-to-1.20.5.yaml
  changelog/fragments/1688657261-Dont-trigger-IOC-alert-on-Windows-uninstall.yaml
  changelog/fragments/1688712693-Removed-calls-to-fleet-setup.yaml
  changelog/fragments/1689883203-Elastic-Defend-runtime-prevention.yaml
  changelog/fragments/1690219594-component-diagnostics.yaml
  changelog/fragments/1690468425-Improves-upgrade-process-to-uses-upgraded-version-of-watcher-to-ensure-for-a-successful-upgrade.yaml
  changelog/fragments/1690916478-fix-cred-scrubbing.yaml
  changelog/fragments/1691070305-Upgrade-to-Go-1.20.7.yaml
  changelog/fragments/1691141314-complete-image-metadata.yaml
  changelog/fragments/1691160301-gomaxprocs-config-option.yaml
  changelog/fragments/1691647276-systemd-increase-upg-watcher-kill-timeout.yaml
  changelog/fragments/1691647290-kibana-diag-collection.yaml
  changelog/fragments/1692323065-bugfix-rollback-restart-agent-no-process.yaml
  changelog/fragments/1693544911-Diagnostics-command-creates-necessary-folders-for--f-flag.yaml
Labels: Team:Elastic-Agent, docs, skip-changelog, forwardport-main

#3365 [Integration Test Framework] Allow creation of deployments in ESS QA Azure region
  magefile.go
  pkg/testing/ess/deployment.go
Labels: Team:Elastic-Agent, backport-skip, skip-changelog

#3383 Implement basic version negotiation with Fleet Server
  .mockery.yaml
  internal/pkg/agent/application/coordinator/coordinator.go
  internal/pkg/agent/application/coordinator/coordinator_test.go
  internal/pkg/agent/application/coordinator/gateway.go
  internal/pkg/agent/application/gateway/fleet/fleet_gateway.go
  internal/pkg/agent/application/gateway/fleet/fleet_gateway_test.go
  internal/pkg/agent/application/managed_mode.go
  internal/pkg/fleetapi/checkin_cmd.go
  internal/pkg/fleetapi/client/client.go
  internal/pkg/fleetapi/client/client_test.go
  internal/pkg/fleetapi/client/round_trippers.go
  internal/pkg/remote/client.go
Labels: enhancement, Team:Elastic-Agent, skip-changelog, backport-v8.10.0

#3382 Improve Upgrade-related logging
  changelog/fragments/1694190260-improve-upgrade-logging.yaml
  internal/pkg/agent/application/upgrade/cleanup.go
  internal/pkg/agent/application/upgrade/crash_checker.go
  internal/pkg/agent/application/upgrade/error_checker.go
  internal/pkg/agent/application/upgrade/rollback.go
  internal/pkg/agent/application/upgrade/step_download.go
  internal/pkg/agent/application/upgrade/step_mark.go
  internal/pkg/agent/application/upgrade/upgrade.go
  internal/pkg/agent/cmd/run.go
  internal/pkg/agent/cmd/watch.go
Labels: Team:Elastic-Agent, backport-v8.10.0

#3401 Update version to 8.10.1
  version/version.go
Labels: Team:Elastic-Agent, release, skip-changelog

#3411 Fix TestRemovePath being flagged as a possible virus
  internal/pkg/agent/install/testblocking/main.go
  internal/pkg/agent/install/uninstall_windows_test.go
  magefile.go
Labels: Team:Elastic-Agent, skip-changelog, backport-v8.10.0

#3393 [Automation] Bump Golang version to 1.20.8
  .github/workflows/govulncheck.yml
  .go-version
  .golangci.yml
  Dockerfile
  Dockerfile.skaffold
  changelog/fragments/1694700200-Upgrade-to-Go-1.20.8.yaml
  version/docs/version.asciidoc
Labels: Team:Elastic-Agent, backport-v8.10.0

#3424 Skip TestRemovePath
  internal/pkg/agent/install/uninstall_windows_test.go
Labels: Team:Elastic-Agent, skip-changelog, Testing, backport-v8.10.0

#3396 Fix creatork8sscript
  changelog/fragments/1694439479-fix_creatork8sscript.yaml
  deploy/kubernetes/Makefile
Labels: backport-skip

#3359 Structure the BK pipeline output for failures
  .buildkite/pipeline.yml
  .buildkite/scripts/steps/integration_tests.sh
Labels: skip-changelog, backport-v8.8.0, ci, backport-v8.9.0, backport-v8.10.0

#3433 [Release] Update version to 8.10.2
  version/version.go
Labels: Team:Automation, release, skip-changelog

#3435 Changelog for 8.10.1
  changelog/8.10.1.asciidoc
  changelog/8.10.1.yaml
  changelog/fragments/1690917883-crash-checker-pid-zero.yaml
  changelog/fragments/1694190260-improve-upgrade-logging.yaml
Labels: Team:Elastic-Agent, skip-changelog, forwardport-main

#3432 docs: update docs versions 8.10.1
  deploy/kubernetes/elastic-agent-managed-kubernetes.yaml
  deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml
  version/docs/version.asciidoc
Labels: Team:Automation, release, docs, in progress, skip-changelog

#3431 Fix TestRemovePath flakiness on windows
  changelog/fragments/1695050880-Improve-retry-strategy-when-uninstalling-agent.yaml
  internal/pkg/agent/install/uninstall.go
  internal/pkg/agent/install/uninstall_windows_test.go
Labels: bug, Team:Elastic-Agent, Testing, backport-v8.10.0

#3426 If one gpg check is working, upgrade should continue
  changelog/fragments/1694700201-gpg-unreachable-url-fix.yaml
  internal/pkg/agent/application/upgrade/artifact/download/composed/verifier.go
  internal/pkg/agent/application/upgrade/artifact/download/composed/verifier_test.go
  internal/pkg/agent/application/upgrade/artifact/download/fs/verifier.go
  internal/pkg/agent/application/upgrade/artifact/download/http/verifier.go
  internal/pkg/agent/application/upgrade/artifact/download/localremote/verifier.go
  internal/pkg/agent/application/upgrade/artifact/download/snapshot/verifier.go
  internal/pkg/agent/application/upgrade/artifact/download/verifier.go
  internal/pkg/agent/application/upgrade/step_download.go
Labels: bug, Team:Elastic-Agent, backport-v8.10.0

#3441 Switch ESS region to azure-eastus2 for integ tests
  .buildkite/scripts/steps/integration_tests.sh
Labels: bug, Team:Elastic-Agent, backport-skip, skip-changelog

#3427 [Bug] Do not fail when remote PGPs are not available
  changelog/fragments/1695035111-Resilient-handling-of-air-gapped-PGP-checks.yaml
  internal/pkg/agent/application/upgrade/artifact/download/fs/verifier.go
  internal/pkg/agent/application/upgrade/artifact/download/fs/verifier_test.go
  internal/pkg/agent/application/upgrade/artifact/download/http/verifier.go
  internal/pkg/agent/application/upgrade/artifact/download/verifier.go
  testing/integration/upgrade_test.go
Labels: bug, Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent, backport-v8.10.0

#3450 docs: update docs versions 8.10.2
  NOTICE.txt
  deploy/kubernetes/elastic-agent-managed-kubernetes.yaml
  deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml
  go.mod
  go.sum
  version/docs/version.asciidoc
Labels: Team:Automation, release, docs, in progress, skip-changelog

#3455 Changelog for 8.10.2
  changelog/8.10.2.asciidoc
  changelog/8.10.2.yaml
  changelog/fragments/1694700200-Upgrade-to-Go-1.20.8.yaml
Labels: Team:Elastic-Agent, docs, skip-changelog, forwardport-main

#3384 Uninstall finds and kills any running `elastic-agent watch` process
  changelog/fragments/1694187216-Uninstall-finds-and-kills-any-running-watcher-process.yaml
  internal/pkg/agent/cmd/install.go
  internal/pkg/agent/cmd/uninstall.go
  internal/pkg/agent/install/install.go
  internal/pkg/agent/install/progress.go
  internal/pkg/agent/install/progress_test.go
  internal/pkg/agent/install/uninstall.go
  pkg/utils/watcher.go
  testing/integration/upgrade_test.go
Labels: Team:Elastic-Agent, backport-skip

#3376 Code cleanup for command checkins
  pkg/component/runtime/command.go
  pkg/component/runtime/manager.go
  pkg/component/runtime/runtime.go
  pkg/component/runtime/state.go
Labels: Team:Elastic-Agent, backport-skip, Cleanup, skip-changelog

#3451 [Release] Update version to 8.10.3
  .buildkite/scripts/steps/integration_tests.sh
  version/version.go
Labels: Team:Automation, release, skip-changelog

#3460 [BUG] Treat elastic-security container platforms as separate inputs
  specs/endpoint-security.spec.yml
Labels: bug, skip-changelog, backport-v8.10.0

#3467 pin the agent version to 8.10.2 until new version is available
  .buildkite/scripts/steps/integration_tests.sh
Labels: Team:Elastic-Agent, skip-changelog, Testing

#3468 Fix test diagnostics collection, zip the install directory when diagnostics collection fails
  pkg/testing/fixture_install.go
Labels: Team:Elastic-Agent, skip-changelog, backport-v8.10.0

#3415 `elastic-agent install`: Only uninstall when Agent is installed
  internal/pkg/agent/cmd/install.go
  internal/pkg/agent/install/install.go
Labels: Team:Elastic-Agent, >bug, skip-changelog, backport-v8.10.0

#3462 add pre exit hook for integration test cleanup
  .buildkite/hooks/pre-exit
Labels: Team:Elastic-Agent, skip-changelog, Testing, backport-v8.10.0

#3252 fix the GCP credentials variable name
  .buildkite/scripts/common.sh
Labels: backport-skip, skip-changelog

#3469 Refactor agent version pinning in integration test script
  .buildkite/scripts/steps/integration_tests.sh
Labels: Team:Elastic-Agent, backport-skip, skip-changelog, forwardport-main, Testing

#3299 [Cloud Security] Support Azure CSPM integration
  specs/cloudbeat.spec.yml
Labels: enhancement, backport-skip, skip-changelog

#3478 Enable tamper protection feature flag by default for Agent 8.11.0
  changelog/fragments/1695780865-Enable-tamper-protection-feature-flag-by-default-for-Agent-8.11.0.yaml
  pkg/features/features.go
Labels: backport-skip, v8.11.0

#3483 Remove override for integration test ESS region
  .buildkite/scripts/steps/integration_tests.sh
Labels: skip-changelog, backport-v8.10.0

#3085 [Integration Test] New Agent after upgrade fails to start
  sonar-project.properties
  testing/integration/upgrade_test.go
Labels: Team:Elastic-Agent, skip-changelog, Testing, backport-v8.10.0

#3473 [Standalone Agent] Disallow upgrade if upgrade is already in progress
  changelog/fragments/1695685534-standalone-prevent-quick-upgrades.yaml
  internal/pkg/agent/application/upgrade/upgrade.go
  internal/pkg/agent/application/upgrade/upgrade_test.go
  internal/pkg/agent/cmd/upgrade.go
  pkg/control/v2/client/client.go
  pkg/control/v2/client/mocks/client.go
  sonar-project.properties
  testing/integration/upgrade_test.go
Labels: Team:Elastic-Agent, >bug, backport-v8.10.0

#3223 Propagate apm config
  docs/tracing.md
  internal/pkg/agent/application/apm_config_modifier.go
  internal/pkg/agent/application/apm_config_modifier_test.go
  internal/pkg/agent/application/application.go
  internal/pkg/agent/application/coordinator/config_patcher.go
  internal/pkg/agent/application/coordinator/diagnostics_test.go
  internal/pkg/agent/cmd/run.go
  internal/pkg/core/monitoring/config/config.go
  pkg/component/component.go
  pkg/component/fake/component/README.md
  pkg/component/fake/component/comp/actions.go
  pkg/component/fake/component/comp/apm.go
  pkg/component/fake/component/comp/component.go
  pkg/component/fake/component/main.go
  pkg/component/runtime/apm_config_mapper.go
  pkg/component/runtime/apm_config_mapper_test.go
  pkg/component/runtime/command.go
  pkg/component/runtime/manager_test.go
  pkg/utils/maps.go
  testing/integration/apm_propagation_test.go
  testing/integration/fake_test.go
  testing/integration/fakes.go
Labels: enhancement, Team:Elastic-Agent, backport-skip, skip-changelog
