Repository elastic/elastic-agent, pull requests merged in 2023-02, with the labels that each got.

#2203 Do not propagate gateway errors.
  internal/pkg/agent/application/gateway/fleet/fleet_gateway.go
  internal/pkg/agent/application/gateway/fleet/fleet_gateway_test.go
  internal/pkg/agent/application/gateway/gateway.go
  internal/pkg/agent/application/managed_mode.go
Labels: bug, Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent, backport-v8.6.0

#2207 Preserve component state on upgrade
  changelog/fragments/1675085396-preserve-state-on-upgrade.yaml
  internal/pkg/agent/application/upgrade/upgrade.go
Labels: bug, Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent, backport-v8.6.0

#2171 Update agent monitoring config to support /inputs of filebeat
  changelog/fragments/1674822835-Enhance-agent-monitoring-config-to-support-filebeat-inputs-endpoint
  internal/pkg/agent/application/monitoring/v1_monitor.go
Labels: enhancement, backport-skip

#2220 Add support for excluded paths in packaging
  dev-tools/packaging/package_test.go
Labels: bug, Team:Elastic-Agent, backport-skip

#2196 filebeat.spec: Add new Entity Analytics input
  changelog/fragments/1674757194-entity-analytics-input.yaml
  specs/filebeat.spec.yml
Labels: enhancement, Team:Security-External Integrations, backport-skip, 8.7-candidate

#2222 Restore downloads directory before downloading
  internal/pkg/agent/application/upgrade/cleanup.go
  internal/pkg/agent/application/upgrade/step_download.go
Labels: bug, Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent, skip-changelog, backport-v8.6.0

#2226 Start/stop components in a more synchronised manner
  pkg/component/runtime/manager.go
  pkg/component/runtime/manager_test.go
  pkg/component/runtime/service.go
Labels: bug, Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent, backport-v8.6.0

#2228 golang: bump automation with updatecli and GH actions
  .ci/bump-go-release-version.sh
  .ci/bump-golang.yml
  .github/workflows/bump-golang.yml
Labels: backport-skip

#2225 [Heartbeat] Enable engine strict validation for synthetics install and update node
  changelog/fragments/1675379107-heartbeat-engine-strict-validation.yaml
  dev-tools/packaging/templates/docker/Dockerfile.elastic-agent.tmpl
Labels: bug, Team:Uptime, v8.7.0, backport-v8.6.0

#2237 Do not always fail on copy
  internal/pkg/agent/application/upgrade/upgrade.go
Labels: bug, Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent, backport-v8.6.0

#2239 Expose fleet connectivity state separately
  control_v2.proto
  internal/pkg/agent/application/application.go
  internal/pkg/agent/application/coordinator/coordinator.go
  internal/pkg/agent/application/gateway/fleet/fleet_gateway.go
  internal/pkg/agent/application/gateway/fleet/fleet_gateway_test.go
  internal/pkg/agent/application/gateway/gateway.go
  internal/pkg/agent/application/managed_mode.go
  internal/pkg/agent/cmd/status.go
  internal/pkg/agent/control/v2/client/client.go
  internal/pkg/agent/control/v2/cproto/control_v2.pb.go
  internal/pkg/agent/control/v2/server/server.go
Labels: bug, Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent, skip-changelog, backport-v8.6.0

#2242 backport: Add 8.7 branch
  .mergify.yml
Labels: Team:Automation, impact:critical, backport-skip, release

#2216 remove quotes from FLEET_ENROLL that prevented kustomize to create valid manifest
  dev-tools/kubernetes/base/elastic-agent-managed/.env
  dev-tools/kubernetes/base/elastic-agent-standalone/daemonset.yaml
Labels: bug, backport-skip

#2241 Bump the version on main to 8.7.0
  version/version.go
Labels: backport-skip

#2250 automation: remove bump snapshots
  .ci/bump-stack-version.sh
  .github/workflows/bump-golang.yml
  .github/workflows/opentelemetry.yml
  .mergify.yml
Labels: backport-v8.7.0

#2246 Enable verification with alternative PGP keys
  control_v2.proto
  dev-tools/cmd/buildpgp/build_pgp.go
  internal/pkg/agent/application/actions/handlers/handler_action_upgrade.go
  internal/pkg/agent/application/coordinator/coordinator.go
  internal/pkg/agent/application/upgrade/artifact/download/composed/verifier.go
  internal/pkg/agent/application/upgrade/artifact/download/composed/verifier_test.go
  internal/pkg/agent/application/upgrade/artifact/download/fs/verifier.go
  internal/pkg/agent/application/upgrade/artifact/download/fs/verifier_test.go
  internal/pkg/agent/application/upgrade/artifact/download/headers_rtt.go
  internal/pkg/agent/application/upgrade/artifact/download/headers_rtt_test.go
  internal/pkg/agent/application/upgrade/artifact/download/http/downloader.go
  internal/pkg/agent/application/upgrade/artifact/download/http/elastic_test.go
  internal/pkg/agent/application/upgrade/artifact/download/http/verifier.go
  internal/pkg/agent/application/upgrade/artifact/download/localremote/verifier.go
  internal/pkg/agent/application/upgrade/artifact/download/snapshot/verifier.go
  internal/pkg/agent/application/upgrade/artifact/download/verifier.go
  internal/pkg/agent/application/upgrade/step_download.go
  internal/pkg/agent/application/upgrade/upgrade.go
  internal/pkg/agent/cmd/upgrade.go
  internal/pkg/agent/control/v2/client/client.go
  internal/pkg/agent/control/v2/cproto/control_v2.pb.go
  internal/pkg/agent/control/v2/server/server.go
  internal/pkg/release/pgp.go
  magefile.go
Labels: enhancement, Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent, backport-v8.7.0

#2259 [Cloud Defend] removing these commented mounts as this feature is not going out until 8.8
  deploy/kubernetes/elastic-agent-managed-kubernetes.yaml
  deploy/kubernetes/elastic-agent-managed/elastic-agent-managed-daemonset.yaml
  deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml
  deploy/kubernetes/elastic-agent-standalone/elastic-agent-standalone-daemonset.yaml
Labels: Cleanup, Team: Cloud Native Integrations, backport-v8.7.0

#2266 action: use composite updatecli
  .github/workflows/bump-golang.yml
Labels: automation, backport-skip

#2270 Add the file extension in unit diagnostics again.
  internal/pkg/diagnostics/diagnostics.go
Labels: v8.7.0, backport-v8.7.0

#2265 Log the binary and platform on build failure.
  magefile.go
Labels: Team:Elastic-Agent, backport-skip

#2256 Migrate unencrypted config if fleet.enc does not exist
  changelog/fragments/1676358802-migrate-unencrypted-config.yaml
  internal/pkg/agent/cmd/run.go
  internal/pkg/agent/migration/migrate_config.go
  internal/pkg/agent/migration/migrate_config_test.go
Labels: bug, backport-v8.6.0, backport-v8.7.0

#2275 Create an overview of the agent v2 architecture
  ARCHITECTURE.md
  img/compute_model.png
  img/coordinator.png
Labels: Team:Elastic-Agent, docs, backport-v8.6.0, backport-v8.7.0

#2280 Delete snyk-scan.yml
  .github/workflows/snyk-scan.yml
Labels: backport-skip

#2268 Support only HTTPS for remote upgrade PGP
  _meta/config/common.p2.yml.tmpl
  _meta/config/common.reference.p2.yml.tmpl
  _meta/config/elastic-agent.docker.yml.tmpl
  _meta/elastic-agent.fleet.yml
  _meta/elastic-agent.yml
  elastic-agent.docker.yml
  elastic-agent.reference.yml
  elastic-agent.yml
  internal/pkg/agent/application/upgrade/artifact/download/verifier.go
  internal/pkg/agent/cmd/upgrade.go
Labels: bug, Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent, backport-v8.6.0, backport-v8.7.0

#2288 Fleet managed K8S resources should match standalone resources
  deploy/kubernetes/elastic-agent-managed-kubernetes.yaml
  deploy/kubernetes/elastic-agent-managed/elastic-agent-managed-daemonset.yaml
  dev-tools/kubernetes/base/elastic-agent-managed/daemonset.yaml
Labels: Team:Cloudnative-Monitoring, backport-v8.6.0, backport-v8.7.0

#2281 Changelog 8.6.2
  changelog/8.6.2.yaml
  changelog/fragments/1675085396-preserve-state-on-upgrade.yaml
  changelog/fragments/1675379107-heartbeat-engine-strict-validation.yaml
Labels: forwardport-main

#2254 docs: update docs versions 8.6.2
  deploy/kubernetes/elastic-agent-managed-kubernetes.yaml
  deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml
  version/docs/version.asciidoc
Labels: Team:Automation, release, docs, in progress

#2298 Restore support for the memcached/metrics input.
  changelog/fragments/1677000534-Restore-support-for-memcached-metrics-inputs.yaml
  specs/metricbeat.spec.yml
Labels: Team:Elastic-Agent, Team:Service-Integrations, backport-v8.7.0

#2255 [Release] Update version to 8.6.3
  version/version.go
Labels: Team:Automation, release

#2295 [Cloud Security] Add vulnerability management support
  specs/cloudbeat.spec.yml
Labels: enhancement, backport-skip

#2297 Render config using variables if --wait-variable option has been specified
  changelog/fragments/1677048898-render-config-for-inspect-with-variable-wait.yaml
  internal/pkg/agent/cmd/inspect.go
Labels: bug, backport-v8.6.0, backport-v8.7.0

#2308 Fix flaky dispatch cancel action unit test
  internal/pkg/agent/application/dispatcher/dispatcher_test.go
Labels: bug, backport-v8.6.0, backport-v8.7.0

#2313 Un-export action store identifiers
  internal/pkg/agent/storage/store/action_store.go
  internal/pkg/agent/storage/store/action_store_test.go
  internal/pkg/agent/storage/store/state_store.go
  internal/pkg/agent/storage/store/state_store_test.go
Labels: Cleanup, backport-v8.6.0, backport-v8.7.0

#2320 Upgrade Watcher: Fix notification channel for crashes
  changelog/fragments/1677255543-upgrade-watcher-fix-log.yaml
  internal/pkg/agent/cmd/watch.go
Labels: >bug, backport-v8.7.0

#2321 Fixing Agent README contents
  NOTICE.txt
  deploy/kubernetes/Makefile
  dev-tools/mage/settings.go
  dev-tools/packaging/templates/common/README.md.tmpl
  go.mod
  go.sum
  version/docs/version.asciidoc
Labels: docs, backport-v8.6.0, backport-v8.7.0

#2143 Cloud deployment with local agent
  README.md
  magefile.go
  testing/environments/cloud/.gitignore
  testing/environments/cloud/.terraform.lock.hcl
  testing/environments/cloud/Makefile
  testing/environments/cloud/README.md
  testing/environments/cloud/docker_image.auto.tfvars.sample
  testing/environments/cloud/main.tf
  testing/environments/cloud/outputs.tf
  testing/environments/cloud/terraform.tfvars
  testing/environments/cloud/variables.tf
  testing/environments/infra/terraform/modules/ec_deployment/.gitignore
  testing/environments/infra/terraform/modules/ec_deployment/README.md
  testing/environments/infra/terraform/modules/ec_deployment/deployment.tf
  testing/environments/infra/terraform/modules/ec_deployment/header.md
  testing/environments/infra/terraform/modules/ec_deployment/outputs.tf
  testing/environments/infra/terraform/modules/ec_deployment/scripts/custom-apm-integration-pkg.tftpl
  testing/environments/infra/terraform/modules/ec_deployment/scripts/drop_pipeline.tftpl
  testing/environments/infra/terraform/modules/ec_deployment/scripts/enable_expvar.tftpl
  testing/environments/infra/terraform/modules/ec_deployment/scripts/index_shards.tftpl
  testing/environments/infra/terraform/modules/ec_deployment/scripts/secret_token.tftpl
  testing/environments/infra/terraform/modules/ec_deployment/terraform.tf
  testing/environments/infra/terraform/modules/ec_deployment/variables.tf
Labels: enhancement, Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent, skip-changelog, backport-v8.6.0

#2325 Map State.STARTING as "starting" at fleet checkin to avoid presenting the agent as unhealthy at startup
  changelog/fragments/1677572502-add-fleet-checkin-starting-state.yaml
  internal/pkg/agent/application/gateway/fleet/fleet_gateway.go
  internal/pkg/agent/application/gateway/fleet/fleet_gateway_test.go
Labels: bug, backport-v8.6.0, backport-v8.7.0
