Repository elastic/elastic-agent, pull requests merged in 2023-04, with the labels that each got.

#2434 Avoid exiting with os.Exit
  NOTICE.txt
  dev-tools/mage/gotest_test.go
  go.mod
  go.sum
  internal/pkg/agent/cmd/common.go
  internal/pkg/agent/cmd/run.go
  main.go
Labels: bug, Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent, backport-v8.7.0

#2441 Update PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: backport-skip

#2218 Report FQDN on host.name as opt-in, enabled by feature flag
  NOTICE.txt
  Vagrantfile
  _meta/config/common.reference.p2.yml.tmpl
  changelog/fragments/1679422558-feature-flags.yaml
  elastic-agent.reference.yml
  go.mod
  go.sum
  internal/pkg/agent/application/application.go
  internal/pkg/agent/application/coordinator/coordinator.go
  internal/pkg/agent/application/coordinator/diagnostics_test.go
  internal/pkg/agent/application/coordinator/testdata/simple_config/elastic-agent.yml
  internal/pkg/agent/application/coordinator/testdata/simple_config/expected/components-expected.yaml
  internal/pkg/agent/application/coordinator/testdata/simple_config/expected/computed-config.yaml
  internal/pkg/agent/application/coordinator/testdata/simple_config/expected/pre-config.yaml
  internal/pkg/agent/application/coordinator/testdata/simple_config/expected/state.yaml
  internal/pkg/agent/application/gateway/fleet/fleet_gateway.go
  internal/pkg/agent/application/info/agent_metadata.go
  internal/pkg/agent/application/monitoring/v1_monitor.go
  internal/pkg/agent/cmd/enroll_cmd.go
  internal/pkg/composable/providers/host/host.go
  internal/pkg/composable/providers/host/host_test.go
  pkg/component/component.go
  pkg/component/fake/component/comp/actions.go
  pkg/component/fake/component/comp/component.go
  pkg/component/fake/component/main.go
  pkg/component/fake/shipper/actions.go
  pkg/component/fake/shipper/main.go
  pkg/component/runtime/failed.go
  pkg/component/runtime/manager_test.go
  pkg/component/runtime/state.go
  pkg/features/features.go
  pkg/features/features_test.go
Labels: enhancement, backport-v8.7.0

#2451 Removing debugging statements
  internal/pkg/agent/application/info/agent_metadata.go
Labels: Cleanup, backport-v8.7.0

#2454 Update Vagrantfile dev box
  Vagrantfile
Labels: enhancement, backport-v8.7.0

#2453 Bumping up versions for Elastic-owned internal dependencies
  NOTICE.txt
  go.mod
  go.sum
Labels: Cleanup, backport-v8.7.0

#2448 Best effort copying of `run` directory
  NOTICE.txt
  go.mod
  go.sum
  internal/pkg/agent/application/upgrade/test/case1/README.md
  internal/pkg/agent/application/upgrade/test/case2/README.md
  internal/pkg/agent/application/upgrade/test/case3/README.md
  internal/pkg/agent/application/upgrade/upgrade.go
  internal/pkg/agent/application/upgrade/upgrade_test.go
Labels: bug, Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent, backport-v8.7.0

#2456 Fix logger not respecting updated level
  changelog/fragments/1680764383-Respecting-logging.level-settings.yaml
  internal/pkg/agent/cmd/run.go
  internal/pkg/composable/providers/kubernetes/kubernetes.go
  internal/pkg/config/operations/inspector.go
  pkg/component/runtime/command.go
  pkg/component/runtime/runtime.go
  pkg/core/logger/logger.go
  pkg/core/logger/logger_test.go
Labels: bug, Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent, backport-v8.7.0

#2467 Update handler_action_diagnostics.go
  internal/pkg/agent/application/actions/handlers/handler_action_diagnostics.go
Labels: Team:Elastic-Agent, backport-skip

#2427 Support Shipper monitoring in elastic-agent
  internal/pkg/agent/application/monitoring/v1_monitor.go
Labels: Team:Elastic-Agent, backport-skip

#2472 Write internal logs under versioned home logs folder
  pkg/core/logger/logger.go
Labels: Team:Elastic-Agent, >bug, backport-v8.7.0

#2473 `TestFQDNFeatureFlagToggle` unit test: Increase sleep to avoid flakiness
  internal/pkg/composable/providers/host/host_test.go
Labels: Team:Elastic-Agent, flaky-test, Cleanup, backport-v8.7.0

#2480 Use `require.Eventually` instead of `time.Sleep` in unit test
  internal/pkg/composable/providers/host/host_test.go
  pkg/features/features.go
Labels: Cleanup, backport-v8.7.0

#2485 Better callback registration/deregistration in host provider's lifecycle
  internal/pkg/agent/application/application.go
  internal/pkg/agent/cmd/run.go
  internal/pkg/agent/vars/vars.go
  internal/pkg/composable/controller.go
  internal/pkg/composable/controller_test.go
  internal/pkg/composable/providers/host/host.go
  internal/pkg/composable/providers/host/host_test.go
  internal/pkg/core/composable/providers.go
  pkg/features/features.go
Labels: Team:Elastic-Agent, Cleanup, backport-v8.7.0

#2490 Fix install on Mac OS to ensure that the /usr/local/bin exists
  changelog/fragments/1681311024-Ensure-local-bin-directory-exists-on-Mac-OS-during-installation..yaml
  internal/pkg/agent/install/install.go
Labels: bug, backport-v8.7.0

#2424 Add fleet-server secret files support
  NOTICE.txt
  changelog/fragments/1680203080-Add-support-for-fleet-server-secret-files.yaml
  go.mod
  go.sum
  internal/pkg/agent/cmd/container.go
  internal/pkg/agent/cmd/enroll.go
  internal/pkg/agent/cmd/enroll_cmd.go
  internal/pkg/agent/cmd/enroll_cmd_test.go
  internal/pkg/agent/cmd/setup_config.go
  internal/pkg/agent/configuration/fleet_server.go
Labels: enhancement, Team:Elastic-Agent-Control-Plane, Team:Fleet, backport-skip

#2496 Make language in CLI commands more consistent
  changelog/fragments/1681340196-More-consistent-language-in-CLI-commands.yaml
  internal/pkg/agent/cmd/container.go
  internal/pkg/agent/cmd/diagnostics.go
  internal/pkg/agent/cmd/enroll.go
  internal/pkg/agent/cmd/inspect.go
  internal/pkg/agent/cmd/install.go
  internal/pkg/agent/cmd/run.go
  internal/pkg/agent/cmd/status.go
  internal/pkg/agent/cmd/uninstall.go
  internal/pkg/agent/cmd/upgrade.go
  internal/pkg/agent/cmd/watch.go
Labels: Team:Elastic-Agent, backport-skip

#2483 Fix TestManager_FakeShipper flakiness.
  pkg/component/runtime/manager_test.go
Labels: backport-skip, skip-changelog

#2458 Disable E2E testing stage for branch/tags
  .ci/Jenkinsfile
  .ci/schedule-daily.groovy
Labels: backport-skip, build-failures

#2499 Add additional unit tests to fleet-server config
  internal/pkg/agent/configuration/fleet_server_test.go
Labels: Team:Elastic-Agent-Control-Plane, backport-skip, technical debt

#2340 Fix container paths config
  changelog/fragments/1677780422-fix-container-paths-config-parsing.yaml
  internal/pkg/agent/cmd/container.go
  internal/pkg/agent/cmd/container_test.go
Labels: >bug, backport-v8.7.0

#2475 [updatecli][githubrelease] Bump version to 1.19.8
  .go-version
  .golangci.yml
  Dockerfile
  version/docs/version.asciidoc
Labels: backport-skip

#2507 Cleanup in preparation for #2500
  internal/pkg/agent/application/upgrade/service.go
  internal/pkg/agent/install/install_unix.go
Labels: backport-skip, Cleanup

#2477 add cloud-defend to agent mage package
  dev-tools/packaging/templates/docker/Dockerfile.elastic-agent.tmpl
  magefile.go
Labels: enhancement, backport-skip

#2511 specs/filebeat.spec.yml - Re-add lumberjack input
  changelog/fragments/1681842199-re-add-lumberjack-input-spec.yaml
  specs/filebeat.spec.yml
Labels: bug, backport-v8.7.0

#2518 Log watcher properly
  internal/pkg/agent/application/upgrade/rollback.go
  internal/pkg/agent/cmd/watch.go
  internal/pkg/agent/install/uninstall.go
  internal/pkg/diagnostics/diagnostics.go
  pkg/core/logger/logger.go
Labels: bug, Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent, backport-skip

#2519 ci: run packaging if .go-version/Dockefile changes
  .ci/Jenkinsfile
Labels: backport-v8.7.0

#2533 Log errors on diagnostics handler
  internal/pkg/agent/application/actions/handlers/handler_action_diagnostics.go
Labels: enhancement, Team:Elastic-Agent, backport-skip, 8.7-candidate

#2527 Copy utility pointing back to proper repo
  NOTICE.txt
  go.mod
  go.sum
  internal/pkg/agent/application/upgrade/upgrade.go
Labels: bug, Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent, backport-v8.7.0

#2523 internal/pkg/diagnostics - Fix creation of sub-directories in logs/
  changelog/fragments/1681942680-fix-diag-zip-file.yaml
  internal/pkg/diagnostics/diagnostics.go
  internal/pkg/diagnostics/dianostics_test.go
Labels: bug, backport-v8.7.0

#2500 Allow users to specify base path with `elastic-agent install`
  changelog/fragments/1681940139-Allow-users-to-specify-custom-base-paths-during-installation.yaml
  internal/pkg/agent/application/info/state.go
  internal/pkg/agent/application/paths/paths.go
  internal/pkg/agent/application/paths/paths_darwin.go
  internal/pkg/agent/application/paths/paths_windows.go
  internal/pkg/agent/application/upgrade/service.go
  internal/pkg/agent/cmd/enroll_cmd.go
  internal/pkg/agent/cmd/install.go
  internal/pkg/agent/cmd/install_test.go
  internal/pkg/agent/cmd/install_windows_test.go
  internal/pkg/agent/cmd/uninstall.go
  internal/pkg/agent/install/install.go
  internal/pkg/agent/install/install_unix.go
  internal/pkg/agent/install/install_windows.go
  internal/pkg/agent/install/installed.go
  internal/pkg/agent/install/perms_unix.go
  internal/pkg/agent/install/perms_windows.go
  internal/pkg/agent/install/svc.go
  internal/pkg/agent/install/uninstall.go
Labels: enhancement, Team:Elastic-Agent, backport-skip

#2540 Update cloud defend args to run as tested in `https://github.com/elastic/elastic-agent/cloud-defend`
  specs/cloud-defend.spec.yml
Labels: bug, backport-skip

#2539 Revert "log errors on diagnostics handler (#2533)"
  internal/pkg/agent/application/actions/handlers/handler_action_diagnostics.go
Labels: backport-skip

#2542 [Universal Profiling] run components in containerized environment
  specs/pf-elastic-collector.spec.yml
  specs/pf-elastic-symbolizer.spec.yml
  specs/pf-host-agent.spec.yml
Labels: enhancement, backport-skip, v8.8.0

#2531 [updatecli][githubrelease] Bump version to 1.19.8
  .go-version
  .golangci.yml
  Dockerfile
  version/docs/version.asciidoc
Labels: backport-skip

#2545 Update arguments in cloud_defend spec file
  specs/cloud-defend.spec.yml
Labels: bug, backport-skip

#2513 8.7.1 release notes
  changelog/8.7.1.yaml
  changelog/fragments/1677780422-fix-container-paths-config-parsing.yaml
  changelog/fragments/1679422558-feature-flags.yaml
  changelog/fragments/1680101776-Fix-actions-acks-delay.yaml
  changelog/fragments/1680764383-Respecting-logging.level-settings.yaml
  changelog/fragments/1681211832-empty-proxy-from-the-policy-don't-overrides-the-proxy-set-by---proxy-url.yaml
  changelog/fragments/1681311024-Ensure-local-bin-directory-exists-on-Mac-OS-during-installation..yaml
  changelog/fragments/1681842199-re-add-lumberjack-input-spec.yaml
Labels: forwardport-main

#2556 backport: Add 8.8 branch
  .mergify.yml
Labels: Team:Automation, impact:critical, backport-skip, release

#2559 Revert "[Release] Update version to 8.8.1"
  version/version.go
Labels: release

#2549 fix diagnostics pprof output
  NOTICE.txt
  changelog/fragments/1682442537-fix-pprof-diagnostics.yaml
  go.mod
  go.sum
  internal/pkg/diagnostics/diagnostics.go
  internal/pkg/diagnostics/dianostics_test.go
Labels: bug, Team:Elastic-Agent, backport-v8.6.0, backport-v8.7.0

#2292 E2e proposal
  NOTICE.txt
  go.mod
  go.sum
  testing/.devcontainer/Dockerfile
  testing/.devcontainer/devcontainer.json
  testing/.gitignore
  testing/e2e/Makefile
  testing/e2e/elastic-agent.yml.tpl
  testing/e2e/test-cluster.yml.tpl
  testing/e2e/tools/agents.go
  testing/e2e/tools/arch.go
  testing/e2e/tools/artifacts_darwin.go
  testing/e2e/tools/artifacts_linux.go
  testing/e2e/tools/cmd_darwin.go
  testing/e2e/tools/cmd_linux.go
  testing/e2e/tools/config.go
  testing/e2e/tools/download.go
  testing/e2e/tools/fleet_tools.go
  testing/e2e/tools/kibana_client.go
  testing/e2e/upgrade_testify_test.go
Labels: backport-skip

#2543 Add `integration:local` mage target, expose `Client()` on `Fixture`, add `Exec()` on `Fixture`.
  magefile.go
  pkg/component/component.go
  pkg/component/component_test.go
  pkg/testing/fixture.go
  testing/integration/fake_test.go
Labels: Team:Elastic-Agent, backport-skip

#2563 E2E testing framework: Remove dependency on devcontainers and VSCode
  testing/.devcontainer/Dockerfile
  testing/.devcontainer/devcontainer.json
  testing/e2e/Makefile
  testing/e2e/tests/upgrade_test.go
  testing/e2e/upgrade_testify_test.go
Labels: Team:Elastic-Agent, backport-skip

#2555 [Release] Bump the version on main to 8.8.0
  version/version.go
Labels: backport-skip, release

#2551 Add changelog entry for Cloud Defend
  changelog/fragments/1682455535-Adding-Cloud-Defend-application-to-Elastic-Agent.yaml
Labels: docs, backport-v8.8.0

#2562 Disable signature validation for policy and actions
  changelog/fragments/1682599444-Disable-policy-and-action-signature-validation-in-the-Agent.yaml
  internal/pkg/agent/application/actions/handlers/handler_action_application.go
  internal/pkg/agent/application/actions/handlers/handler_action_policy_change.go
  internal/pkg/agent/application/coordinator/coordinator.go
Labels: enhancement, backport-skip, v8.8.0, 8.8-candidate

#2566 [Backport 8.8]: Disable signature validation for policy and actions (#2562)
  changelog/fragments/1682599444-Disable-policy-and-action-signature-validation-in-the-Agent.yaml
  internal/pkg/agent/application/actions/handlers/handler_action_application.go
  internal/pkg/agent/application/actions/handlers/handler_action_policy_change.go
  internal/pkg/agent/application/coordinator/coordinator.go
Labels: enhancement, v8.8.0, 8.8-candidate, backport

#2568 Fixing white spaces in desc of kibana Manifests auto generated from CI
  deploy/kubernetes/creator_k8s_manifest.sh
Labels: backport-skip

#2529 Fix issue where inspect and diagnostics didn't include local elastic-agent configuration.
  changelog/fragments/1682005908-Add-local-config.yaml-to-diagnostics-and-merge-together-in-inspect..yaml
  internal/pkg/agent/application/actions/handlers/handler_action_upgrade_test.go
  internal/pkg/agent/application/application.go
  internal/pkg/agent/application/coordinator/coordinator.go
  internal/pkg/agent/application/coordinator/coordinator_test.go
  internal/pkg/agent/application/coordinator/diagnostics_test.go
  internal/pkg/agent/application/coordinator/testdata/simple_config/expected/local-config.yaml
  internal/pkg/config/config.go
  internal/pkg/config/config_test.go
  internal/pkg/config/operations/inspector.go
Labels: Team:Elastic-Agent, backport-v8.8.0
