Repository elastic/elastic-agent, pull requests merged in 2023-06, with the labels that each got.

#2751 Feature/introduce artifact api utils
  pkg/testing/tools/artifacts_api.go
  pkg/testing/tools/artifacts_api_test.go
Labels: enhancement, Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent, backport-skip, skip-changelog

#2763 Bump elastic-agent-client to v7.1.2
  NOTICE.txt
  go.mod
  go.sum
Labels: skip-changelog, backport-v8.7.0, backport-v8.8.0

#2777 docs: update docs versions 8.8.1
  deploy/kubernetes/elastic-agent-managed-kubernetes.yaml
  deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml
  version/docs/version.asciidoc
Labels: Team:Automation, release, docs, in progress

#2776 Retry upgrade downloads
  NOTICE.txt
  _meta/config/common.p2.yml.tmpl
  _meta/config/common.reference.p2.yml.tmpl
  changelog/fragments/1685751999-retry-download-step-in-upgrade-process.yaml
  elastic-agent.reference.yml
  elastic-agent.yml
  go.mod
  internal/pkg/agent/application/coordinator/testdata/simple_config/elastic-agent.yml
  internal/pkg/agent/application/coordinator/testdata/simple_config/expected/computed-config.yaml
  internal/pkg/agent/application/coordinator/testdata/simple_config/expected/local-config.yaml
  internal/pkg/agent/application/coordinator/testdata/simple_config/expected/pre-config.yaml
  internal/pkg/agent/application/upgrade/artifact/config.go
  internal/pkg/agent/application/upgrade/step_download.go
  internal/pkg/agent/application/upgrade/step_download_test.go
Labels: bug, Team:Elastic-Agent, backport-v8.8.0

#2787 Fix race detector errors in TestFQDNFeatureFlagToggle, TestContextProvider
  internal/pkg/composable/providers/host/host_test.go
Labels: bug, Team:Elastic-Agent, backport-skip, skip-changelog

#2752 Feature/allow upgrade to snapshots
  changelog/fragments/1684731814-Allow-upgrade-to-snapshots.yaml
  internal/pkg/agent/application/upgrade/artifact/download/localremote/downloader.go
  internal/pkg/agent/application/upgrade/artifact/download/localremote/verifier.go
  internal/pkg/agent/application/upgrade/artifact/download/snapshot/downloader.go
  internal/pkg/agent/application/upgrade/artifact/download/snapshot/verifier.go
  internal/pkg/agent/application/upgrade/step_download.go
  internal/pkg/agent/application/upgrade/step_download_test.go
  pkg/testing/fixture_install.go
  pkg/testing/tools/cmd.go
  testing/integration/upgrade_test.go
Labels: enhancement, Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent, backport-skip

#2791 Fix race detector errors in TestPrintLogs
  internal/pkg/agent/cmd/logs_test.go
Labels: Team:Elastic-Agent, backport-skip, skip-changelog

#2786 Document goroutine call patterns, cleanup
  internal/pkg/agent/application/coordinator/coordinator.go
  internal/pkg/agent/application/coordinator/coordinator_test.go
  internal/pkg/agent/application/coordinator/state/state.go
  internal/pkg/agent/cmd/run.go
  pkg/component/runtime/manager.go
  pkg/component/runtime/manager_test.go
  pkg/component/runtime/runtime.go
Labels: Team:Elastic-Agent, backport-skip, Cleanup, skip-changelog

#2779 Add `integration:matrix` and `integration:single` mage targets
  docs/test-framework-dev-guide.md
  magefile.go
  pkg/testing/runner/config.go
  pkg/testing/runner/debian.go
  pkg/testing/runner/runner.go
  pkg/testing/runner/supported.go
Labels: Team:Elastic-Agent, skip-changelog, backport-v8.8.0

#2795 Prepare 8.8.1 changelog
  changelog/8.8.1.asciidoc
  changelog/8.8.1.yaml
  changelog/fragments/1685029627-Fix-deadlock-condition-in-RuntimeManager.yaml
  changelog/fragments/1685751999-retry-download-step-in-upgrade-process.yaml
Labels: docs

#2804 Fix flakiness in host/TestContextProvider
  internal/pkg/composable/controller.go
  internal/pkg/composable/providers/host/host_test.go
  internal/pkg/composable/testing/context.go
Labels: bug, Team:Elastic-Agent, backport-skip, skip-changelog

#2805 Make `mage integration clean` remove ogc cache
  docs/test-framework-dev-guide.md
  magefile.go
Labels: Team:Elastic-Agent, backport-skip, skip-changelog, Testing

#2778 [Release] Update version to 8.8.2
  version/version.go
Labels: Team:Automation, release

#2644 Update elastic-agent-gke-autopilot.md
  docs/elastic-agent-gke-autopilot.md
Labels: Team:Elastic-Agent, backport-skip, skip-changelog

#2814 Remove newlines filter_condition
  catalog-info.yaml
Labels: backport-skip, ci

#2815 Allow SNAPSHOT=true for mage integration:*
  magefile.go
Labels: Team:Elastic-Agent, skip-changelog, backport-v8.8.0

#2817 Fix timer reset patterns in the Agent
  internal/pkg/agent/application/managed_mode.go
  internal/pkg/composable/controller.go
  pkg/component/runtime/manager_test.go
  pkg/component/runtime/service.go
Labels: bug, Team:Elastic-Agent, skip-changelog, backport-v8.8.0

#2803 Improve error handling in integration tests, update deps
  NOTICE.txt
  go.mod
  go.sum
  magefile.go
  pkg/testing/define/batch.go
  pkg/testing/tools/tools.go
  testing/integration/fqdn_test.go
  testing/integration/upgrade_test.go
Labels: bug, backport-skip, skip-changelog

#2799 Runtime + Coordinator cleanups
  internal/pkg/agent/application/coordinator/coordinator.go
  pkg/component/runtime/command.go
  pkg/component/runtime/failed.go
  pkg/component/runtime/manager.go
  pkg/component/runtime/runtime.go
  pkg/component/runtime/service.go
Labels: Team:Elastic-Agent, backport-skip, Cleanup, skip-changelog

#2823 Log an error when a store exists but we can't load it
  internal/pkg/agent/storage/store/action_store.go
  internal/pkg/agent/storage/store/state_store.go
Labels: Team:Elastic-Agent, backport-skip, Cleanup, skip-changelog

#2809 Fix `TestFleetManagedUpgrade` test + cleanup
  NOTICE.txt
  go.mod
  go.sum
  pkg/version/version_parser.go
  testing/integration/upgrade_retry_download_test.go
  testing/integration/upgrade_test.go
Labels: Team:Elastic-Agent, backport-skip, skip-changelog, Testing

#2832 Update branch configuration
  catalog-info.yaml
Labels: backport-skip, ci

#2833 Small fixes and improvements on non production code
  dev-tools/mage/pkg.go
  magefile.go
  pkg/testing/define/batch.go
  pkg/testing/fixture.go
  pkg/testing/fixture_install.go
  pkg/testing/tools/cmd.go
  pkg/testing/tools/tools.go
Labels: Team:Elastic-Agent, backport-skip, Cleanup, skip-changelog

#2837 Fixing compile errors + more consistent naming
  pkg/testing/tools/cmd.go
  pkg/testing/tools/tools.go
  testing/integration/fqdn_test.go
  testing/integration/upgrade_test.go
Labels: Team:Elastic-Agent, Cleanup, skip-changelog, backport-v8.8.0, Testing

#2728 Clean up / document Agent policy processing
  README.md
  docs/agent-policy.md
  docs/architecture.md
  docs/component-specs.md
  docs/images/components-example.d2
  docs/images/components-example.svg
  docs/images/components-shipper-example.d2
  docs/images/components-shipper-example.svg
  internal/pkg/agent/application/coordinator/coordinator_test.go
  internal/pkg/agent/application/gateway/fleet/fleet_gateway.go
  internal/pkg/agent/application/info/agent_info.go
  pkg/component/component.go
  pkg/component/component_test.go
  pkg/component/load.go
  pkg/component/runtime/manager_shipper.go
  pkg/component/runtime/manager_test.go
  pkg/component/spec.go
  testing/integration/fake_test.go
Labels: Team:Elastic-Agent, backport-skip, Cleanup, docs, skip-changelog

#2748 Initial buildkite test pipeline
  .buildkite/hooks/pre-command
  .buildkite/hooks/pre-exit
  .buildkite/pipeline.yml
  .buildkite/scripts/integration_tests.sh
Labels: Team:Elastic-Agent, backport-skip, skip-changelog

#2845 Revert "Fix timer reset patterns in the Agent"
  internal/pkg/agent/application/managed_mode.go
  internal/pkg/composable/controller.go
  pkg/component/runtime/manager_test.go
  pkg/component/runtime/service.go
Labels: backport-skip, skip-changelog

#2846 [Automation] Bump Golang version to 1.19.10
  .go-version
  .golangci.yml
  Dockerfile
  changelog/fragments/1686684090-Increase-Go-version-to-1.19.10..yaml
  version/docs/version.asciidoc
Labels: backport-v8.8.0

#2862 Add slack notification for buildkite build
  .buildkite/pipeline.yml
Labels: backport-skip

#2861 Fix a few small issues in integration test logging
  pkg/testing/runner/debian.go
  pkg/testing/runner/runner.go
Labels: bug, Team:Elastic-Agent, backport-skip, skip-changelog

#2867 Add slack var at the root level.
  .buildkite/pipeline.yml
  catalog-info.yaml
Labels: backport-skip

#2871 Delete unused files
  testing/e2e/Makefile
  testing/e2e/elastic-agent.yml.tpl
  testing/e2e/test-cluster.yml.tpl
Labels: Team:Elastic-Agent, Cleanup, skip-changelog, backport-v8.8.0

#2869 Run mage check in CI.
  Makefile
  magefile.go
  pkg/testing/tools/artifacts_api.go
  pkg/testing/tools/artifacts_api_test.go
  testing/fleetservertest/checkin.go
  testing/fleetservertest/fleetserver.go
  testing/fleetservertest/fleetserver_test.go
  testing/fleetservertest/handlers.go
  testing/fleetservertest/models.go
  testing/fleetservertest/server.go
Labels: Team:Elastic-Agent, skip-changelog, backport-v8.8.0

#2859 Fix broken diagram links in architecture document.
  docs/architecture.md
  docs/images/compute_model.png
  docs/images/coordinator.png
Labels: Team:Elastic-Agent, backport-skip, skip-changelog

#2870 [Component spec files] Add units to duration values
  changelog/fragments/1686770028-spec-timeout-units.yaml
  pkg/component/component_test.go
  specs/endpoint-security.spec.yml
Labels: Team:Elastic-Agent, backport-v8.8.0

#2879 [Service runtime] Change log level to `INFO` for logging in `start`/`stop` methods
  changelog/fragments/1686833548-service-runtime-info-logging.yaml
  pkg/component/runtime/service.go
Labels: Team:Elastic-Agent, backport-v8.8.0

#2884 Update the integration OGC usage to tag :blake
  pkg/testing/runner/runner.go
Labels: Team:Elastic-Agent, skip-changelog, backport-v8.8.0

#2881 deployment/kubernetes: add elements for Universal Profiling
  changelog/fragments/1686845318-deployment-kubernetes-add-elements-for-Universal-Profiling.yaml
  deploy/kubernetes/elastic-agent-managed-kubernetes.yaml
  deploy/kubernetes/elastic-agent-managed/elastic-agent-managed-daemonset.yaml
  deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml
  deploy/kubernetes/elastic-agent-standalone/elastic-agent-standalone-daemonset.yaml
Labels: enhancement, backport-skip, skip-changelog

#2901 Fix typo in uninstall location error message.
  internal/pkg/agent/cmd/uninstall.go
Labels: Team:Elastic-Agent, backport-skip, skip-changelog

#2891 Bump elastic-agent-autodiscover version to 0.6.2
  NOTICE.txt
  go.mod
  go.sum
Labels: backport-skip, skip-changelog

#2905 Add support for diagnostics logging collection on k8s
  changelog/fragments/1687251084-Fixed-diagnostics-logging-collection-on-k8s.yaml
  internal/pkg/diagnostics/diagnostics.go
Labels: bug, Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent, backport-v8.8.0

#2754 Add support for deploying Agent on k8s with kustomize
  deploy/kubernetes/Makefile
  deploy/kubernetes/README.md
  deploy/kubernetes/elastic-agent-kustomize/default/elastic-agent-managed/base/elastic-agent-managed-daemonset.yaml
  deploy/kubernetes/elastic-agent-kustomize/default/elastic-agent-managed/base/elastic-agent-managed-role-binding.yaml
  deploy/kubernetes/elastic-agent-kustomize/default/elastic-agent-managed/base/elastic-agent-managed-role.yaml
  deploy/kubernetes/elastic-agent-kustomize/default/elastic-agent-managed/base/elastic-agent-managed-service-account.yaml
  deploy/kubernetes/elastic-agent-kustomize/default/elastic-agent-managed/base/kustomization.yaml
  deploy/kubernetes/elastic-agent-kustomize/default/elastic-agent-managed/kustomization.yaml
  deploy/kubernetes/elastic-agent-kustomize/default/elastic-agent-standalone/base/elastic-agent-standalone-daemonset-configmap.yaml
  deploy/kubernetes/elastic-agent-kustomize/default/elastic-agent-standalone/base/elastic-agent-standalone-daemonset.yaml
  deploy/kubernetes/elastic-agent-kustomize/default/elastic-agent-standalone/base/elastic-agent-standalone-ksm-daemonset-configmap.yaml
  deploy/kubernetes/elastic-agent-kustomize/default/elastic-agent-standalone/base/elastic-agent-standalone-ksm-statefulset-configmap.yaml
  deploy/kubernetes/elastic-agent-kustomize/default/elastic-agent-standalone/base/elastic-agent-standalone-role-binding.yaml
  deploy/kubernetes/elastic-agent-kustomize/default/elastic-agent-standalone/base/elastic-agent-standalone-role.yaml
  deploy/kubernetes/elastic-agent-kustomize/default/elastic-agent-standalone/base/elastic-agent-standalone-service-account.yaml
  deploy/kubernetes/elastic-agent-kustomize/default/elastic-agent-standalone/base/kustomization.yaml
  deploy/kubernetes/elastic-agent-kustomize/default/elastic-agent-standalone/kustomization.yaml
  deploy/kubernetes/elastic-agent-kustomize/ksm-autosharding/elastic-agent-managed/base/elastic-agent-managed-daemonset.yaml
  deploy/kubernetes/elastic-agent-kustomize/ksm-autosharding/elastic-agent-managed/base/elastic-agent-managed-role-binding.yaml
  deploy/kubernetes/elastic-agent-kustomize/ksm-autosharding/elastic-agent-managed/base/elastic-agent-managed-role.yaml
  deploy/kubernetes/elastic-agent-kustomize/ksm-autosharding/elastic-agent-managed/base/elastic-agent-managed-service-account.yaml
  deploy/kubernetes/elastic-agent-kustomize/ksm-autosharding/elastic-agent-managed/base/kustomization.yaml
  deploy/kubernetes/elastic-agent-kustomize/ksm-autosharding/elastic-agent-managed/extra/elastic-agent-managed-statefulset.yaml
  deploy/kubernetes/elastic-agent-kustomize/ksm-autosharding/elastic-agent-managed/kustomization.yaml
  deploy/kubernetes/elastic-agent-kustomize/ksm-autosharding/elastic-agent-standalone/base/elastic-agent-standalone-daemonset.yaml
  deploy/kubernetes/elastic-agent-kustomize/ksm-autosharding/elastic-agent-standalone/base/elastic-agent-standalone-ksm-daemonset-configmap.yaml
  deploy/kubernetes/elastic-agent-kustomize/ksm-autosharding/elastic-agent-standalone/base/elastic-agent-standalone-ksm-statefulset-configmap.yaml
  deploy/kubernetes/elastic-agent-kustomize/ksm-autosharding/elastic-agent-standalone/base/elastic-agent-standalone-role-binding.yaml
  deploy/kubernetes/elastic-agent-kustomize/ksm-autosharding/elastic-agent-standalone/base/elastic-agent-standalone-role.yaml
  deploy/kubernetes/elastic-agent-kustomize/ksm-autosharding/elastic-agent-standalone/base/elastic-agent-standalone-service-account.yaml
  deploy/kubernetes/elastic-agent-kustomize/ksm-autosharding/elastic-agent-standalone/base/kustomization.yaml
  deploy/kubernetes/elastic-agent-kustomize/ksm-autosharding/elastic-agent-standalone/extra/elastic-agent-standalone-statefulset.yaml
  deploy/kubernetes/elastic-agent-kustomize/ksm-autosharding/elastic-agent-standalone/kustomization.yaml
  deploy/kubernetes/elastic-agent-standalone/elastic-agent-standalone-ksm-daemonset-configmap.yaml
  deploy/kubernetes/elastic-agent-standalone/elastic-agent-standalone-ksm-statefulset-configmap.yaml
  version/docs/version.asciidoc
Labels: backport-skip, skip-changelog

#2710 Ksmsharding
  docs/elastic-agent-ksm-sharding.md
  docs/elastic-agent-scaling-tests.md
  docs/images/ksm-ksm01.png
  docs/images/ksm-ksm02.png
  docs/images/ksm-sidecontainer.png
  docs/images/ksm01.png
  docs/images/ksm02.png
  docs/images/leader-ksm-sidecontainer.png
  docs/images/tolerationsdaemonset.png
  docs/images/tolerationsksm0.png
  docs/manifests/hostnetwork/elastic-agent-managed-daemonset-ksm-0.yaml
  docs/manifests/hostnetwork/elastic-agent-managed-deployment-ksm-1.yaml
  docs/manifests/hostnetwork/elastic-agent-standalone-daemonset-ksm-0.yaml
  docs/manifests/hostnetwork/elastic-agent-standalone-deployment-ksm-1.yaml
  docs/manifests/kustomize-autosharding/README.md
  docs/manifests/kustomize-autosharding/elastic-agent-kustomize/agent-cluster-role-binding.yaml
  docs/manifests/kustomize-autosharding/elastic-agent-kustomize/agent-cluster-role.yaml
  docs/manifests/kustomize-autosharding/elastic-agent-kustomize/agent-role-binding.yaml
  docs/manifests/kustomize-autosharding/elastic-agent-kustomize/agent-role.yaml
  docs/manifests/kustomize-autosharding/elastic-agent-kustomize/agent-service-account.yaml
  docs/manifests/kustomize-autosharding/elastic-agent-kustomize/agent-statefulset.yaml
  docs/manifests/kustomize-autosharding/elastic-agent-kustomize/kustomization.yaml
  docs/manifests/kustomize-autosharding/elastic-agent-managed-kubernetes.yaml
  docs/manifests/kustomize-autosharding/elastic-agent-standalone-kubernetes-side-leader.yaml
  docs/manifests/kustomize-autosharding/elastic-agent-standalone-statefulset-side-ksm.yaml
  docs/manifests/kustomize-autosharding/kustomization.yaml
  docs/manifests/tolerations/elastic-agent-managed-daemonset-ksm-0.yaml
  docs/manifests/tolerations/elastic-agent-managed-deployment-ksm-1.yaml
  docs/manifests/tolerations/elastic-agent-standalone-daemonset-ksm-0.yaml
  docs/manifests/tolerations/elastic-agent-standalone-deployment-ksm-1.yaml
Labels: Team:Elastic-Agent, backport-skip, skip-changelog

#2916 backport: Add 8.9 branch
  .mergify.yml
Labels: Team:Automation, impact:critical, backport-skip, release, skip-changelog

#2911 Fix JSON output from integration tests
  magefile.go
  pkg/testing/runner/json.go
Labels: Team:Elastic-Agent, skip-changelog, backport-v8.8.0

#2919 Isolate standalone upgrade retry test
  testing/integration/upgrade_test.go
Labels: Team:Elastic-Agent, skip-changelog, backport-v8.8.0, Testing, backport-v8.9.0

#2915 Bump the version on main to 8.9.0
  version/version.go
Labels: backport-skip, skip-changelog

#2923 Update version to 8.9.0
  deploy/kubernetes/elastic-agent-kustomize/default/elastic-agent-managed/base/elastic-agent-managed-daemonset.yaml
  deploy/kubernetes/elastic-agent-kustomize/default/elastic-agent-standalone/base/elastic-agent-standalone-daemonset.yaml
  deploy/kubernetes/elastic-agent-kustomize/ksm-autosharding/elastic-agent-managed/base/elastic-agent-managed-daemonset.yaml
  deploy/kubernetes/elastic-agent-kustomize/ksm-autosharding/elastic-agent-managed/extra/elastic-agent-managed-statefulset.yaml
  deploy/kubernetes/elastic-agent-kustomize/ksm-autosharding/elastic-agent-standalone/base/elastic-agent-standalone-daemonset.yaml
  deploy/kubernetes/elastic-agent-kustomize/ksm-autosharding/elastic-agent-standalone/extra/elastic-agent-standalone-statefulset.yaml
Labels: skip-changelog

#2924 [Integration Testing Framework] Randomize test order
  magefile.go
Labels: Team:Elastic-Agent, backport-skip, skip-changelog, Testing

#2925 fixing links with updated urls
  deploy/kubernetes/README.md
Labels: Team:Elastic-Agent, backport-skip

#2926 fixing links with updated urls
  docs/elastic-agent-ksm-sharding.md
Labels: backport-skip, skip-changelog

#2932 Agent hash workaround for upgrade to snapshot integration test
  pkg/testing/fetcher_artifact.go
  pkg/testing/fixture.go
  pkg/testing/tools/artifacts_api.go
  testing/integration/upgrade_test.go
Labels: bug, Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent, backport-skip, skip-changelog

#2934 [Integration Test Framework] Disable timeout for test binary execution
  magefile.go
  testing/integration/upgrade_test.go
Labels: Team:Elastic-Agent, skip-changelog, Testing, backport-v8.9.0

#2882 Integration tests: Pass along verbse statements in debian handler, tweak archiver
  magefile.go
  pkg/testing/runner/archiver.go
  pkg/testing/runner/config.go
  pkg/testing/runner/debian.go
  pkg/testing/runner/runner.go
Labels: enhancement, Team:Elastic-Agent, skip-changelog, backport-v8.8.0, backport-v8.9.0

#2927 [Cloud Security] Support GCP CSPM integration
  specs/cloudbeat.spec.yml
Labels: enhancement, backport-skip, skip-changelog

#2849 Create non-blocking broadcaster helper and use it to manage Coordinator state notifications
  internal/pkg/agent/application/actions/handlers/handler_action_application.go
  internal/pkg/agent/application/actions/handlers/handler_action_upgrade.go
  internal/pkg/agent/application/actions/handlers/handler_action_upgrade_test.go
  internal/pkg/agent/application/coordinator/coordinator.go
  internal/pkg/agent/application/coordinator/coordinator_state.go
  internal/pkg/agent/application/coordinator/coordinator_test.go
  internal/pkg/agent/application/coordinator/coordinator_unit_test.go
  internal/pkg/agent/application/coordinator/diagnostics_test.go
  internal/pkg/agent/application/coordinator/mocks/capability.go
  internal/pkg/agent/application/coordinator/mocks/components_modifier.go
  internal/pkg/agent/application/coordinator/mocks/config_change.go
  internal/pkg/agent/application/coordinator/mocks/config_manager.go
  internal/pkg/agent/application/coordinator/mocks/fetch_context_provider.go
  internal/pkg/agent/application/coordinator/mocks/monitor_manager.go
  internal/pkg/agent/application/coordinator/mocks/re_exec_manager.go
  internal/pkg/agent/application/coordinator/mocks/runtime_manager.go
  internal/pkg/agent/application/coordinator/mocks/upgrade_manager.go
  internal/pkg/agent/application/coordinator/mocks/vars_manager.go
  internal/pkg/agent/application/coordinator/state/state.go
  internal/pkg/agent/application/coordinator/testdata/simple_config/elastic-agent.yml
  internal/pkg/agent/application/coordinator/testdata/simple_config/expected/components-actual.yaml
  internal/pkg/agent/application/coordinator/testdata/simple_config/expected/components-expected.yaml
  internal/pkg/agent/application/coordinator/testdata/simple_config/expected/computed-config.yaml
  internal/pkg/agent/application/coordinator/testdata/simple_config/expected/local-config.yaml
  internal/pkg/agent/application/coordinator/testdata/simple_config/expected/pre-config.yaml
  internal/pkg/agent/application/coordinator/testdata/simple_config/expected/state.yaml
  internal/pkg/agent/application/coordinator/testdata/simple_config/expected/variables.yaml
  internal/pkg/agent/application/coordinator/testdata/simple_config/mocked_components_units.yaml
  internal/pkg/agent/application/gateway/fleet/fleet_gateway.go
  internal/pkg/agent/application/gateway/fleet/fleet_gateway_test.go
  internal/pkg/agent/application/managed_mode.go
  pkg/component/component.go
  pkg/component/error.go
  pkg/control/v2/server/server.go
  pkg/control/v2/server/server_test.go
  pkg/utils/broadcaster/broadcaster.go
  pkg/utils/broadcaster/broadcaster_test.go
Labels: bug, enhancement, Team:Elastic-Agent, backport-skip, skip-changelog

#2858 [Developer Documentation] Illustrate the Agent upgrade process
  docs/upgrades.md
Labels: documentation, Team:Fleet, Team:Elastic-Agent, backport-skip, skip-changelog

#2913 docs: update docs versions 8.8.2
  deploy/kubernetes/elastic-agent-managed-kubernetes.yaml
  deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml
  version/docs/version.asciidoc
Labels: Team:Automation, release, docs, in progress

#2939 Changelog for 8.8.2
  changelog/8.8.2.asciidoc
  changelog/8.8.2.yaml
  changelog/fragments/1686684090-Increase-Go-version-to-1.19.10..yaml
  changelog/fragments/1686770028-spec-timeout-units.yaml
  changelog/fragments/1686833548-service-runtime-info-logging.yaml
  changelog/fragments/1687251084-Fixed-diagnostics-logging-collection-on-k8s.yaml
Labels: Team:Elastic-Agent, skip-changelog, forwardport-main

#2914 [Release] Update version to 8.8.3
  version/version.go
Labels: Team:Automation, release

#2738 Use skaffold to run agent in k8s
  .dockerignore
  Dockerfile.skaffold
  deploy/skaffold/.env.example
  deploy/skaffold/.gitignore
  deploy/skaffold/kustomization.yaml
  deploy/skaffold/patches/elastic-agent-managed-entrypoint.yaml
  deploy/skaffold/patches/elastic-agent-standalone-entrypoint.yaml
  deploy/skaffold/patches/elasticsearch-env-vars.yaml
  deploy/skaffold/patches/fleet-env-vars.yaml
  docs/local-k8s-testing.md
  skaffold.yaml
Labels: enhancement, Team:Elastic-Agent, backport-skip, skip-changelog

#2952 Fix / clarify capabilities API
  internal/pkg/agent/application/application.go
  internal/pkg/agent/application/coordinator/coordinator.go
  internal/pkg/agent/application/coordinator/coordinator_test.go
  internal/pkg/agent/application/coordinator/diagnostics_test.go
  internal/pkg/agent/cmd/inspect.go
  internal/pkg/agent/install/uninstall.go
  internal/pkg/capabilities/capabilities.go
  internal/pkg/capabilities/capabilities_test.go
  internal/pkg/capabilities/input.go
  internal/pkg/capabilities/input_test.go
  internal/pkg/capabilities/output.go
  internal/pkg/capabilities/output_test.go
  internal/pkg/capabilities/rule.go
  internal/pkg/capabilities/rule_test.go
  internal/pkg/capabilities/spec.go
  internal/pkg/capabilities/spec_test.go
  internal/pkg/capabilities/string_matcher.go
  internal/pkg/capabilities/string_matcher_test.go
  internal/pkg/capabilities/testdata/allow_metrics-capabilities.yml
  internal/pkg/capabilities/testdata/allow_metrics-config.yml
  internal/pkg/capabilities/testdata/allow_metrics-result.yml
  internal/pkg/capabilities/testdata/deny_logs-capabilities.yml
  internal/pkg/capabilities/testdata/deny_logs-config.yml
  internal/pkg/capabilities/testdata/deny_logs-result.yml
  internal/pkg/capabilities/testdata/filter_metrics-capabilities.yml
  internal/pkg/capabilities/testdata/filter_metrics-config.yml
  internal/pkg/capabilities/testdata/filter_metrics-result.yml
  internal/pkg/capabilities/testdata/invalid-capabilities.yml
  internal/pkg/capabilities/testdata/invalid-config.yml
  internal/pkg/capabilities/testdata/invalid_output-capabilities.yml
  internal/pkg/capabilities/testdata/invalid_output-config.yml
  internal/pkg/capabilities/testdata/no_caps-config.yml
  internal/pkg/capabilities/testdata/no_caps-result.yml
  internal/pkg/capabilities/upgrade.go
  internal/pkg/capabilities/upgrade_test.go
  pkg/component/component.go
  pkg/component/component_test.go
Labels: bug, Team:Elastic-Agent, backport-skip, skip-changelog

#2889 [Service Runtime] Add ability for service operations to be retried
  changelog/fragments/1687301871-service-command-retries.yaml
  docs/component-specs.md
  pkg/component/runtime/service.go
  pkg/component/runtime/service_command.go
  pkg/component/runtime/service_command_test.go
  pkg/component/spec.go
Labels: Team:Elastic-Agent, backport-v8.9.0

#2968 Downgrade _two_ minors in integration test
  testing/integration/upgrade_test.go
Labels: Team:Elastic-Agent, skip-changelog, Testing, backport-v8.9.0

#2967 Adjust timeouts to remove flakiness from test
  pkg/component/runtime/service_command_test.go
Labels: Team:Elastic-Agent, flaky-test, skip-changelog, Testing, backport-v8.9.0

#2957 Make upgrade watcher configurable
  internal/pkg/agent/application/upgrade/crash_checker.go
  internal/pkg/agent/application/upgrade/crash_checker_test.go
  internal/pkg/agent/application/upgrade/error_checker.go
  internal/pkg/agent/cmd/watch.go
  internal/pkg/agent/configuration/settings.go
  internal/pkg/agent/configuration/upgrade.go
  pkg/testing/fixture.go
  testing/integration/upgrade_test.go
Labels: skip-changelog, Testing, backport-v8.9.0

#2965 Create test for installing and enrolling an agent
  NOTICE.txt
  go.mod
  pkg/testing/fixture.go
  pkg/testing/tools/elasticsearch.go
  pkg/testing/tools/tools.go
  testing/integration/diagnostics_test.go
  testing/integration/enroll_test.go
  testing/integration/fqdn_test.go
Labels: enhancement, backport-skip, skip-changelog, Testing
