Repository elastic/elastic-agent, pull requests merged in 2024-10, with the labels that each got.

#5536 Allow setting ES api key via env variable in container mode
  _meta/config/elastic-agent.docker.yml.tmpl
  changelog/fragments/1726144746-container-default-credentials.yaml
  changelog/fragments/1726145045-container-api-key.yaml
  elastic-agent.docker.yml
Labels: Team:Elastic-Agent-Control-Plane, backport-skip, breaking change

#5442 Fix linter errors
  .golangci.yml
  dev-tools/cmd/buildfleetcfg/buildfleetcfg.go
  dev-tools/licenses/license_generate.go
  dev-tools/mage/check.go
  dev-tools/mage/gotool/go.go
  dev-tools/mage/kubernetes/kubectl.go
  dev-tools/mage/target/common/package.go
  internal/pkg/agent/application/monitoring/processes_cloud_test.go
  internal/pkg/agent/application/upgrade/artifact/download/headers_rtt_test.go
  internal/pkg/agent/errors/error_test.go
  internal/pkg/fleetapi/uploader/uploader_test.go
  pkg/component/fake/component/comp/dialer.go
  pkg/component/fake/component/comp/dialer_windows.go
  pkg/component/runtime/service_command.go
  pkg/control/v1/client/dial.go
  pkg/control/v1/client/dial_windows.go
  pkg/control/v2/client/dial.go
  pkg/control/v2/client/dial_windows.go
  testing/upgradetest/upgrader.go
Labels: Team:Elastic-Agent-Control-Plane, Cleanup, skip-changelog, backport-8.15, backport-8.x

#5647 Include python wheel packages when moving downloaded dependencies archives
  magefile.go
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog, backport-8.x

#5353 TestManager_StartStopComponent add test logs, alternate manager ready signal
  pkg/component/runtime/manager.go
  pkg/component/runtime/manager_fake_input_test.go
  pkg/component/runtime/manager_test.go
Labels: Team:Elastic-Agent-Control-Plane, flaky-test, backport-skip, skip-changelog, backport-8.x

#5638 Clarify that Agent package used by integration tests relies on Beats unified release
  docs/test-framework-dev-guide.md
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog, backport-8.x

#5614 Adjust memory requests and limits for elastic-agent when run in Kubernetes cluster
  changelog/fragments/1727271745-resource-limits-kubernetes.yaml
  deploy/kubernetes/elastic-agent-kustomize/default/elastic-agent-managed/base/elastic-agent-managed-daemonset.yaml
  deploy/kubernetes/elastic-agent-kustomize/default/elastic-agent-standalone/base/elastic-agent-standalone-daemonset.yaml
  deploy/kubernetes/elastic-agent-kustomize/ksm-autosharding/elastic-agent-managed/base/elastic-agent-managed-daemonset.yaml
  deploy/kubernetes/elastic-agent-kustomize/ksm-autosharding/elastic-agent-managed/extra/elastic-agent-managed-statefulset.yaml
  deploy/kubernetes/elastic-agent-kustomize/ksm-autosharding/elastic-agent-standalone/base/elastic-agent-standalone-daemonset.yaml
  deploy/kubernetes/elastic-agent-kustomize/ksm-autosharding/elastic-agent-standalone/extra/elastic-agent-standalone-statefulset.yaml
  deploy/kubernetes/elastic-agent-managed-kubernetes.yaml
  deploy/kubernetes/elastic-agent-managed/elastic-agent-managed-daemonset.yaml
  deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml
  deploy/kubernetes/elastic-agent-standalone/elastic-agent-standalone-daemonset.yaml
  dev-tools/kubernetes/base/elastic-agent-managed/daemonset.yaml
  dev-tools/kubernetes/base/elastic-agent-standalone/daemonset.yaml
  docs/manifests/elastic-agent-managed-gke-autopilot.yaml
  docs/manifests/elastic-agent-standalone-gke-autopilot.yaml
  docs/manifests/kustomize-autosharding/elastic-agent-standalone-kubernetes-side-leader.yaml
  docs/manifests/kustomize-autosharding/elastic-agent-standalone-statefulset-side-ksm.yaml
Labels: backport-8.15, backport-8.x

#5658 Fix docker image build when multiple platforms are specified
  dev-tools/mage/dockerbuilder.go
  magefile.go
Labels: bug, Team:Elastic-Agent-Control-Plane, skip-changelog, backport-8.x

#5655 Revert "Skip flaky integration test - TestAPMConfig"
  testing/integration/apm_propagation_test.go
Labels: skip-changelog, backport-8.x

#5663 Update Makefile to remove reviewers
  deploy/kubernetes/Makefile
Labels: backport-skip, skip-changelog, backport-8.x

#5443 mage: check that links are live in the OTel README
  NOTICE.txt
  dev-tools/mage/check.go
  dev-tools/mage/gotool/linkcheck.go
  dev-tools/mage/install.go
  go.mod
  go.sum
  magefile.go
  tools/tools.go
Labels: enhancement, Team:Elastic-Agent-Control-Plane, skip-changelog, backport-8.x

#5599 Add daily cron for elastic-agent
  .buildkite/integration.pipeline.yml
  catalog-info.yaml
Labels: skip-changelog, Team:Ingest-EngProd, backport-8.x

#5629 chore: update kind version to v0.24.0
  .buildkite/integration.pipeline.yml
  .buildkite/pipeline.yml
Labels: Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent-Data-Plane, Cleanup, skip-changelog, backport-8.x

#5651 fix go vet errors with Go 1.24
  internal/pkg/agent/application/monitoring/handler.go
  internal/pkg/agent/vault/aesgcm/aesgcm_test.go
  internal/pkg/cli/confirm.go
  internal/pkg/cli/input.go
  pkg/control/v1/client/client.go
  pkg/control/v2/client/client.go
  pkg/testing/multipass/provisioner.go
Labels: Team:Elastic-Agent-Data-Plane, Cleanup, skip-changelog, backport-8.x

#5302 Call fleet-server audit/unenroll endpoint on uninstall
  changelog/fragments/1723675050-Call-fleet-server-audit-unenroll-endpoint-on-uninstall.yaml
  internal/pkg/agent/cmd/install.go
  internal/pkg/agent/cmd/uninstall.go
  internal/pkg/agent/install/uninstall.go
  internal/pkg/agent/install/uninstall_test.go
  internal/pkg/fleetapi/audit_unenroll_cmd.go
  internal/pkg/fleetapi/audit_unenroll_cmd_test.go
  testing/integration/install_test.go
Labels: enhancement, Team:Elastic-Agent-Control-Plane, backport-skip, backport-8.x

#5497 Fixing helm-chart values.yaml presets docs
  deploy/helm/elastic-agent/README.md
  deploy/helm/elastic-agent/values.yaml
Labels: Team:Elastic-Agent-Control-Plane, backport-skip, skip-changelog, backport-8.x

#5692 Stop elastic-agent inspect from printing output twice
  changelog/fragments/1727994385-Stop-elastic-agent-inspect-from-printing-output-twice.yaml
  internal/pkg/agent/cmd/inspect.go
Labels: bug, Team:Elastic-Agent-Control-Plane, backport-8.15, backport-8.x

#5644 chore: update Ubuntu base image from 20.04 to 24.04
  changelog/fragments/1727778754-update-base-ubuntu-from-20.04-to-24.04.yaml
  dev-tools/packaging/packages.yml
  dev-tools/packaging/templates/docker/Dockerfile.elastic-agent.tmpl
Labels: Team:Elastic-Agent-Control-Plane, backport-8.x

#5316 add logging to flakey test case
  pkg/testing/fixture_install.go
  testing/fleetservertest/server.go
  testing/integration/proxy_url_test.go
Labels: Team:Elastic-Agent-Control-Plane, backport-skip, skip-changelog, backport-8.x

#5694 Add comment to replace ES query with API call
  testing/integration/install_test.go
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog, backport-8.x

#5677 Shorten allowlist for `replace`able dependencies
  .golangci.yml
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog, chore, backport-8.x

#5621 redact secret_paths from elastic-agent inspect output
  changelog/fragments/1727453779-inspect-command-will-redact-secret_paths-in-policy.yaml
  internal/pkg/agent/cmd/inspect.go
  internal/pkg/diagnostics/diagnostics.go
  internal/pkg/diagnostics/diagnostics_test.go
  testing/fleetservertest/checkin.go
  testing/fleetservertest/fleetserver_test.go
  testing/integration/inspect_test.go
Labels: enhancement, Team:Elastic-Agent-Control-Plane, backport-8.x

#4483 Update elastic-agent-logging.md with right calculation details for disk sizing
  docs/elastic-agent-logging.md
Labels: Team:Elastic-Agent-Data-Plane, skip-changelog, backport-v8.6.0, backport-v8.7.0, backport-v8.8.0, backport-v8.9.0, backport-v8.10.0, backport-v8.11.0, backport-v8.12.0, backport-v8.13.0, backport-8.x

#5717 [CI] Pipeline resource for BK integration tests
  catalog-info.yaml
Labels: enhancement, skip-changelog, Team:Ingest-EngProd, backport-8.x

#5481 Remove cloud-defend from agent
  changelog/fragments/1725913991-remove-cloud-defend.yaml
  deploy/kubernetes/elastic-agent-kustomize/default/elastic-agent-managed/base/elastic-agent-managed-daemonset.yaml
  deploy/kubernetes/elastic-agent-kustomize/default/elastic-agent-standalone/base/elastic-agent-standalone-daemonset.yaml
  deploy/kubernetes/elastic-agent-kustomize/ksm-autosharding/elastic-agent-managed/base/elastic-agent-managed-daemonset.yaml
  deploy/kubernetes/elastic-agent-kustomize/ksm-autosharding/elastic-agent-managed/extra/elastic-agent-managed-statefulset.yaml
  deploy/kubernetes/elastic-agent-kustomize/ksm-autosharding/elastic-agent-standalone/base/elastic-agent-standalone-daemonset.yaml
  deploy/kubernetes/elastic-agent-kustomize/ksm-autosharding/elastic-agent-standalone/extra/elastic-agent-standalone-statefulset.yaml
  deploy/kubernetes/elastic-agent-managed-kubernetes.yaml
  deploy/kubernetes/elastic-agent-managed/elastic-agent-managed-daemonset.yaml
  deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml
  deploy/kubernetes/elastic-agent-standalone/elastic-agent-standalone-daemonset.yaml
  dev-tools/mage/checksums.go
  dev-tools/mage/pkgtypes.go
  dev-tools/packaging/templates/docker/Dockerfile.elastic-agent.tmpl
  docs/manifests/kustomize-autosharding/elastic-agent-kustomize/agent-statefulset.yaml
  pkg/testing/testdata/build-manifest.json
Labels: Team:Cloudnative-Monitoring, backport-skip, Packaging, Team:Security-Deployment and Devices

#5699 Only watch metadata for ReplicaSets in K8s provider
  changelog/fragments/1728039144-k8s-replicaset-onlymeta.yaml
  internal/pkg/composable/providers/kubernetes/pod.go
Labels: enhancement, Team:Elastic-Agent-Control-Plane, backport-8.15, backport-8.x

#5113 Ess terraform + run integration tests on BK agents
  .buildkite/bk.integration.pipeline.yml
  .buildkite/scripts/common2.sh
  .buildkite/scripts/retry.sh
  .buildkite/scripts/steps/ess.sh
  .buildkite/scripts/steps/ess_down.sh
  .buildkite/scripts/steps/ess_start.sh
  .buildkite/scripts/steps/integration_tests_tf.sh
  .buildkite/scripts/steps/integration_tests_tf_sudo.sh
  .buildkite/scripts/sudo-integration-tests.sh
  dev-tools/mage/gotest.go
  test_infra/ess/.gitignore
  test_infra/ess/deployment.tf
  test_infra/ess/output.tf
  test_infra/ess/terraform.tf
Labels: enhancement, Team:Elastic-Agent-Control-Plane, backport-skip, skip-changelog, backport-8.x

#5720 Update all inconsistent OTel dependencies to v0.110.0
  NOTICE.txt
  go.mod
  go.sum
  internal/pkg/otel/README.md
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog, backport-8.x

#5473 Add JUnit annotate BK plugin
  .buildkite/pipeline.yml
  .buildkite/scripts/steps/merge.sh
  .buildkite/scripts/steps/unit-tests.ps1
  .buildkite/scripts/steps/unit-tests.sh
  dev-tools/mage/gotest.go
Labels: skip-changelog, ci, Team:Ingest-EngProd, backport-8.x

#5741 Fix `internal/pkg/agent/cmd.TestEnroll`
  internal/pkg/agent/cmd/enroll_cmd_test.go
Labels: skip-changelog, backport-8.x

#5648 [testing/integration]: fix TestLogIngestionFleetManaged
  NOTICE.txt
  go.mod
  go.sum
  testing/integration/logs_ingestion_test.go
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog, backport-8.x

#5753 Add more details about Docker image variants
  README.md
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog, backport-8.x

#4722 Update labels to use kubernetes recommended labels
  changelog/fragments/1715551124-Update-kubernetes-manifests-to-adopt-official-recommended-labels.yaml
  deploy/kubernetes/elastic-agent-kustomize/default/elastic-agent-managed/base/elastic-agent-managed-daemonset.yaml
  deploy/kubernetes/elastic-agent-kustomize/default/elastic-agent-managed/base/elastic-agent-managed-role.yaml
  deploy/kubernetes/elastic-agent-kustomize/default/elastic-agent-managed/base/elastic-agent-managed-service-account.yaml
  deploy/kubernetes/elastic-agent-kustomize/default/elastic-agent-standalone/base/elastic-agent-standalone-daemonset-configmap.yaml
  deploy/kubernetes/elastic-agent-kustomize/default/elastic-agent-standalone/base/elastic-agent-standalone-daemonset.yaml
  deploy/kubernetes/elastic-agent-kustomize/default/elastic-agent-standalone/base/elastic-agent-standalone-ksm-daemonset-configmap.yaml
  deploy/kubernetes/elastic-agent-kustomize/default/elastic-agent-standalone/base/elastic-agent-standalone-ksm-statefulset-configmap.yaml
  deploy/kubernetes/elastic-agent-kustomize/default/elastic-agent-standalone/base/elastic-agent-standalone-role.yaml
  deploy/kubernetes/elastic-agent-kustomize/default/elastic-agent-standalone/base/elastic-agent-standalone-service-account.yaml
  deploy/kubernetes/elastic-agent-kustomize/ksm-autosharding/elastic-agent-managed/base/elastic-agent-managed-daemonset.yaml
  deploy/kubernetes/elastic-agent-kustomize/ksm-autosharding/elastic-agent-managed/base/elastic-agent-managed-role.yaml
  deploy/kubernetes/elastic-agent-kustomize/ksm-autosharding/elastic-agent-managed/base/elastic-agent-managed-service-account.yaml
  deploy/kubernetes/elastic-agent-kustomize/ksm-autosharding/elastic-agent-managed/extra/elastic-agent-managed-statefulset.yaml
  deploy/kubernetes/elastic-agent-kustomize/ksm-autosharding/elastic-agent-standalone/base/elastic-agent-standalone-daemonset.yaml
  deploy/kubernetes/elastic-agent-kustomize/ksm-autosharding/elastic-agent-standalone/base/elastic-agent-standalone-ksm-daemonset-configmap.yaml
  deploy/kubernetes/elastic-agent-kustomize/ksm-autosharding/elastic-agent-standalone/base/elastic-agent-standalone-ksm-statefulset-configmap.yaml
  deploy/kubernetes/elastic-agent-kustomize/ksm-autosharding/elastic-agent-standalone/base/elastic-agent-standalone-role.yaml
  deploy/kubernetes/elastic-agent-kustomize/ksm-autosharding/elastic-agent-standalone/base/elastic-agent-standalone-service-account.yaml
  deploy/kubernetes/elastic-agent-kustomize/ksm-autosharding/elastic-agent-standalone/extra/elastic-agent-standalone-statefulset.yaml
  deploy/kubernetes/elastic-agent-managed-kubernetes.yaml
  deploy/kubernetes/elastic-agent-managed/elastic-agent-managed-daemonset.yaml
  deploy/kubernetes/elastic-agent-managed/elastic-agent-managed-role.yaml
  deploy/kubernetes/elastic-agent-managed/elastic-agent-managed-service-account.yaml
  deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml
  deploy/kubernetes/elastic-agent-standalone/elastic-agent-standalone-daemonset-configmap.yaml
  deploy/kubernetes/elastic-agent-standalone/elastic-agent-standalone-daemonset.yaml
  deploy/kubernetes/elastic-agent-standalone/elastic-agent-standalone-ksm-daemonset-configmap.yaml
  deploy/kubernetes/elastic-agent-standalone/elastic-agent-standalone-ksm-statefulset-configmap.yaml
  deploy/kubernetes/elastic-agent-standalone/elastic-agent-standalone-role.yaml
  deploy/kubernetes/elastic-agent-standalone/elastic-agent-standalone-service-account.yaml
  dev-tools/kubernetes/base/elastic-agent-managed/kustomization.yml
  dev-tools/kubernetes/base/elastic-agent-standalone/kustomization.yml
  docs/manifests/elastic-agent-managed-gke-autopilot.yaml
  docs/manifests/elastic-agent-standalone-gke-autopilot.yaml
  docs/manifests/hostnetwork/elastic-agent-managed-daemonset-ksm-0.yaml
  docs/manifests/hostnetwork/elastic-agent-managed-deployment-ksm-1.yaml
  docs/manifests/hostnetwork/elastic-agent-standalone-daemonset-ksm-0.yaml
  docs/manifests/hostnetwork/elastic-agent-standalone-deployment-ksm-1.yaml
  docs/manifests/kustomize-autosharding/elastic-agent-kustomize/agent-cluster-role.yaml
  docs/manifests/kustomize-autosharding/elastic-agent-kustomize/agent-role.yaml
  docs/manifests/kustomize-autosharding/elastic-agent-kustomize/agent-service-account.yaml
  docs/manifests/kustomize-autosharding/elastic-agent-kustomize/agent-statefulset.yaml
  docs/manifests/kustomize-autosharding/elastic-agent-managed-kubernetes.yaml
  docs/manifests/kustomize-autosharding/elastic-agent-standalone-kubernetes-side-leader.yaml
  docs/manifests/kustomize-autosharding/elastic-agent-standalone-statefulset-side-ksm.yaml
  docs/manifests/tolerations/elastic-agent-managed-daemonset-ksm-0.yaml
  docs/manifests/tolerations/elastic-agent-managed-deployment-ksm-1.yaml
  docs/manifests/tolerations/elastic-agent-standalone-daemonset-ksm-0.yaml
  docs/manifests/tolerations/elastic-agent-standalone-deployment-ksm-1.yaml
Labels: Team:Elastic-Agent-Control-Plane, Team:Cloudnative-Monitoring, backport-skip, backport-8.x

#5761 Update CODEOWNERS for Eng Prod ownership
  .github/CODEOWNERS
Labels: skip-changelog, backport-8.x

#5756 Lower retry count and improve error message of uninstall notifications
  internal/pkg/agent/install/uninstall.go
Labels: bug, Team:Elastic-Agent-Control-Plane, skip-changelog, backport-8.x

#5764 Retrying choco install
  pkg/testing/windows/windows.go
Labels: skip-changelog, backport-8.15, backport-8.x

#5778 Bump up APM components version
  NOTICE.txt
  go.mod
  go.sum
  internal/pkg/otel/README.md
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog, backport-8.x

#5773 Exclude the coverage files from the annotate step
  .buildkite/pipeline.yml
  dev-tools/mage/gotest.go
Labels: Team:Elastic-Agent-Control-Plane, backport-skip, skip-changelog, ci, Team:Ingest-EngProd

#5779 Add retries to choco install steps
  pkg/testing/windows/windows.go
Labels: skip-changelog, backport-8.15, backport-8.x

#5748 Don't run any agent service when running `otel` subcommand
  internal/pkg/agent/application/application.go
  internal/pkg/agent/application/application_test.go
  internal/pkg/agent/application/coordinator/coordinator_test.go
  internal/pkg/agent/cmd/otel.go
  internal/pkg/agent/cmd/run.go
  pkg/component/runtime/manager.go
  pkg/component/runtime/manager_fake_input_test.go
  pkg/component/runtime/manager_test.go
  pkg/testing/fixture.go
  testing/integration/kubernetes_agent_service_test.go
  testing/integration/kubernetes_agent_standalone_test.go
  testing/integration/otel_test.go
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog, backport-8.x

#5745 Diagnostics file writes use RedactSecretPaths
  changelog/fragments/1728425752-Diagnostics-files-will-redact-secret_paths.yaml
  internal/pkg/diagnostics/diagnostics.go
  internal/pkg/diagnostics/diagnostics_test.go
  testing/fleetservertest/checkin.go
  testing/fleetservertest/fleetserver_test.go
  testing/integration/diagnostics_test.go
  testing/integration/inspect_test.go
Labels: enhancement, Team:Elastic-Agent-Control-Plane, backport-8.x

#5791 Add label backport:skip for k8s buildkite job
  deploy/kubernetes/Makefile
Labels: skip-changelog, backport-8.x

#5790 Add all Docker images to K8s integration tests
  testing/integration/kubernetes_agent_standalone_test.go
Labels: Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent, skip-changelog, backport-8.x

#5799 Move back merged coverage report to build folder
  .buildkite/pipeline.yml
  .buildkite/scripts/steps/merge.sh
Labels: backport-skip, skip-changelog, ci, Team:Ingest-EngProd

#5794 Revert change to collect process dump after every test
  pkg/testing/fixture_install.go
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog, Testing, backport-8.x

#5810 backport: Add 8.16 branch
  .mergify.yml
Labels: release, skip-changelog, backport-8.x

#5815 Bump version to 8.17.0
  .package-version
  deploy/helm/elastic-agent/examples/eck/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/kubernetes-default/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/kubernetes-hints-autodiscover/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/kubernetes-only-logs/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/multiple-integrations/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/nginx-custom-integration/rendered/manifest.yaml
  deploy/helm/elastic-agent/values.yaml
  deploy/kubernetes/elastic-agent-kustomize/default/elastic-agent-managed/base/elastic-agent-managed-daemonset.yaml
  deploy/kubernetes/elastic-agent-kustomize/default/elastic-agent-standalone/base/elastic-agent-standalone-daemonset.yaml
  deploy/kubernetes/elastic-agent-kustomize/ksm-autosharding/elastic-agent-managed/base/elastic-agent-managed-daemonset.yaml
  deploy/kubernetes/elastic-agent-kustomize/ksm-autosharding/elastic-agent-managed/extra/elastic-agent-managed-statefulset.yaml
  deploy/kubernetes/elastic-agent-kustomize/ksm-autosharding/elastic-agent-standalone/base/elastic-agent-standalone-daemonset.yaml
  deploy/kubernetes/elastic-agent-kustomize/ksm-autosharding/elastic-agent-standalone/extra/elastic-agent-standalone-statefulset.yaml
  deploy/kubernetes/elastic-agent-kustomize/ksm-hints/elastic-agent-standalone/kustomization.yaml
  deploy/kubernetes/elastic-agent-managed-kubernetes.yaml
  deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml
  version/version.go
Labels: skip-changelog

#5816 Update .agent-versions.json
  .agent-versions.json
Labels: backport-skip, skip-changelog

#5783 CODEOWNERS refactor
  .github/CODEOWNERS
Labels: skip-changelog, backport-8.15, backport-8.x

#5819 Temporarily pin versions for integration tests to `8.16.0`
  .buildkite/scripts/steps/beats_tests.sh
  .buildkite/scripts/steps/integration-package.sh
  .buildkite/scripts/steps/integration_tests.sh
  .buildkite/scripts/steps/k8s-extended-tests.sh
  testing/integration/upgrade_broken_package_test.go
Labels: Team:Elastic-Agent-Control-Plane, backport-skip, release, skip-changelog

#5549 [chore][otel] Enable persistence in otel.yml
  changelog/fragments/1726572104-enable-persistence-by-default.yaml
  internal/pkg/agent/cmd/otel.go
  internal/pkg/otel/README.md
  internal/pkg/otel/templates/README.md.tmpl
  otel.yml
Labels: documentation, enhancement, Team:Elastic-Agent-Control-Plane, opentelemetry, backport-8.x

#5777 Devmachine mage target
  .tool-versions
  NOTICE.txt
  dev-tools/devmachine/devmachine.go
  go.mod
  go.sum
  magefile.go
Labels: enhancement, Team:Elastic-Agent-Control-Plane, backport-skip, skip-changelog

#5826 Update otel samples to send otel native data
  internal/pkg/otel/samples/darwin/logs_metrics_traces.yml
  internal/pkg/otel/samples/darwin/platformlogs.yml
  internal/pkg/otel/samples/darwin/platformlogs_hostmetrics.yml
  internal/pkg/otel/samples/linux/logs_metrics_traces.yml
  internal/pkg/otel/samples/linux/platformlogs.yml
  internal/pkg/otel/samples/linux/platformlogs_hostmetrics.yml
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog, backport-8.x, backport-8.16

#5844 Add notification for when the packaging pipeline fails
  catalog-info.yaml
Labels: bug, backport-skip, skip-changelog

#5847 Switch crossbuilding to Debian 11
  changelog/fragments/1729750939-crossbuild-debian11.yaml
  dev-tools/mage/crossbuild.go
Labels: Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent, backport-8.x, breaking change

#5802 proxytest: proxy HTTPS request using MITM
  testing/proxytest/https.go
  testing/proxytest/proxytest.go
  testing/proxytest/proxytest_example_test.go
  testing/proxytest/proxytest_test.go
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog, Testing, backport-8.x

#5868 remove DEV=true from CI build steps
  .buildkite/scripts/steps/integration-package.sh
  .buildkite/scripts/steps/k8s-extended-tests.sh
Labels: skip-changelog, backport-8.x

#5866 use production api key link instead of staging
  docs/test-framework-dev-guide.md
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog, backport-8.x

#5617 Revert forcing Agent version to be 8.16.0
  .buildkite/scripts/steps/beats_tests.sh
  .buildkite/scripts/steps/integration-package.sh
  .buildkite/scripts/steps/integration_tests.sh
  .buildkite/scripts/steps/k8s-extended-tests.sh
  testing/integration/upgrade_broken_package_test.go
  testing/upgradetest/versions.go
  testing/upgradetest/versions_test.go
Labels: skip-changelog, backport-8.x

#5854 [helm]: implement support for defining image pull secrets
  deploy/helm/elastic-agent/README.md
  deploy/helm/elastic-agent/examples/kubernetes-default/README.md
  deploy/helm/elastic-agent/templates/agent/eck/_pod_template.tpl
  deploy/helm/elastic-agent/templates/agent/k8s/_pod_template.tpl
  deploy/helm/elastic-agent/values.schema.json
  deploy/helm/elastic-agent/values.yaml
Labels: enhancement, Team:Elastic-Agent-Control-Plane, skip-changelog, backport-8.x, backport-8.16

#5853 [helm]: integration config for scheduler and controller-manager conditions and containers logs
  deploy/helm/elastic-agent/examples/eck/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/kubernetes-default/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/kubernetes-hints-autodiscover/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/kubernetes-only-logs/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/multiple-integrations/rendered/manifest.yaml
  deploy/helm/elastic-agent/templates/integrations/_kubernetes/_kubernetes_controller_manager.tpl
  deploy/helm/elastic-agent/templates/integrations/_kubernetes/_kubernetes_logs_containers.tpl
  deploy/helm/elastic-agent/templates/integrations/_kubernetes/_kubernetes_scheduler.tpl
  deploy/helm/elastic-agent/values.schema.json
Labels: bug, Team:Elastic-Agent-Control-Plane, skip-changelog, backport-8.x, backport-8.16

#5855 [helm]: implement system integration as chart built-in
  deploy/helm/elastic-agent/README.md
  deploy/helm/elastic-agent/examples/README.md
  deploy/helm/elastic-agent/examples/system-custom-auth-paths/README.md
  deploy/helm/elastic-agent/examples/system-custom-auth-paths/agent-system-values.yaml
  deploy/helm/elastic-agent/examples/system-custom-auth-paths/rendered/manifest.yaml
  deploy/helm/elastic-agent/templates/NOTES.txt
  deploy/helm/elastic-agent/templates/agent/_helpers.tpl
  deploy/helm/elastic-agent/templates/integrations/_system/_system.tpl
  deploy/helm/elastic-agent/templates/integrations/_system/_system_logs.tpl
  deploy/helm/elastic-agent/templates/integrations/_system/_system_metrics.tpl
  deploy/helm/elastic-agent/values.schema.json
  deploy/helm/elastic-agent/values.yaml
Labels: enhancement, Team:Elastic-Agent-Control-Plane, skip-changelog, backport-8.x, backport-8.16

#5891 Skip TestAPMConfig
  testing/integration/apm_propagation_test.go
Labels: Team:Elastic-Agent-Control-Plane, backport-skip, skip-changelog, Testing

#5892 Fix elastic-agent-service Docker container entrypoint
  dev-tools/packaging/templates/docker/Dockerfile.elastic-agent.tmpl
  testing/integration/kubernetes_agent_service_test.go
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog, backport-8.x, backport-8.16

#5878 [Flaky Test] Fix TestHTTPSProxy
  testing/proxytest/proxytest_test.go
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog, Testing, backport-8.x, backport-8.16

#5827 Revert "Temporarily pin versions for integration tests to `8.16.0`"
  .buildkite/scripts/steps/beats_tests.sh
  .buildkite/scripts/steps/integration-package.sh
  .buildkite/scripts/steps/integration_tests.sh
  .buildkite/scripts/steps/k8s-extended-tests.sh
  testing/integration/upgrade_broken_package_test.go
Labels: Team:Elastic-Agent-Control-Plane, backport-skip, skip-changelog
