Repository elastic/elastic-agent, pull requests merged in 2024-05, with the labels that each got.

#4644 Remove unused sections in PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent-Data-Plane, backport-skip, skip-changelog, chore

#4649 Fix ability for unprivileged Windows to upgrade
  internal/pkg/agent/install/user_windows.go
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog, backport-v8.14.0

#4652 [8.14] Remove `8.12.3-SNAPSHOT` from `.agent-version.json`
  .agent-versions.json
Labels: Team:Elastic-Agent-Control-Plane, backport-skip, skip-changelog

#4638 Use otel version 0.97.0
  NOTICE.txt
  go.mod
  go.sum
  internal/pkg/otel/README.md
  internal/pkg/otel/run.go
Labels: Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent, backport-skip, skip-changelog

#4636 Keep `go.mod` toolchain version in sync with `.go-version` contents
  .ci/bump-golang.yml
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog, chore, backport-v8.14.0

#4640 [Release] Update version to 8.13.4
  .buildkite/scripts/steps/integration_tests.sh
  deploy/kubernetes/elastic-agent-managed-kubernetes.yaml
  deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml
  testing/integration/upgrade_broken_package_test.go
  version/version.go
Labels: Team:Automation, release, skip-changelog

#4658 Add unprivileged state to agent provider
  internal/pkg/composable/providers/agent/agent.go
  internal/pkg/composable/providers/agent/agent_test.go
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog, backport-v8.14.0

#4639 docs: update docs versions 8.13.3
  version/docs/version.asciidoc
Labels: Team:Automation, release, docs, in progress, skip-changelog

#4667 Fix dependency on `elastic-agent.yml`
  internal/pkg/agent/application/application.go
  testing/integration/otel_test.go
Labels: Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent, skip-changelog, backport-v8.14.0

#4562 Rename define.NewFixture to define.NewFixtureFromLocalBuild
  pkg/testing/define/define.go
  testing/integration/agent_long_running_leak_test.go
  testing/integration/apm_propagation_test.go
  testing/integration/container_cmd_test.go
  testing/integration/delay_enroll_test.go
  testing/integration/diagnostics_test.go
  testing/integration/endpoint_security_test.go
  testing/integration/fake_test.go
  testing/integration/fqdn_test.go
  testing/integration/install_privileged_test.go
  testing/integration/install_test.go
  testing/integration/logs_ingestion_test.go
  testing/integration/metrics_monitoring_test.go
  testing/integration/otel_test.go
  testing/integration/package_version_test.go
  testing/integration/proxy_url_test.go
  testing/integration/upgrade_broken_package_test.go
  testing/integration/upgrade_downgrade_test.go
  testing/integration/upgrade_fleet_test.go
  testing/integration/upgrade_gpg_test.go
  testing/integration/upgrade_rollback_test.go
  testing/integration/upgrade_standalone_inprogress_test.go
  testing/integration/upgrade_standalone_retry_test.go
  testing/integration/upgrade_standalone_same_commit_test.go
  testing/integration/upgrade_standalone_test.go
  testing/integration/upgrade_uninstall_test.go
Labels: enhancement, backport-skip, skip-changelog, Testing

#4671 Patched changelog for PR 4579
  changelog/fragments/1713257367-Remove-beat-state-metricset-from-elastic-agent-monitoring.yaml
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog, backport-v8.14.0

#4633 Reduce agent logs by default
  changelog/fragments/1714717717-Reduce-agent-logs-by-default.yaml
  docs/scripts/es/elastic-agent-logs-comparison.http
  internal/pkg/agent/application/monitoring/v1_monitor.go
  internal/pkg/agent/application/upgrade/artifact/download/composed/verifier.go
Labels: enhancement, Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent, backport-skip

#4676 Finish rename started in #4562
  testing/integration/diagnostics_test.go
  testing/integration/fake_test.go
  testing/integration/monitoring_probe_preserve_text_cfg_test.go
  testing/integration/monitoring_probe_reload_test.go
Labels: bug, Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent, backport-skip, skip-changelog

#4674 Updated otel readme
  internal/pkg/otel/README.md
  internal/pkg/otel/templates/README.md.tmpl
Labels: Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent, skip-changelog, backport-v8.14.0

#4645 Add disruptive change mitigations section to PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent-Data-Plane, backport-skip, skip-changelog, chore

#4673 [Automation] Add the `Team:Elastic-Agent-Control-Plane` label to "Update .agent-versions.json" PRs
  .github/workflows/bump-agent-versions.sh
Labels: Team:Elastic-Agent-Control-Plane, automation, backport-skip, skip-changelog

#4688 pass unprivileged flag to store migration
  internal/pkg/agent/storage/store/state_store.go
  internal/pkg/config/operations/inspector.go
Labels: bug, Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent, skip-changelog, backport-v8.14.0

#4698 Bumping up `elastic/e2e-testing dependency` version
  NOTICE.txt
  go.mod
  go.sum
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog, chore, backport-v8.14.0

#4707 Make `elasticsearchexporter` available in Agent running in OTel mode
  NOTICE.txt
  changelog/fragments/1715178161-otel-mode-add-elasticsearch-exporter.yaml
  go.mod
  go.sum
  internal/pkg/otel/README.md
  internal/pkg/otel/components.go
Labels: Team:Elastic-Agent-Control-Plane, backport-v8.14.0

#4708 Make `filterprocessor` available in Agent running in OTel mode
  NOTICE.txt
  changelog/fragments/1715178093-otel-mode-add-filter-processor.yaml
  go.mod
  go.sum
  internal/pkg/otel/README.md
  internal/pkg/otel/components.go
Labels: Team:Elastic-Agent-Control-Plane, backport-v8.14.0

#4697 [Automation] Bump Golang version to 1.21.10
  .go-version
  .golangci.yml
  Dockerfile
  Dockerfile.skaffold
  changelog/fragments/1712176768-Upgrade-to-Go-1.21.10.yaml
  go.mod
  version/docs/version.asciidoc
Labels: Team:Elastic-Agent-Control-Plane, backport-v8.14.0

#4713 Update elastic/e2e-testing to 1.2.1
  NOTICE.txt
  go.mod
  go.sum
Labels: Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent, skip-changelog, backport-v8.14.0

#4672 Use `go install` instead of `go get`
  magefile.go
Labels: Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent, backport-skip, skip-changelog

#4696 Document how to build for different architectures
  README.md
Labels: Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent, backport-skip, skip-changelog

#4663 [main][Automation] Update .agent-versions.json
  .agent-versions.json
Labels: Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent, backport-skip, skip-changelog, update-versions

#4689 Replacing memory limiter processor with extension
  NOTICE.txt
  go.mod
  go.sum
  internal/pkg/otel/README.md
  internal/pkg/otel/components.go
  otel.yml
Labels: Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent, backport-skip, skip-changelog

#4693 Don't use artifact API for snapshot downloads
  changelog/fragments/1715158488-use-snapshot-api.yaml
  internal/pkg/agent/application/upgrade/artifact/download/snapshot/downloader.go
  internal/pkg/agent/application/upgrade/artifact/download/snapshot/downloader_test.go
  internal/pkg/agent/application/upgrade/artifact/download/snapshot/testdata/latest-snapshot.json
  pkg/testing/fetcher_artifact.go
  pkg/testing/fetcher_artifact_test.go
Labels: enhancement, Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent, backport-v8.14.0

#4360 [Elastic Agent]-PR- Introduce log message for not supported annotations for Hints based autodiscover
  NOTICE.txt
  changelog/fragments/1709656001-logshints.yaml
  go.mod
  go.sum
  internal/pkg/composable/providers/kubernetes/hints.go
  internal/pkg/composable/providers/kubernetes/hints_test.go
  internal/pkg/composable/providers/kubernetes/pod.go
  internal/pkg/composable/providers/kubernetes/pod_test.go
Labels: Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent, Team:Cloudnative-Monitoring, backport-skip

#4692 [Release] Update version to 8.13.5
  .buildkite/scripts/steps/integration_tests.sh
  deploy/kubernetes/elastic-agent-managed-kubernetes.yaml
  deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml
  version/version.go
Labels: Team:Automation, release, skip-changelog

#4691 docs: update docs versions 8.13.4
  version/docs/version.asciidoc
Labels: Team:Automation, release, docs, in progress, skip-changelog

#4725 Add agent-info.yaml to diagnostics output
  changelog/fragments/1715259944-Add-agent-info.yaml-to-diagnostics-bundle.yaml
  internal/pkg/agent/application/coordinator/coordinator.go
  internal/pkg/agent/application/coordinator/diagnostics_test.go
  testing/integration/diagnostics_test.go
Labels: Team:Elastic-Agent-Control-Plane, backport-v8.14.0

#4732 [main][Automation] Update .agent-versions.json
  .agent-versions.json
Labels: Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent, backport-skip, skip-changelog, update-versions

#4737 [main][Automation] Update .agent-versions.json
  .agent-versions.json
Labels: Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent, backport-skip, skip-changelog, update-versions

#4731 Use same version of golangci-lint in makefile as github actions
  Makefile
Labels: Team:Elastic-Agent-Control-Plane, backport-skip, skip-changelog

#3090 Support log level setting from policy
  .mockery.yaml
  changelog/fragments/1715257644-Set-log-level-from-fleet-policy.yaml
  internal/pkg/agent/application/actions/handlers/handler_action_application.go
  internal/pkg/agent/application/actions/handlers/handler_action_diagnostics_test.go
  internal/pkg/agent/application/actions/handlers/handler_action_policy_change.go
  internal/pkg/agent/application/actions/handlers/handler_action_policy_change_test.go
  internal/pkg/agent/application/actions/handlers/handler_action_settings.go
  internal/pkg/agent/application/actions/handlers/handler_action_settings_test.go
  internal/pkg/agent/application/actions/handlers/loglevelsetter.go
  internal/pkg/agent/application/coordinator/coordinator.go
  internal/pkg/agent/application/coordinator/diagnostics_test.go
  internal/pkg/agent/application/info/agent_info.go
  internal/pkg/agent/application/managed_mode.go
  internal/pkg/agent/application/upgrade/rollback_test.go
  internal/pkg/agent/application/upgrade/upgrade_test.go
  internal/pkg/agent/cmd/run.go
  internal/pkg/agent/configuration/configuration.go
  magefile.go
  pkg/component/runtime/runtime_comm_test.go
  pkg/control/v2/client/client.go
  testing/integration/log_level_test.go
  testing/mocks/internal_/pkg/agent/application/actions/handlers/diagnostics_provider_mock.go
  testing/mocks/internal_/pkg/agent/application/actions/handlers/log_level_setter_mock.go
  testing/mocks/internal_/pkg/agent/application/actions/handlers/uploader_mock.go
  testing/mocks/internal_/pkg/agent/application/info/agent_mock.go
  testing/mocks/internal_/pkg/fleetapi/acker/acker_mock.go
  testing/mocks/pkg/control/v2/client/client_mock.go
Labels: Team:Elastic-Agent-Control-Plane, backport-skip

#4740 Pin OGC to a newer release version
  pkg/testing/ogc/provisioner.go
Labels: Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent, skip-changelog, backport-v8.14.0

#4746 Fix wrong permissions when installation with enrollment on Windows in privileged mode
  internal/pkg/agent/cmd/enroll_windows.go
  internal/pkg/agent/perms/windows.go
Labels: Team:Elastic-Agent-Control-Plane, impact:critical, skip-changelog, backport-v8.14.0

#4751 fix log message when settings log level from SETTINGS action
  internal/pkg/agent/application/actions/handlers/handler_action_settings.go
Labels: enhancement, Team:Elastic-Agent-Control-Plane, backport-skip, skip-changelog

#4767 Make error checks in TestLogIngestionFleetManaged more resilient
  pkg/testing/tools/estools/elasticsearch.go
  testing/integration/logs_ingestion_test.go
Labels: Team:Elastic-Agent-Control-Plane, backport-skip, skip-changelog

#4768 Automate fetching the latest package version
  .buildkite/scripts/steps/integration_tests.sh
  .github/workflows/bump-agent-versions.sh
  .github/workflows/bump-agent-versions.yml
  .package-version
  magefile.go
Labels: Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent, backport-skip, skip-changelog

#4739 [CI] Separated extended testing pipeline
  .buildkite/hooks/pre-command
  .buildkite/hooks/pre-exit
  .buildkite/integration.pipeline.yml
  .buildkite/pipeline.yml
  .pre-commit-config.yaml
Labels: enhancement, backport-skip, skip-changelog, ci, Team:Ingest-EngProd

#4757 Remove pinning to 8.14.0.
  .package-version
  testing/integration/upgrade_broken_package_test.go
Labels: Team:Elastic-Agent, backport-skip, skip-changelog

#4774 Fix default beat name to elastic-agent instead of the repo directory name
  dev-tools/mage/settings.go
Labels: Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent, backport-skip, skip-changelog, chore

#4745 Add TLS support for proxytest
  internal/pkg/agent/application/upgrade/artifact/download/http/verifier_test.go
  testing/proxytest/proxytest.go
  testing/proxytest/proxytest_test.go
Labels: enhancement, Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent, backport-skip, skip-changelog, Testing

#4761 Add permission checks to all install and upgrade integration tests
  testing/installtest/checks.go
  testing/installtest/checks_unix.go
  testing/installtest/checks_windows.go
  testing/integration/install_privileged_test.go
  testing/integration/install_test.go
  testing/integration/install_unix_test.go
  testing/integration/install_windows_test.go
  testing/integration/logs_ingestion_test.go
  testing/upgradetest/upgrader.go
  testing/upgradetest/versions.go
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog, backport-v8.14.0

#4782 Run integration test steps in different data centers
  .buildkite/integration.pipeline.yml
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog, backport-v8.14.0

#4786 github-actions: use GitHub secrets
  .github/workflows/bump-golang.yml
Labels: Team:Elastic-Agent-Control-Plane, backport-skip, skip-changelog

#4779 Fix issue with `--delay-enroll` and `--unprivileged` on Windows
  changelog/fragments/1716227441-Fix-delay-enrollment-to-work-in-unprivileged-mode-on-Windows.yaml
  internal/pkg/agent/cmd/enroll_cmd.go
  testing/integration/delay_enroll_test.go
Labels: Team:Elastic-Agent-Control-Plane, backport-v8.14.0

#4781 Remove outdated comment on OTel v0.97.0
  go.mod
Labels: Team:Elastic-Agent-Control-Plane, backport-skip, Cleanup, skip-changelog

#4744 github-action: delete opentelemetry workflow
  .github/workflows/opentelemetry.yml
Labels: backport-skip, skip-changelog

#4788 Elaborate on Github check names to show parent relationship
  .buildkite/integration.pipeline.yml
Labels: Team:Elastic-Agent-Control-Plane, Cleanup, skip-changelog, ci, Team:Ingest-EngProd, backport-v8.13.0, backport-v8.14.0

#4773 [main][Automation] Update versions
  .agent-versions.json
  .package-version
Labels: Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent, backport-skip, skip-changelog, update-versions

#4795 [8.13] Remove pin to 8.13.4 stack version.
  .buildkite/scripts/steps/integration_tests.sh
  testing/integration/upgrade_broken_package_test.go
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog

#4727 Make delayed enrollment try indefinitely
  changelog/fragments/1715266989-Make-delayed-enrollment-try-indefinitely.yaml
  internal/pkg/agent/cmd/run.go
Labels: Team:Elastic-Agent-Control-Plane, backport-v8.14.0

#4790 github-actions: remove apm-ci role/secret vault
  .github/workflows/bump-agent-versions.yml
Labels: backport-skip, skip-changelog

#4787 Add test for OTel Collector start
  internal/pkg/otel/run_test.go
  internal/pkg/otel/testdata/all-components.windows.yml
  internal/pkg/otel/testdata/all-components.yml
  internal/pkg/otel/testdata/nonexistent-component.yml
  internal/pkg/otel/testdata/otel.yml
Labels: Team:Elastic-Agent-Control-Plane, backport-skip, skip-changelog, Testing

#4793 Auto-update GitHub actions with Dependabot
  .github/dependabot.yml
Labels: Team:Elastic-Agent-Control-Plane, backport-skip, skip-changelog

#4802 Update labels on Dependabot PRs
  .github/dependabot.yml
Labels: Team:Elastic-Agent-Control-Plane, backport-skip, skip-changelog

#4643 Send fleet-server elasticsearch config under new bootstrap attribute
  changelog/fragments/1714505172-Send-fleet-server-component-output-under-bootstrap-key.yaml
  docs/fleet-server-bootstrap.asciidoc
  internal/pkg/agent/application/fleet_server_bootstrap.go
  internal/pkg/agent/application/fleet_server_bootstrap_test.go
  internal/pkg/agent/configuration/fleet_server.go
  pkg/testing/fixture_install.go
  pkg/testing/tools/estools/elasticsearch.go
  testing/integration/fleet-server.json
  testing/integration/fleetserver_test.go
Labels: enhancement, Team:Elastic-Agent-Control-Plane, backport-skip

#4803 Remove deprecated fields from OTel ResolverSettings
  internal/pkg/otel/run.go
Labels: Team:Elastic-Agent-Control-Plane, backport-skip, skip-changelog

#4804 Add asset inventory as input to cloudbeat
  changelog/fragments/1716543533-add-cloudbeat-asset-inventory-aws.yaml
  specs/cloudbeat.spec.yml
Labels: enhancement, backport-skip
