Repository elastic/elastic-agent, pull requests merged in 2024-12, with the labels that each got.

#6169 Only run providers that are referenced in the policy
  changelog/fragments/1732840106-Only-run-providers-referenced-in-the-policy.yaml
  internal/pkg/agent/application/coordinator/coordinator.go
  internal/pkg/agent/application/coordinator/coordinator_test.go
  internal/pkg/agent/cmd/run.go
  internal/pkg/agent/transpiler/ast.go
  internal/pkg/agent/transpiler/ast_test.go
  internal/pkg/agent/transpiler/vars.go
  internal/pkg/agent/vars/vars.go
  internal/pkg/composable/benchmark_test.go
  internal/pkg/composable/config.go
  internal/pkg/composable/controller.go
  internal/pkg/composable/controller_test.go
Labels: Team:Elastic-Agent-Control-Plane, backport-8.x

#6128 Add an indicative limit for judging if a PR is too big in PR guidelines
  CONTRIBUTING.md
Labels: documentation, skip-changelog, chore, backport-8.x

#6140 Revert "Temporarily pin versions for integration tests to `8.17.0`"
  .buildkite/scripts/steps/beats_tests.sh
  .buildkite/scripts/steps/integration-package.sh
  .buildkite/scripts/steps/integration_tests.sh
  .buildkite/scripts/steps/k8s-extended-tests.sh
  .package-version
  testing/integration/upgrade_broken_package_test.go
Labels: Team:Elastic-Agent-Control-Plane, backport-skip, skip-changelog

#6190 Skipping flaky unit test: `TestUpgradeHandlerSameVersion`
  internal/pkg/agent/application/actions/handlers/handler_action_upgrade_test.go
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog, backport-8.x, backport-8.16, backport-8.17

#6109 Make redaction of common keys in diagnostics case insensitive
  changelog/fragments/1732184289-redact-case-insensitive.yaml
  internal/pkg/diagnostics/diagnostics.go
  internal/pkg/diagnostics/diagnostics_test.go
Labels: Team:Elastic-Agent-Control-Plane, >bug, backport-8.x, backport-8.16, backport-8.17

#5988 Add support for pre existing Active Directory user
  changelog/fragments/1731314919-Added-support-for-custom-Active-Directory-user-for-unprivileged-mode.yaml
  internal/pkg/agent/cmd/install.go
  internal/pkg/agent/cmd/privileged.go
  internal/pkg/agent/cmd/unprivileged.go
  internal/pkg/agent/install/install.go
  internal/pkg/agent/install/install_test.go
  internal/pkg/agent/install/install_unix.go
  internal/pkg/agent/install/install_windows.go
  internal/pkg/agent/install/install_windows_test.go
  internal/pkg/agent/install/prereq.go
  internal/pkg/agent/install/switch.go
  internal/pkg/agent/install/user_darwin.go
  internal/pkg/agent/install/user_linux.go
  internal/pkg/agent/install/user_test.go
  internal/pkg/agent/install/user_windows.go
  pkg/testing/fixture_install.go
  testing/installtest/checks.go
  testing/installtest/checks_unix.go
  testing/installtest/checks_windows.go
  testing/integration/install_test.go
  testing/integration/switch_unprivileged_test.go
Labels: enhancement, Team:Elastic-Agent-Control-Plane, QA:Ready For Testing, backport-8.x

#6137 gh-actions: fix slack bump
  .github/workflows/bump-agent-versions.yml
  .github/workflows/bump-golang.yml
  .github/workflows/updatecli-compose.yml
Labels: skip-changelog, backport-8.x

#6218 Remove SonarQube badge from README
  README.md
Labels: skip-changelog, chore, backport-8.x, backport-8.16, backport-8.17

#6173 [CI] Skip new ARM tests
  .buildkite/bk.integration.pipeline.yml
Labels: enhancement, backport-skip, skip-changelog, Team:Ingest-EngProd

#6172 [CI] Reverted test collector plugin for BK integration tests.
  .buildkite/bk.integration.pipeline.yml
Labels: enhancement, backport-skip, skip-changelog, Team:Ingest-EngProd

#6230 Add support for failureThreshold passed as float64 from policy
  internal/pkg/agent/application/monitoring/v1_monitor.go
  internal/pkg/agent/application/monitoring/v1_monitor_test.go
Labels: bug, Team:Elastic-Agent-Control-Plane, skip-changelog, backport-8.x, backport-8.17

#6224 Redact common secrets in `elastic-agent inspect` output
  changelog/fragments/1733397457-redact-common-secrets-in-inspect-output.yaml
  internal/pkg/agent/cmd/inspect.go
  internal/pkg/diagnostics/diagnostics.go
  testing/integration/endpoint_security_test.go
  testing/integration/inspect_test.go
Labels: enhancement, Team:Elastic-Agent-Control-Plane, backport-8.x, backport-8.17

#6241 [CI] Add build/diagnostics dir to artifacts
  .buildkite/bk.integration.pipeline.yml
Labels: enhancement, backport-skip, skip-changelog, Team:Ingest-EngProd, skip-it

#6199 Integration tests autodiscovery
  pkg/testing/define/define.go
  pkg/testing/define/define_autodiscovery.go
  pkg/testing/define/define_autodiscovery_test.go
  pkg/testing/define/define_flags.go
  testing/integration/main_test.go
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog, Testing, backport-8.x

#6180 Add config generation benchmark
  internal/pkg/agent/application/coordinator/coordinator_test.go
  internal/pkg/agent/application/coordinator/testdata/config.yaml
  internal/pkg/agent/application/coordinator/testdata/variables.yaml
Labels: enhancement, Team:Elastic-Agent-Control-Plane, skip-changelog, skip-it, backport-8.x, backport-8.16, backport-8.17

#6243 [CI] Added test report aggregation for test-collector plugin
  .buildkite/bk.integration.pipeline.yml
  .buildkite/hooks/pre-command
  .buildkite/scripts/buildkite-integration-tests.sh
  .buildkite/scripts/integration-tests.ps1
Labels: enhancement, backport-skip, skip-changelog, Team:Ingest-EngProd, skip-it

#6184 Avoid unnecessary copies during config generation
  changelog/fragments/1733158776-avoid-copies-config-gen.yaml
  internal/pkg/agent/application/coordinator/coordinator.go
  internal/pkg/agent/transpiler/ast.go
  internal/pkg/agent/transpiler/ast_test.go
  internal/pkg/agent/transpiler/utils.go
Labels: enhancement, Team:Elastic-Agent-Control-Plane, backport-8.x, backport-8.16, backport-8.17

#6178 Do external package manager check only at startup
  changelog/fragments/1733131399-vars-for-platform.yaml
  pkg/component/component.go
  pkg/component/platforms.go
Labels: enhancement, Team:Elastic-Agent-Control-Plane, backport-8.x, backport-8.16, backport-8.17

#6078 Replaced HOME change in sudo int tests
  .buildkite/scripts/buildkite-integration-tests.sh
Labels: skip-changelog, backport-8.15, backport-8.x, backport-8.16, backport-8.17

#5822 docs: add EDOT colletor kube-stack Helm values
  changelog/fragments/1729235281-kube-stack-helm-chart.yaml
  deploy/helm/edot-collector/kube-stack/README.md
  deploy/helm/edot-collector/kube-stack/values.yaml
  magefile.go
  testing/integration/otel_helm_test.go
Labels: Team:Elastic-Agent-Control-Plane, backport-8.x, backport-8.16, backport-8.17

#6148 Run BK integration tests on PRs and release branches
  .buildkite/bk.integration.pipeline.yml
  .buildkite/integration.pipeline.yml
  .buildkite/pipeline.yml
  docs/test-framework-dev-guide.md
Labels: enhancement, Team:Elastic-Agent-Control-Plane, backport-skip, skip-changelog, Team:Ingest-EngProd

#6229 Cache conditions when applying variables to config
  changelog/fragments/1733411331-cache-conditions-in-config.yaml
  internal/pkg/agent/transpiler/ast.go
  internal/pkg/agent/transpiler/ast_test.go
Labels: enhancement, Team:Elastic-Agent-Control-Plane, backport-8.x, backport-8.16, backport-8.17

#6257 Re-enabled notifyFleetAuditUninstall on Windows
  changelog/fragments/1733768621-Notify-Fleet-of-uninstall-on-Windows.yaml
  internal/pkg/agent/install/uninstall.go
  pkg/testing/fixture.go
  pkg/testing/fixture_install.go
  testing/integration/install_test.go
Labels: Team:Elastic-Agent-Control-Plane, backport-8.x

#6188 Update CODEOWNERS according to k8s ownership transfer plan
  .github/CODEOWNERS
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog, backport-8.x, backport-8.16, backport-8.17

#6310 Add support for running version updates on multiple branches
  .github/workflows/bump-agent-versions.sh
Labels: Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent, skip-changelog, Testing, backport-8.x, backport-8.16, backport-8.17

#6309 Run agent test version bump on all active branches
  .github/workflows/bump-agent-versions.yml
Labels: Team:Elastic-Agent-Control-Plane, backport-skip, skip-changelog, Testing

#6322 [CI] Backport buildkite integration tests to 8.x
  .buildkite/bk.integration.pipeline.yml
  .buildkite/hooks/pre-command
  .buildkite/pipeline.yml
  .buildkite/scripts/buildkite-integration-tests.sh
  .buildkite/scripts/integration-tests.ps1
  .buildkite/scripts/steps/integration_tests_tf.sh
  .buildkite/scripts/steps/merge.sh
  .tool-versions
  catalog-info.yaml
  test_infra/ess/deployment.tf
Labels: enhancement, backport, Team:Ingest-EngProd

#6335 fix: use a different branch name for the auto-updates
  .github/workflows/bump-agent-versions.sh
Labels: skip-changelog, backport-8.x, backport-8.16, backport-8.17

#6293 chore: update version and appVersion in the elastic-agent helm chart
  deploy/helm/elastic-agent/Chart.yaml
  deploy/helm/elastic-agent/examples/eck/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/fleet-managed/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/kubernetes-default/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/kubernetes-hints-autodiscover/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/kubernetes-only-logs/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/multiple-integrations/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/nginx-custom-integration/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/system-custom-auth-paths/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/user-cluster-role/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/user-service-account/rendered/manifest.yaml
  magefile.go
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog, backport-8.x, backport-8.16, backport-8.17

#6277 [k8s]: transition integration tests to adapter pattern
  testing/integration/kubernetes_agent_service_test.go
  testing/integration/kubernetes_agent_standalone_test.go
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog, Testing, backport-8.x, backport-8.16, backport-8.17

#6085 Fix audit/unenroll calls when agent runs fleet-server
  changelog/fragments/1732043830-Fix-audit-unenroll-call-when-running-fleet-server.yaml
  internal/pkg/agent/install/uninstall.go
  internal/pkg/agent/install/uninstall_test.go
  internal/pkg/fleetapi/ack_cmd.go
  internal/pkg/fleetapi/audit_unenroll_cmd.go
  internal/pkg/fleetapi/checkin_cmd.go
  testing/integration/fleetserver_test.go
  testing/integration/install_test.go
Labels: bug, Team:Elastic-Agent-Control-Plane, backport-8.x, backport-8.16, backport-8.17

#6276 Fix/5163 retry download upgrade verifiers
  changelog/fragments/1733936340-add-retries-for-download-upgrade-verifiers.yaml
  internal/pkg/agent/application/upgrade/artifact/download/composed/verifier.go
  internal/pkg/agent/application/upgrade/artifact/download/composed/verifier_test.go
  internal/pkg/agent/application/upgrade/artifact/download/fs/verifier.go
  internal/pkg/agent/application/upgrade/artifact/download/fs/verifier_test.go
  internal/pkg/agent/application/upgrade/artifact/download/http/common_test.go
  internal/pkg/agent/application/upgrade/artifact/download/http/downloader_test.go
  internal/pkg/agent/application/upgrade/artifact/download/http/verifier.go
  internal/pkg/agent/application/upgrade/artifact/download/http/verifier_test.go
  internal/pkg/agent/application/upgrade/artifact/download/http/verify_backoff_rtt.go
  internal/pkg/agent/application/upgrade/artifact/download/http/verify_backoff_rtt_test.go
  internal/pkg/agent/application/upgrade/artifact/download/snapshot/verifier.go
  internal/pkg/agent/application/upgrade/artifact/download/verifier.go
  internal/pkg/agent/application/upgrade/step_download.go
Labels: backport-8.x

#6329 Prevent leaking secrets when logging component model
  changelog/fragments/1734098868-prevent-leaking-secrets-when-logging-component-model.yaml
  internal/pkg/agent/application/coordinator/coordinator.go
  pkg/component/component.go
  pkg/component/component_test.go
Labels: enhancement, Team:Elastic-Agent-Control-Plane, backport-8.x, backport-8.17

#6144 Return actionable error message when enrolling
  changelog/fragments/1732656422-add-actionable-error-message-for-enroll-command.yaml
  internal/pkg/agent/cmd/enroll.go
  internal/pkg/agent/cmd/enroll_match_fileowner_unix.go
  internal/pkg/agent/cmd/enroll_match_fileowner_unix_test.go
  internal/pkg/agent/cmd/enroll_match_fileowner_windows.go
  internal/pkg/agent/cmd/enroll_match_fileowner_windows_test.go
  pkg/testing/tools/tools.go
  testing/integration/enroll_unprivileged_test.go
Labels: Team:Elastic-Agent-Control-Plane, backport-8.x

#6381 [k8s] embed hints inputs in agent container image
  changelog/fragments/1734512365-embed-hints-inputs-in-agent-container-image.yaml
  deploy/helm/elastic-agent/examples/kubernetes-hints-autodiscover/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/multiple-integrations/rendered/manifest.yaml
  deploy/helm/elastic-agent/templates/integrations/_kubernetes/_kubernetes.tpl
  deploy/helm/elastic-agent/templates/integrations/_kubernetes/_kubernetes_hints.tpl
  deploy/helm/elastic-agent/templates/integrations/_kubernetes/_preset_pernode.tpl
  dev-tools/packaging/package_test.go
  dev-tools/packaging/packages.yml
  internal/pkg/agent/application/application.go
  internal/pkg/composable/providers/kubernetes/config.go
  internal/pkg/composable/providers/kubernetes/config_test.go
  internal/pkg/config/loader.go
Labels: Team:Elastic-Agent-Control-Plane, backport-8.x

#6413 [ESS Testing] Update ESS region and deployment template ID
  testing/environments/cloud/variables.tf
Labels: Team:Elastic-Agent-Control-Plane, >bug, skip-changelog, backport-8.x, backport-8.16, backport-8.17

#6212 Enhancement/5832 deb rpm docker tests
  pkg/testing/fixture_install.go
  testing/integration/kubernetes_agent_standalone_test.go
  testing/integration/restrict_upgrade_deb_test.go
  testing/integration/restrict_upgrade_rpm_test.go
Labels: skip-changelog, backport-8.x

#6345 [helm] fleet mode fixes
  deploy/helm/elastic-agent/README.md
  deploy/helm/elastic-agent/examples/eck/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/fleet-managed/README.md
  deploy/helm/elastic-agent/examples/fleet-managed/fleet-values.yaml
  deploy/helm/elastic-agent/examples/fleet-managed/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/kubernetes-default/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/kubernetes-hints-autodiscover/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/kubernetes-only-logs/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/multiple-integrations/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/system-custom-auth-paths/agent-system-values.yaml
  deploy/helm/elastic-agent/examples/system-custom-auth-paths/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/user-service-account/rendered/manifest.yaml
  deploy/helm/elastic-agent/templates/agent/_helpers.tpl
  deploy/helm/elastic-agent/templates/integrations/_kubernetes/_preset_pernode.tpl
  deploy/helm/elastic-agent/values.yaml
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog, backport-8.x, backport-8.16, backport-8.17

#6434 [flaky] temporarily skip TestBeatsServerless
  testing/integration/beats_serverless_test.go
Labels: Team:Elastic-Agent, skip-changelog, backport-8.x

#6412 Call tlscommon.SetInsecureDefaults
  internal/pkg/config/config.go
  internal/pkg/config/test/tls_version_test.go
  internal/pkg/config/testdata/tls.yml
  internal/pkg/config/testdata/tls10.yml
Labels: Team:Elastic-Agent-Control-Plane, backport

#6415 Update pull request guidelines
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
Labels: Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent-Data-Plane, skip-changelog, backport-8.x

#6438 [integration] - enable TestBeatsServerless
  testing/integration/beats_serverless_test.go
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog, backport-8.x

#6393 Switch back to Ubuntu 20.04-based Docker images in the cloud
  changelog/fragments/1734687016-revert-cloud-image.yaml
  dev-tools/packaging/packages.yml
  dev-tools/packaging/templates/docker/Dockerfile.elastic-agent.tmpl
Labels: Team:Elastic-Agent-Control-Plane, backport-8.16

#6414 Add Journald to the examples and default configuration
  _meta/config/common.p2.yml.tmpl
  _meta/config/common.reference.p2.yml.tmpl
  elastic-agent.reference.yml
  elastic-agent.yml
Labels: Team:Elastic-Agent-Data-Plane, skip-changelog, backport-8.x

#6410 Add logging to EventLog for error, install, uninstall
  changelog/fragments/1734626964-Windows-add-Event-Logging-to-install,-uninstall,-enroll.yaml
  internal/pkg/agent/cmd/enroll.go
  internal/pkg/agent/cmd/install.go
  internal/pkg/agent/cmd/uninstall.go
Labels: backport-8.x

#6206 Added skip audit/unenroll flag to uninstall command
  changelog/fragments/1733248787-flag-to-skip-fleet-audit.yaml
  internal/pkg/agent/cmd/install.go
  internal/pkg/agent/cmd/uninstall.go
  internal/pkg/agent/install/uninstall.go
  internal/pkg/agent/install/uninstall_test.go
Labels: backport-8.x

#6408 Build only cloud image variant when it's requested
  magefile.go
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog, backport-8.x, backport-8.16, backport-8.17

#6437 fix(6023): replace list with items
  changelog/fragments/1735137195-remove-deprecated-list-in-favor-of-items.yaml
  internal/pkg/agent/cmd/container.go
  internal/pkg/agent/cmd/container_test.go
  testing/integration/validate_items_deprecated_list_test.go
Labels: bug, Team:Elastic-Agent-Control-Plane, backport-8.x
