Repository elastic/elastic-agent, pull requests merged in 2024-01, with the labels that each got.

#3966 Update pipeline.yml
  .buildkite/pipeline.yml
Labels: Team:Elastic-Agent, backport-skip, skip-changelog

#3975 Update notice year to 2024
  NOTICE.txt
Labels: Team:Elastic-Agent, skip-changelog, backport-v8.12.0

#3971 Avoid nested Eventually calls in APM Ingestion E2E test
  pkg/testing/log_watcher.go
  testing/integration/otel_test.go
Labels: Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent, flaky-test, backport-skip, skip-changelog

#3930 Fix (*artifact.Config).Unpack not preserving not overridden values
  NOTICE.txt
  go.mod
  internal/pkg/agent/application/upgrade/artifact/config.go
  internal/pkg/agent/application/upgrade/artifact/config_test.go
Labels: Team:Elastic-Agent, skip-changelog, backport-v8.12.0

#3929 Move FQDN tests to its own group
  testing/integration/fqdn_test.go
  testing/integration/groups_test.go
Labels: Team:Elastic-Agent, backport-skip, skip-changelog

#3939 Fix issue on Windows for creating a copy of the install directory
  pkg/testing/fixture_install.go
Labels: Team:Elastic-Agent, backport-skip, skip-changelog

#3980 Skip flaky test TestContainerCMD
  testing/integration/container_cmd_test.go
Labels: Team:Elastic-Agent, flaky-test, skip-changelog, backport-v8.12.0

#3987 Fix TestWriteMarkerFileWithTruncation flaky test
  internal/pkg/agent/application/upgrade/marker_access_test.go
Labels: bug, Team:Elastic-Agent, skip-changelog, backport-v8.12.0

#3937 Add test ensuring all the agent.download settings are reloaded
  internal/pkg/agent/application/upgrade/upgrade.go
  internal/pkg/agent/application/upgrade/upgrade_test.go
Labels: Team:Elastic-Agent, skip-changelog, backport-v8.12.0

#3985 Fix flaky test TestContainerCMD
  testing/integration/container_cmd_test.go
Labels: Team:Elastic-Agent, flaky-test, skip-changelog, backport-v8.12.0

#3992 Added Readme file for otel
  internal/pkg/otel/README.md
  internal/pkg/otel/templates/README.md.tmpl
  magefile.go
Labels: Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent, backport-skip, skip-changelog

#3999 Add test framework architecture diagram.
  README.md
  docs/images/testing-framework.png
  docs/test-framework-dev-guide.md
Labels: Team:Elastic-Agent, backport-skip, skip-changelog

#3988 switch to consistent HasRoot method on windows and fix memory leak
  pkg/control/v2/server/listener_windows.go
  pkg/utils/root_windows.go
Labels: bug, Team:Elastic-Agent-Control-Plane, skip-changelog, backport-v8.12.0

#3997 [updatecli][shell] Bump version to 1.21
  .github/workflows/golangci-lint.yml
  .go-version
  .golangci.yml
  Dockerfile
  Dockerfile.skaffold
  changelog/fragments/1697229987-Upgrade-to-Go-1.20.10.yaml
  changelog/fragments/1704304944-Upgrade-to-Go-1.21.5.yaml
  go.mod
  go.sum
  version/docs/version.asciidoc
Labels: Team:Elastic-Agent, backport-skip

#4003 Merge dependabot into single combination
  .github/dependabot.yml
Labels: Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent, backport-skip, skip-changelog

#4011 Increase PrepareAgentCommand ctx deadline for TestContainerCMD
  testing/integration/container_cmd_test.go
Labels: Team:Elastic-Agent, flaky-test, skip-changelog, backport-v8.12.0

#4012 Setup mage for post dependabot action
  .github/workflows/post-dependabot.yml
Labels: bug, Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent, backport-skip, skip-changelog

#3909 [Unprivileged] Adjust the control socket path add `--path.socket` option
  changelog/fragments/1702501610-Adjust-control-socket-path-into-the-installation-directory.yaml
  internal/pkg/agent/application/info/agent_metadata.go
  internal/pkg/agent/application/info/state.go
  internal/pkg/agent/application/info/state_unix.go
  internal/pkg/agent/application/paths/common.go
  internal/pkg/agent/application/paths/paths.go
  internal/pkg/agent/application/paths/paths_darwin.go
  internal/pkg/agent/application/paths/paths_linux.go
  internal/pkg/agent/application/paths/paths_unix.go
  internal/pkg/agent/application/paths/paths_windows.go
  internal/pkg/agent/application/upgrade/upgrade.go
  internal/pkg/agent/cmd/common.go
  internal/pkg/agent/cmd/container.go
  internal/pkg/agent/cmd/enroll_cmd.go
  internal/pkg/agent/cmd/install.go
  internal/pkg/agent/cmd/run.go
  internal/pkg/agent/cmd/uninstall.go
  internal/pkg/agent/install/install.go
  internal/pkg/agent/install/install_unix.go
  internal/pkg/agent/install/install_windows.go
  pkg/control/addr.go
  pkg/control/addr_common.go
  pkg/control/addr_windows.go
  pkg/control/v1/client/dial_windows.go
  pkg/control/v2/client/dial_windows.go
  pkg/control/v2/server/listener.go
  pkg/control/v2/server/listener_windows.go
  pkg/control/v2/server/server.go
  pkg/testing/fixture_install.go
  testing/integration/install_unprivileged_test.go
Labels: Team:Elastic-Agent, backport-skip

#3982 Return the current agent state on Fixture.IsHealthy method
  pkg/testing/fixture.go
  testing/integration/container_cmd_test.go
Labels: enhancement, Team:Elastic-Agent, skip-changelog, Testing, backport-v8.12.0

#4038 Use correct 8.12 version for watcher details checks.
  testing/upgradetest/upgrader.go
Labels: Team:Elastic-Agent, skip-changelog, backport-v8.12.0

#4044 Omit download rate when it is calculated as +Inf to prevent checkin errors
  internal/pkg/agent/application/upgrade/details/details.go
  internal/pkg/agent/application/upgrade/details/details_test.go
Labels: Team:Elastic-Agent, skip-changelog, backport-v8.12.0

#3901 Remove the OVERRIDE_AGENT_PACKAGE_VERSION value as 8.13 is now built
  .buildkite/scripts/steps/integration_tests.sh
Labels: Team:Elastic-Agent, backport-skip, skip-changelog

#4042 set SkipDaemonRestart in tryDelayEnroll
  internal/pkg/agent/cmd/run.go
  pkg/testing/fixture_install.go
  pkg/testing/tools/tools.go
  testing/integration/delay_enroll_test.go
Labels: bug, Team:Elastic-Agent-Control-Plane, skip-changelog, backport-v8.12.0

#3908 Fix regex to locate elastic-agent .zip packages in package tests
  dev-tools/packaging/package_test.go
Labels: bug, Team:Elastic-Agent-Control-Plane, backport-skip, skip-changelog, Testing

#4065 Fix DRA Regex
  magefile.go
Labels: Team:Elastic-Agent, backport-skip, skip-changelog

#4069 Fix separator with no value caught
  magefile.go
Labels: backport-skip, skip-changelog

#4066 docs: update docs versions 8.11.4
  deploy/kubernetes/elastic-agent-managed-kubernetes.yaml
  deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml
  version/docs/version.asciidoc
Labels: Team:Automation, release, docs, in progress, skip-changelog

#4067 [Release] Update version to 8.11.5
  version/version.go
Labels: Team:Automation, release, skip-changelog

#4071 Changelog for 8.11.4 version
  changelog/8.11.4.asciidoc
  changelog/8.11.4.yaml
  changelog/fragments/1702055473-Upgrade-to-Go-1.20.12.yaml
Labels: Team:Elastic-Agent, skip-changelog, forwardport-main

#4073 [Automation] Bump Golang version to 1.21.6
  .go-version
  .golangci.yml
  Dockerfile
  Dockerfile.skaffold
  changelog/fragments/1704304944-Upgrade-to-Go-1.21.6.yaml
  version/docs/version.asciidoc
Labels: backport-skip

#4090 Add commit hashes to logged versions in upgrader
  testing/upgradetest/upgrader.go
Labels: enhancement, Team:Elastic-Agent, backport-skip, skip-changelog

#4079 Move FakeInput tests into their own test suite
  pkg/component/runtime/manager_fake_input_test.go
  pkg/component/runtime/manager_test.go
Labels: Team:Elastic-Agent, backport-skip, Cleanup, skip-changelog

#3876 [Release] Update version to 8.12.1
  .buildkite/scripts/steps/integration_tests.sh
  deploy/kubernetes/elastic-agent-managed-kubernetes.yaml
  deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml
  version/version.go
Labels: Team:Automation, release, skip-changelog

#4088 Add retries to control server connection and ensure logs are captured on failure
  pkg/testing/fixture.go
Labels: Team:Elastic-Agent, skip-changelog, backport-v8.12.0

#4096 Update flaky-test.md template
  .github/ISSUE_TEMPLATE/flaky-test.md
Labels: enhancement, Team:Elastic-Agent, backport-skip, skip-changelog

#3884 Fix component control protocol to allow checkin to be chunked across multiple messages
  NOTICE.txt
  changelog/fragments/1701975889-Fix-component-control-protocol-to-allow-checkin-to-be-chunked-across-multiple-messages.yaml
  control_v2.proto
  go.mod
  go.sum
  internal/pkg/agent/application/coordinator/diagnostics_test.go
  internal/pkg/agent/configuration/grpc.go
  internal/pkg/diagnostics/diagnostics_test.go
  pkg/component/fake/component/main.go
  pkg/component/fake/shipper/main.go
  pkg/component/runtime/conn_info_server_test.go
  pkg/component/runtime/manager.go
  pkg/component/runtime/manager_fake_input_test.go
  pkg/component/runtime/runtime.go
  pkg/component/runtime/runtime_comm.go
  pkg/component/runtime/state.go
  pkg/control/v1/proto/control_v1.pb.go
  pkg/control/v1/proto/control_v1_grpc.pb.go
  pkg/control/v2/client/client.go
  pkg/control/v2/cproto/control_v2.pb.go
  pkg/control/v2/cproto/control_v2_grpc.pb.go
  pkg/control/v2/server/server.go
  pkg/control/v2/server/server_test.go
Labels: bug, Team:Elastic-Agent, backport-skip

#4101 Increase short 10 second timeout in TestFakeComponent
  pkg/testing/fixture.go
  testing/integration/fake_test.go
Labels: Team:Elastic-Agent, skip-changelog, backport-v8.12.0

#4064 increase time to wait for watcher in upgrade
  testing/upgradetest/upgrader.go
Labels: Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent, backport-skip, skip-changelog, Testing, backport-v8.12.0

#4007 Add mTLS flags to install and enroll commands
  NOTICE.txt
  changelog/fragments/1704397113-Add-mTLS-flags-to-install-enroll.yaml
  go.mod
  go.sum
  internal/pkg/agent/cmd/enroll.go
  internal/pkg/agent/cmd/enroll_cmd.go
  internal/pkg/agent/cmd/enroll_cmd_test.go
  internal/pkg/agent/cmd/install_test.go
  internal/pkg/agent/cmd/install_windows_test.go
  internal/pkg/agent/configuration/fleet_server.go
Labels: enhancement, Team:Elastic-Agent-Control-Plane, Team:Fleet, backport-skip

#4100 Fix creation of containing directories for files in tar packages
  changelog/fragments/1705605734-fix-creation-of-directories-when-unpacking-tar.gz-packages.yaml
  internal/pkg/agent/application/upgrade/step_unpack.go
  internal/pkg/agent/application/upgrade/step_unpack_test.go
  internal/pkg/agent/application/upgrade/upgrade.go
Labels: bug, Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent, backport-skip

#4095 Look for the latest build with a non-matching commit hash
  testing/integration/upgrade_downgrade_test.go
  testing/integration/upgrade_fleet_test.go
  testing/upgradetest/upgrader.go
Labels: enhancement, Team:Elastic-Agent, backport-skip, skip-changelog

#4099 Update and rename flaky-test.md to flaky-test.yml
  .github/ISSUE_TEMPLATE/flaky-test.yml
Labels: Team:Elastic-Agent, backport-skip, skip-changelog

#4111 Fix YAML formatting in the flaky-test form
  .github/ISSUE_TEMPLATE/flaky-test.yml
Labels: Team:Elastic-Agent, backport-skip, skip-changelog

#4039 Disable Go Workspaces when executing 'go list' in agent packaging process
  dev-tools/mage/gotool/go.go
Labels: enhancement, Team:Elastic-Agent, skip-changelog, backport-v8.12.0

#4107 Start state watch after starting process.
  pkg/testing/fixture.go
Labels: Team:Elastic-Agent, skip-changelog, backport-v8.12.0

#4106 Remove all io/ioutil imports.
  dev-tools/cmd/buildfleetcfg/buildfleetcfg.go
  dev-tools/licenses/license_generate.go
  dev-tools/mage/common.go
  dev-tools/mage/config.go
  dev-tools/mage/copy.go
  dev-tools/mage/gotest.go
  dev-tools/mage/integtest_docker.go
  dev-tools/mage/kubernetes/kind.go
  dev-tools/mage/kubernetes/kuberemote.go
  dev-tools/mage/kubernetes/kubernetes.go
  dev-tools/mage/pkgspecs.go
  dev-tools/mage/pkgtypes.go
  dev-tools/mage/settings.go
  internal/pkg/agent/application/actions/handlers/handler_action_policy_change.go
  internal/pkg/agent/application/filelock/locker_test.go
  internal/pkg/agent/application/gateway/fleet/fleet_gateway_test.go
  internal/pkg/agent/application/monitoring/process.go
  internal/pkg/agent/application/upgrade/artifact/download/headers_rtt_test.go
  internal/pkg/agent/application/upgrade/artifact/download/http/downloader_test.go
  internal/pkg/agent/application/upgrade/artifact/download/http/verifier.go
  internal/pkg/agent/application/upgrade/artifact/download/verifier.go
  internal/pkg/agent/application/upgrade/step_mark.go
  internal/pkg/agent/application/upgrade/upgrade_test.go
  internal/pkg/agent/cleaner/cleaner_test.go
  internal/pkg/agent/cmd/component_spec.go
  internal/pkg/agent/cmd/upgrade.go
  internal/pkg/agent/storage/encrypted_disk_storage_windows_linux_test.go
  internal/pkg/agent/storage/replace_store.go
  internal/pkg/agent/storage/storage_test.go
  internal/pkg/agent/storage/store/action_store_test.go
  internal/pkg/agent/vault/seed.go
  internal/pkg/basecmd/version/cmd_test.go
  internal/pkg/config/config.go
  internal/pkg/crypto/io_test.go
  internal/pkg/dir/discover_test.go
  internal/pkg/filewatcher/watcher_test.go
  internal/pkg/fleetapi/ack_cmd.go
  internal/pkg/fleetapi/acker/fleet/fleet_acker_test.go
  internal/pkg/fleetapi/checkin_cmd.go
  internal/pkg/fleetapi/checkin_cmd_test.go
  internal/pkg/fleetapi/client/client.go
  internal/pkg/fleetapi/client/client_test.go
  internal/pkg/remote/client_test.go
  internal/pkg/remote/round_trippers.go
  pkg/component/load.go
  pkg/component/load_test.go
  pkg/packer/packer.go
  pkg/packer/packer_test.go
  pkg/testing/fixture.go
Labels: Team:Elastic-Agent, skip-changelog, backport-v8.12.0

#4074 Add error statements to inspect and config library
  changelog/fragments/1704994055-add-error-statements.yaml
  internal/pkg/agent/cmd/inspect.go
  internal/pkg/config/config.go
  internal/pkg/config/operations/inspector.go
Labels: Team:Elastic-Agent, backport-skip

#4047 Status subcommand reporting agent status for otel mode - Phase 2
  .gitignore
  internal/pkg/agent/application/application.go
  internal/pkg/agent/application/application_test.go
  internal/pkg/agent/cmd/run.go
  internal/pkg/otel/config_manager.go
  internal/pkg/otel/run.go
  pkg/testing/fixture.go
  testing/integration/otel_test.go
Labels: enhancement, Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent, backport-skip, skip-changelog

#4115 Add some deployment tags for helping with tracing
  pkg/testing/ess/statful_provisioner.go
Labels: backport-skip, skip-changelog, Team:Ingest-EngProd

#4123 [CI] Disables win 10 unit tests
  .buildkite/pipeline.yml
Labels: enhancement, skip-changelog, backport-v8.12.0

#4139 package_test.go - Support OCI Image Layout
  dev-tools/mage/copy.go
  dev-tools/packaging/package_test.go
Labels: Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent, skip-changelog, backport-v8.12.0

#4050 Add fleet config change logger
  changelog/fragments/1704824761-fleet-config-change-logging.yaml
  internal/pkg/agent/application/coordinator/coordinator.go
  internal/pkg/agent/application/coordinator/coordinator_test.go
Labels: Team:Elastic-Agent, backport-skip

#4146 flaky TestStandaloneUpgradeUninstallKillWatcher
  testing/integration/upgrade_uninstall_test.go
Labels: Team:Elastic-Agent, skip-changelog, backport-v8.12.0

#3910 Add manifest to package
  dev-tools/mage/common.go
  dev-tools/mage/settings.go
  dev-tools/packaging/package_test.go
  dev-tools/packaging/packages.yml
  pkg/api/v1/api.go
  pkg/api/v1/manifest.go
  pkg/api/v1/manifest_test.go
Labels: enhancement, Team:Elastic-Agent-Control-Plane, backport-skip, skip-changelog

#4157 Agent runs from directory with or without version
  internal/pkg/agent/application/application.go
  internal/pkg/agent/application/paths/common.go
  internal/pkg/agent/application/paths/common_test.go
  internal/pkg/agent/cmd/common.go
  internal/pkg/release/version.go
  version/helper.go
Labels: enhancement, Team:Elastic-Agent, backport-skip, skip-changelog

#4156 Windows has prefix fix
  internal/pkg/agent/application/paths/paths_test.go
  internal/pkg/agent/application/paths/paths_windows.go
Labels: Team:Elastic-Agent-Data-Plane, backport-skip, skip-changelog

#4165 enable intermediate builds on version branches
  catalog-info.yaml
Labels: backport-skip, skip-changelog

#3886 ci(action): auto-bump daily and change slack notification channel
  .github/workflows/bump-golang.yml
Labels: backport-skip, skip-changelog
