Repository elastic/elastic-agent, pull requests merged in 2024-06, with the labels that each got.

#4813 Refactor ProxyURL integration tests
  internal/pkg/remote/config.go
  testing/integration/proxy_url_test.go
Labels: Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent, backport-skip, skip-changelog, chore

#4815 Increase timeout for TestStartCollector
  internal/pkg/otel/run_test.go
Labels: Team:Elastic-Agent-Control-Plane, flaky-test, backport-skip, skip-changelog

#4825 Update elastic-agent-libs to v0.9.11
  NOTICE.txt
  go.mod
  go.sum
Labels: Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent, backport-skip, skip-changelog

#4798 Improve integration testing cloud client DeploymentIsReady.
  pkg/testing/ess/deployment.go
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog, backport-v8.14.0

#4836 [CI] Trigger improvements
  .buildkite/pull-requests.json
  .github/PULL_REQUEST_TEMPLATE.md
Labels: enhancement, Team:Elastic-Agent-Control-Plane, skip-changelog, backport-v8.14.0

#4847 Use higher tier ARM VM for integration testing
  pkg/testing/ogc/supported.go
Labels: Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent, skip-changelog, backport-v8.14.0

#4849 Add changelog for adding benchmark input
  changelog/fragments/1717523676-Add-benchmark-input.yaml
Labels: backport-skip

#4852 Disable integration tests on ARM due to instability
  pkg/testing/ogc/supported.go
Labels: Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent, skip-changelog, backport-v8.14.0

#4842 Update the versions file
  .agent-versions.json
Labels: Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent, backport-skip, skip-changelog

#4843 Support package version update on any release branch
  magefile.go
  pkg/testing/tools/git/git.go
Labels: Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent, skip-changelog, backport-v8.14.0

#4865 github-actions: set git config user/email
  .github/workflows/bump-agent-versions.yml
Labels: Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent, backport-skip, skip-changelog

#4872 Create a version update branch after the mage target is run
  .github/workflows/bump-agent-versions.sh
  .github/workflows/bump-agent-versions.yml
Labels: Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent, skip-changelog, backport-v8.14.0

#4869 Skip flaky proxy URL tests
  testing/integration/proxy_url_test.go
Labels: Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent, backport-skip, skip-changelog, skipped-test

#4594 [Release] Update version to 8.14.1
  deploy/kubernetes/elastic-agent-managed-kubernetes.yaml
  deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml
  testing/integration/upgrade_broken_package_test.go
  version/version.go
Labels: Team:Automation, release, skip-changelog

#4834 Wait on the watcher at startup instead of just releasing resources associated with it
  changelog/fragments/1717185708-Stop-creating-a-zombie-process-on-each-restart.yaml
  internal/pkg/agent/application/upgrade/rollback.go
Labels: Team:Elastic-Agent-Control-Plane, backport-skip

#4862 Disable controller code for otel mode
  internal/pkg/agent/application/application.go
  internal/pkg/agent/application/coordinator/coordinator.go
  internal/pkg/agent/cmd/run.go
  internal/pkg/composable/providers/kubernetessecrets/kubernetes_secrets.go
  internal/pkg/core/composable/providers.go
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog, backport-v8.14.0

#4249 Agent/beats grpc comms over domain socket/named pipe
  changelog/fragments/1707781046-Agent-beats-grpc-comms-over-domain-socket-named-pipe.yaml
  internal/pkg/agent/application/application.go
  internal/pkg/agent/application/coordinator/coordinator_test.go
  internal/pkg/agent/configuration/grpc.go
  pkg/component/runtime/conn_info_server.go
  pkg/component/runtime/conn_info_server_test.go
  pkg/component/runtime/conn_info_server_unix_test.go
  pkg/component/runtime/conn_info_server_windows_test.go
  pkg/component/runtime/manager.go
  pkg/component/runtime/manager_fake_input_test.go
  pkg/component/runtime/manager_test.go
  pkg/component/runtime/runtime.go
  pkg/component/runtime/service.go
  pkg/component/runtime/service_test.go
  pkg/component/spec.go
  pkg/component/spec_test.go
  pkg/control/v2/server/listener.go
  pkg/ipc/listener.go
  pkg/ipc/listener_windows.go
  specs/endpoint-security.spec.yml
Labels: enhancement, Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent, backport-skip

#4549 Log raw events to a separate log file
  NOTICE.txt
  _meta/config/common.reference.p2.yml.tmpl
  changelog/fragments/1712935205-Log-raw-events-to-a-separate-log-file.yaml
  docs/elastic-agent-logging.md
  elastic-agent.reference.yml
  go.mod
  go.sum
  internal/pkg/agent/application/actions/handlers/handler_action_diagnostics.go
  internal/pkg/agent/application/actions/handlers/handler_action_diagnostics_test.go
  internal/pkg/agent/application/application.go
  internal/pkg/agent/application/coordinator/coordinator_test.go
  internal/pkg/agent/application/dispatcher/dispatcher.go
  internal/pkg/agent/application/dispatcher/dispatcher_test.go
  internal/pkg/agent/application/managed_mode.go
  internal/pkg/agent/application/paths/common.go
  internal/pkg/agent/application/upgrade/cleanup_test.go
  internal/pkg/agent/cmd/diagnostics.go
  internal/pkg/agent/cmd/enroll.go
  internal/pkg/agent/cmd/logs.go
  internal/pkg/agent/cmd/logs_test.go
  internal/pkg/agent/cmd/run.go
  internal/pkg/agent/configuration/settings.go
  internal/pkg/agent/protection/policy_test.go
  internal/pkg/basecmd/version/cmd_test.go
  internal/pkg/cli/streams.go
  internal/pkg/composable/providers/kubernetes/pod_test.go
  internal/pkg/diagnostics/diagnostics.go
  internal/pkg/diagnostics/diagnostics_test.go
  internal/pkg/fleetapi/acker/lazy/lazy_acker_test.go
  internal/pkg/fleetapi/action.go
  internal/pkg/testutils/testutils.go
  pkg/component/runtime/manager_test.go
  pkg/control/v2/control_test.go
  pkg/core/logger/logger.go
  specs/auditbeat.spec.yml
  specs/cloudbeat.spec.yml
  specs/filebeat.spec.yml
  specs/heartbeat.spec.yml
  specs/metricbeat.spec.yml
  specs/osquerybeat.spec.yml
  specs/packetbeat.spec.yml
  testing/integration/logs_ingestion_test.go
Labels: Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent, backport-skip, skipped-test

#4893 Make `k8sattributesprocessor` available in Agent running in OTel mode
  NOTICE.txt
  changelog/fragments/1717939159-add-k8sattributesprocessor.yaml
  go.mod
  go.sum
  internal/pkg/otel/README.md
  internal/pkg/otel/components.go
Labels: Team:Elastic-Agent-Control-Plane, backport-skip

#4898 Add Ubuntu 24.04 to integration testing.
  pkg/testing/multipass/provisioner.go
  pkg/testing/ogc/supported.go
  pkg/testing/runner/supported.go
  pkg/testing/runner/supported_test.go
Labels: Team:Elastic-Agent-Control-Plane, backport-skip, skip-changelog

#4621 Add `unprivileged` and `privileged` subcommand to Elastic Agent
  changelog/fragments/1715266075-Add-unprivileged-and-privileged-switch-commands.yaml
  internal/pkg/agent/cmd/common.go
  internal/pkg/agent/cmd/enroll_cmd.go
  internal/pkg/agent/cmd/inspect.go
  internal/pkg/agent/cmd/install.go
  internal/pkg/agent/cmd/privileged.go
  internal/pkg/agent/cmd/unprivileged.go
  internal/pkg/agent/install/install.go
  internal/pkg/agent/install/install_unix.go
  internal/pkg/agent/install/install_windows.go
  internal/pkg/agent/install/prereq.go
  internal/pkg/agent/install/switch.go
  internal/pkg/agent/install/switch_darwin.go
  internal/pkg/agent/install/switch_other.go
  internal/pkg/agent/install/uninstall.go
  internal/pkg/agent/perms/windows.go
  pkg/component/component.go
  pkg/component/component_test.go
  pkg/component/load.go
  pkg/component/platforms.go
  pkg/control/v2/client/wait/agent.go
  pkg/control/v2/client/wait/common.go
  testing/integration/endpoint_security_test.go
  testing/integration/switch_privileged_test.go
  testing/integration/switch_unprivileged_test.go
  testing/integration/upgrade_rollback_test.go
Labels: Team:Elastic-Agent-Control-Plane, backport-skip

#4894 docs: update docs versions 8.14.1
  version/docs/version.asciidoc
Labels: Team:Automation, release, docs, in progress, skip-changelog

#4770 Apply mTLS config from policy
  changelog/fragments/1716490302-Load-fleet.ssl.certificate_authorities-from-agent-policy.yaml
  changelog/fragments/1716490372-Load-fleet.ssl.certificate-and-fleet.ssl.key-from-agent-policy.yaml
  internal/pkg/agent/application/actions/handlers/handler_action_policy_change.go
  internal/pkg/agent/application/actions/handlers/handler_action_policy_change_test.go
  internal/pkg/agent/application/dispatcher/dispatcher.go
  internal/pkg/remote/config.go
  pkg/testing/fixture_install.go
  testing/fleetservertest/checkin.go
  testing/fleetservertest/fleetserver_test.go
  testing/integration/proxy_url_test.go
  testing/proxytest/proxytest.go
Labels: enhancement, Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent, backport-skip

#4910 Fix issue with log_writer panic on line with all spaces
  changelog/fragments/1718138001-Fix-possible-crash-in-reading-component-logs.yaml
  pkg/component/runtime/log_writer.go
  pkg/component/runtime/log_writer_test.go
Labels: Team:Elastic-Agent-Control-Plane, backport-v8.14.0

#4846 [windows] if `elastic-agent run` fails, log error to Application EventLog
  changelog/fragments/1717516439-Capture-early-errors-on-Windows.yaml
  internal/pkg/agent/cmd/run.go
  internal/pkg/agent/cmd/run_unix.go
  internal/pkg/agent/cmd/run_windows.go
  internal/pkg/agent/install/install_windows.go
  internal/pkg/agent/install/uninstall.go
Labels: enhancement, Team:Elastic-Agent-Control-Plane, backport-skip

#4911 Add `IsStandalone()` to agent info, report management mode to gRPC
  internal/pkg/agent/application/coordinator/diagnostics_test.go
  internal/pkg/agent/application/info/agent_id.go
  internal/pkg/agent/application/info/agent_id_test.go
  internal/pkg/agent/application/info/agent_info.go
  pkg/component/runtime/runtime_comm.go
  pkg/component/runtime/runtime_comm_test.go
  testing/mocks/internal_/pkg/agent/application/info/agent_mock.go
Labels: Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent-Data-Plane, backport-skip, skip-changelog

#4906 [CI] Monorepo diff plugin for integration tests
  .buildkite/pipeline.yml
  .buildkite/pull-requests.json
Labels: enhancement, skip-changelog, Team:Ingest-EngProd, backport-v8.14.0

#4838 Fix log level value reported by Agent to Fleet
  internal/pkg/agent/application/gateway/fleet/fleet_gateway.go
  internal/pkg/agent/application/info/agent_metadata_test.go
  pkg/testing/fixture.go
  testing/integration/log_level_test.go
Labels: bug, Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent, backport-skip, skip-changelog

#4859 Repoint kardianos/service to fork elastic/kardianos-service
  NOTICE.txt
  go.mod
  go.sum
  internal/pkg/agent/application/upgrade/service_update_linux.go
  internal/pkg/agent/install/install.go
  internal/pkg/agent/install/installed.go
  internal/pkg/agent/install/svc.go
  internal/pkg/agent/install/switch.go
  internal/pkg/agent/install/uninstall.go
  pkg/component/runtime/service.go
  testing/integration/upgrade_rollback_test.go
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog, chore, backport-v8.14.0

#4921 Increase removal timeout when uninstall
  changelog/fragments/1718268915-increase-remove-timeout.yaml
  internal/pkg/agent/install/uninstall.go
Labels: bug, Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent, backport-v8.14.0

#4895 [Release] Update version to 8.14.2
  deploy/kubernetes/elastic-agent-managed-kubernetes.yaml
  deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml
  version/version.go
Labels: Team:Automation, release, skip-changelog

#4928 Revert "Repoint kardianos/service to fork elastic/kardianos-service"
  NOTICE.txt
  go.mod
  go.sum
  internal/pkg/agent/application/upgrade/service_update_linux.go
  internal/pkg/agent/install/install.go
  internal/pkg/agent/install/installed.go
  internal/pkg/agent/install/svc.go
  internal/pkg/agent/install/switch.go
  internal/pkg/agent/install/uninstall.go
  pkg/component/runtime/service.go
  testing/integration/upgrade_rollback_test.go
Labels: backport-skip, skip-changelog

#4938 Revert "Fix log level value reported by Agent to Fleet"
  internal/pkg/agent/application/gateway/fleet/fleet_gateway.go
  internal/pkg/agent/application/info/agent_metadata_test.go
  pkg/testing/fixture.go
  testing/integration/log_level_test.go
Labels: Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent, backport-skip, skip-changelog

#4789 Allow agent to monitor endpoint
  changelog/fragments/1716320508-add-endpoint-monitoring.yaml
  internal/pkg/agent/application/coordinator/coordinator.go
  internal/pkg/agent/application/coordinator/coordinator_state.go
  internal/pkg/agent/application/coordinator/coordinator_test.go
  internal/pkg/agent/application/coordinator/coordinator_unit_test.go
  internal/pkg/agent/application/coordinator/diagnostics_test.go
  internal/pkg/agent/application/monitoring/v1_monitor.go
  internal/pkg/agent/application/monitoring/v1_monitor_test.go
  internal/pkg/agent/cmd/inspect.go
  internal/pkg/agent/install/uninstall.go
  pkg/component/component.go
  pkg/component/component_test.go
  pkg/component/runtime/runtime_comm.go
  pkg/component/runtime/state.go
  testing/integration/endpoint_security_test.go
  testing/integration/endpoint_test_tools.go
  testing/integration/monitoring_endpoint_test.go
Labels: Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent, backport-skip

#4811 Add Resource Detection processor to OTel mode
  NOTICE.txt
  changelog/fragments/1716543099-add-otel-resource-detection-processor.yaml
  dev-tools/notice/overrides.json
  dev-tools/notice/rules.json
  go.mod
  go.sum
  internal/pkg/otel/README.md
  internal/pkg/otel/components.go
  internal/pkg/otel/testdata/all-components.yml
Labels: enhancement, Team:Elastic-Agent-Control-Plane, backport-skip

#4943 [CI] Disabled Github triggers for extended testing
  catalog-info.yaml
Labels: enhancement, backport-skip, skip-changelog, Team:Ingest-EngProd

#4940 refactor: drop golang.org/x/exp dependency
  NOTICE.txt
  go.mod
  internal/pkg/agent/application/upgrade/artifact/config_test.go
Labels: enhancement, Team:Elastic-Agent-Control-Plane, backport-skip, skip-changelog

#4912 simplify packaging pre-requisites
  README.md
Labels: Team:Elastic-Agent-Control-Plane, backport-skip, docs, skip-changelog

#4941 Revert "Revert "Fix log level value reported by Agent to Fleet (#4838)" (#4938)"
  internal/pkg/agent/application/gateway/fleet/fleet_gateway.go
  internal/pkg/agent/application/info/agent_metadata_test.go
  testing/integration/log_level_test.go
Labels: Team:Elastic-Agent-Control-Plane, backport-skip, skip-changelog

#4949 Allow bot triggered PRs to run CI
  .buildkite/pull-requests.json
Labels: backport-skip, skip-changelog, ci

#4946 Add conn param and conn-skip flag to diagnostics command
  changelog/fragments/1718660806-Add-diagnostics-skip-conn-flag.yaml
  control_v2.proto
  internal/pkg/agent/cmd/diagnostics.go
  pkg/control/v1/proto/control_v1.pb.go
  pkg/control/v1/proto/control_v1_grpc.pb.go
  pkg/control/v2/cproto/control_v2.pb.go
  pkg/control/v2/cproto/control_v2_grpc.pb.go
Labels: enhancement, Team:Elastic-Agent-Control-Plane, backport-skip

#4954 Set correct org and team tags to integration tests resources
  pkg/testing/ess/statful_provisioner.go
  pkg/testing/ogc/provisioner.go
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog, chore, backport-v8.13.0, backport-v8.14.0

#4908 Added k8s components to otel distribution
  NOTICE.txt
  go.mod
  go.sum
  internal/pkg/agent/cmd/cmd_test.go
  internal/pkg/agent/cmd/common.go
  internal/pkg/agent/cmd/otel.go
  internal/pkg/agent/cmd/otel_flags.go
  internal/pkg/agent/cmd/otel_flags_test.go
  internal/pkg/agent/cmd/otel_windows.go
  internal/pkg/agent/cmd/otel_windows_test.go
  internal/pkg/agent/cmd/validate.go
  internal/pkg/agent/cmd/validate_test.go
  internal/pkg/otel/README.md
  internal/pkg/otel/components.go
  internal/pkg/otel/config_file_provider.go
  internal/pkg/otel/config_file_provider_test.go
  internal/pkg/otel/run.go
  internal/pkg/otel/run_test.go
  internal/pkg/otel/testdata/all-components.yml
  internal/pkg/otel/validate.go
Labels: Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent, backport-skip, skip-changelog

#4961 Introduce agent.monitoring.metrics_period
  _meta/config/common.p2.yml.tmpl
  _meta/config/common.reference.p2.yml.tmpl
  _meta/config/elastic-agent.docker.yml.tmpl
  changelog/fragments/1718818524-support-monitoring-metrics-interval.yaml
  elastic-agent.docker.yml
  elastic-agent.reference.yml
  elastic-agent.yml
  internal/pkg/agent/application/coordinator/diagnostics_test.go
  internal/pkg/agent/application/monitoring/v1_monitor.go
  internal/pkg/agent/application/monitoring/v1_monitor_test.go
  internal/pkg/core/monitoring/config/config.go
Labels: enhancement, Team:Elastic-Agent-Control-Plane, backport-skip

#4964 Remove now unused Beat spec files
  pkg/component/component_test.go
  pkg/component/load_test.go
  specs/auditbeat.spec.yml
  specs/heartbeat.spec.yml
  specs/metricbeat.spec.yml
  specs/osquerybeat.spec.yml
  specs/packetbeat.spec.yml
  specs/testbeat.spec.yml
Labels: Team:Elastic-Agent-Control-Plane, backport-skip, skip-changelog

#4822 Allow installing a second agent on the same machine for development
  README.md
  internal/pkg/agent/application/paths/common.go
  internal/pkg/agent/application/paths/common_namespace.go
  internal/pkg/agent/application/paths/common_namespace_test.go
  internal/pkg/agent/application/paths/paths_darwin.go
  internal/pkg/agent/application/paths/paths_linux.go
  internal/pkg/agent/application/paths/paths_unix.go
  internal/pkg/agent/application/paths/paths_windows.go
  internal/pkg/agent/application/reexec/reexec_windows.go
  internal/pkg/agent/application/upgrade/service_update_linux.go
  internal/pkg/agent/application/upgrade/service_update_linux_test.go
  internal/pkg/agent/cmd/enroll_cmd.go
  internal/pkg/agent/cmd/install.go
  internal/pkg/agent/cmd/run.go
  internal/pkg/agent/cmd/run_windows.go
  internal/pkg/agent/configuration/grpc.go
  internal/pkg/agent/install/install.go
  internal/pkg/agent/install/install_windows.go
  internal/pkg/agent/install/svc.go
  internal/pkg/agent/install/switch.go
  internal/pkg/agent/install/uninstall.go
  magefile.go
  pkg/testing/fixture.go
  pkg/testing/fixture_install.go
  testing/installtest/checks.go
  testing/installtest/checks_unix.go
  testing/installtest/checks_windows.go
  testing/integration/install_privileged_test.go
  testing/integration/install_test.go
  testing/integration/logs_ingestion_test.go
  testing/integration/switch_privileged_test.go
  testing/integration/switch_unprivileged_test.go
  testing/upgradetest/upgrader.go
Labels: Team:Elastic-Agent-Control-Plane, backport-skip, skip-changelog

#4909 Ensure socket path is < 104 characters when STATE_PATH is set.
  changelog/fragments/1718226176-Ensure.yaml
  internal/pkg/agent/cmd/container.go
  testing/integration/container_cmd_test.go
Labels: Team:Elastic-Agent-Control-Plane, backport-skip

#4983 Update Elastic Agent Ironbank Docker image to use ubi 9.4
  dev-tools/packaging/templates/ironbank/Dockerfile.tmpl
Labels: Team:Elastic-Agent-Control-Plane, backport-skip, skip-changelog

#4968 Add Elastic Infra Metrics processor to `otel` mode
  NOTICE.txt
  changelog/fragments/1718863753-otel-add-elastic-infra-metrics-processor.yaml
  go.mod
  go.sum
  internal/pkg/otel/README.md
  internal/pkg/otel/components.go
  internal/pkg/otel/testdata/all-components.yml
  magefile.go
Labels: enhancement, Team:Elastic-Agent-Control-Plane, backport-skip

#4977 Added `httpcheckreceiver`, `otlphttpexporter` and `spanmetricsconnector`
  NOTICE.txt
  go.mod
  go.sum
  internal/pkg/otel/README.md
  internal/pkg/otel/components.go
  internal/pkg/otel/templates/README.md.tmpl
  internal/pkg/otel/testdata/all-components.yml
  magefile.go
Labels: enhancement, Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent, Agent, skip-changelog, backport-v8.14.0

#4957 [CI] Integration tests matrix pipeline resource
  catalog-info.yaml
Labels: enhancement, Team:Elastic-Agent-Control-Plane, backport-skip, skip-changelog, Team:Ingest-EngProd

#4970 [CI] Relaxed permissions for extended testing pipeline
  catalog-info.yaml
Labels: enhancement, skip-changelog, Team:Ingest-EngProd, backport-v8.14.0

#4986 Remove unneeded `Infof` line in runtime
  pkg/component/runtime/runtime_comm.go
Labels: Team:Elastic-Agent-Control-Plane, backport-skip, skip-changelog

#4182 [Packaging] Remove unused section from packing spec
  dev-tools/packaging/packages.yml
Labels: Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent, Cleanup, skip-changelog, backport-v8.12.0

#4996 Make `mage integration:auth` work again
  magefile.go
  pkg/testing/ess/users.go
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog, chore, backport-v8.14.0

#4959 [CI] Integration tests matrix pipeline
  .buildkite/hooks/pre-command
  .buildkite/hooks/pre-exit
  .buildkite/pipeline.integration-test-matrix.yml
  pkg/testing/runner/supported.go
Labels: enhancement, Team:Elastic-Agent-Control-Plane, skip-changelog, Team:Ingest-EngProd, backport-v8.14.0

#4754 Adding kustomize templates for k8s onboarding
  .buildkite/scripts/steps/sync-k8s.sh
  changelog/fragments/1715773969-kustomize-onboarding.yaml
  deploy/kubernetes/Makefile
  deploy/kubernetes/elastic-agent-kustomize/default/README.md
  deploy/kubernetes/elastic-agent-kustomize/default/elastic-agent-managed/base/elastic-agent-managed-daemonset.yaml
  deploy/kubernetes/elastic-agent-kustomize/default/elastic-agent-managed/base/kustomization.yaml
  deploy/kubernetes/elastic-agent-kustomize/default/elastic-agent-managed/environmental-variables-remove.yaml
  deploy/kubernetes/elastic-agent-kustomize/default/elastic-agent-managed/fleet-enrollment-token-patch.yaml
  deploy/kubernetes/elastic-agent-kustomize/default/elastic-agent-managed/kustomization.yaml
  deploy/kubernetes/elastic-agent-kustomize/default/elastic-agent-standalone/api-key-patch.yaml
  deploy/kubernetes/elastic-agent-kustomize/default/elastic-agent-standalone/base/elastic-agent-standalone-daemonset-configmap.yaml
  deploy/kubernetes/elastic-agent-kustomize/default/elastic-agent-standalone/base/elastic-agent-standalone-daemonset.yaml
  deploy/kubernetes/elastic-agent-kustomize/default/elastic-agent-standalone/environmental-variables-remove.yaml
  deploy/kubernetes/elastic-agent-kustomize/default/elastic-agent-standalone/kustomization.yaml
  deploy/kubernetes/elastic-agent-kustomize/ksm-autosharding/elastic-agent-managed/base/elastic-agent-managed-daemonset.yaml
  deploy/kubernetes/elastic-agent-kustomize/ksm-autosharding/elastic-agent-managed/extra/elastic-agent-managed-statefulset.yaml
  deploy/kubernetes/elastic-agent-kustomize/ksm-autosharding/elastic-agent-standalone/base/elastic-agent-standalone-daemonset.yaml
  deploy/kubernetes/elastic-agent-kustomize/ksm-autosharding/elastic-agent-standalone/extra/elastic-agent-standalone-statefulset.yaml
  deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml
  deploy/kubernetes/elastic-agent-standalone/elastic-agent-standalone-daemonset-configmap.yaml
  deploy/kubernetes/elastic-agent-standalone/elastic-agent-standalone-daemonset.yaml
Labels: Team:Elastic-Agent-Control-Plane, Team:Cloudnative-Monitoring, backport-v8.14.0

#4975 [Kubernetes Provider] Fix namespace filter on pod and service watchers
  changelog/fragments/1718953844-fix-namespace-filter-on-watchers.yaml
  internal/pkg/composable/providers/kubernetes/pod.go
  internal/pkg/composable/providers/kubernetes/service.go
Labels: Team:Elastic-Agent-Control-Plane, Team:Cloudnative-Monitoring, backport-skip

#4441 Fix and refactor the state store
  changelog/fragments/1712067343-fix-state-store.yaml
  internal/pkg/agent/application/actions/handlers/handler_action_cancel.go
  internal/pkg/agent/application/actions/handlers/handler_action_diagnostics.go
  internal/pkg/agent/application/actions/handlers/handler_action_diagnostics_test.go
  internal/pkg/agent/application/actions/handlers/handler_action_policy_change.go
  internal/pkg/agent/application/actions/handlers/handler_action_policy_change_test.go
  internal/pkg/agent/application/actions/handlers/handler_action_settings.go
  internal/pkg/agent/application/actions/handlers/handler_action_settings_test.go
  internal/pkg/agent/application/actions/handlers/handler_action_unenroll.go
  internal/pkg/agent/application/actions/handlers/handler_action_upgrade.go
  internal/pkg/agent/application/actions/handlers/handler_action_upgrade_test.go
  internal/pkg/agent/application/dispatcher/dispatcher.go
  internal/pkg/agent/application/dispatcher/dispatcher_test.go
  internal/pkg/agent/application/gateway/fleet/fleet_gateway.go
  internal/pkg/agent/application/managed_mode.go
  internal/pkg/agent/application/paths/files.go
  internal/pkg/agent/application/upgrade/step_mark.go
  internal/pkg/agent/cmd/run.go
  internal/pkg/agent/protection/action.go
  internal/pkg/agent/protection/action_test.go
  internal/pkg/agent/storage/encrypted_disk_store.go
  internal/pkg/agent/storage/storage.go
  internal/pkg/agent/storage/store/action_store.go
  internal/pkg/agent/storage/store/action_store_test.go
  internal/pkg/agent/storage/store/internal/migrations/migrations.go
  internal/pkg/agent/storage/store/migrations.go
  internal/pkg/agent/storage/store/migrations_test.go
  internal/pkg/agent/storage/store/state_store.go
  internal/pkg/agent/storage/store/state_store_test.go
  internal/pkg/agent/storage/store/testdata/7.17.18-action_store_empty.yml
  internal/pkg/agent/storage/store/testdata/7.17.18-action_store_policy_change.yml
  internal/pkg/agent/storage/store/testdata/7.18.18-action_store_unenroll.yml
  internal/pkg/agent/storage/store/testdata/7.18.18-action_store_unknown.yml
  internal/pkg/agent/storage/store/testdata/8.0.0-action_policy_change.yml
  internal/pkg/agent/storage/store/testdata/8.0.0-action_unenroll.yml
  internal/pkg/agent/storage/store/testdata/8.0.0-action_unknown.yml
  internal/pkg/agent/storage/store/testdata/8.0.0-empty.yml
  internal/pkg/config/operations/inspector.go
  internal/pkg/fleetapi/ack_cmd_test.go
  internal/pkg/fleetapi/acker/fleet/fleet_acker_test.go
  internal/pkg/fleetapi/action.go
  internal/pkg/fleetapi/action_test.go
  internal/pkg/fleetapi/checkin_cmd_test.go
  internal/pkg/queue/actionqueue.go
  internal/pkg/queue/actionqueue_test.go
  testing/fleetservertest/fleetserver_test.go
Labels: bug, Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent, backport-skip

#5010 [Heartbeat] Upgrade node to latest LTS v18.20.3
  changelog/fragments/1719483857-Upgrade-NodeJS-to-LTS-18.20.3.yaml
  dev-tools/packaging/templates/docker/Dockerfile.elastic-agent.tmpl
Labels: Team:Elastic-Agent-Control-Plane, Cleanup, backport-v8.14.0

#4991 report privileged mode to gRPC
  pkg/component/runtime/runtime_comm.go
  pkg/component/runtime/runtime_comm_test.go
Labels: Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent, backport-skip, skip-changelog

#5002 [otel] Add basic configuration samples
  dev-tools/packaging/packages.yml
  internal/pkg/otel/samples/darwin/logs_hostmetrics.yml
  internal/pkg/otel/samples/darwin/logs_metrics_traces.yml
  internal/pkg/otel/samples/darwin/platformlogs.yml
  internal/pkg/otel/samples/darwin/platformlogs_hostmetrics.yml
  internal/pkg/otel/samples/linux/logs_hostmetrics.yml
  internal/pkg/otel/samples/linux/logs_metrics_traces.yml
  internal/pkg/otel/samples/linux/platformlogs.yml
  internal/pkg/otel/samples/linux/platformlogs_hostmetrics.yml
Labels: Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent, skip-changelog, backport-v8.14.0

#4965 "install -f" uses exec to uninstall an existing agent
  changelog/fragments/1718833116-Check-for-tamper-protection-when-uninstalling.yaml
  internal/pkg/agent/cmd/install.go
  internal/pkg/agent/install/install.go
  testing/integration/endpoint_security_test.go
Labels: bug, Team:Elastic-Agent-Control-Plane, backport-v8.14.0
