Repository elastic/elastic-agent, pull requests merged in 2024-11, with the labels that each got.

#5910 [Integration Testing Framework][ESS] Stop using deprecated ESS resource IDs
  pkg/testing/ess/create_deployment_csp_configuration.yaml
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog, Testing, backport-8.x

#5909 Trim spaces and add unit tests for `cli.confirm` function
  changelog/fragments/1730418510-confirm-test.yaml
  internal/pkg/cli/confirm.go
  internal/pkg/cli/confirm_test.go
Labels: bug, Team:Elastic-Agent-Control-Plane, Testing, backport-8.x

#5879 Assume installed agent on upgrade
  changelog/fragments/1730284359-assume-installed-agent-on-upgrade.yaml
  internal/pkg/agent/application/paths/paths_test.go
  internal/pkg/agent/application/paths/paths_unix.go
  internal/pkg/agent/application/paths/paths_windows.go
  internal/pkg/agent/application/upgrade/watcher.go
  internal/pkg/agent/cmd/run.go
  testing/upgradetest/watcher.go
Labels: bug, Team:Elastic-Agent-Control-Plane, backport-8.x, backport-8.16

#5831 Use a PodTemplate resource in the Helm Chart
  deploy/helm/elastic-agent/examples/eck/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/kubernetes-default/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/kubernetes-hints-autodiscover/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/kubernetes-only-logs/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/multiple-integrations/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/nginx-custom-integration/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/system-custom-auth-paths/rendered/manifest.yaml
  deploy/helm/elastic-agent/templates/agent/eck/_pod_template.tpl
  deploy/helm/elastic-agent/templates/agent/eck/_pod_template.yaml
  deploy/helm/elastic-agent/templates/agent/eck/daemonset.yaml
  deploy/helm/elastic-agent/templates/agent/eck/deployment.yaml
  deploy/helm/elastic-agent/templates/agent/eck/statefulset.yaml
  deploy/helm/elastic-agent/templates/agent/k8s/_pod_template.tpl
  deploy/helm/elastic-agent/templates/agent/k8s/_pod_template.yaml
  deploy/helm/elastic-agent/templates/agent/k8s/daemonset.yaml
  deploy/helm/elastic-agent/templates/agent/k8s/deployment.yaml
  deploy/helm/elastic-agent/templates/agent/k8s/statefulset.yaml
Labels: enhancement, Team:Elastic-Agent-Control-Plane, skip-changelog, backport-8.x, backport-8.16

#5889 Add integration tests using a proxy with mTLS for control plane with Elastic Defend installed
  pkg/testing/define/define.go
  pkg/testing/fixture.go
  pkg/testing/fixture_install.go
  pkg/testing/tools/tools.go
  testing/integration/endpoint_security_test.go
  testing/integration/endpoint_test_tools.go
  testing/proxytest/https.go
  testing/proxytest/proxytest.go
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog, backport-8.x, backport-8.16

#5939 [helm] derive the lease name from the release and preset names
  deploy/helm/elastic-agent/examples/eck/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/fleet-managed/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/kubernetes-default/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/kubernetes-hints-autodiscover/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/kubernetes-only-logs/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/multiple-integrations/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/nginx-custom-integration/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/system-custom-auth-paths/rendered/manifest.yaml
  deploy/helm/elastic-agent/templates/agent/_helpers.tpl
  deploy/helm/elastic-agent/values.yaml
Labels: enhancement, Team:Elastic-Agent-Control-Plane, skip-changelog, backport-8.x, backport-8.16

#5900 Introduce filter by group and dry-run for integration tests
  pkg/testing/define/define.go
  pkg/testing/define/define_flags.go
  pkg/testing/define/parser.go
  testing/integration/main_test.go
Labels: enhancement, Team:Elastic-Agent-Control-Plane, skip-changelog, backport-8.x

#5957 Add support of the new branch setup to the version update automation
  pkg/testing/tools/git/git.go
  pkg/testing/tools/git/git_test.go
Labels: bug, Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent, skip-changelog, backport-8.15, backport-8.x, backport-8.16

#5950 [proxytest] Wait all requests to finish before closing the server
  testing/proxytest/proxytest.go
Labels: Team:Elastic-Agent-Control-Plane, flaky-test, skip-changelog, backport-8.x, backport-8.16

#5864 Feature/4890 detect fail early upgrade
  changelog/fragments/1729971565-detect-fail-early-fleet-managed-cli-upgrade.yaml
  control_v2.proto
  internal/pkg/agent/application/coordinator/coordinator.go
  internal/pkg/agent/application/coordinator/coordinator_state.go
  internal/pkg/agent/application/info/agent_id.go
  internal/pkg/agent/cmd/upgrade.go
  internal/pkg/agent/cmd/upgrade_test.go
  pkg/control/v2/client/client.go
  pkg/control/v2/cproto/control_v2.pb.go
  pkg/control/v2/server/server.go
Labels: enhancement, Team:Elastic-Agent-Control-Plane, backport-8.x

#5979 Add go.mod full version support to updatecli
  .ci/updatecli/updatecli-bump-golang.yml
  go.mod
Labels: bug, Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent, backport-skip, skip-changelog, backport-8.x

#5981 [helm] agent preset replicas
  deploy/helm/elastic-agent/examples/README.md
  deploy/helm/elastic-agent/examples/kubernetes-default/README.md
  deploy/helm/elastic-agent/templates/agent/eck/deployment.yaml
  deploy/helm/elastic-agent/templates/agent/eck/statefulset.yaml
  deploy/helm/elastic-agent/templates/agent/k8s/deployment.yaml
  deploy/helm/elastic-agent/templates/agent/k8s/statefulset.yaml
Labels: bug, Team:Elastic-Agent-Control-Plane, skip-changelog, backport-8.x, backport-8.16

#5956 [CI] Buildkite integration tests: Run integration tests on ARM
  .buildkite/bk.integration.pipeline.yml
  .buildkite/scripts/steps/ess_start.sh
  .buildkite/scripts/steps/integration_tests_tf_sudo.sh
  .buildkite/scripts/sudo-integration-tests.sh
  test_infra/ess/deployment.tf
Labels: enhancement, skip-changelog, Team:Ingest-EngProd, backport-8.x

#5992 [helm] add envFrom in agent preset
  deploy/helm/elastic-agent/templates/agent/eck/_pod_template.yaml
  deploy/helm/elastic-agent/templates/agent/k8s/_pod_template.yaml
  deploy/helm/elastic-agent/values.schema.json
Labels: enhancement, Team:Elastic-Agent-Control-Plane, skip-changelog, backport-8.x, backport-8.16

#6004 [helm] fix disabling cluster role and service account
  deploy/helm/elastic-agent/examples/nginx-custom-integration/README.md
  deploy/helm/elastic-agent/examples/nginx-custom-integration/agent-nginx-values.yaml
  deploy/helm/elastic-agent/examples/nginx-custom-integration/rendered/manifest.yaml
  deploy/helm/elastic-agent/templates/agent/cluster-role-binding.yaml
  deploy/helm/elastic-agent/templates/agent/eck/_pod_template.yaml
  deploy/helm/elastic-agent/templates/agent/k8s/_pod_template.yaml
  deploy/helm/elastic-agent/values.schema.json
Labels: bug, Team:Elastic-Agent-Control-Plane, skip-changelog, backport-8.x, backport-8.16

#6013 [CI] Run Buildkite integration tests by CRON
  catalog-info.yaml
Labels: enhancement, backport-skip, skip-changelog, Team:Ingest-EngProd

#6010 Buildkite integration tests: Windows 2022 Sudo tests
  .buildkite/bk.integration.pipeline.yml
  .buildkite/hooks/pre-command.ps1
  .buildkite/pipeline.yml
  .buildkite/scripts/install-go.ps1
  .buildkite/scripts/integration-tests.ps1
  .buildkite/scripts/steps/integration_tests_tf_sudo.sh
  .buildkite/scripts/sudo-integration-tests.sh
  .tool-versions
Labels: enhancement, Team:Elastic-Agent-Control-Plane, skip-changelog, Team:Ingest-EngProd, backport-8.x

#6019 [CI] Fix windows image prefix in the new integration pipeline
  .buildkite/bk.integration.pipeline.yml
Labels: bug, skip-changelog, Team:Ingest-EngProd, backport-8.x

#5987 Enhancement/5320 add integration test escape secrets in policy
  testing/integration/escaping_secrets_in_policy_test.go
Labels: enhancement, Team:Elastic-Agent-Control-Plane, skip-changelog, backport-8.x

#5817 [Release] Update version to 8.16.1
  deploy/helm/elastic-agent/examples/eck/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/fleet-managed/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/kubernetes-default/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/kubernetes-hints-autodiscover/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/kubernetes-only-logs/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/multiple-integrations/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/nginx-custom-integration/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/system-custom-auth-paths/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/user-cluster-role/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/user-service-account/rendered/manifest.yaml
  deploy/helm/elastic-agent/values.yaml
  deploy/kubernetes/elastic-agent-kustomize/default/elastic-agent-managed/base/elastic-agent-managed-daemonset.yaml
  deploy/kubernetes/elastic-agent-kustomize/default/elastic-agent-standalone/base/elastic-agent-standalone-daemonset.yaml
  deploy/kubernetes/elastic-agent-kustomize/ksm-autosharding/elastic-agent-managed/base/elastic-agent-managed-daemonset.yaml
  deploy/kubernetes/elastic-agent-kustomize/ksm-autosharding/elastic-agent-managed/extra/elastic-agent-managed-statefulset.yaml
  deploy/kubernetes/elastic-agent-kustomize/ksm-autosharding/elastic-agent-standalone/base/elastic-agent-standalone-daemonset.yaml
  deploy/kubernetes/elastic-agent-kustomize/ksm-autosharding/elastic-agent-standalone/extra/elastic-agent-standalone-statefulset.yaml
  deploy/kubernetes/elastic-agent-kustomize/ksm-hints/elastic-agent-standalone/kustomization.yaml
  deploy/kubernetes/elastic-agent-managed-kubernetes.yaml
  deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml
  version/version.go
Labels: Team:Elastic-Agent-Control-Plane, release, skip-changelog

#6031 fix: updated excluded error strings
  testing/integration/logs_ingestion_test.go
Labels: skip-changelog, backport-8.15, backport-8.x, backport-8.16

#6016 Remove endpoint security from linux containers
  changelog/fragments/1731517501-removed-endpoint-security-from-linux-containers.yaml
  dev-tools/mage/manifest/manifest.go
  dev-tools/mage/pkgcommon/pkgcommon-types.go
  dev-tools/mage/pkgtypes.go
  magefile.go
Labels: Team:Elastic-Agent-Control-Plane, backport-8.x

#6030 [CI] Buildkite integration tests: Windows ess retry script
  .buildkite/scripts/integration-tests.ps1
  .buildkite/scripts/steps/ess.ps1
Labels: enhancement, skip-changelog, Team:Ingest-EngProd, backport-8.x

#6011 Emit Pod data only for running Pods in the Kubernetes provider
  changelog/fragments/1731500837-pod-status-updates.yaml
  internal/pkg/composable/providers/kubernetes/pod.go
  internal/pkg/composable/providers/kubernetes/pod_test.go
Labels: enhancement, backport-8.15, backport-8.x, backport-8.16

#6044 Add RHEL8 rpm sudo integration tests step
  .buildkite/bk.integration.pipeline.yml
  .buildkite/scripts/sudo-integration-tests.sh
Labels: skip-changelog, Team:Ingest-EngProd, backport-8.x

#6061 Improve TestOtelFileProcessing integration test
  testing/integration/otel_test.go
Labels: enhancement, Team:Elastic-Agent-Control-Plane, skip-changelog, backport-8.x

#6064 [CI] Buildkite integration tests: Made AWS ARM instance size equal to GCP x86_64
  .buildkite/bk.integration.pipeline.yml
Labels: enhancement, skip-changelog, Team:Ingest-EngProd, backport-8.x

#6065 Skip notifyFleetAuditUninstall on Windows
  changelog/fragments/1731951823-Skip-notify-Fleet-on-Windows-uninstall.yaml
  internal/pkg/agent/install/uninstall.go
  testing/integration/install_test.go
Labels: Team:Elastic-Agent-Control-Plane, backport-8.x, backport-8.16

#6069 [CI] Fix logs integration test
  testing/integration/logs_ingestion_test.go
Labels: enhancement, Team:Elastic-Agent-Control-Plane, skip-changelog, backport-8.x, backport-8.16

#5919 [CI] MacOS 15 testing
  .buildkite/pipeline.yml
Labels: enhancement, skip-changelog, Team:Ingest-EngProd, backport-8.x, backport-8.16

#5999 Add failureThreshold to elastic-agent self-monitoring config
  internal/pkg/agent/application/coordinator/diagnostics_test.go
  internal/pkg/agent/application/monitoring/v1_monitor.go
  internal/pkg/agent/application/monitoring/v1_monitor_test.go
  internal/pkg/core/monitoring/config/config.go
Labels: bug, Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent, skip-changelog, backport-8.x

#6060 [helm] add lint checks for renderExamples
  deploy/helm/elastic-agent/templates/agent/cluster-role-binding.yaml
  deploy/helm/elastic-agent/templates/agent/cluster-role.yaml
  deploy/helm/elastic-agent/templates/agent/eck/daemonset.yaml
  deploy/helm/elastic-agent/templates/agent/eck/secret.yaml
  deploy/helm/elastic-agent/templates/agent/k8s/_secret.tpl
  deploy/helm/elastic-agent/templates/agent/k8s/secret.yaml
  deploy/helm/elastic-agent/templates/agent/service-account.yaml
  magefile.go
Labels: bug, Team:Elastic-Agent-Control-Plane, skip-changelog, backport-8.x, backport-8.16

#6079 [helm] remove unsupported Release fields for publishing the chart as EKS addon
  deploy/helm/elastic-agent/examples/eck/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/fleet-managed/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/kubernetes-default/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/kubernetes-hints-autodiscover/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/kubernetes-only-logs/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/multiple-integrations/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/nginx-custom-integration/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/system-custom-auth-paths/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/user-cluster-role/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/user-service-account/rendered/manifest.yaml
  deploy/helm/elastic-agent/templates/NOTES.txt
  deploy/helm/elastic-agent/templates/agent/_helpers.tpl
Labels: enhancement, Team:Elastic-Agent-Control-Plane, skip-changelog, backport-8.x, backport-8.16

#6058 Don't deepcopy AST when generating vars
  internal/pkg/agent/transpiler/ast.go
  internal/pkg/agent/transpiler/ast_test.go
  internal/pkg/agent/transpiler/vars.go
  internal/pkg/composable/controller.go
Labels: enhancement, Team:Elastic-Agent-Control-Plane, skip-changelog, backport-8.15, backport-8.x, backport-8.16

#6121 Temporarily pin versions for integration tests to `8.17.0`
  .buildkite/scripts/steps/beats_tests.sh
  .buildkite/scripts/steps/integration-package.sh
  .buildkite/scripts/steps/integration_tests.sh
  .buildkite/scripts/steps/k8s-extended-tests.sh
  testing/integration/upgrade_broken_package_test.go
Labels: Team:Elastic-Agent-Control-Plane, backport-skip, release, skip-changelog

#5990 [Kubernetes provider]Update kubernetes provider README
  changelog/fragments/1732005233-kubernetes-provider-readme.yaml
  internal/pkg/composable/providers/kubernetes/README.md
Labels: Team:Elastic-Agent-Control-Plane, Team:Cloudnative-Monitoring, backport-8.15, backport-8.x, backport-8.16

#6120 fix(6107): skipping escaping secrets in policy test because it is flaky
  testing/integration/escaping_secrets_in_policy_test.go
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog, skipped-test, backport-8.x

#6095 Elastic Defend cannot run in emulation
  changelog/fragments/1732110636-elastic-defend-cannot-run-in-emulation.yaml
  specs/endpoint-security.spec.yml
Labels: bug, Team:Elastic-Agent-Control-Plane, backport-8.x

#6126 mark and skip flaky TestOTelManager_Run
  internal/pkg/otel/manager/manager_test.go
Labels: Team:Elastic-Agent-Control-Plane, flaky-test, skip-changelog, Testing, skipped-test, backport-8.x

#6145 Added analytics plugin
  .buildkite/bk.integration.pipeline.yml
Labels: backport-skip, skip-changelog, ci, Team:Ingest-EngProd

#6146 [CI] Test improvement: propely collect hostnames for logging
  pkg/testing/tools/fleettools/fleet.go
Labels: enhancement, Team:Elastic-Agent-Control-Plane, skip-changelog, backport-8.x

#6153 [CI] Add BUILDKITE_ANALYTICS_TOKEN to buildkite integration tests
  .buildkite/hooks/pre-command
  .buildkite/scripts/integration-tests.ps1
  .buildkite/scripts/steps/integration_tests.sh
  .buildkite/scripts/steps/integration_tests_tf.sh
Labels: enhancement, backport-skip, skip-changelog, Team:Ingest-EngProd

#6068 re-enable otel subcommand on Windows
  changelog/fragments/1731962301-re-enable-otel-subcommand-on-Windows.yaml
  internal/pkg/agent/cmd/otel.go
  internal/pkg/agent/cmd/run.go
  internal/pkg/agent/cmd/validate_test.go
  testing/integration/otel_test.go
Labels: Team:Elastic-Agent-Control-Plane, backport-8.x

#6114 Store AST directly in provider mappings
  internal/pkg/agent/transpiler/ast.go
  internal/pkg/composable/benchmark_test.go
  internal/pkg/composable/controller.go
Labels: enhancement, Team:Elastic-Agent-Control-Plane, skip-changelog, backport-8.x, backport-8.16, backport-8.17

#6163 Hotfix BUILDKITE_ANALYTICS_TOKEN
  .buildkite/hooks/pre-command
  .buildkite/scripts/steps/integration_tests.sh
Labels: bug, backport-skip, skip-changelog, Team:Ingest-EngProd

#6160 Increase failure threshold for agent monitoring inputs from 2 to 5
  internal/pkg/agent/application/monitoring/v1_monitor.go
  internal/pkg/agent/application/monitoring/v1_monitor_test.go
Labels: bug, Team:Elastic-Agent-Control-Plane, skip-changelog, backport-8.x, backport-8.16, backport-8.17

#6003 Update catalog-info file with correct system property
  catalog-info.yaml
Labels: skip-changelog, Team:Ingest-EngProd, backport-8.x

#6075 Add 1 independent release into upgrade matrix
  pkg/testing/fetcher_artifact.go
  pkg/version/version_parser.go
  pkg/version/version_parser_test.go
  testing/integration/testdata/.upgrade-test-agent-versions.yml
  testing/upgradetest/versions.go
Labels: enhancement, Team:Elastic-Agent-Control-Plane, skip-changelog, backport-8.x
