Repository elastic/elastic-agent, pull requests merged in 2024-09, with the labels that each got.

#5393 Create mergify config for 8.x backports
  .mergify.yml
Labels: backport-skip, skip-changelog

#5375 Fix TestLogIngestionFleetManaged, TestDebLogIngestFleetManaged
  internal/pkg/agent/application/upgrade/upgrade.go
  pkg/testing/define/define.go
  pkg/testing/fixture.go
  pkg/testing/fixture_install.go
  pkg/testing/tools/estools/elasticsearch.go
  testing/integration/logs_ingestion_test.go
  testing/integration/upgrade_rollback_test.go
Labels: Team:Elastic-Agent, backport-skip, skip-changelog

#5385 Use buildkite test collector plugins for flaky tests analysis
  .buildkite/hooks/pre-command
  .buildkite/hooks/pre-exit
  .buildkite/integration.pipeline.yml
  .buildkite/scripts/unset-secrets.sh
Labels: backport-skip, skip-changelog

#5399 Skip eventlogfile test
  testing/integration/event_logging_test.go
Labels: backport-skip, skip-changelog, skipped-test

#5333 Avoid reporting empty version_info for components that just started
  testing/integration/package_version_test.go
Labels: Team:Elastic-Agent-Control-Plane, flaky-test, skip-changelog, backport-v8.15.0

#5408 [Flaky Test] TestComponentBuildHashInDiagnostics: save diagnostic and agent status on failure
  pkg/testing/fixture_install.go
  testing/integration/package_version_test.go
Labels: flaky-test, backport-skip, skip-changelog

#5355 refactor: replace pkg/errors with stdlib errors
  NOTICE.txt
  dev-tools/mage/build.go
  dev-tools/mage/config.go
  dev-tools/mage/fmt.go
  dev-tools/mage/gomod.go
  dev-tools/mage/integtest_docker.go
  dev-tools/mage/kubernetes/kuberemote.go
  dev-tools/mage/kubernetes/kubernetes.go
  dev-tools/mage/pkgdeps.go
  dev-tools/mage/platforms.go
  go.mod
  internal/pkg/agent/errors/error_test.go
  internal/pkg/crypto/io.go
  internal/pkg/remote/round_trippers.go
Labels: enhancement, Team:Elastic-Agent-Control-Plane, backport-skip, skip-changelog

#5323 Add Azure Asset Inventory definition to cloudbeat
  changelog/fragments/1724156595-add-cloudbeat-azure-asset-inventory.yaml
  specs/cloudbeat.spec.yml
Labels: enhancement, Team:Elastic-Agent-Control-Plane, backport-skip

#5369 Add `health_check` extension to bundled `otel.yml` file
  changelog/fragments/1724804905-otel-health-check.yaml
  otel.yml
Labels: bug, Team:Elastic-Agent-Control-Plane, backport-v8.15.0, opentelemetry

#5348 Add debug log for check-in miss
  pkg/component/runtime/command.go
Labels: enhancement, Team:Elastic-Agent-Control-Plane, backport-skip, skip-changelog

#5384 [testing/integration] make sure all unit are healthy for `agent_long_running_leak_test`
  testing/integration/agent_long_running_leak_test.go
Labels: enhancement, Team:Elastic-Agent-Control-Plane, skip-changelog, backport-v8.15.0

#5420 [Flaky Test] TestComponentBuildHashInDiagnostics improve agent state check
  testing/integration/package_version_test.go
Labels: flaky-test, skip-changelog, backport-v8.15.0, backport-v8.x

#5396 Upgrade mage from 1.14.0 to 1.15.0
  .buildkite/scripts/common.sh
  Makefile
Labels: Team:Elastic-Agent-Control-Plane, backport-skip, skip-changelog

#5405 Fix flaky test Test_runDispatcher/gateway_actions_passed
  internal/pkg/agent/application/managed_mode_test.go
Labels: Team:Elastic-Agent-Control-Plane, backport-skip, skip-changelog

#5364 Fix flaky test `TestActionDispatcher/Cancel_queued_action`
  internal/pkg/agent/application/dispatcher/dispatcher_test.go
Labels: Team:Elastic-Agent-Control-Plane, backport-skip, skip-changelog

#5366 Fix flaky test `TestActionDispatcher/Dispatch_multiple_events_returns_one_error`
  internal/pkg/agent/application/dispatcher/dispatcher_test.go
Labels: Team:Elastic-Agent-Control-Plane, backport-skip, skip-changelog

#5426 updatecli: use GITHUB_ACTOR instead
  .ci/updatecli/updatecli-bump-golang.yml
Labels: backport-skip, skip-changelog

#5400 use Stringer to get string values for eaclient Unit types
  internal/pkg/agent/application/gateway/fleet/fleet_gateway.go
Labels: Team:Elastic-Agent-Control-Plane, backport-skip, Cleanup, skip-changelog

#5027 Switch to PAT generated GH token
  .buildkite/scripts/steps/sync-k8s.sh
Labels: v7.17.0, skip-changelog, Team:Ingest-EngProd, backport-v8.14.0, backport-v8.15.0

#5392 Remove test binaries
  dev-tools/mage/target/common/clean.go
  magefile.go
Labels: Team:Elastic-Agent, backport-skip, skip-changelog

#5439 fix(updatecli): use values file
  .github/workflows/bump-golang.yml
Labels: backport-skip, skip-changelog

#5409 [Integration Test Framework] fix createTempDir and flaky tests
  internal/pkg/agent/application/actions/handlers/handler_action_upgrade_test.go
  pkg/testing/fixture.go
  testing/integration/event_logging_test.go
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog, backport-v8.15.0

#5346 Improve testing logger
  internal/pkg/agent/application/actions/handlers/handler_action_diagnostics_test.go
  internal/pkg/agent/application/actions/handlers/handler_action_policy_change_test.go
  internal/pkg/agent/application/actions/handlers/handler_action_settings_test.go
  internal/pkg/agent/application/apm_config_modifier_test.go
  internal/pkg/agent/application/application_test.go
  internal/pkg/agent/application/coordinator/coordinator_unit_test.go
  internal/pkg/agent/application/dispatcher/dispatcher_test.go
  internal/pkg/agent/application/gateway/fleet/fleet_gateway_test.go
  internal/pkg/agent/application/monitoring/reload/reload_test.go
  internal/pkg/agent/application/upgrade/artifact/config_test.go
  internal/pkg/agent/application/upgrade/artifact/download/fs/verifier_test.go
  internal/pkg/agent/application/upgrade/artifact/download/http/downloader_test.go
  internal/pkg/agent/application/upgrade/artifact/download/snapshot/downloader_test.go
  internal/pkg/agent/application/upgrade/artifact/download/verifier_test.go
  internal/pkg/agent/application/upgrade/marker_watcher_test.go
  internal/pkg/agent/application/upgrade/rollback_test.go
  internal/pkg/agent/application/upgrade/step_download_test.go
  internal/pkg/agent/application/upgrade/step_unpack_test.go
  internal/pkg/agent/application/upgrade/upgrade_test.go
  internal/pkg/agent/application/upgrade/watcher_test.go
  internal/pkg/agent/cmd/enroll_cmd_test.go
  internal/pkg/agent/cmd/watch_test.go
  internal/pkg/agent/storage/store/migrations_test.go
  internal/pkg/fleetapi/client/client_test.go
  pkg/component/runtime/manager_fake_input_test.go
  pkg/core/logger/loggertest/logger.go
  pkg/core/logger/loggertest/logger_test.go
  pkg/core/logger/testing.go
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog, Testing, backport-v8.15.0

#5429 Endpoint should be allowed to run on Windows Server 2012/2012R2
  changelog/fragments/1725483799-Endpoint-should-be-allowed-to-run-on-Windows-Server-2012.yaml
  specs/endpoint-security.spec.yml
Labels: enhancement, backport-skip

#5445 Fix TestStandaloneUpgradeRollback
  testing/integration/upgrade_rollback_test.go
  testing/upgradetest/upgrader.go
Labels: bug, Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent, backport-skip, skip-changelog

#5438 Fix state store SetAction panic
  changelog/fragments/1725523126-fix-state-store-SetAction-panic.yaml
  internal/pkg/agent/application/actions/handlers/handler_action_unenroll.go
  internal/pkg/agent/application/actions/handlers/handler_action_unenroll_test.go
  internal/pkg/agent/storage/store/state_store.go
  internal/pkg/agent/storage/store/state_store_test.go
Labels: bug, Team:Elastic-Agent-Control-Plane, backport-v8.15.0, backport-v8.x

#5450 Temporarily remove 7.17.X from the upgrade version list until integration tests are stable again
  .agent-versions.json
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog

#5471 Revert "Temporarily remove 7.17.X from the upgrade version list until integration tests are stable again (#5450)"
  .agent-versions.json
Labels: bug, Team:Elastic-Agent-Control-Plane, skip-changelog

#5452 set default log level when not set in policy
  changelog/fragments/1725620525-fix-default-log-level-policy-change.yaml
  internal/pkg/agent/application/actions/handlers/handler_action_policy_change.go
  internal/pkg/agent/application/actions/handlers/handler_action_settings.go
  internal/pkg/agent/application/actions/handlers/handler_action_settings_test.go
Labels: bug, backport-v8.15.0

#5476 [CI] Correct Go version when running the coverage report
  .buildkite/pipeline.yml
Labels: bug, skip-changelog, Team:Ingest-EngProd, backport-v8.15.0

#5329 Fixes issue where context cancelling could result in an invalid error being reported
  internal/pkg/agent/application/gateway/fleet/fleet_gateway.go
  testing/integration/endpoint_security_test.go
  testing/integration/linux_rpm_test.go
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog, backport-v8.15.0

#5458 Fix minor issues with the test framework guide
  docs/test-framework-dev-guide.md
Labels: Team:Elastic-Agent-Control-Plane, backport-skip, docs, skip-changelog

#5422 Add GCP Asset Inventory input to cloudbeat spec
  changelog/fragments/1725444403-add-cloudbeat-gcp-asset-inventory.yaml
  specs/cloudbeat.spec.yml
Labels: enhancement, backport-skip

#5479 mergify: automate the backport to 8.x when PRs targeting main
  .mergify.yml
Labels: backport-skip, skip-changelog

#5493 Run DRA steps for *.x branches as well
  .buildkite/pipeline.elastic-agent-binary-dra.yml
Labels: backport-skip, skip-changelog, backport-8.x, backport-8.15

#5496 mergify: add backport-v8.x always for main
  .mergify.yml
Labels: backport-skip, skip-changelog

#5500 Removed aged out snapshot version
  .agent-versions.json
Labels: skip-changelog, Testing, backport-v8.x, backport-8.15

#5483 mergify: support for backport-major.minor
  .mergify.yml
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog, backport-v8.x

#5475 Add `elastic-agent-wolfi-complete` Docker image
  dev-tools/mage/dockervariants.go
  dev-tools/packaging/packages.yml
  dev-tools/packaging/templates/docker/Dockerfile.elastic-agent.tmpl
Labels: Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent, backport-skip, skip-changelog, backport-v8.x, backport-8.x

#5512 Update the regex used to identify release branches to include 8.x
  pkg/testing/tools/git/git.go
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog, backport-v8.x, backport-8.x

#5394 Bump version to 9.0.0
  deploy/helm/elastic-agent/examples/eck/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/kubernetes-default/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/kubernetes-hints-autodiscover/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/kubernetes-only-logs/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/multiple-integrations/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/nginx-custom-integration/rendered/manifest.yaml
  deploy/helm/elastic-agent/values.yaml
  deploy/kubernetes/elastic-agent-kustomize/default/elastic-agent-managed/base/elastic-agent-managed-daemonset.yaml
  deploy/kubernetes/elastic-agent-kustomize/default/elastic-agent-standalone/base/elastic-agent-standalone-daemonset.yaml
  deploy/kubernetes/elastic-agent-kustomize/ksm-autosharding/elastic-agent-managed/base/elastic-agent-managed-daemonset.yaml
  deploy/kubernetes/elastic-agent-kustomize/ksm-autosharding/elastic-agent-managed/extra/elastic-agent-managed-statefulset.yaml
  deploy/kubernetes/elastic-agent-kustomize/ksm-autosharding/elastic-agent-standalone/base/elastic-agent-standalone-daemonset.yaml
  deploy/kubernetes/elastic-agent-kustomize/ksm-autosharding/elastic-agent-standalone/extra/elastic-agent-standalone-statefulset.yaml
  deploy/kubernetes/elastic-agent-managed-kubernetes.yaml
  deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml
  dev-tools/mage/manifest/manifest.go
  testing/upgradetest/versions_test.go
  version/version.go
Labels: Team:Elastic-Agent-Control-Plane, backport-skip, skip-changelog, backport-8.x

#5521 mergify: avoid label automation always
  .mergify.yml
Labels: backport-skip, skip-changelog, backport-8.x

#5517 mergify: replace queue action for queue_rules
  .mergify.yml
Labels: backport-skip, skip-changelog, backport-8.x

#5461 Improve the integration tests framework documentation
  docs/test-framework-dev-guide.md
Labels: Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent, backport-skip, skip-changelog, backport-8.x

#5557 Rename elastic-agent-wolfi-complete->elastic-agent-complete-wolfi
  dev-tools/mage/dockervariants.go
  dev-tools/packaging/packages.yml
Labels: Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent, skip-changelog, backport-8.x

#5563 Fix the complete image for Wolfi
  dev-tools/packaging/templates/docker/Dockerfile.elastic-agent.tmpl
Labels: Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent, skip-changelog, backport-8.x

#5565 Force agent version to 8.16.0 to fix CI
  .buildkite/scripts/steps/beats_tests.sh
  .buildkite/scripts/steps/integration-package.sh
  .buildkite/scripts/steps/integration_tests.sh
  .buildkite/scripts/steps/k8s-extended-tests.sh
  testing/integration/upgrade_broken_package_test.go
Labels: Team:Elastic-Agent-Control-Plane, backport-skip, skip-changelog, chore

#5564 Read Kibana version to build dashboard export folder
  pkg/testing/define/define.go
  testing/integration/beats_serverless_test.go
Labels: Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent, skip-changelog, backport-8.x

#5538 Update docker dependency to latest
  NOTICE.txt
  go.mod
  go.sum
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog, backport-8.15, backport-8.x

#5494 Add support for CLI flag for mTLS client certificate key passphrase
  changelog/fragments/1726040648-Add-support-for-passphrase-protected-mTLS-client-certificate-key.yaml
  internal/pkg/agent/application/actions/handlers/handler_action_policy_change_test.go
  internal/pkg/agent/cmd/enroll.go
  internal/pkg/agent/cmd/enroll_cmd.go
  internal/pkg/agent/cmd/enroll_cmd_test.go
Labels: Team:Elastic-Agent-Control-Plane, backport-8.x

#5522 Clarify purpose of `.agent-versions` file
  .agent-versions.json
  .github/workflows/bump-agent-versions.sh
  magefile.go
  testing/integration/testdata/.upgrade-test-agent-versions.yml
  testing/upgradetest/versions.go
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog, backport-8.x

#5556 Add pprofextension from the OTel-contrib
  NOTICE.txt
  changelog/fragments/1726739016-otel-pprof-extension.yaml
  go.mod
  go.sum
  internal/pkg/otel/README.md
  internal/pkg/otel/components.go
Labels: Team:Elastic-Agent-Control-Plane, backport-8.x

#5527 Change maintainer label to opencontainers in Dockerfile
  changelog/fragments/1726238750-change-deprecated-maintainer-label-in-Dockerfile-to-org.opencontainers.image.authors.yaml
  dev-tools/packaging/templates/docker/Dockerfile.elastic-agent.tmpl
Labels: Team:Elastic-Agent-Control-Plane, backport-skip, Cleanup

#5535 [Helm] Implement values.schema.json
  deploy/helm/elastic-agent/README.md
  deploy/helm/elastic-agent/README.md.gotmpl
  deploy/helm/elastic-agent/examples/kubernetes-default/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/kubernetes-hints-autodiscover/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/kubernetes-only-logs/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/multiple-integrations/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/nginx-custom-integration/rendered/manifest.yaml
  deploy/helm/elastic-agent/templates/agent/_helpers.tpl
  deploy/helm/elastic-agent/templates/agent/_outputs.tpl
  deploy/helm/elastic-agent/templates/agent/eck/_pod_template.tpl
  deploy/helm/elastic-agent/templates/agent/k8s/_pod_template.tpl
  deploy/helm/elastic-agent/values.schema.json
  deploy/helm/elastic-agent/values.yaml
  testing/integration/kubernetes_agent_standalone_test.go
Labels: enhancement, Team:Elastic-Agent-Control-Plane, skip-changelog, backport-8.x

#5547 Add ability to run the same tests with multi docker image variants
  .buildkite/integration.pipeline.yml
  .buildkite/pipeline.yml
  .buildkite/scripts/steps/k8s-extended-tests.sh
  docs/test-framework-dev-guide.md
  magefile.go
  pkg/testing/define/batch.go
  pkg/testing/define/requirements.go
  pkg/testing/kubernetes/image.go
  pkg/testing/kubernetes/kind/provisioner.go
  pkg/testing/kubernetes/supported.go
  pkg/testing/runner/config.go
  pkg/testing/runner/runner.go
  pkg/testing/runner/supported.go
  testing/integration/kubernetes_agent_standalone_test.go
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog, backport-8.x

#5562 Add pprof endpoints to the monitoring server if enabled
  changelog/fragments/1726740792-pprof-endpoint.yaml
  internal/pkg/agent/application/monitoring/server.go
  internal/pkg/agent/application/monitoring/server_test.go
Labels: bug, Team:Elastic-Agent-Control-Plane, backport-8.15, backport-8.x

#5616 Fix ownership of component specs in elastic-agent docker image
  dev-tools/packaging/templates/docker/Dockerfile.elastic-agent.tmpl
Labels: bug, Team:Elastic-Agent-Control-Plane, backport-skip, skip-changelog, backport-8.x

#5587 add kubernetes v1.31 to test matrix
  .buildkite/integration.pipeline.yml
  .buildkite/pipeline.yml
  docs/test-framework-dev-guide.md
  pkg/testing/kubernetes/supported.go
Labels: Team:Elastic-Agent-Data-Plane, Cleanup, skip-changelog, Team:obs-ds-hosted-services, backport-8.x

#5625 Skip flaky integration test - TestAPMConfig
  testing/integration/apm_propagation_test.go
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog, skipped-test, backport-8.x

#5391 Add ability to generate buildkite pipelines from integration testing framework
  magefile.go
  pkg/testing/buildkite/buildkite.go
  pkg/testing/buildkite/steps.go
  pkg/testing/common/batch.go
  pkg/testing/common/build.go
  pkg/testing/common/config.go
  pkg/testing/common/config_test.go
  pkg/testing/common/instance.go
  pkg/testing/common/logger.go
  pkg/testing/common/prefix_output.go
  pkg/testing/common/runner.go
  pkg/testing/common/stack.go
  pkg/testing/common/supported.go
  pkg/testing/ess/serverless.go
  pkg/testing/ess/serverless_provisioner.go
  pkg/testing/ess/serverless_test.go
  pkg/testing/ess/statful_provisioner.go
  pkg/testing/kubernetes/image.go
  pkg/testing/kubernetes/kind/provisioner.go
  pkg/testing/kubernetes/runner.go
  pkg/testing/linux/debian.go
  pkg/testing/linux/linux.go
  pkg/testing/linux/rhel.go
  pkg/testing/multipass/provisioner.go
  pkg/testing/ogc/provisioner.go
  pkg/testing/ogc/supported.go
  pkg/testing/runner/runner.go
  pkg/testing/runner/runner_test.go
  pkg/testing/ssh/client.go
  pkg/testing/ssh/file.go
  pkg/testing/ssh/interface.go
  pkg/testing/ssh/keys.go
  pkg/testing/supported/batch.go
  pkg/testing/supported/supported.go
  pkg/testing/supported/supported_test.go
  pkg/testing/windows/windows.go
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog, backport-8.x

#5610 Handle BUILDKITE_MESSAGE length in pre-command.ps1
  .buildkite/hooks/pre-command.ps1
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog, Team:Ingest-EngProd, backport-8.x

#5349 Add elastic-agent-service container to packaging
  .buildkite/integration.pipeline.yml
  dev-tools/mage/checksums.go
  dev-tools/mage/dockervariants.go
  dev-tools/mage/manifest/manifest.go
  dev-tools/mage/manifest/manifest_test.go
  dev-tools/packaging/files/linux/connectors.sh
  dev-tools/packaging/packages.yml
  dev-tools/packaging/templates/docker/Dockerfile.elastic-agent.tmpl
  magefile.go
  pkg/testing/kubernetes/supported.go
  specs/connectors.spec.yml
  testing/integration/kubernetes_agent_service_test.go
  testing/integration/kubernetes_agent_standalone_test.go
  testing/integration/testdata/connectors.agent.yml
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog, backport-8.x

#5586 [CI] Soft fail merge coverage reports step
  .buildkite/pipeline.yml
  .buildkite/scripts/steps/merge.sh
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog, backport-8.x
