Repository elastic/elastic-agent, pull requests merged in 2024-07, with the labels that each got.

#4942 add process dump after failed install
  pkg/testing/fixture.go
  pkg/testing/fixture_install.go
Labels: Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent, backport-skip, skip-changelog, Testing

#5008 Update K8s version to 1.30
  .buildkite/pipeline.yml
Labels: Team:Elastic-Agent-Control-Plane, backport-skip, skip-changelog

#5022 Updated ES Exporter to point to hash
  NOTICE.txt
  go.mod
  go.sum
  internal/pkg/otel/README.md
Labels: Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent, skip-changelog, backport-v8.14.0

#5017 Add retry to DownloadPackage
  pkg/testing/fetcher_artifact.go
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog, backport-v8.14.0

#5024 docs: fix typos and repetition in test framework dev guide
  docs/test-framework-dev-guide.md
Labels: Team:Elastic-Agent-Control-Plane, backport-skip, docs, skip-changelog

#4995 Write `container-paths.yml` into the `STATE_PATH`
  changelog/fragments/1719266012-Don't-fail-when-unable-to-write-container-paths.yaml
  internal/pkg/agent/cmd/container.go
  testing/integration/container_cmd_test.go
Labels: Team:Elastic-Agent-Control-Plane, backport-v8.14.0

#4885 [Ind Agent] Update packaging to properly package from manifest if given
  dev-tools/mage/checksums.go
  dev-tools/mage/manifest/manifest.go
  dev-tools/mage/manifest/manifest_test.go
  dev-tools/mage/manifest/manifestspecs.go
  dev-tools/mage/manifest/testdata/manifest-8.14.0+build202406201002.json
  dev-tools/mage/manifest/testdata/manifest-8.14.2-SNAPSHOT.json
  dev-tools/mage/manifest/testdata/manifest-8.14.2.json
  magefile.go
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog, backport-v8.14.0

#5034 Fix indefinite memory and CPU consumption when waiting fleet to be ready
  changelog/fragments/1719934992-Fix-indefinite-memory-and-CPU-consumption-when-waiting-fleet-to-be-ready.yaml
  internal/pkg/agent/cmd/enroll_cmd.go
  internal/pkg/agent/cmd/enroll_cmd_test.go
  internal/pkg/core/backoff/exponential.go
Labels: bug, Team:Elastic-Agent-Control-Plane, backport-v8.14.0

#5036 Update to golang 1.22.
  .go-version
  .golangci.yml
  Dockerfile
  Dockerfile.skaffold
  changelog/fragments/1712176768-Upgrade-to-Go-1.22.4.yaml
  go.mod
  version/docs/version.asciidoc
Labels: Team:Elastic-Agent-Control-Plane, backport-skip

#5035 Add ability to escape variable expansion in policy
  NOTICE.txt
  changelog/fragments/1719935188-Add-ability-to-escape-variables-in-policy.yaml
  go.mod
  go.sum
  internal/pkg/agent/transpiler/vars.go
  internal/pkg/agent/transpiler/vars_test.go
  internal/pkg/eql/Eql.g4
  internal/pkg/eql/eql_test.go
  internal/pkg/eql/expression.go
  internal/pkg/eql/parser/Eql.interp
  internal/pkg/eql/parser/Eql.tokens
  internal/pkg/eql/parser/EqlLexer.interp
  internal/pkg/eql/parser/EqlLexer.tokens
  internal/pkg/eql/parser/eql_base_listener.go
  internal/pkg/eql/parser/eql_base_visitor.go
  internal/pkg/eql/parser/eql_lexer.go
  internal/pkg/eql/parser/eql_listener.go
  internal/pkg/eql/parser/eql_parser.go
  internal/pkg/eql/parser/eql_visitor.go
  internal/pkg/eql/visitor.go
Labels: Team:Elastic-Agent-Control-Plane, backport-skip

#5030 Updated config files, removed redundant ones
  internal/pkg/otel/samples/darwin/logs_hostmetrics.yml
  internal/pkg/otel/samples/darwin/logs_metrics_traces.yml
  internal/pkg/otel/samples/darwin/platformlogs.yml
  internal/pkg/otel/samples/darwin/platformlogs_hostmetrics.yml
  internal/pkg/otel/samples/linux/logs_hostmetrics.yml
  internal/pkg/otel/samples/linux/logs_metrics_traces.yml
  internal/pkg/otel/samples/linux/platformlogs.yml
  internal/pkg/otel/samples/linux/platformlogs_hostmetrics.yml
Labels: Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent, skip-changelog, backport-v8.14.0

#5018 Conditional runtime server for otel mode
  internal/pkg/agent/application/application.go
  internal/pkg/agent/application/coordinator/coordinator_test.go
  pkg/component/runtime/manager.go
  pkg/component/runtime/manager_fake_input_test.go
  pkg/component/runtime/manager_test.go
  testing/integration/otel_test.go
Labels: bug, Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent, skip-changelog, backport-v8.14.0

#5048 Improve the enroll sub command help
  internal/pkg/agent/cmd/enroll.go
Labels: documentation, Team:Elastic-Agent-Control-Plane, skip-changelog, backport-v8.14.0

#4081 Remove artifacts from deprecated Elastic Endpoint in K8s project
  deploy/kubernetes/elastic-agent-kustomize/default/elastic-agent-managed/base/elastic-agent-managed-daemonset.yaml
  deploy/kubernetes/elastic-agent-kustomize/ksm-autosharding/elastic-agent-managed/base/elastic-agent-managed-daemonset.yaml
  deploy/kubernetes/elastic-agent-kustomize/ksm-autosharding/elastic-agent-managed/extra/elastic-agent-managed-statefulset.yaml
  deploy/kubernetes/elastic-agent-managed-kubernetes.yaml
  deploy/kubernetes/elastic-agent-managed/elastic-agent-managed-daemonset.yaml
Labels: Cleanup, skip-changelog, backport-v8.14.0

#5061 Updated es infra processor and dependabot rules to include further up…
  .github/dependabot.yml
  NOTICE.txt
  go.mod
  go.sum
  internal/pkg/otel/README.md
Labels: Team:Elastic-Agent, skip-changelog, backport-v8.14.0, backport-v8.15.0

#5070 Fix wrong binary for setting capabilities
  changelog/fragments/1720195309-add-agentbeat-capabilities.yaml
  dev-tools/packaging/templates/docker/Dockerfile.elastic-agent.tmpl
Labels: bug, Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent, backport-v8.14.0, backport-v8.15.0

#5050 Remove use of artifacts-api.elastic.co and its client
  dev-tools/mage/checksums.go
  dev-tools/mage/manifest/manifest.go
  dev-tools/mage/manifest/manifest_test.go
  dev-tools/mage/manifest/manifestspecs.go
  magefile.go
  pkg/testing/tools/artifacts_api.go
  pkg/testing/tools/artifacts_api_test.go
  testing/integration/upgrade_downgrade_test.go
Labels: Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent, backport-skip, skip-changelog

#5073 Set capabilities in the builder Docker image instead of the final
  changelog/fragments/1720209553-reduce-docker-size.yaml
  dev-tools/packaging/templates/docker/Dockerfile.elastic-agent.tmpl
Labels: enhancement, Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent, backport-v8.14.0, backport-v8.15.0

#5069 Add GH vault plugin bot to allowed list
  .buildkite/pull-requests.json
Labels: Team:Elastic-Agent-Control-Plane, backport-skip, skip-changelog

#5078 Updating elastic-agent image to version 8.14.3
  deploy/kubernetes/elastic-agent-kustomize/default/elastic-agent-managed/base/elastic-agent-managed-daemonset.yaml
  deploy/kubernetes/elastic-agent-kustomize/default/elastic-agent-standalone/base/elastic-agent-standalone-daemonset.yaml
  deploy/kubernetes/elastic-agent-kustomize/ksm-autosharding/elastic-agent-managed/base/elastic-agent-managed-daemonset.yaml
  deploy/kubernetes/elastic-agent-kustomize/ksm-autosharding/elastic-agent-managed/extra/elastic-agent-managed-statefulset.yaml
  deploy/kubernetes/elastic-agent-kustomize/ksm-autosharding/elastic-agent-standalone/base/elastic-agent-standalone-daemonset.yaml
  deploy/kubernetes/elastic-agent-kustomize/ksm-autosharding/elastic-agent-standalone/extra/elastic-agent-standalone-statefulset.yaml
Labels: backport-skip, skip-changelog

#5080 Updated elasticinframetricsprocessor to 0.7.0
  NOTICE.txt
  go.mod
  go.sum
  internal/pkg/otel/README.md
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog, backport-v8.14.0, backport-v8.15.0

#5044 Inject `HTTPS_PROXY/HTTP_PROXY` env var into endpoint elasticsearch output units as proxy_url
  changelog/fragments/1720034703-Inject-proxy_url-into-endpoint-elasticsearch-output.yaml
  internal/pkg/agent/application/application.go
  internal/pkg/agent/application/fleet_server_bootstrap.go
  internal/pkg/agent/application/inject_proxy_component_modifier.go
  internal/pkg/agent/application/inject_proxy_component_modifier_test.go
Labels: enhancement, Team:Elastic-Agent-Control-Plane, backport-v8.15.0

#5090 Update make check-ci command to support kustomize manifest updates
  Makefile
Labels: backport-skip, skip-changelog

#4939 feat: upgrade go agent to v2
  NOTICE.txt
  go.mod
  go.sum
  internal/pkg/agent/application/application.go
  internal/pkg/agent/application/coordinator/coordinator.go
  internal/pkg/agent/application/coordinator/coordinator_test.go
  internal/pkg/agent/application/dispatcher/dispatcher.go
  internal/pkg/agent/application/monitoring/server.go
  internal/pkg/agent/application/upgrade/artifact/download/composed/downloader.go
  internal/pkg/agent/application/upgrade/artifact/download/fs/downloader.go
  internal/pkg/agent/application/upgrade/step_download.go
  internal/pkg/agent/application/upgrade/upgrade.go
  internal/pkg/agent/cmd/enroll_cmd.go
  internal/pkg/agent/cmd/run.go
  internal/pkg/basecmd/version/cmd_test.go
  internal/pkg/fleetapi/ack_cmd.go
  internal/pkg/fleetapi/acker/fleet/fleet_acker.go
  internal/pkg/fleetapi/acker/lazy/lazy_acker.go
  pkg/component/fake/component/comp/apm.go
  pkg/component/runtime/manager.go
  pkg/component/runtime/manager_fake_input_test.go
  pkg/component/runtime/manager_test.go
  pkg/control/v1/server/server.go
  pkg/control/v2/control_test.go
  pkg/control/v2/server/server.go
Labels: enhancement, Team:Elastic-Agent-Control-Plane, backport-skip, skip-changelog

#5093 [otel] docs: fix spaces in README
  internal/pkg/otel/README.md
  internal/pkg/otel/templates/README.md.tmpl
Labels: Team:Elastic-Agent-Control-Plane, backport-skip, Cleanup, docs, skip-changelog

#5087 [otel] docs: Add links to components in OTel README
  internal/pkg/otel/README.md
  internal/pkg/otel/templates/README.md.tmpl
  magefile.go
Labels: Team:Elastic-Agent-Control-Plane, backport-skip, docs, skip-changelog

#4932 Update event logger configuration via Fleet and environment variable (container command)
  NOTICE.txt
  changelog/fragments/1719345278-container.yaml
  go.mod
  go.sum
  internal/pkg/agent/application/actions/handlers/handler_action_policy_change.go
  internal/pkg/agent/application/actions/handlers/handler_action_policy_change_test.go
  internal/pkg/agent/application/managed_mode.go
  internal/pkg/agent/cmd/container.go
  testing/integration/container_cmd_test.go
  testing/integration/event_logging_test.go
  testing/integration/logs_ingestion_test.go
Labels: Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent, backport-skip

#5102 refactor: replace gotest.tools assertions with testify
  NOTICE.txt
  go.mod
  go.sum
  internal/pkg/agent/application/gateway/fleet/fleet_gateway_test.go
  internal/pkg/agent/cmd/logs_test.go
  internal/pkg/agent/errors/error_test.go
  internal/pkg/capabilities/expr_test.go
  internal/pkg/core/monitoring/config/config_test.go
  testing/integration/pkgversion_common_test.go
Labels: Team:Elastic-Agent-Control-Plane, backport-skip, Cleanup, skip-changelog

#5086 [otel] Add integration test for logs ingestion
  testing/integration/otel_test.go
Labels: Team:Elastic-Agent-Control-Plane, backport-skip, skip-changelog, Testing

#5119 Remove Agent override version in integration tests
  .buildkite/scripts/steps/integration_tests.sh
  testing/integration/upgrade_broken_package_test.go
Labels: Team:Elastic-Agent-Control-Plane, backport-skip, skip-changelog, Testing

#5136 Fixing the hints autodiscovery configuration path in Elastic Agent Manifests
  deploy/kubernetes/creator_k8s_manifest.sh
  deploy/kubernetes/elastic-agent-kustomize/default/elastic-agent-standalone/base/elastic-agent-standalone-daemonset-configmap.yaml
  deploy/kubernetes/elastic-agent-kustomize/default/elastic-agent-standalone/base/elastic-agent-standalone-ksm-daemonset-configmap.yaml
  deploy/kubernetes/elastic-agent-kustomize/ksm-autosharding/elastic-agent-standalone/base/elastic-agent-standalone-ksm-daemonset-configmap.yaml
  deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml
  deploy/kubernetes/elastic-agent-standalone/elastic-agent-standalone-daemonset-configmap.yaml
  deploy/kubernetes/elastic-agent-standalone/elastic-agent-standalone-ksm-daemonset-configmap.yaml
Labels: Team:Cloudnative-Monitoring, backport, backport-v8.14.0, backport-v8.15.0

#5129 [CI] Separated packaging step
  .buildkite/integration.pipeline.yml
  .buildkite/scripts/steps/integration-package.sh
  .buildkite/scripts/steps/integration_tests.sh
Labels: enhancement, skip-changelog, Team:Ingest-EngProd, backport-v8.14.0, backport-v8.15.0

#5140 Updating sync-k8s.sh test with correct order of commands
  .buildkite/scripts/steps/sync-k8s.sh
Labels: Team:Cloudnative-Monitoring, backport, skip-changelog, backport-v8.14.0, backport-v8.15.0

#5134 [8.15](backport #5087) [otel] docs: Add links to components in OTel README
  internal/pkg/otel/README.md
  internal/pkg/otel/templates/README.md.tmpl
  magefile.go
Labels: Team:Elastic-Agent-Control-Plane, backport

#5145 [CI] Automatic retries for integration tests
  .buildkite/integration.pipeline.yml
Labels: enhancement, skip-changelog, Team:Ingest-EngProd, backport-v8.14.0, backport-v8.15.0

#5165 Remove `set -x` from Buildkite scripts
  .buildkite/scripts/install-gh.sh
  .buildkite/scripts/steps/merge.sh
Labels: skip-changelog, backport-v8.15.0

#5162 Temporary skip TestEventLogOutputConfiguredViaFleet
  testing/integration/event_logging_test.go
Labels: Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent, skip-changelog, skipped-test, backport-v8.15.0

#5062 Make Wolfi a part of Docker packaging
  changelog/fragments/1720208209-add-docker-wolfi.yaml
  dev-tools/packaging/packages.yml
  dev-tools/packaging/templates/docker/Dockerfile.elastic-agent.tmpl
Labels: enhancement, Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent, backport-skip, Packaging

#5170 [CI] Revert integration tests retries
  .buildkite/integration.pipeline.yml
Labels: enhancement, backport-skip, skip-changelog, Team:Ingest-EngProd

#5097 Add unit tests for `$$` appearing within policy inputs
  internal/pkg/agent/application/actions/handlers/handler_action_policy_change_test.go
  internal/pkg/agent/transpiler/ast_test.go
  internal/pkg/agent/transpiler/vars_test.go
  internal/pkg/config/config_test.go
Labels: Team:Elastic-Agent-Control-Plane, backport-skip, technical debt, skip-changelog

#5180 [CI] Fix DRA variables
  .buildkite/pipeline.elastic-agent-package.yml
Labels: enhancement, skip-changelog, Team:Ingest-EngProd, backport-v8.14.0, backport-v8.15.0

#5118 Fix issue with getting ownership on Windows
  changelog/fragments/1720713910-Fix-issue-with-Windows-install-when-user-has-no-home-directory.yaml
  internal/pkg/agent/cmd/enroll_unix.go
  internal/pkg/agent/cmd/run.go
  internal/pkg/agent/install/install_test.go
  internal/pkg/agent/install/uninstall.go
  internal/pkg/agent/install/uninstall_test.go
  internal/pkg/agent/perms/opts.go
  internal/pkg/agent/perms/unix.go
  internal/pkg/agent/perms/windows.go
  internal/pkg/agent/vault/vault.go
  internal/pkg/agent/vault/vault_file_test.go
  internal/pkg/agent/vault/vault_options.go
  pkg/utils/perm_unix.go
  pkg/utils/perm_windows.go
Labels: Team:Elastic-Agent-Control-Plane, backport-v8.15.0

#5169 Small clean up of the fleet gateway "run" function implementation
  internal/pkg/agent/application/gateway/fleet/fleet_gateway.go
Labels: Team:Elastic-Agent-Control-Plane, backport-skip, Cleanup, skip-changelog

#5132 Require a valid version of github.com/openshift/api
  .golangci.yml
  NOTICE.txt
  go.mod
  go.sum
Labels: Team:Elastic-Agent-Control-Plane, backport-skip, skip-changelog

#5168 [CI] Add packaging step to integration matrix pipeline
  .buildkite/pipeline.integration-test-matrix.yml
Labels: enhancement, Team:Elastic-Agent-Control-Plane, backport-skip, skip-changelog, Team:Ingest-EngProd

#5191 use go-sysinfo v1.14.1 and elastic-agent-system-metrics v0.10.6
  NOTICE.txt
  changelog/fragments/1721910073-Fix-FQDN-being-lower-cased-for-.yaml
  go.mod
  go.sum
  internal/pkg/agent/application/info/agent_metadata.go
  internal/pkg/composable/providers/host/host.go
Labels: Team:Elastic-Agent-Control-Plane, backport-skip

#5201 Remove verbose debug log line.
  internal/pkg/agent/application/coordinator/coordinator.go
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog, backport-v8.14.0, backport-v8.15.0

#5197 Remove dependency on github.com/elastic/e2e-testing
  NOTICE.txt
  dev-tools/mage/downloads/_testresources/dra/snapshot_artifacts_test.json
  dev-tools/mage/downloads/_testresources/gcp/commits.json
  dev-tools/mage/downloads/_testresources/gcp/nextPageParam.json
  dev-tools/mage/downloads/_testresources/gcp/snapshots.json
  dev-tools/mage/downloads/buckets.go
  dev-tools/mage/downloads/buckets_test.go
  dev-tools/mage/downloads/curl.go
  dev-tools/mage/downloads/io.go
  dev-tools/mage/downloads/io_test.go
  dev-tools/mage/downloads/releases.go
  dev-tools/mage/downloads/releases_test.go
  dev-tools/mage/downloads/retry.go
  dev-tools/mage/downloads/utils.go
  dev-tools/mage/downloads/utils_test.go
  dev-tools/mage/downloads/versions.go
  dev-tools/mage/downloads/versions_test.go
  dev-tools/notice/overrides.json
  go.mod
  go.sum
  magefile.go
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog, chore, backport-v8.15.0

#4925 Extend agent container initialisation logic
  .buildkite/pipeline.yml
  NOTICE.txt
  changelog/fragments/1718273218-container-init-capabilities.yaml
  deploy/kubernetes/elastic-agent-kustomize/default/elastic-agent-standalone/base/elastic-agent-standalone-daemonset.yaml
  deploy/kubernetes/elastic-agent-kustomize/ksm-autosharding/elastic-agent-standalone/base/elastic-agent-standalone-daemonset.yaml
  deploy/kubernetes/elastic-agent-kustomize/ksm-autosharding/elastic-agent-standalone/extra/elastic-agent-standalone-statefulset.yaml
  deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml
  deploy/kubernetes/elastic-agent-standalone/elastic-agent-standalone-daemonset.yaml
  dev-tools/mage/gotest.go
  dev-tools/packaging/templates/docker/Dockerfile.elastic-agent.tmpl
  go.mod
  go.sum
  internal/pkg/agent/cmd/common.go
  internal/pkg/agent/cmd/container.go
  internal/pkg/agent/cmd/container_init_linux.go
  internal/pkg/agent/cmd/container_init_other.go
  internal/pkg/agent/cmd/container_init_test.go
  pkg/testing/kubernetes/image.go
  pkg/testing/kubernetes/kind/provisioner.go
  testing/integration/kubernetes_agent_standalone_test.go
  testing/kubernetes_inner/agent_paths_ownership_test.go
Labels: enhancement, Team:Elastic-Agent-Control-Plane, backport-skip

#5208 [tests][integration] fix monitoring test cases
  pkg/testing/fixture.go
  testing/integration/agent_long_running_leak_test.go
  testing/integration/monitoring_probe_preserve_text_cfg_test.go
  testing/integration/monitoring_probe_reload_test.go
Labels: Team:Elastic-Agent-Control-Plane, backport-skip, skip-changelog
