Repository elastic/elastic-agent, pull requests merged in 2025-08, with the labels that each got.

#9216 Update CODEOWNERS: remove ci-contractors
  .github/CODEOWNERS
Labels: skip-changelog, backport-active-all

#9244 skip: TestUpgradeAgentWithTamperProtectedEndpoint_DEB
  testing/integration/ess/endpoint_security_test.go
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog, backport-active-all

#9256 Bump EDOT .NET image tag
  deploy/helm/edot-collector/kube-stack/managed_otlp/values.yaml
  deploy/helm/edot-collector/kube-stack/values.yaml
Labels: enhancement, skip-changelog, backport-8.x, backport-9.0

#9266 [FIPS] Only consider versions available in ECH region for `TestUpgradeIntegrationsServer`
  testing/integration/ess/upgrade_integrations_server_test.go
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog, backport-8.19, Testing:run:TestUpgradeIntegrationsServer, backport-9.1

#9346 enhancement(5235): removed HTTPTransportSettings embedded struct field use from http downloader
  internal/pkg/agent/application/upgrade/artifact/download/http/downloader.go
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog, backport-active-all

#9198 [CI][FIPS] Reconfigure pipeline to use Staging GovCloud/FRH ESS environment
  .buildkite/bk.integration-fips.pipeline.yml
  .buildkite/scripts/steps/ess_start.sh
  .buildkite/scripts/steps/integration_tests_tf.sh
  test_infra/ess/deployment.tf
Labels: skip-changelog, backport-8.19, backport-9.1

#9436 Revert "[9.1][Automation] Bump VM Image version to 1755306060"
  .buildkite/bk.integration-fips.pipeline.yml
  .buildkite/bk.integration.pipeline.yml
  .buildkite/integration.pipeline.yml
  .buildkite/pipeline.yml
Labels: skip-changelog, ci

#9437 Revert "[9.0][Automation] Bump VM Image version to 1755306060"
  .buildkite/bk.integration.pipeline.yml
  .buildkite/integration.pipeline.yml
  .buildkite/pipeline.yml
Labels: skip-changelog, ci

#9439 Revert "[8.17][Automation] Bump VM Image version to 1755306060"
  .buildkite/bk.integration.pipeline.yml
  .buildkite/integration.pipeline.yml
  .buildkite/pipeline.yml
Labels: skip-changelog, ci

#9475 Revert "[main][Automation] Update versions"
  .package-version
  dev-tools/packaging/templates/linux/preinstall.sh.tmpl
  testing/integration/testdata/.upgrade-test-agent-versions.yml
Labels: skip-changelog

#9476 Revert "[8.19][Automation] Update versions"
  dev-tools/packaging/templates/linux/preinstall.sh.tmpl
  testing/integration/testdata/.upgrade-test-agent-versions.yml
Labels: skip-changelog

#9451 Add support for variable parser to handle `:` as default constant .
  changelog/fragments/1755544412-Fix-default-constant-support-in-output-configuration.yaml
  internal/pkg/agent/transpiler/vars.go
  internal/pkg/agent/transpiler/vars_test.go
Labels: Team:Elastic-Agent-Control-Plane, backport-8.x, backport-8.18, backport-9.0, backport-8.19, backport-9.1

#9224 Retry saving Agent information file (`fleet.enc`) on Windows
  changelog/fragments/1754346816-fleet-enc-save-retries.yaml
  internal/pkg/agent/application/actions/handlers/handler_action_policy_change.go
  internal/pkg/agent/application/actions/handlers/handler_helpers_other.go
  internal/pkg/agent/application/actions/handlers/handler_helpers_test.go
  internal/pkg/agent/application/actions/handlers/handler_helpers_windows.go
Labels: Team:Elastic-Agent-Control-Plane, backport-active-all

#9226 Verify download checksums during packaging
  dev-tools/mage/downloads/utils.go
  dev-tools/mage/downloads/utils_test.go
  dev-tools/mage/downloads/versions.go
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog, chore, backport-active-all

#9506 Add "backport-active-all" label to Dependabot-created PRs
  .github/dependabot.yml
Labels: backport-skip, skip-changelog, chore

#9594 Enroll options contains parsable URI after FromFleetConfig call
  internal/pkg/agent/application/coordinator/coordinator_unit_test.go
  internal/pkg/agent/application/enroll/options.go
  internal/pkg/agent/application/enroll/options_test.go
Labels: bug, Team:Elastic-Agent-Control-Plane, backport-skip, skip-changelog

#9610 Changelog for 8.19.3
  changelog/8.19.3.asciidoc
  changelog/8.19.3.yaml
  changelog/fragments/1753950420-adjust-endpoint-check-timeout.yaml
  changelog/fragments/1754346816-fleet-enc-save-retries.yaml
  changelog/fragments/1754944400-k8s-hints-env-vars-in-annotations.yaml
  changelog/fragments/1755059673-endpoint-28-not-fatal.yaml
  changelog/fragments/1755076749-fix-jitter-backoff-strategy-reset.yaml
  changelog/fragments/1755085444-update-otel-components-to-v0.130.0.yaml
  changelog/fragments/1755544412-Fix-default-constant-support-in-output-configuration.yaml
  changelog/fragments/1755547590-Upgrade-to-Go-1.24.6..yaml
  changelog/fragments/1755601979-deb-upgrade-stop-agent-service.yaml
Labels: release, docs, skip-changelog

#9607 Changelog 8.18.6
  changelog/8.18.6.asciidoc
  changelog/8.18.6.yaml
  changelog/fragments/1753950420-adjust-endpoint-check-timeout.yaml
  changelog/fragments/1754346816-fleet-enc-save-retries.yaml
  changelog/fragments/1754944400-k8s-hints-env-vars-in-annotations.yaml
  changelog/fragments/1755059673-endpoint-28-not-fatal.yaml
  changelog/fragments/1755076749-fix-jitter-backoff-strategy-reset.yaml
  changelog/fragments/1755547590-Upgrade-to-Go-1.24.6..yaml
  changelog/fragments/1755601979-deb-upgrade-stop-agent-service.yaml
Labels: release, docs, skip-changelog

#9565 Changelog for 9.1.3
  changelog/9.1.3.asciidoc
  changelog/9.1.3.yaml
  changelog/fragments/1753950420-adjust-endpoint-check-timeout.yaml
  changelog/fragments/1754346816-fleet-enc-save-retries.yaml
  changelog/fragments/1754944400-k8s-hints-env-vars-in-annotations.yaml
  changelog/fragments/1755059673-endpoint-28-not-fatal.yaml
  changelog/fragments/1755076749-fix-jitter-backoff-strategy-reset.yaml
  changelog/fragments/1755149089-update-otel-components-to-v0.130.0.yaml
  changelog/fragments/1755544412-Fix-default-constant-support-in-output-configuration.yaml
  changelog/fragments/1755547590-Upgrade-to-Go-1.24.6..yaml
  changelog/fragments/1755601979-deb-upgrade-stop-agent-service.yaml
Labels: release, docs, skip-changelog

#9630 Add a basic overview of Beats receivers and Hybrid Agent that explains how to test them
  docs/hybrid-agent-beats-receivers.md
  docs/images/hybrid-agent.png
Labels: skip-changelog, backport-8.19, backport-9.1

#9612 Add /readiness and /liveness when enrolling with the container
  changelog/fragments/1756325090-Fix-missing-liveness-healthcheck-during-container-enrollment.yaml
  internal/pkg/agent/application/monitoring/liveness.go
  internal/pkg/agent/application/monitoring/liveness_test.go
  internal/pkg/agent/application/monitoring/process.go
  internal/pkg/agent/application/monitoring/readiness.go
  internal/pkg/agent/application/monitoring/readiness_test.go
  internal/pkg/agent/application/monitoring/server.go
  internal/pkg/agent/application/monitoring/server_test.go
  internal/pkg/agent/application/monitoring/v1_monitor.go
  internal/pkg/agent/cmd/container.go
  internal/pkg/agent/cmd/run.go
Labels: Team:Elastic-Agent-Control-Plane, backport-active-all
