Repository elastic/elastic-agent, pull requests merged in 2025-04, with the labels that each got.

#7521 Followup to #6638: Added more integration tests and logging
  dev-tools/packaging/templates/linux/preinstall.sh.tmpl
  pkg/testing/fixture.go
  testing/integration/install_test.go
  testing/integration/linux_deb_test.go
  testing/integration/linux_rpm_test.go
  testing/integration/otel_test.go
Labels: bug, Team:Elastic-Agent-Control-Plane, skip-changelog, backport-active-9

#7629 [bug] do not panic when info.Metadata errors in FleetGateway execute
  changelog/fragments/1743421027-Fix-panic-during-shutdown-in-fleetgateway.yaml
  internal/pkg/agent/application/gateway/fleet/fleet_gateway.go
Labels: bug, Team:Elastic-Agent-Control-Plane, backport-active-all

#7670 Revert "Pinned broken CI images to the previous version"
  .buildkite/bk.integration.pipeline.yml
  .buildkite/pipeline.yml
Labels: skip-changelog

#7659 [Helm] allow additional processors for container logs to be defined
  deploy/helm/elastic-agent/README.md
  deploy/helm/elastic-agent/templates/integrations/_kubernetes/_kubernetes_logs_containers.tpl
  deploy/helm/elastic-agent/values.schema.json
  deploy/helm/elastic-agent/values.yaml
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog, backport-8.x, backport-8.18, backport-9.0

#7602 Make components in packages configurable
  dev-tools/mage/checksums.go
  dev-tools/mage/manifest/manifest.go
  dev-tools/mage/manifest/manifest_test.go
  dev-tools/mage/pkg.go
  dev-tools/packaging/packages.yml
  dev-tools/packaging/settings.go
  dev-tools/packaging/testing/package_test.go
  magefile.go
  pkg/version/version_parser.go
Labels: Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent, skip-changelog

#7651 Pre-install EPM packages needed by integration tests in Fleet
  .buildkite/scripts/steps/ess.sh
  .buildkite/scripts/steps/ess_start.sh
  .buildkite/scripts/steps/fleet.sh
  testing/integration/agent_long_running_leak_test.go
  testing/integration/agent_long_test_apache.json
  testing/integration/auditd_monitoring_test.go
  testing/integration/endpoint_test_tools.go
  testing/integration/fleetserver_test.go
  testing/integration/init.go
  testing/integration/logs_ingestion_test.go
  testing/integration/metrics_monitoring_test.go
  testing/integration/monitoring_probe_preserve_text_cfg_test.go
  testing/integration/monitoring_probe_reload_test.go
  testing/integration/network_traffic_monitoring_test.go
  testing/integration/osquery_monitoring_test.go
  testing/integration/testdata/auditd_package.json
  testing/integration/testdata/network_traffic_package.json
  testing/integration/testdata/preinstalled_packages.json
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog, backport-active-all

#7627 Enable unit tests with -tags=requirefips when FIPS=true
  .buildkite/pipeline.yml
  dev-tools/mage/gotest.go
  internal/pkg/agent/application/actions/handlers/handler_action_policy_change_nofips_test.go
  internal/pkg/agent/application/actions/handlers/handler_action_policy_change_test.go
  internal/pkg/agent/application/endpoint_component_modifier_nofips_test.go
  internal/pkg/agent/application/endpoint_component_modifier_test.go
  internal/pkg/agent/application/upgrade/upgrade_test.go
  internal/pkg/agent/cmd/command_components_fips_test.go
  internal/pkg/agent/cmd/command_components_nofips_test.go
  internal/pkg/agent/cmd/enroll_cmd_nofips_test.go
  internal/pkg/agent/cmd/enroll_cmd_test.go
  internal/pkg/agent/cmd/testdata/otel/components-output-fips.yml
  internal/pkg/otel/run_fips_test.go
  internal/pkg/otel/run_nofips_test.go
  internal/pkg/otel/run_test.go
  internal/pkg/otel/testdata/all-components-fips.yml
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog, Testing, backport-8.x

#7703 [flaky] force the installing of packages after provisioning the ESS stack
  testing/integration/testdata/preinstalled_packages.json
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog, backport-active-all

#7327 [otel/kube-stack] Update EDOT SDK k8s auto-instrumentation images to their latest versions
  deploy/helm/edot-collector/kube-stack/managed_otlp/values.yaml
  deploy/helm/edot-collector/kube-stack/values.yaml
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog, backport-active-9, backport-active-8

#7647 ci: add kubernetes v1.32 to test matrix
  .buildkite/bk.integration.pipeline.yml
  .buildkite/pipeline.yml
  .buildkite/scripts/install-kubectl.sh
  docs/test-framework-dev-guide.md
  pkg/testing/kubernetes/supported.go
Labels: Team:Elastic-Agent-Data-Plane, Cleanup, skip-changelog, backport-8.x, backport-9.0

#7687 ci: extend updatecli to bump wrappers/windows/archive-proxy golang version
  .ci/updatecli/updatecli-bump-golang.yml
Labels: skip-changelog, backport-8.x

#7589 [bug] wait for service to be reported as not found during switch
  changelog/fragments/1743062612-Wait-for-windows-server.yaml
  internal/pkg/agent/install/install.go
  internal/pkg/agent/install/switch.go
  internal/pkg/agent/install/wait_service_other.go
  internal/pkg/agent/install/wait_service_windows.go
Labels: bug, Team:Elastic-Agent-Control-Plane, backport-active-all

#7671 [Helm]: add missing 'elasticagent.init' inclusion in service.yaml
  deploy/helm/elastic-agent/templates/agent/service.yaml
Labels: bug, Team:Elastic-Agent-Control-Plane, skip-changelog, backport-8.x, backport-8.18, backport-9.0

#7724 Ensure consistent input order in self-monitoring configuration
  changelog/fragments/1744022861-consistent-monitoring-config.yaml
  internal/pkg/agent/application/monitoring/server_test.go
  internal/pkg/agent/application/monitoring/testdata/monitoring_config_full.yaml
  internal/pkg/agent/application/monitoring/v1_monitor.go
  internal/pkg/agent/application/monitoring/v1_monitor_test.go
Labels: Team:Elastic-Agent-Control-Plane, Cleanup, backport-active-all

#7737 Dynamically set go version in test
  pkg/testing/runner/runner_test.go
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog, chore, backport-active-all

#7635 Fix upgrade for same versions
  internal/pkg/agent/application/actions/handlers/handler_action_upgrade.go
  internal/pkg/agent/application/actions/handlers/handler_action_upgrade_test.go
  internal/pkg/agent/application/application.go
  internal/pkg/agent/application/coordinator/coordinator.go
  internal/pkg/agent/application/coordinator/coordinator_test.go
  internal/pkg/agent/application/managed_mode.go
  internal/pkg/agent/application/upgrade/upgrade.go
  internal/pkg/agent/application/upgrade/upgrade_test.go
Labels: bug, Team:Elastic-Agent-Control-Plane, skip-changelog, backport-active-9, backport-active-8

#7735 Update way of backporting
  .github/workflows/backport-active.yml
  .mergify.yml
Labels: enhancement, backport-skip, skip-changelog, ci, backport-active-9

#7757 Update mergify to allow command from github-actions bot
  .mergify.yml
Labels: Team:Elastic-Agent-Control-Plane, backport-skip, skip-changelog, backport-active-9

#7759 feat: bump go to 1.23.8
  .buildkite/pipeline.yml
  .buildkite/scripts/buildkite-k8s-integration-tests.sh
  .go-version
  .golangci.yml
  .tool-versions
  Dockerfile
  Dockerfile.skaffold
  changelog/fragments/1739375044-windows-change-how-process-handles-are-obtained-when-assigning-sub-processes-to-Job-objects..yaml
  go.mod
  pkg/core/process/external_windows.go
  pkg/core/process/job_windows.go
  pkg/testing/fixture_install.go
  pkg/testing/tools/check/check.go
  pkg/testing/tools/tools.go
  testing/integration/logs_ingestion_test.go
  testing/integration/upgrade_fleet_test.go
  version/docs/version.asciidoc
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog

#7749 [Helm] fix preset outputs
  deploy/helm/elastic-agent/examples/kubernetes-custom-output/README.md
  deploy/helm/elastic-agent/examples/kubernetes-custom-output/agent-kubernetes-values.yaml
  deploy/helm/elastic-agent/examples/kubernetes-custom-output/rendered/manifest.yaml
  deploy/helm/elastic-agent/templates/agent/_helpers.tpl
  deploy/helm/elastic-agent/templates/integrations/_kubernetes/_kubernetes_apiserver.tpl
  deploy/helm/elastic-agent/templates/integrations/_kubernetes/_kubernetes_controller_manager.tpl
  deploy/helm/elastic-agent/templates/integrations/_kubernetes/_kubernetes_kubelet_containers.tpl
  deploy/helm/elastic-agent/templates/integrations/_kubernetes/_kubernetes_kubelet_nodes.tpl
  deploy/helm/elastic-agent/templates/integrations/_kubernetes/_kubernetes_kubelet_pods.tpl
  deploy/helm/elastic-agent/templates/integrations/_kubernetes/_kubernetes_kubelet_system.tpl
  deploy/helm/elastic-agent/templates/integrations/_kubernetes/_kubernetes_kubelet_volumes.tpl
  deploy/helm/elastic-agent/templates/integrations/_kubernetes/_kubernetes_logs_audit.tpl
  deploy/helm/elastic-agent/templates/integrations/_kubernetes/_kubernetes_logs_containers.tpl
  deploy/helm/elastic-agent/templates/integrations/_kubernetes/_kubernetes_proxy.tpl
  deploy/helm/elastic-agent/templates/integrations/_kubernetes/_kubernetes_scheduler.tpl
  deploy/helm/elastic-agent/templates/integrations/_kubernetes/_kubernetes_state.tpl
  deploy/helm/elastic-agent/templates/integrations/_system/_system_logs.tpl
  deploy/helm/elastic-agent/templates/integrations/_system/_system_metrics.tpl
Labels: bug, Team:Elastic-Agent-Control-Plane, skip-changelog, backport-active-all

#7779 Revert "Update way of backporting"
  .github/workflows/backport-active.yml
  .mergify.yml
Labels: backport-skip, skip-changelog

#7780 fix: bump golangci-lint-action@v6.5.0 and golangci-lint@v1.64.5
  .github/workflows/golangci-lint.yml
  .golangci.yml
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog

#7760 Running mage controlProto
  magefile.go
  pkg/control/v1/proto/control_v1.pb.go
  pkg/control/v1/proto/control_v1_grpc.pb.go
  pkg/control/v2/cproto/control_v2.pb.go
  pkg/control/v2/cproto/control_v2_grpc.pb.go
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog, chore, backport-9.0

#7762 Expose whether Agent is FIPS compliant via v2 control protocol
  control_v2.proto
  pkg/control/v2/client/client.go
  pkg/control/v2/control_test.go
  pkg/control/v2/cproto/control_v2.pb.go
  pkg/control/v2/server/server.go
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog, backport-9.0

#7739 Revert "Switch to NewGCMWithRandomNonce for fips (#7474)"
  internal/pkg/agent/vault/aesgcm/aesgcm.go
  internal/pkg/agent/vault/aesgcm/aesgcm_fips.go
  internal/pkg/agent/vault/aesgcm/aesgcm_nofips.go
  internal/pkg/crypto/io.go
  internal/pkg/crypto/io_fips.go
  internal/pkg/crypto/io_nofips.go
  internal/pkg/crypto/io_opts_fips.go
  internal/pkg/crypto/io_opts_fips_test.go
  internal/pkg/crypto/io_opts_nofips.go
  internal/pkg/crypto/io_opts_nofips_test.go
Labels: bug, Team:Elastic-Agent-Control-Plane, skip-changelog

#7740 Revert "[8.x](backport #7474) Switch to NewGCMWithRandomNonce for fips"
  internal/pkg/agent/vault/aesgcm/aesgcm.go
  internal/pkg/agent/vault/aesgcm/aesgcm_fips.go
  internal/pkg/agent/vault/aesgcm/aesgcm_nofips.go
  internal/pkg/crypto/io.go
  internal/pkg/crypto/io_fips.go
  internal/pkg/crypto/io_nofips.go
  internal/pkg/crypto/io_opts_fips.go
  internal/pkg/crypto/io_opts_fips_test.go
  internal/pkg/crypto/io_opts_nofips.go
  internal/pkg/crypto/io_opts_nofips_test.go
Labels: Team:Elastic-Agent-Control-Plane, backport

#7795 Correctly inject dependency list when packaging using DROP_PATH
  magefile.go
Labels: bug, Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent, backport-skip, skip-changelog

#7785 [Helm] Allow providing SSL settings to the Elastic Agent (standalone mode)
  deploy/helm/elastic-agent/examples/kubernetes-custom-output/README.md
  deploy/helm/elastic-agent/examples/kubernetes-custom-output/agent-kubernetes-values.yaml
  deploy/helm/elastic-agent/examples/kubernetes-custom-output/rendered/manifest.yaml
  deploy/helm/elastic-agent/templates/agent/_helpers.tpl
  deploy/helm/elastic-agent/templates/agent/_outputs.tpl
  deploy/helm/elastic-agent/templates/agent/eck/secret.yaml
  deploy/helm/elastic-agent/templates/agent/k8s/_secret.tpl
  deploy/helm/elastic-agent/templates/integrations/_presets/_ksm_sidecar.tpl
  deploy/helm/elastic-agent/values.schema.json
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog, backport-8.x, backport-8.18, backport-9.0

#7805 Restore qualifier=core for elastic-agent-core packaging specs
  dev-tools/packaging/packages.yml
Labels: bug, Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent, backport-skip, skip-changelog

#7818 Modify fips core spec qualifier and name
  dev-tools/packaging/packages.yml
Labels: bug, Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent, backport-skip, skip-changelog

#7702 Enable buildkite step for unit testing with GODEBUG=fips140=only
  .buildkite/pipeline.yml
  dev-tools/mage/gotest.go
  internal/pkg/agent/application/endpoint_component_modifier_test.go
  internal/pkg/agent/application/info/agent_id_test.go
  internal/pkg/agent/application/secret/secret_test.go
  internal/pkg/agent/application/upgrade/artifact/download/fs/verifier_test.go
  internal/pkg/agent/application/upgrade/artifact/download/http/downloader_test.go
  internal/pkg/agent/application/upgrade/artifact/download/http/verifier_test.go
  internal/pkg/agent/install/uninstall_test.go
  internal/pkg/agent/migration/migrate_config_test.go
  internal/pkg/agent/storage/encrypted_disk_storage_windows_linux_test.go
  internal/pkg/agent/storage/store/state_store_test.go
  internal/pkg/agent/vault/aesgcm/aesgcm_test.go
  internal/pkg/agent/vault/vault_file_fips_test.go
  internal/pkg/agent/vault/vault_file_test.go
  internal/pkg/core/authority/ca.go
  internal/pkg/crypto/io_test.go
  internal/pkg/testutils/fipsutils/fipsOnlySkip.go
  internal/pkg/testutils/testutils.go
  magefile.go
Labels: Team:Elastic-Agent-Control-Plane, technical debt, skip-changelog, backport-8.x

#7734 Refactor self-monitoring metrics config generation
  internal/pkg/agent/application/monitoring/v1_monitor.go
Labels: Team:Elastic-Agent-Control-Plane, technical debt, skip-changelog, chore, backport-8.x, backport-8.18, backport-active-9

#7822 Enable building FIPS packages using manifest
  .buildkite/pipeline.elastic-agent-package.yml
  dev-tools/mage/pkgtypes.go
  dev-tools/packaging/packages.yml
Labels: Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent, backport-skip, skip-changelog

#7233 Add support for more input types in otelmanager
  internal/pkg/otel/configtranslate/otelconfig.go
  internal/pkg/otel/configtranslate/otelconfig_test.go
  testing/integration/otel_test.go
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog, backport-8.x, backport-9.0

#7833 [ci] include the full containerStatus on k8s integration test failure
  testing/integration/kubernetes_agent_standalone_test.go
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog, backport-active-all

#7701 feat(agentless): add agentless release pipelines
  .buildkite/pipeline.agentless-app-release.yaml
  .buildkite/pipeline.agentless-tests.yaml
  .buildkite/pipeline.tests-production.yaml
  .buildkite/pipeline.tests-qa.yaml
  .buildkite/pipeline.tests-staging.yaml
  .buildkite/scripts/steps/ecp-internal-release.sh
  .buildkite/scripts/steps/run-agentless-tests.sh
  catalog-info.yaml
Labels: Team:Elastic-Agent-Control-Plane, backport-skip, skip-changelog

#7830 Changelog for 8.17.5
  changelog/8.17.5.asciidoc
  changelog/8.17.5.yaml
  changelog/fragments/1739375044-windows-change-how-process-handles-are-obtained-when-assigning-sub-processes-to-Job-objects..yaml
  changelog/fragments/1742562383-Rework-Windows-user-password.yaml
  changelog/fragments/1743004444-synthetics-upgrade-node-18.20.7.yaml
  changelog/fragments/1743062612-Wait-for-windows-server.yaml
  changelog/fragments/1743421027-Fix-panic-during-shutdown-in-fleetgateway.yaml
  changelog/fragments/1744022861-consistent-monitoring-config.yaml
Labels: skip-changelog, forwardport-main

#7840 Disable ironbank target when packaging with FIPS=true
  .buildkite/scripts/steps/package.sh
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog, backport-8.x

#7738 Correctly handle sending signal to child process
  changelog/fragments/1744059162-send-correct-signal-on-windows.yaml
  magefile.go
  pkg/core/process/cmd.go
  pkg/core/process/cmd_darwin.go
  pkg/core/process/cmd_linux.go
  pkg/core/process/cmd_test.go
  pkg/core/process/testsignal/main.go
  pkg/core/process/testsignal/proc.go
  pkg/core/process/testsignal/proc_win.go
Labels: bug, Team:Elastic-Agent-Control-Plane

#7867 [Chore] Improve error reporting when otel collector fails to start
  internal/pkg/otel/manager/manager.go
Labels: skip-changelog, backport-8.x, backport-9.0

#7872 mergify: support 8.19 and remove support 8.x
  .mergify.yml
Labels: backport-skip, skip-changelog

#7862 Rename FIPS-compliant to FIPS-capable
  changelog/fragments/1740773781-Add-elastic.agent.fips-to-local_metadata.yaml
  changelog/fragments/1741808763-FIPS-Compliant-agent-file-vault.yaml
  changelog/fragments/1741897911-fips-to-fips-upgrades.yaml
  dev-tools/packaging/packages.yml
  dev-tools/packaging/testing/package_test.go
  internal/pkg/release/version.go
  pkg/control/v2/cproto/control_v2.pb.go
Labels: Team:Elastic-Agent-Control-Plane, backport-8.x

#7877 Rename buildkite test step to avoid confusion
  .buildkite/pipeline.yml
Labels: Team:Elastic-Agent-Control-Plane, technical debt, skip-changelog, backport-8.x

#7854 Refactor monitoring log config generation
  internal/pkg/agent/application/monitoring/v1_monitor.go
Labels: Team:Elastic-Agent-Control-Plane, technical debt, Cleanup, skip-changelog, backport-8.18, backport-active-9, backport-8.19

#7661 Update golangci-lint to `v2.0.2`
  .github/workflows/golangci-lint.yml
  .golangci.yml
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog, backport-active-all

#7855 fix: preinstall fleet packages on the newly provisioned ESS stack of a retried step
  .buildkite/scripts/steps/integration_tests_tf.sh
Labels: skip-changelog, backport-active-all

#7882 [Managed OTLP][Helm] Update to use current container repo
  changelog/fragments/1744839123-fix-MOtel-config-image-value.yaml
  deploy/helm/edot-collector/kube-stack/managed_otlp/values.yaml
Labels: Team:Elastic-Agent-Control-Plane, backport-active-9

#7888 [chore][testing] fix `PreviousMinor` function
  testing/upgradetest/versions.go
  testing/upgradetest/versions_test.go
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog, backport-9.0, backport-8.19

#7917 [Integration Tests] Do not print out curl verbose output
  .buildkite/scripts/steps/fleet.sh
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog, backport-active-all

#7866 [FIPS] Ensure that TLS connections initiated by Agent use FIPS-compliant TLS versions
  internal/pkg/remote/client.go
  internal/pkg/remote/client_fips_test.go
  internal/pkg/remote/config.go
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog, backport-8.19

#7933 Add prometheusreceiver to replace allowlist
  .golangci.yml
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog, chore, backport-8.18, backport-active-9, backport-8.19

#7791 github-actions: support release helm-chart for a given commit/branch
  .github/workflows/release-helm-charts-manual.yml
Labels: backport-skip, skip-changelog

#7894 [otel] Disable process scraper of hostmetrics receiver
  changelog/fragments/1744886313-otel_disable_process_scraper.yaml
  deploy/helm/edot-collector/kube-stack/managed_otlp/values.yaml
  deploy/helm/edot-collector/kube-stack/values.yaml
  internal/pkg/otel/samples/darwin/logs_metrics_traces.yml
  internal/pkg/otel/samples/darwin/managed_otlp/logs_metrics_traces.yml
  internal/pkg/otel/samples/darwin/managed_otlp/platformlogs_hostmetrics.yml
  internal/pkg/otel/samples/darwin/platformlogs_hostmetrics.yml
  internal/pkg/otel/samples/linux/logs_metrics_traces.yml
  internal/pkg/otel/samples/linux/managed_otlp/logs_metrics_traces.yml
  internal/pkg/otel/samples/linux/managed_otlp/platformlogs_hostmetrics.yml
  internal/pkg/otel/samples/linux/platformlogs_hostmetrics.yml
Labels: Team:Elastic-Agent-Control-Plane, backport-9.0

#7958 Pin VM version for check-ci
  .buildkite/bk.integration.pipeline.yml
  .buildkite/pipeline.yml
Labels: Team:Obs-InfraObs, skip-changelog, ci, backport-active-9, backport-active-8

#7956 bk: staging should not run the helmcharts with SNAPSHOT=false in DEV
  .buildkite/pipeline.elastic-agent-binary-dra.yml
Labels: skip-changelog, backport-8.18, backport-9.0, backport-8.19

#7948 Removing unreachable files
  .buildkite/scripts/install-go.ps1
  .buildkite/scripts/retry.sh
  .ci/scripts/install-go.bat
  .ci/scripts/install-go.sh
  dev-tools/common.bash
  dev-tools/run_with_go_ver
Labels: Team:Elastic-Agent-Control-Plane, backport-skip, skip-changelog

#7919 [ci] migrate serverless integration tests to buildkite
  .buildkite/bk.integration.pipeline.yml
  .buildkite/integration.pipeline.yml
  .buildkite/scripts/buildkite-integration-tests.sh
  .buildkite/scripts/integration-tests.ps1
  .buildkite/scripts/steps/integration_tests_tf.sh
  .buildkite/scripts/steps/serverless.ps1
  .buildkite/scripts/steps/serverless.sh
  .buildkite/scripts/steps/serverless_down.sh
  .buildkite/scripts/steps/serverless_start.sh
  test_infra/serverless/.gitignore
  test_infra/serverless/deployment.tf
  test_infra/serverless/output.tf
  test_infra/serverless/terraform.tf
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog, backport-active-all

#7986 Revert "[ci] migrate serverless integration tests to buildkite (#7919)"
  .buildkite/bk.integration.pipeline.yml
  .buildkite/integration.pipeline.yml
  .buildkite/scripts/buildkite-integration-tests.sh
  .buildkite/scripts/integration-tests.ps1
  .buildkite/scripts/steps/integration_tests_tf.sh
  .buildkite/scripts/steps/serverless.ps1
  .buildkite/scripts/steps/serverless.sh
  .buildkite/scripts/steps/serverless_down.sh
  .buildkite/scripts/steps/serverless_start.sh
  test_infra/serverless/.gitignore
  test_infra/serverless/deployment.tf
  test_infra/serverless/output.tf
  test_infra/serverless/terraform.tf
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog, backport-active-all

#7932 [testing] - minor enhancements to perform testing against local changes
  dev-tools/mage/crossbuild.go
  docs/test-framework-dev-guide.md
Labels: enhancement, Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent-Data-Plane, skip-changelog, backport-active-all

#7754 Set fullnameOverride and validate Otel kube-stack deployment datastreams are being written (metrics, traces)
  changelog/fragments/1744384247-set-collector's-fullnameOverride-for-edot-kube-stack-values.yaml
  deploy/helm/edot-collector/kube-stack/managed_otlp/values.yaml
  deploy/helm/edot-collector/kube-stack/values.yaml
  testing/integration/kubernetes_agent_standalone_test.go
  testing/integration/otel_helm_test.go
  testing/integration/testdata/java_app.yaml
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog, backport-active-all

#7976 fix(agentless-tests): Prevent git output from contaminating SHA extraction
  .buildkite/scripts/steps/run-agentless-tests.sh
Labels: skip-changelog

#6819 otel: fix flakiness and enable logs_dynamic_index in TestFBOtelRestartE2E
  testing/integration/otel_test.go
Labels: Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent-Data-Plane, skip-changelog, backport-9.0, backport-8.19

#8015 docs: fix OTel casing
  docs/test-framework-dev-guide.md
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog, backport-active-all

#8012 Improve status reporting in Otel manager test
  internal/pkg/otel/manager/manager_test.go
Labels: Team:Elastic-Agent-Control-Plane, flaky-test, skip-changelog, backport-active-all

#8013 test: validate cluster-stats collector metrics
  testing/integration/otel_helm_test.go
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog, backport-active-all
