Repository elastic/elastic-agent, pull requests merged in 2025-03, with the labels that each got.

#7130 [otel/kube-stack] Drop deprecated parameter from routing connector
  deploy/helm/edot-collector/kube-stack/values.yaml
Labels: Team:Elastic-Agent-Control-Plane, Cleanup, skip-changelog, backport-active-all

#7145 Add a changelog note that the agent Docker container is not longer available from docker.elastic.co/beats/elastic-agent
  changelog/fragments/1741035554-Elastic-Agent-docker-container-no-longer-availble-from-docker.elastic.co-beats-elastic-agent.yaml
Labels: Team:Elastic-Agent-Control-Plane, forwardport-main

#7056 Disable interpolation for monorepo plugin
  .buildkite/pipeline.yml
Labels: skip-changelog, backport-active-9, backport-active-8

#7057 [flakiness] kubernetes_secrets provider unit tests
  internal/pkg/composable/providers/kubernetessecrets/kubernetes_secrets.go
  internal/pkg/composable/providers/kubernetessecrets/kubernetes_secrets_test.go
Labels: Team:Elastic-Agent-Control-Plane, flaky-test, skip-changelog, backport-8.x, backport-8.17, backport-8.18, backport-9.0

#6983 Make enroll command backoff more conservative
  changelog/fragments/1740399399-fleet-backoff.yaml
  internal/pkg/agent/application/gateway/fleet/fleet_gateway.go
  internal/pkg/agent/application/gateway/fleet/fleet_gateway_test.go
  internal/pkg/agent/cmd/enroll.go
  internal/pkg/agent/cmd/enroll_cmd.go
  internal/pkg/agent/cmd/enroll_cmd_test.go
  internal/pkg/agent/cmd/run.go
Labels: bug, Team:Elastic-Agent-Control-Plane, backport-active-all

#7058 [flakiness]: utilise socket helper funcs in unit-tests
  pkg/component/runtime/conn_info_server_test.go
Labels: Team:Elastic-Agent-Control-Plane, flaky-test, skip-changelog, backport-active-all

#6874 feat(elastic-agent-services): add another tag to docker image for agentless use
  dev-tools/mage/dockerbuilder.go
  dev-tools/mage/pkg_test.go
  dev-tools/mage/pkgtypes.go
  dev-tools/mage/settings.go
  dev-tools/packaging/packages.yml
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog, backport-9.0

#6972 [CI] Fixed container images packaging
  .buildkite/bk.integration.pipeline.yml
  .buildkite/integration.pipeline.yml
  dev-tools/mage/crossbuild.go
Labels: enhancement, Team:Elastic-Agent-Control-Plane, skip-changelog, Team:Ingest-EngProd, backport-active-all

#7190 Increase timeout for assertions in TestSetLogLevelFleetManaged
  testing/integration/log_level_test.go
Labels: Team:Elastic-Agent-Control-Plane, flaky-test, skip-changelog, backport-active-all

#7112 Add fips attribute to agent metadata sent to fleet
  changelog/fragments/1740773781-Add-elastic.agent.fips-to-local_metadata.yaml
  internal/pkg/agent/application/coordinator/diagnostics_test.go
  internal/pkg/agent/application/info/agent_metadata.go
  internal/pkg/agent/application/info/agent_metadata_test.go
  testing/fleetservertest/fleetserver_test.go
Labels: enhancement, Team:Elastic-Agent-Control-Plane, backport-8.x, backport-8.18, backport-9.0

#7184 [CI] Serverless beats tests migration to beats
  .buildkite/integration.pipeline.yml
  .buildkite/serverless.beats.tests.yml
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog, Team:Ingest-EngProd, backport-active-all

#7165 [flakiness] Correct group for TestEndpointAgentServiceMonitoring
  testing/integration/monitoring_endpoint_test.go
Labels: Team:Elastic-Agent-Control-Plane, flaky-test, skip-changelog, backport-active-all

#7176 ci(buildkite): add initial elastic-agent-helm-charts pipeline
  .buildkite/pipeline.elastic-agent-helm-charts.yml
  catalog-info.yaml
Labels: backport-skip, skip-changelog

#7203 [CI] Fix Core DRA crossbuild
  .buildkite/pipeline.elastic-agent-binary-dra.yml
Labels: skip-changelog, Team:Ingest-EngProd, backport-active-all

#7205 [CI] Fix unified release ARM packaging
  .buildkite/pipeline.elastic-agent-package.yml
Labels: bug, skip-changelog, backport-active-all

#7240 chore(ci): Validate catalog-info.yaml
  .buildkite/pipeline.yml
Labels: backport-skip, skip-changelog

#7202 Fix a bug preventing kind cluster deletion in K8s tests
  pkg/testing/kubernetes/kind/provisioner.go
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog, ci, Team:Ingest-EngProd, backport-active-all

#7241 [helm]: bump elastic-agent helm chart ksm dependency
  deploy/helm/elastic-agent/Chart.lock
  deploy/helm/elastic-agent/Chart.yaml
  deploy/helm/elastic-agent/examples/eck/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/fleet-managed-ksm-sharding/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/fleet-managed/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/kubernetes-default/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/kubernetes-hints-autodiscover/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/kubernetes-ksm-sharding/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/multiple-integrations/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/user-service-account/rendered/manifest.yaml
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog, backport-8.x, backport-8.18, backport-9.0

#7191 [flakiness] improve reliability of kubernetes integration tests
  .buildkite/bk.integration.pipeline.yml
  .buildkite/integration.pipeline.yml
  .buildkite/scripts/buildkite-k8s-integration-tests.sh
  .buildkite/scripts/steps/integration_tests_tf.sh
  pkg/testing/define/define.go
  pkg/testing/define/requirements.go
Labels: Team:Elastic-Agent-Control-Plane, flaky-test, skip-changelog, backport-active-all

#7281 [Flaky Test]: skip running unit-tests for internal/pkg/otel/manager on windows
  internal/pkg/otel/manager/manager_test.go
Labels: Team:Elastic-Agent-Control-Plane, flaky-test, skip-changelog, backport-active-all

#7288 catalog-info: add GH team to automate triggering the build in GH actions
  catalog-info.yaml
Labels: backport-skip, skip-changelog

#7274 [Helm] support creating priority class
  deploy/helm/elastic-agent/examples/priority-class/README.md
  deploy/helm/elastic-agent/examples/priority-class/priority-class-values.yaml
  deploy/helm/elastic-agent/examples/priority-class/rendered/manifest.yaml
  deploy/helm/elastic-agent/templates/agent/eck/_pod_template.yaml
  deploy/helm/elastic-agent/templates/agent/eck/daemonset.yaml
  deploy/helm/elastic-agent/templates/agent/eck/deployment.yaml
  deploy/helm/elastic-agent/templates/agent/eck/statefulset.yaml
  deploy/helm/elastic-agent/templates/agent/k8s/_pod_template.yaml
  deploy/helm/elastic-agent/templates/agent/k8s/daemonset.yaml
  deploy/helm/elastic-agent/templates/agent/k8s/deployment.yaml
  deploy/helm/elastic-agent/templates/agent/k8s/statefulset.yaml
  deploy/helm/elastic-agent/templates/agent/priority-class.yaml
  deploy/helm/elastic-agent/values.schema.json
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog, backport-8.x, backport-8.18, backport-9.0

#7302 [ci]: parse agent version from version/version.go for k8s integration tests
  .buildkite/scripts/buildkite-k8s-integration-tests.sh
Labels: skip-changelog, ci, backport-active-all

#6730 Add conditions to copy_fields processor
  changelog/fragments/1738855375-Add-conditions-to-copy_fields-processors.yaml
  internal/pkg/agent/application/monitoring/v1_monitor.go
  testing/integration/container_cmd_test.go
  testing/integration/event_logging_test.go
  testing/integration/logs_ingestion_test.go
Labels: Team:Elastic-Agent-Control-Plane, backport-active-all

#7054 Update all usages of fleettools to use the installed Agent ID
  pkg/testing/fixture.go
  pkg/testing/tools/check/check.go
  pkg/testing/tools/fleettools/fleet.go
  pkg/testing/tools/tools.go
  testing/integration/agent_long_running_leak_test.go
  testing/integration/container_cmd_test.go
  testing/integration/delay_enroll_test.go
  testing/integration/endpoint_security_test.go
  testing/integration/enroll_replace_token_test.go
  testing/integration/enroll_unprivileged_test.go
  testing/integration/escaping_secrets_in_policy_test.go
  testing/integration/fqdn_test.go
  testing/integration/linux_deb_test.go
  testing/integration/linux_rpm_test.go
  testing/integration/logs_ingestion_test.go
  testing/integration/metrics_monitoring_test.go
  testing/integration/monitoring_endpoint_test.go
  testing/integration/monitoring_probe_preserve_text_cfg_test.go
  testing/integration/monitoring_probe_reload_test.go
  testing/integration/upgrade_fleet_test.go
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog, backport-8.x, backport-8.18, backport-9.0

#7282 enhancement(4811): added fips in the package manifest
  pkg/api/v1/manifest.go
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog, backport-8.x, backport-9.0

#7204 [CI] Moved Serverless beats tests pipeline resource from beats to here
  catalog-info.yaml
Labels: enhancement, backport-skip, skip-changelog, Team:Ingest-EngProd

#7232 [Helm]: add helm package mage target
  .buildkite/pipeline.elastic-agent-binary-dra.yml
  .buildkite/pipeline.elastic-agent-helm-charts.yml
  .buildkite/scripts/steps/helm-charts.sh
  .buildkite/scripts/steps/trigger-publish-helm-charts.sh
  magefile.go
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog, backport-8.x, backport-8.18, backport-9.0

#7350 catalog-info: allow robots to elastic-agent-package and avoid everyone to run beats-agent-serverless-tests
  catalog-info.yaml
Labels: backport-skip, skip-changelog, Team:Ingest-EngProd

#7303 github-actions: post-release event to publish helm-chart
  .github/workflows/release-helm-charts.yml
Labels: backport-skip, skip-changelog

#7357 [skip] flaky TestKubernetesAgentStandaloneKustomize
  testing/integration/kubernetes_agent_standalone_test.go
Labels: backport-skip, skip-changelog, skipped-test

#7345 fix(docker): make `otelcol` executable
  changelog/fragments/1741775827-docker-otelcol-executable.yaml
  dev-tools/packaging/package_test.go
  dev-tools/packaging/templates/docker/Dockerfile.elastic-agent.tmpl
Labels: bug, Team:Elastic-Agent-Control-Plane, backport-active-all

#7359 [flaky] fix kustomize integration tests
  testing/integration/kubernetes_agent_service_test.go
  testing/integration/kubernetes_agent_standalone_test.go
Labels: Team:Elastic-Agent-Control-Plane, flaky-test, skip-changelog, backport-active-all

#7351 bk: helmcharts for snapshot in the snapshot group
  .buildkite/pipeline.elastic-agent-binary-dra.yml
Labels: skip-changelog, Team:Ingest-EngProd, backport-8.x, backport-8.18, backport-active-9

#7355 github-actions: use raw values
  .github/workflows/release-helm-charts.yml
Labels: backport-skip, skip-changelog, Team:Ingest-EngProd

#7380 Fix exporter configuration in kube-stack values
  changelog/fragments/1741865161-fix-otel-kube-stack-config.yaml
  deploy/helm/edot-collector/kube-stack/values.yaml
Labels: bug, Team:Elastic-Agent-Control-Plane, backport-active-all

#7370 Shorten fragment filename to avoid issue cloning on Windows
  changelog/fragments/1740692584-Fixes-Windows-FixPermissions-error-handling.yaml
Labels: Team:Elastic-Agent-Control-Plane, technical debt, skip-ci, backport-active-all

#7305 [bug]: fix permissions for windows on not found paths and files errors
  changelog/fragments/1741622468-Do-not-fail-Windows-permission-updates-on-missing-files-paths..yaml
  internal/pkg/acl/acl_windows.go
  internal/pkg/acl/acl_windows_test.go
  internal/pkg/agent/perms/windows.go
  internal/pkg/agent/perms/windows_test.go
Labels: bug, Team:Elastic-Agent-Control-Plane, backport-active-all

#7342 Capture in progress the error of uninstalling elastic-agent service
  internal/pkg/agent/install/switch.go
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog, backport-active-all

#7366 .../application/dispatcher: use reflect.Type rather than string for dispatch
  internal/pkg/agent/application/dispatcher/dispatcher.go
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog

#7159 Add script to update OTel components
  .ci/scripts/otel-update.sh
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog, Team:Ingest-EngProd, skip-ci, backport-active-all

#7358 ci(buildkite): use custom ubuntu amd64 vm image with the preinstalled go modules
  .buildkite/pipeline.yml
Labels: skip-changelog, ci, backport-active-9, backport-active-8

#7072 Enhancement/5039 remove x crypto fips
  internal/pkg/agent/vault/vault_file_notwindows.go
  internal/pkg/crypto/hash.go
  internal/pkg/crypto/io.go
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog, backport-8.x, backport-9.0

#7367 Add AgentMonitoring Test for Beat Receivers work
  testing/integration/beat_receivers_test.go
Labels: Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent-Data-Plane, skip-changelog

#7415 [CI] Dedicated elastic-agent VM images for integration tests
  .buildkite/bk.integration.pipeline.yml
Labels: enhancement, skip-changelog, Team:Ingest-EngProd, backport-active-all

#7394 [CI] Run Ubuntu and Windows unit tests using custom VM images
  .buildkite/pipeline.yml
Labels: enhancement, skip-changelog, Team:Ingest-EngProd, backport-active-all

#7430 Replace ingest-eng-prod by observablt-robots
  .github/CODEOWNERS
Labels: backport-skip, skip-changelog

#7368 pkg/component/runtime: limit scope of updateInProgress status flag
  pkg/component/runtime/manager.go
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog

#7413 catalog-info: permissions for triggering builds does not work
  catalog-info.yaml
Labels: backport-skip, skip-changelog, Team:Ingest-EngProd

#7449 [CI] Grant build and read permission for serverless beats pipeline
  catalog-info.yaml
Labels: enhancement, backport-skip, skip-changelog, Team:Ingest-EngProd

#7445 Fix issue with ToMapStr not expanding path separator when reading configuration
  internal/pkg/config/config.go
  internal/pkg/config/config_test.go
  internal/pkg/config/loader_test.go
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog, backport-8.x, backport-9.0

#7328 Allow switching inputs to the otel runtime manager
  internal/pkg/agent/application/coordinator/coordinator.go
  internal/pkg/agent/application/coordinator/coordinator_unit_test.go
  internal/pkg/agent/application/coordinator/diagnostics_test.go
  pkg/component/component.go
  pkg/component/component_test.go
  testing/integration/diagnostics_test.go
  testing/integration/otel_test.go
Labels: enhancement, Team:Elastic-Agent-Control-Plane, skip-changelog, backport-8.x

#7173 EDOT and Slim docker images added
  .buildkite/bk.integration.pipeline.yml
  .buildkite/scripts/buildkite-k8s-integration-tests.sh
  dev-tools/mage/copy.go
  dev-tools/mage/dockerbuilder.go
  dev-tools/mage/dockervariants.go
  dev-tools/mage/pkgtypes.go
  dev-tools/packaging/package_test.go
  dev-tools/packaging/packages.yml
  dev-tools/packaging/templates/docker/Dockerfile.elastic-agent.tmpl
  dev-tools/packaging/templates/docker/docker-entrypoint.edot.tmpl
  pkg/testing/kubernetes/supported.go
  testing/integration/kubernetes_agent_standalone_test.go
  testing/integration/otel_helm_test.go
Labels: enhancement, Team:Elastic-Agent-Control-Plane, skip-changelog, backport-active-9

#7442 Update CODEOWNERS
  .github/CODEOWNERS
Labels: backport-skip, skip-changelog

#6638 [RPM/DEB] Changes to binary distribution
  dev-tools/packaging/templates/linux/postinstall.sh.tmpl
  dev-tools/packaging/templates/linux/preinstall.sh.tmpl
  internal/pkg/agent/cmd/apply_flavor.go
  internal/pkg/agent/cmd/common.go
  internal/pkg/agent/install/flavors.go
  internal/pkg/agent/install/flavors_test.go
  pkg/testing/fixture_install.go
  testing/integration/install_test.go
  testing/integration/linux_deb_test.go
  testing/integration/linux_rpm_test.go
Labels: bug, Team:Elastic-Agent-Control-Plane, skip-changelog, backport-active-9

#6801 [e2e] Add tests for self monitoring agent logs in otel mode
  testing/integration/beat_receivers_test.go
  testing/integration/otel_test.go
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog, backport-8.x

#7414 Fix flaky diagnostics redaction integration test
  testing/integration/diagnostics_test.go
Labels: Team:Elastic-Agent-Control-Plane, flaky-test, skip-changelog, backport-active-all

#7483 Update golangci-lint.yml
  .github/workflows/golangci-lint.yml
Labels: backport-skip, skip-changelog

#7187 Add FIPS pbkdf2 validation
  changelog/fragments/1741122475-Validate-pbkdf2-settings-when-in-FIPS-mode.yaml
  internal/pkg/crypto/io.go
  internal/pkg/crypto/io_opts_fips.go
  internal/pkg/crypto/io_opts_fips_test.go
  internal/pkg/crypto/io_opts_nofips.go
  internal/pkg/crypto/io_opts_nofips_test.go
Labels: enhancement, Team:Elastic-Agent-Control-Plane, backport-8.x, backport-9.0

#7486 Skip FIPS components when packaging elastic-agent from a Manifest
  dev-tools/mage/checksums.go
Labels: bug, Team:Elastic-Agent-Control-Plane, skip-changelog

#7487 bk(packaging): split arm64 from amd64 workers
  .buildkite/pipeline.elastic-agent-binary-dra.yml
  .buildkite/pipeline.elastic-agent-package.yml
Labels: skip-changelog, backport-8.x, backport-8.18, backport-9.0

#7360 FIPS complaint agent file vault
  changelog/fragments/1741808763-FIPS-Compliant-agent-file-vault.yaml
  internal/pkg/agent/vault/seed.go
  internal/pkg/agent/vault/seed_fips.go
  internal/pkg/agent/vault/seed_fips_test.go
  internal/pkg/agent/vault/seed_nofips.go
  internal/pkg/agent/vault/seed_nofips_test.go
  internal/pkg/agent/vault/seed_test.go
  internal/pkg/agent/vault/vault_file.go
  internal/pkg/agent/vault/vault_file_fips_test.go
  internal/pkg/agent/vault/vault_file_nofips_test.go
  internal/pkg/agent/vault/vault_file_notwindows.go
  internal/pkg/agent/vault/vault_file_test.go
Labels: enhancement, Team:Elastic-Agent-Control-Plane, backport-8.x, backport-9.0

#7505 Revert "Test integrations with basic installation"
  testing/integration/auditd_monitoring_test.go
  testing/integration/auditd_package.json
  testing/integration/metrics_monitoring_test.go
  testing/integration/network_traffic_monitoring_test.go
  testing/integration/network_traffic_package.json
  testing/integration/osquery_monitoring_test.go
  testing/integration/osquery_package.json
Labels: Team:Elastic-Agent-Control-Plane, backport-skip, skip-changelog

#7341 [ci] capture logs of pods in the test namespace and kube-system
  .buildkite/bk.integration.pipeline.yml
  .buildkite/scripts/buildkite-k8s-integration-tests.sh
  testing/integration/kubernetes_agent_standalone_test.go
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog, backport-active-all

#7354 Add ITs for Debian 12
  .buildkite/bk.integration.pipeline.yml
Labels: skip-changelog, ci, backport-active-9, backport-active-8

#7453 enhancement(4811): updated the errors returned from check upgrade and…
  changelog/fragments/1742318642-fips-to-fips-upgrade-error-reword.yaml
  internal/pkg/agent/application/upgrade/upgrade.go
  internal/pkg/agent/application/upgrade/upgrade_test.go
Labels: Team:Elastic-Agent-Control-Plane

#7502 internal/pkg/agent/cmd: remove redundant addCommandIfNotNil func
  internal/pkg/agent/cmd/cmd_test.go
  internal/pkg/agent/cmd/common.go
Labels: Team:Elastic-Agent-Control-Plane, Cleanup, skip-changelog, backport-8.x

#7369 pkg/component/runtime: use atomic.Pointer rather than locks for current component
  pkg/component/runtime/runtime.go
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog

#7474 Switch to NewGCMWithRandomNonce for fips
  internal/pkg/agent/vault/aesgcm/aesgcm.go
  internal/pkg/agent/vault/aesgcm/aesgcm_fips.go
  internal/pkg/agent/vault/aesgcm/aesgcm_nofips.go
  internal/pkg/crypto/io.go
  internal/pkg/crypto/io_fips.go
  internal/pkg/crypto/io_fips_test.go
  internal/pkg/crypto/io_nofips.go
  internal/pkg/crypto/io_nofips_test.go
  internal/pkg/crypto/io_opts_fips.go
  internal/pkg/crypto/io_opts_nofips.go
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog, backport-8.x

#7540 updatecli: update other files
  .ci/updatecli/updatecli-bump-golang.yml
Labels: backport-skip, skip-changelog

#7545 Use local HTTP server instead of downloading file on test
  dev-tools/mage/downloads/testdata/some-file.txt
  dev-tools/mage/downloads/utils_test.go
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog, backport-active-all

#7583 [Synthetics] Upgrade node to latest LTS 18.20.7
  changelog/fragments/1743004444-synthetics-upgrade-node-18.20.7.yaml
  dev-tools/packaging/templates/docker/Dockerfile.elastic-agent.tmpl
Labels: Team:Elastic-Agent-Control-Plane, dependency, Cleanup, Team:obs-ds-hosted-services, backport-active-9, backport-active-8

#7594 dependabot: add github composite actions
  .github/dependabot.yml
Labels: backport-skip, skip-changelog

#7507 [bug] rework Windows user password generation to match security constraints
  changelog/fragments/1742562383-Rework-Windows-user-password.yaml
  internal/pkg/agent/install/user_windows.go
  internal/pkg/agent/install/user_windows_test.go
Labels: bug, Team:Elastic-Agent-Control-Plane, backport-active-all

#7623 [mergify] Remove 8.16 as an active branch
  .mergify.yml
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog, chore

#7601 [packaging] proxy binary to be for the root dir of windows archive
  dev-tools/packaging/packages.yml
  magefile.go
  wrapper/windows/archive-proxy/go.mod
  wrapper/windows/archive-proxy/go.sum
  wrapper/windows/archive-proxy/main.go
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog, backport-8.x, backport-8.18, backport-9.0

#7604 Fix SHA512 generation for windows
  magefile.go
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog

#7573 pkg/component/runtime: improve documentation for MonitoringManager
  internal/pkg/agent/application/coordinator/coordinator_test.go
  internal/pkg/agent/application/monitoring/v1_monitor.go
  pkg/component/runtime/command.go
  pkg/component/runtime/manager_test.go
Labels: documentation, Team:Elastic-Agent-Control-Plane, skip-changelog, Team:Security-Service Integrations
