Repository elastic/elastic-agent, pull requests merged in 2025-05, with the labels that each got.

#7999 [deb/rpm] copy run folder from old agent installation
  changelog/fragments/1745923884-deb-rpm-preserve-run-state.yaml
  dev-tools/packaging/templates/linux/preinstall.sh.tmpl
  pkg/testing/fixture.go
  testing/integration/linux_deb_test.go
  testing/integration/linux_rpm_test.go
  testing/integration/restrict_upgrade_deb_test.go
Labels: bug, Team:Elastic-Agent-Control-Plane, backport-active-all

#8057 [Integration Testing] Add support for FIPS-capable artifacts
  pkg/testing/fetch_test.go
  pkg/testing/fetcher.go
  pkg/testing/fetcher_artifact.go
  pkg/testing/fixture.go
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog, backport-8.19

#7817 docker: use the official Red Hat images
  dev-tools/packaging/packages.yml
  dev-tools/packaging/templates/docker/Dockerfile.elastic-agent.tmpl
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog, backport-active-all

#8086 ksm autosharing integration configuration update
  deploy/helm/elastic-agent/examples/fleet-managed-ksm-sharding/README.md
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog, backport-8.18, backport-9.0, backport-8.19

#8094 fix(agentless): overcome SIGPIPE in agentless promotion pipeline
  .buildkite/scripts/steps/run-agentless-tests.sh
Labels: skip-changelog

#8065 Adding new configuration setting: `agent.upgrade.rollback.window`
  _meta/config/common.reference.p2.yml.tmpl
  changelog/fragments/1746197293-config-rollback-window.yaml
  elastic-agent.reference.yml
  internal/pkg/agent/configuration/upgrade.go
  internal/pkg/agent/configuration/upgrade_test.go
Labels: Team:Elastic-Agent-Control-Plane, backport-skip

#8031 Allow using beats receivers for self-monitoring
  internal/pkg/agent/application/monitoring/v1_monitor.go
  internal/pkg/agent/application/monitoring/v1_monitor_test.go
  internal/pkg/core/monitoring/config/config.go
  testing/integration/beat_receivers_test.go
Labels: enhancement, Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent-Data-Plane, skip-changelog, backport-active-9, backport-8.19

#8062 Changelog for 8.17.6 version
  changelog/8.17.6.asciidoc
  changelog/8.17.6.yaml
  changelog/fragments/1744384247-set-collector's-fullnameOverride-for-edot-kube-stack-values.yaml
Labels: release, skip-changelog

#8056 Retry enrollment requests when an error is returned, add enrollment timeout
  changelog/fragments/1746113477-Retry-enrollment-for-all-errors.yaml
  internal/pkg/agent/cmd/container.go
  internal/pkg/agent/cmd/enroll.go
  internal/pkg/agent/cmd/enroll_cmd.go
  internal/pkg/agent/cmd/enroll_cmd_test.go
  internal/pkg/agent/cmd/setup_config.go
  internal/pkg/fleetapi/enroll_cmd.go
Labels: enhancement, Team:Elastic-Agent-Control-Plane, backport-8.19

#8107 Guard against `nil` pointer dereference
  testing/integration/beat_receivers_test.go
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog, backport-active-9, backport-8.19

#8045 [Release] Update version to 9.0.2
  deploy/helm/edot-collector/kube-stack/managed_otlp/values.yaml
  deploy/helm/edot-collector/kube-stack/values.yaml
  deploy/helm/elastic-agent/Chart.yaml
  deploy/helm/elastic-agent/examples/eck/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/fleet-managed-certificates/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/fleet-managed-ksm-sharding/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/fleet-managed/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/kubernetes-custom-output/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/kubernetes-default/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/kubernetes-hints-autodiscover/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/kubernetes-ksm-sharding/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/kubernetes-only-logs/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/multiple-integrations/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/netflow-service/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/nginx-custom-integration/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/priority-class/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/system-custom-auth-paths/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/user-cluster-role/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/user-service-account/rendered/manifest.yaml
  deploy/helm/elastic-agent/values.yaml
  deploy/kubernetes/elastic-agent-kustomize/default/elastic-agent-managed/base/elastic-agent-managed-daemonset.yaml
  deploy/kubernetes/elastic-agent-kustomize/default/elastic-agent-standalone/base/elastic-agent-standalone-daemonset.yaml
  deploy/kubernetes/elastic-agent-kustomize/ksm-autosharding/elastic-agent-managed/base/elastic-agent-managed-daemonset.yaml
  deploy/kubernetes/elastic-agent-kustomize/ksm-autosharding/elastic-agent-managed/extra/elastic-agent-managed-statefulset.yaml
  deploy/kubernetes/elastic-agent-kustomize/ksm-autosharding/elastic-agent-standalone/base/elastic-agent-standalone-daemonset.yaml
  deploy/kubernetes/elastic-agent-kustomize/ksm-autosharding/elastic-agent-standalone/extra/elastic-agent-standalone-statefulset.yaml
  deploy/kubernetes/elastic-agent-kustomize/ksm-hints/elastic-agent-standalone/kustomization.yaml
  deploy/kubernetes/elastic-agent-managed-kubernetes.yaml
  deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml
  version/version.go
Labels: Team:Automation, release, skip-changelog

#8121 Remove 9.0.0 version pinning from tests
  .buildkite/bk.integration.pipeline.yml
  .buildkite/scripts/buildkite-integration-tests.sh
  .buildkite/scripts/integration-tests.ps1
  .buildkite/scripts/steps/integration-package.sh
  .buildkite/scripts/steps/integration_tests.sh
  .buildkite/scripts/steps/k8s-extended-tests.sh
  testing/integration/upgrade_broken_package_test.go
Labels: Team:Elastic-Agent-Control-Plane, backport-skip, skip-changelog, Testing

#8104 [k8s tests] Add versions + comments explaining why
  .buildkite/bk.integration.pipeline.yml
Labels: Team:Elastic-Agent-Control-Plane, Cleanup, skip-changelog, backport-9.0, backport-8.19

#8123 mage: clean up .agent-testing folder on mage clean
  dev-tools/mage/clean.go
  docs/test-framework-dev-guide.md
Labels: Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent-Data-Plane, Cleanup, skip-changelog, backport-9.0, backport-8.19

#8130 Bump version to 8.17.7
  deploy/helm/edot-collector/kube-stack/managed_otlp/values.yaml
  deploy/helm/edot-collector/kube-stack/values.yaml
  deploy/helm/elastic-agent/Chart.yaml
  deploy/helm/elastic-agent/README.md
  deploy/helm/elastic-agent/examples/eck/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/fleet-managed/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/kubernetes-default/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/kubernetes-hints-autodiscover/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/kubernetes-only-logs/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/multiple-integrations/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/nginx-custom-integration/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/system-custom-auth-paths/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/user-cluster-role/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/user-service-account/rendered/manifest.yaml
  deploy/helm/elastic-agent/values.yaml
  deploy/kubernetes/elastic-agent-kustomize/default/elastic-agent-managed/base/elastic-agent-managed-daemonset.yaml
  deploy/kubernetes/elastic-agent-kustomize/default/elastic-agent-standalone/base/elastic-agent-standalone-daemonset.yaml
  deploy/kubernetes/elastic-agent-kustomize/ksm-autosharding/elastic-agent-managed/base/elastic-agent-managed-daemonset.yaml
  deploy/kubernetes/elastic-agent-kustomize/ksm-autosharding/elastic-agent-managed/extra/elastic-agent-managed-statefulset.yaml
  deploy/kubernetes/elastic-agent-kustomize/ksm-autosharding/elastic-agent-standalone/base/elastic-agent-standalone-daemonset.yaml
  deploy/kubernetes/elastic-agent-kustomize/ksm-autosharding/elastic-agent-standalone/extra/elastic-agent-standalone-statefulset.yaml
  deploy/kubernetes/elastic-agent-kustomize/ksm-hints/elastic-agent-standalone/kustomization.yaml
  deploy/kubernetes/elastic-agent-managed-kubernetes.yaml
  deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml
  version/docs/version.asciidoc
  version/version.go
Labels: skip-changelog

#8092 Add ms_tls13kdf buildtag for FIPS builds
  dev-tools/mage/gotest.go
  dev-tools/packaging/packages.yml
  dev-tools/packaging/testing/package_test.go
  magefile.go
Labels: Team:Elastic-Agent-Control-Plane, technical debt, skip-changelog, backport-8.19

#8135 Bump version to 8.18.2
  deploy/helm/edot-collector/kube-stack/managed_otlp/values.yaml
  deploy/helm/edot-collector/kube-stack/values.yaml
  deploy/helm/elastic-agent/Chart.yaml
  deploy/helm/elastic-agent/examples/eck/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/fleet-managed-certificates/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/fleet-managed-ksm-sharding/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/fleet-managed/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/kubernetes-custom-output/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/kubernetes-default/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/kubernetes-hints-autodiscover/kubernetes-ksm-sharding/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/kubernetes-hints-autodiscover/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/kubernetes-only-logs/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/multiple-integrations/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/netflow-service/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/nginx-custom-integration/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/priority-class/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/system-custom-auth-paths/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/user-cluster-role/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/user-service-account/rendered/manifest.yaml
  deploy/helm/elastic-agent/values.yaml
  deploy/kubernetes/elastic-agent-kustomize/default/elastic-agent-managed/base/elastic-agent-managed-daemonset.yaml
  deploy/kubernetes/elastic-agent-kustomize/default/elastic-agent-standalone/base/elastic-agent-standalone-daemonset.yaml
  deploy/kubernetes/elastic-agent-kustomize/ksm-autosharding/elastic-agent-managed/base/elastic-agent-managed-daemonset.yaml
  deploy/kubernetes/elastic-agent-kustomize/ksm-autosharding/elastic-agent-managed/extra/elastic-agent-managed-statefulset.yaml
  deploy/kubernetes/elastic-agent-kustomize/ksm-autosharding/elastic-agent-standalone/base/elastic-agent-standalone-daemonset.yaml
  deploy/kubernetes/elastic-agent-kustomize/ksm-autosharding/elastic-agent-standalone/extra/elastic-agent-standalone-statefulset.yaml
  deploy/kubernetes/elastic-agent-kustomize/ksm-hints/elastic-agent-standalone/kustomization.yaml
  deploy/kubernetes/elastic-agent-managed-kubernetes.yaml
  deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml
  version/docs/version.asciidoc
  version/version.go
Labels: skip-changelog

#8093 github-action: add catalog-validate for GitHub actions
  .github/workflows/catalog-info.yml
Labels: skip-changelog

#8153 Unpin VM images
  .buildkite/bk.integration.pipeline.yml
  .buildkite/pipeline.yml
Labels: skip-changelog, ci, backport-active-9, backport-active-8

#8084 ci(test): skip skipped tests from the Test JUnit output
  .buildkite/scripts/buildkite-integration-tests.sh
  .buildkite/scripts/buildkite-k8s-integration-tests.sh
  .buildkite/scripts/integration-tests.ps1
  Makefile
  dev-tools/mage/gotest.go
  go.mod
  go.sum
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog, backport-active-9, backport-8.19

#8091 enhancment: bumped golangci-lint version to 2.1.0
  .github/workflows/golangci-lint.yml
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog

#8175 ci: fix deb and rpm flavor tests
  testing/integration/linux_deb_test.go
  testing/integration/linux_rpm_test.go
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog, backport-9.0

#8159 update managed OTLP endpoint timeout to 15seconds
  deploy/helm/edot-collector/kube-stack/managed_otlp/values.yaml
Labels: backport, skip-changelog, backport-9.0

#8154 ci: add Kubernetes v1.33 to test matrix
  .buildkite/pipeline.yml
  .buildkite/scripts/steps/k8s-tests.sh
  docs/test-framework-dev-guide.md
  pkg/testing/kubernetes/supported.go
Labels: Team:Elastic-Agent-Data-Plane, Cleanup, skip-changelog, backport-9.0, backport-8.19

#8174 Automatically update beats module versions
  .ci/scripts/update-beats.sh
  .ci/updatecli/update-beats.yml
  .github/workflows/bump-beats-version.yml
  dev-tools/mage/target/update/update.go
  magefile.go
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog, ci, backport-9.0, backport-8.19

#8215 fix(diagnostics): handle log rotation races
  changelog/fragments/1747938268-fix-diag-race-condition.yaml
  internal/pkg/diagnostics/diagnostics.go
Labels: bug, Team:Elastic-Agent-Control-Plane, backport-active-all

#8233 Fix minor typo in beats update job
  .ci/updatecli/update-beats.yml
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog, chore, backport-8.19

#8241 [Chore] Remove `http/metric` streams for beat receivers
  internal/pkg/agent/application/monitoring/testdata/monitoring_config_full.yaml
  internal/pkg/agent/application/monitoring/v1_monitor.go
Labels: skip-changelog, backport-9.0, backport-8.19

#8262 Add support for desired outcome
  internal/pkg/agent/application/upgrade/rollback_test.go
  internal/pkg/agent/application/upgrade/step_mark.go
  internal/pkg/agent/application/upgrade/step_mark_test.go
  internal/pkg/agent/application/upgrade/upgrade.go
Labels: enhancement, skip-changelog, backport-active-9

#8271 [documentation] Update test-framework-dev-guide.md
  docs/test-framework-dev-guide.md
Labels: documentation, Team:Elastic-Agent-Control-Plane, backport-skip, skip-changelog

#8009 [otel]: Add e2e test for monitoring metrics in otel mode
  testing/integration/beat_receivers_test.go
  testing/integration/otel_test.go
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog, backport-9.0, backport-8.19
