Repository elastic/elastic-agent, pull requests merged in 2025-02, with the labels that each got.

#6682 Pin agent version for integration tests
  .buildkite/scripts/buildkite-integration-tests.sh
  .buildkite/scripts/integration-tests.ps1
  .buildkite/scripts/steps/integration-package.sh
  .buildkite/scripts/steps/integration_tests.sh
  .buildkite/scripts/steps/k8s-extended-tests.sh
  .package-version
  testing/integration/upgrade_broken_package_test.go
Labels: Team:Elastic-Agent-Control-Plane, backport-skip, skip-changelog, Testing, ci

#6559 Fix/5595 force uninstall correct installation
  changelog/fragments/1737473147-force-install-replaces-correct-agent.yaml
  internal/pkg/agent/cmd/install.go
  internal/pkg/agent/cmd/install_test.go
  internal/pkg/agent/cmd/uninstall.go
  testing/integration/install_test.go
Labels: Team:Elastic-Agent-Control-Plane, backport-8.x

#6705 updatecli: set force to false, it won't try to update the base branch
  .ci/updatecli/updatecli-bump-golang.yml
Labels: backport-skip, skip-changelog

#6326 github-actions: filter by current active branches in the repository
  .github/workflows/bump-agent-versions.yml
Labels: Team:Elastic-Agent-Control-Plane, backport-skip, skip-changelog, Team:Ingest-EngProd

#6708 mergify: support backport-active-8, backport-active-9 and backport-active-all
  .mergify.yml
Labels: Team:Elastic-Agent-Control-Plane, backport-skip, skip-changelog, Team:Ingest-EngProd

#6323 [CI] Backport buildkite integration tests to 8.17
  .buildkite/bk.integration.pipeline.yml
  .buildkite/hooks/pre-command
  .buildkite/hooks/pre-command.ps1
  .buildkite/integration.pipeline.yml
  .buildkite/pipeline.yml
  .buildkite/scripts/buildkite-integration-tests.sh
  .buildkite/scripts/install-go.ps1
  .buildkite/scripts/integration-tests.ps1
  .buildkite/scripts/steps/ess.ps1
  .buildkite/scripts/steps/ess.sh
  .buildkite/scripts/steps/ess_start.sh
  .buildkite/scripts/steps/integration_tests_tf.sh
  .buildkite/scripts/steps/integration_tests_tf_sudo.sh
  .buildkite/scripts/sudo-integration-tests.sh
  .tool-versions
  test_infra/ess/deployment.tf
Labels: backport, Team:Ingest-EngProd

#6720 mergify: support 8.x for the backport-active-8
  .mergify.yml
Labels: backport-skip, skip-changelog

#6734 Skip flaky tests on windows while root cause is being investigated
  testing/integration/upgrade_gpg_test.go
  testing/integration/upgrade_rollback_test.go
  testing/integration/upgrade_standalone_retry_test.go
  testing/integration/upgrade_standalone_same_commit_test.go
Labels: flaky-test, backport-skip, skip-changelog, ci

#6721 ci(buildkite): skip ci builds when changing the .mergify.yml file
  .buildkite/pull-requests.json
Labels: backport-skip, skip-changelog

#6710 Redacted nested secrets path value
  changelog/fragments/1738874791-Fix-secret_paths-redaction-along-complex-paths.yaml
  internal/pkg/diagnostics/diagnostics.go
  internal/pkg/diagnostics/diagnostics_test.go
Labels: bug, Team:Elastic-Agent-Control-Plane, backport-8.x, backport-8.16, backport-8.17, backport-8.18, backport-9.0

#6743 Mergify: add backport-9.0
  .mergify.yml
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog

#6401 Split packaging into separate steps
  .buildkite/bk.integration.pipeline.yml
  .buildkite/integration.pipeline.yml
  .buildkite/scripts/steps/integration-package.sh
Labels: enhancement, skip-changelog, ci, Team:Ingest-EngProd, backport-8.x, backport-8.16, backport-8.17, backport-9.0

#6602 Add support for variables in outputs and default provider
  changelog/fragments/1737816507-Add-context-variable-support-to-outputs.yaml
  internal/pkg/agent/application/coordinator/coordinator.go
  internal/pkg/agent/application/coordinator/coordinator_test.go
  internal/pkg/agent/application/coordinator/coordinator_unit_test.go
  internal/pkg/agent/application/coordinator/diagnostics_test.go
  internal/pkg/agent/transpiler/ast.go
  internal/pkg/agent/transpiler/ast_test.go
  internal/pkg/agent/transpiler/inputs.go
  internal/pkg/agent/transpiler/inputs_test.go
  internal/pkg/agent/transpiler/outputs.go
  internal/pkg/agent/transpiler/outputs_test.go
  internal/pkg/agent/transpiler/vars.go
  internal/pkg/agent/transpiler/vars_test.go
  internal/pkg/composable/benchmark_test.go
  internal/pkg/composable/config.go
  internal/pkg/composable/controller.go
  internal/pkg/composable/controller_test.go
  internal/pkg/composable/providers/agent/agent.go
  internal/pkg/composable/providers/agent/agent_test.go
  internal/pkg/composable/providers/env/env.go
  internal/pkg/composable/providers/env/env_test.go
  internal/pkg/composable/providers/local/local.go
  internal/pkg/composable/providers/local/local_test.go
  internal/pkg/composable/providers/localdynamic/localdynamic.go
  internal/pkg/composable/providers/localdynamic/localdynamic_test.go
  internal/pkg/composable/providers/path/path.go
  internal/pkg/composable/providers/path/path_test.go
  internal/pkg/config/config.go
  internal/pkg/config/config_test.go
  pkg/component/component.go
  pkg/component/component_test.go
Labels: Team:Elastic-Agent-Control-Plane, backport-8.x, backport-9.0

#6735 Clean up message when audit/uninstall returns 401
  changelog/fragments/1738867024-Improve-message-when-audit-uninstall-returns-401.yaml
  internal/pkg/agent/install/uninstall.go
  internal/pkg/agent/install/uninstall_test.go
Labels: bug, Team:Elastic-Agent-Control-Plane, backport-active-9, backport-active-8

#6706 mergify: update rules
  .mergify.yml
Labels: backport-skip, skip-changelog

#6712 Update tests for flavors
  testing/integration/upgrade_standalone_flavors_test.go
  testing/upgradetest/upgrader.go
  testing/upgradetest/versions.go
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog, Testing, backport-9.0

#6752 ci(catalog-info): disable tags builds
  catalog-info.yaml
Labels: backport-skip, skip-changelog

#6726 ci: remove Dependabot config for OTel components
  .github/dependabot.yml
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog, ci, backport-8.x, backport-8.17, backport-8.18, backport-9.0

#6228 otel: add test for filebeatreceiver delivery guarantees during a collector restart
  testing/integration/otel_test.go
Labels: Cleanup, skip-changelog, backport-8.x, backport-9.0

#6623 [k8s] Fix logical race conditions in kubernetes_secrets provider
  changelog/fragments/1738139927-Fix-logical-race-conditions-in-kubernetes_secrets-provider.yaml
  internal/pkg/composable/providers/kubernetessecrets/config.go
  internal/pkg/composable/providers/kubernetessecrets/expiration_cache.go
  internal/pkg/composable/providers/kubernetessecrets/kubernetes_secrets.go
  internal/pkg/composable/providers/kubernetessecrets/kubernetes_secrets_test.go
  internal/pkg/composable/providers/kubernetessecrets/store_test.go
Labels: bug, Team:Elastic-Agent-Control-Plane, backport-8.x, backport-8.17, backport-8.18, backport-9.0

#6498 Add ability to enroll with defined ID and replace_token
  changelog/fragments/1738784301-Add-id-and-replace-token-to-enrollment.yaml
  internal/pkg/agent/application/coordinator/diagnostics_test.go
  internal/pkg/agent/cmd/container.go
  internal/pkg/agent/cmd/container_test.go
  internal/pkg/agent/cmd/enroll.go
  internal/pkg/agent/cmd/enroll_cmd.go
  internal/pkg/agent/cmd/setup_config.go
  internal/pkg/agent/configuration/fleet.go
  internal/pkg/fleetapi/enroll_cmd.go
  pkg/testing/fixture_install.go
  pkg/testing/tools/check/check.go
  testing/integration/enroll_replace_token_test.go
Labels: enhancement, Team:Elastic-Agent-Control-Plane, backport-8.x, backport-9.0

#6666 [k8s] Fix System Integration to utilise hostfs mounts
  deploy/helm/elastic-agent/examples/system-custom-auth-paths/rendered/manifest.yaml
  deploy/helm/elastic-agent/templates/integrations/_system/_system_metrics.tpl
  deploy/kubernetes/elastic-agent-kustomize/default/elastic-agent-standalone/base/elastic-agent-standalone-daemonset-configmap.yaml
  deploy/kubernetes/elastic-agent-kustomize/default/elastic-agent-standalone/base/elastic-agent-standalone-ksm-daemonset-configmap.yaml
  deploy/kubernetes/elastic-agent-kustomize/ksm-autosharding/elastic-agent-standalone/base/elastic-agent-standalone-ksm-daemonset-configmap.yaml
  deploy/kubernetes/elastic-agent-kustomize/ksm-hints/elastic-agent-standalone/elastic-agent-standalone-daemonset-configmap.yaml
  deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml
  deploy/kubernetes/elastic-agent-standalone/elastic-agent-standalone-daemonset-configmap.yaml
  deploy/kubernetes/elastic-agent-standalone/elastic-agent-standalone-ksm-daemonset-configmap.yaml
Labels: bug, Team:Elastic-Agent-Control-Plane, skip-changelog, backport-8.x, backport-8.17, backport-8.18, backport-9.0

#6793 Fix runtime error reporting in Otel manager
  internal/pkg/otel/manager/manager.go
  internal/pkg/otel/manager/manager_test.go
Labels: bug, Team:Elastic-Agent-Control-Plane, skip-changelog, backport-8.x, backport-active-9

#5619 Make running windows in the CI with faster instances
  pkg/testing/ogc/supported.go
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog, backport-8.x

#6325 [CI] Backport buildkite integration tests from main to 8.16
  .buildkite/bk.integration.pipeline.yml
  .buildkite/hooks/pre-command
  .buildkite/hooks/pre-command.ps1
  .buildkite/integration.pipeline.yml
  .buildkite/pipeline.yml
  .buildkite/scripts/install-go.ps1
  .buildkite/scripts/integration-tests.ps1
  .buildkite/scripts/steps/ess_start.sh
  .buildkite/scripts/steps/integration_tests_tf.sh
  .buildkite/scripts/steps/integration_tests_tf_sudo.sh
  .buildkite/scripts/sudo-integration-tests.sh
  .tool-versions
  docs/test-framework-dev-guide.md
  test_infra/ess/deployment.tf
Labels: backport, skip-changelog, Team:Ingest-EngProd

#6833 Bump .package-version
  .package-version
Labels: enhancement, backport-skip, skip-changelog

#6719 [CI] Remove instances configurations from the integration test stack
  .buildkite/pipeline.yml
  test_infra/ess/deployment.tf
Labels: enhancement, Team:Elastic-Agent-Control-Plane, skip-changelog, Team:Ingest-EngProd, backport-active-all

#6724 [k8s] Correct agent image repository
  deploy/helm/edot-collector/kube-stack/values.yaml
  deploy/helm/elastic-agent/README.md
  deploy/helm/elastic-agent/examples/eck/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/fleet-managed-ksm-sharding/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/fleet-managed/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/kubernetes-default/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/kubernetes-hints-autodiscover/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/kubernetes-ksm-sharding/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/kubernetes-only-logs/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/multiple-integrations/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/netflow-service/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/nginx-custom-integration/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/system-custom-auth-paths/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/user-cluster-role/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/user-service-account/rendered/manifest.yaml
  deploy/helm/elastic-agent/values.yaml
  deploy/kubernetes/elastic-agent-kustomize/default/elastic-agent-managed/base/elastic-agent-managed-daemonset.yaml
  deploy/kubernetes/elastic-agent-kustomize/default/elastic-agent-standalone/base/elastic-agent-standalone-daemonset.yaml
  deploy/kubernetes/elastic-agent-kustomize/ksm-autosharding/elastic-agent-managed/base/elastic-agent-managed-daemonset.yaml
  deploy/kubernetes/elastic-agent-kustomize/ksm-autosharding/elastic-agent-managed/extra/elastic-agent-managed-statefulset.yaml
  deploy/kubernetes/elastic-agent-kustomize/ksm-autosharding/elastic-agent-standalone/base/elastic-agent-standalone-daemonset.yaml
  deploy/kubernetes/elastic-agent-kustomize/ksm-autosharding/elastic-agent-standalone/extra/elastic-agent-standalone-statefulset.yaml
  deploy/kubernetes/elastic-agent-kustomize/ksm-hints/elastic-agent-standalone/kustomization.yaml
  deploy/kubernetes/elastic-agent-kustomize/ksm-hints/elastic-agent-standalone/kustomization.yaml.original
  deploy/kubernetes/elastic-agent-managed-kubernetes.yaml
  deploy/kubernetes/elastic-agent-managed/elastic-agent-managed-daemonset.yaml
  deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml
  deploy/kubernetes/elastic-agent-standalone/elastic-agent-standalone-daemonset.yaml
  dev-tools/packaging/packages.yml
  docs/local-k8s-testing.md
  internal/pkg/otel/README.md
  internal/pkg/otel/templates/README.md.tmpl
  pkg/testing/kubernetes/supported.go
  skaffold.yaml
Labels: bug, skip-changelog, backport-8.x, backport-8.16, backport-8.17, backport-8.18, backport-9.0

#6349 [CI] Integration tests regrouping
  .buildkite/bk.integration.pipeline.yml
  pkg/testing/tools/fleettools/fleet.go
  testing/integration/endpoint_security_test.go
  testing/integration/groups_test.go
  testing/integration/install_test.go
  testing/integration/upgrade_standalone_test.go
Labels: enhancement, skip-changelog, Team:Ingest-EngProd, backport-8.x, backport-8.16, backport-8.17, backport-8.18, backport-9.0

#6619 enhancement(5423): added logic to replaces scheduler with long-wait scheduler in case of exceeded unauth response limit
  changelog/fragments/1738199968-update-scheduler-when-received-too-many-unathorized-responses.yaml
  internal/pkg/agent/application/gateway/fleet/fleet_gateway.go
  internal/pkg/agent/application/gateway/fleet/fleet_gateway_test.go
  internal/pkg/scheduler/scheduler.go
Labels: Team:Elastic-Agent-Control-Plane, backport-8.x

#6825 Windows: Fix Windows job assignment to work on Go 1.23+
  changelog/fragments/1739375044-windows-change-how-process-handles-are-obtained-when-assigning-sub-processes-to-Job-objects..yaml
  pkg/core/process/external_windows.go
  pkg/core/process/job_windows.go
  pkg/testing/fixture_install.go
  pkg/testing/tools/check/check.go
  pkg/testing/tools/tools.go
  testing/integration/logs_ingestion_test.go
  testing/integration/upgrade_fleet_test.go
Labels: Team:Elastic-Agent-Data-Plane, backport-active-9, backport-active-8

#6804 Better error handling for flavor detection
  internal/pkg/agent/application/upgrade/step_unpack.go
  internal/pkg/agent/install/flavors.go
  testing/integration/upgrade_gpg_test.go
  testing/integration/upgrade_standalone_retry_test.go
  testing/integration/upgrade_standalone_same_commit_test.go
Labels: bug, Team:Elastic-Agent-Control-Plane, skip-changelog, backport-active-9

#6681 otel: add test for document equivalence between agent filestream input and filebeat receiver
  pkg/testing/fixture.go
  testing/integration/otel_test.go
Labels: Team:Elastic-Agent-Data-Plane, Cleanup, skip-changelog, backport-8.x, backport-9.0

#6869 ci: update version in k8s manifests and skip flaky TestSetLogLevelFleetManaged
  deploy/helm/edot-collector/kube-stack/values.yaml
  deploy/helm/elastic-agent/Chart.yaml
  deploy/helm/elastic-agent/examples/eck/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/fleet-managed/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/kubernetes-default/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/kubernetes-hints-autodiscover/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/kubernetes-only-logs/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/multiple-integrations/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/nginx-custom-integration/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/system-custom-auth-paths/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/user-cluster-role/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/user-service-account/rendered/manifest.yaml
  deploy/helm/elastic-agent/values.yaml
  deploy/kubernetes/elastic-agent-kustomize/default/elastic-agent-managed/base/elastic-agent-managed-daemonset.yaml
  deploy/kubernetes/elastic-agent-kustomize/default/elastic-agent-standalone/base/elastic-agent-standalone-daemonset.yaml
  deploy/kubernetes/elastic-agent-kustomize/ksm-autosharding/elastic-agent-managed/base/elastic-agent-managed-daemonset.yaml
  deploy/kubernetes/elastic-agent-kustomize/ksm-autosharding/elastic-agent-managed/extra/elastic-agent-managed-statefulset.yaml
  deploy/kubernetes/elastic-agent-kustomize/ksm-autosharding/elastic-agent-standalone/base/elastic-agent-standalone-daemonset.yaml
  deploy/kubernetes/elastic-agent-kustomize/ksm-autosharding/elastic-agent-standalone/extra/elastic-agent-standalone-statefulset.yaml
  deploy/kubernetes/elastic-agent-kustomize/ksm-hints/elastic-agent-standalone/kustomization.yaml
  deploy/kubernetes/elastic-agent-managed-kubernetes.yaml
  deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml
  testing/integration/log_level_test.go
Labels: Team:Elastic-Agent-Control-Plane, flaky-test, skip-changelog

#6727 Fail install in case Fleet Server flags are used and `--install-server` flag is missing
  internal/pkg/agent/cmd/install.go
Labels: bug, Team:Elastic-Agent-Control-Plane, skip-changelog, backport-active-9

#6870 [CI] New upgrade-flavor test group for TestStandaloneUpgrade_Flavor tests
  .buildkite/bk.integration.pipeline.yml
  testing/integration/groups_test.go
  testing/integration/upgrade_standalone_flavors_test.go
Labels: enhancement, Team:Elastic-Agent-Control-Plane, skip-changelog, Team:Ingest-EngProd, backport-9.0

#6871 mage: run mage update steps in parallel
  magefile.go
Labels: Team:Elastic-Agent-Data-Plane, Cleanup, skip-changelog, backport-8.x, backport-9.0

#6640 Update config to reflect `degrade_on_partial`
  _meta/config/common.p2.yml.tmpl
  _meta/config/common.reference.p2.yml.tmpl
  _meta/elastic-agent.yml
  elastic-agent.reference.yml
  elastic-agent.yml
Labels: enhancement, Team:Elastic-Agent-Control-Plane, skip-changelog, backport-8.x, backport-9.0

#6894 Add a test for empty local provider
  internal/pkg/composable/controller_test.go
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog, Testing, backport-8.x, backport-8.18, backport-9.0

#6803 Add statePersistence value to helm chart presets
  deploy/helm/elastic-agent/examples/eck/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/netflow-service/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/nginx-custom-integration/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/user-cluster-role/rendered/manifest.yaml
  deploy/helm/elastic-agent/templates/agent/_helpers.tpl
  deploy/helm/elastic-agent/templates/agent/eck/_pod_template.yaml
  deploy/helm/elastic-agent/templates/agent/k8s/_pod_template.yaml
  deploy/helm/elastic-agent/values.schema.json
  deploy/helm/elastic-agent/values.yaml
Labels: enhancement, Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent, skip-changelog

#5309 feat: bump go to 1.23.6
  .buildkite/pipeline.yml
  .github/workflows/bump-agent-versions.yml
  .go-version
  .golangci.yml
  .tool-versions
  Dockerfile
  Dockerfile.skaffold
  Makefile
  changelog/fragments/1723829102-Upgrade-to-Go-1.23.0.yaml
  go.mod
  pkg/testing/runner/runner_test.go
  version/docs/version.asciidoc
Labels: enhancement, Team:Elastic-Agent-Control-Plane, backport-8.x, backport-8.18, backport-9.0

#6948 Use newer multiarch support for DRA packaging in ARM
  .buildkite/pipeline.elastic-agent-package.yml
Labels: skip-changelog, backport-8.x, backport-8.18, backport-9.0

#6927 Fix deadlock in error handling in OTelManager
  changelog/fragments/1739981369-Fix-deadlock-in-OTelManager.yaml
  internal/pkg/otel/manager/manager.go
  internal/pkg/otel/manager/manager_test.go
Labels: Team:Elastic-Agent-Control-Plane, backport-active-9, backport-active-8

#6630 [Managed OTLP] Add Host/K8s onboarding configurations
  changelog/fragments/1739544282-add-MOtel-sample-configurations.yaml
  deploy/helm/edot-collector/kube-stack/managed_otlp/values.yaml
  internal/pkg/otel/samples/darwin/managed_otlp/logs_metrics_traces.yml
  internal/pkg/otel/samples/darwin/managed_otlp/platformlogs.yml
  internal/pkg/otel/samples/darwin/managed_otlp/platformlogs_hostmetrics.yml
  internal/pkg/otel/samples/linux/managed_otlp/logs_metrics_traces.yml
  internal/pkg/otel/samples/linux/managed_otlp/platformlogs.yml
  internal/pkg/otel/samples/linux/managed_otlp/platformlogs_hostmetrics.yml
  magefile.go
  testing/integration/otel_helm_test.go
Labels: Team:Elastic-Agent-Control-Plane, backport-8.x, backport-8.18, backport-9.0

#6980 Allow PR comments for failures from the elastic-agent pipeline
  catalog-info.yaml
Labels: backport-skip, skip-changelog, ci

#6971 [CI] Windows 2025 integration tests
  .buildkite/bk.integration.pipeline.yml
  .buildkite/pipeline.yml
Labels: enhancement, skip-changelog, Team:Ingest-EngProd, backport-active-all

#6966 Fix config used in Otel manager test
  internal/pkg/otel/manager/manager_test.go
Labels: Team:Elastic-Agent-Control-Plane, Cleanup, skip-changelog, Testing, backport-8.x, backport-8.18, backport-active-9

#7009 Add missing null checks to AST methods
  changelog/fragments/1740485771-ast-null-checks.yaml
  internal/pkg/agent/transpiler/ast.go
  internal/pkg/agent/transpiler/ast_test.go
Labels: bug, Team:Elastic-Agent-Control-Plane, backport-active-all

#7011 fix: set gateway k8s replicas spec
  changelog/fragments/1740492672-set-replicas-for-gateway-collector.yaml
  deploy/helm/edot-collector/kube-stack/managed_otlp/values.yaml
  testing/integration/otel_helm_test.go
Labels: backport-8.x, backport-8.17, backport-8.18, backport-9.0

#6578 Fix selection of testing version
  testing/integration/testdata/.upgrade-test-agent-versions.yml
  testing/upgradetest/versions.go
Labels: bug, Team:Elastic-Agent-Control-Plane, skip-changelog, backport-active-all

#6973 Fix warning on emitting diagnostics for otel hybrid mode
  internal/pkg/diagnostics/diagnostics.go
  internal/pkg/diagnostics/diagnostics_test.go
Labels: bug, Team:Elastic-Agent-Control-Plane, skip-changelog, backport-8.x, backport-8.17, backport-8.18, backport-active-9

#7061 pin stack version
  .package-version
  pkg/testing/ess/create_deployment_csp_configuration.yaml
  pkg/testing/ess/create_deployment_request.tmpl.json
  pkg/testing/ess/deployment.go
  pkg/testing/ess/deployment_test.go
  test_infra/ess/deployment.tf
Labels: skip-changelog

#6958 Fix panic on fetch provider initialization
  internal/pkg/composable/context.go
  internal/pkg/composable/controller.go
  internal/pkg/composable/controller_test.go
  internal/pkg/composable/dynamic.go
  internal/pkg/composable/registry.go
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog, backport-8.x, backport-8.18, backport-9.0

#7049 Add http response status checks to TestSetLogLevelFleetManaged
  testing/integration/log_level_test.go
Labels: bug, flaky-test, skip-changelog

#6565 FIPS Build
  .buildkite/integration.pipeline.yml
  dev-tools/mage/build.go
  dev-tools/mage/build_test.go
  dev-tools/mage/crossbuild.go
  dev-tools/mage/dockerbuilder.go
  dev-tools/mage/gotest.go
  dev-tools/mage/pkg.go
  dev-tools/mage/pkgtypes.go
  dev-tools/mage/settings.go
  dev-tools/packaging/package_test.go
  internal/pkg/release/version.go
  internal/pkg/release/version_test.go
  magefile.go
Labels: Team:Elastic-Agent-Control-Plane, technical debt, skip-changelog, backport-8.x, backport-8.18

#6982 Automatic retry for all steps prone to flakiness
  .buildkite/bk.integration.pipeline.yml
  .buildkite/integration.pipeline.yml
  .buildkite/pipeline.yml
Labels: skip-changelog, ci, backport-8.x, backport-8.17, backport-8.18, backport-9.0

#7012 [flakiness]: List agents by hostname and policy id
  pkg/testing/tools/fleettools/fleet.go
Labels: Team:Elastic-Agent-Control-Plane, flaky-test, skip-changelog, backport-active-all

#6997 Remove unnecessary loop variable copies
  .golangci.yml
  internal/pkg/agent/application/monitoring/processes_cloud_test.go
  internal/pkg/eql/eql_test.go
  internal/pkg/otel/configtranslate/otelconfig.go
  testing/fleetservertest/server.go
Labels: Team:Elastic-Agent-Control-Plane, Cleanup, skip-changelog, backport-8.x

#7036 fix(ipv6): do not build malformed enroll url with ipv6 host
  changelog/fragments/1740712347-support-ipv6-enroll-url.yaml
  internal/pkg/agent/cmd/enroll_cmd.go
Labels: bug, Team:Elastic-Agent-Control-Plane, backport-active-all

#7035 fix(ipv6): support ipv6 address in grpc config
  changelog/fragments/1740712540-support-grpc-ipv6-host.yaml
  internal/pkg/agent/configuration/grpc.go
  internal/pkg/agent/configuration/grpc_test.go
  pkg/component/runtime/manager.go
Labels: bug, Team:Elastic-Agent-Control-Plane, backport-active-all

#6902 [CI] [Integration tests] Enable ARM tests for common test groups
  .buildkite/bk.integration.pipeline.yml
Labels: enhancement, skip-changelog, Team:Ingest-EngProd, backport-active-all
