Repository elastic/elastic-agent, pull requests merged in 2025-06, with the labels that each got.

#8279 feat: introduce new mage tidy target
  .ci/scripts/otel-update.sh
  README.md
  dev-tools/mage/target/common/check.go
  dev-tools/mage/target/common/notice.go
  dev-tools/mage/target/common/tidy.go
  dev-tools/mage/target/update/update.go
  wrapper/windows/archive-proxy/go.mod
  wrapper/windows/archive-proxy/go.sum
Labels: skip-changelog, backport-active-all

#8278 [ci] fix update versions
  testing/upgradetest/versions.go
  testing/upgradetest/versions_test.go
Labels: skip-changelog, backport-active-all

#8237 Changelog for 8.17.7
  changelog/8.17.7.asciidoc
  changelog/8.17.7.yaml
  changelog/fragments/1745923884-deb-rpm-preserve-run-state.yaml
  changelog/fragments/1746652545-Upgrade-to-Go-1.24.3..yaml
Labels: skip-changelog

#7931 [ci] migrate extended runtime leak tests to buildkite
  .buildkite/bk.integration.pipeline.yml
  .buildkite/integration.pipeline.yml
  .buildkite/scripts/buildkite-integration-tests.sh
  .buildkite/scripts/integration-tests.ps1
  .buildkite/scripts/steps/integration_tests_tf.sh
Labels: skip-changelog, backport-active-all

#8320 ci: update all n1-standard-8 type runners to n2-standard-8
  .buildkite/bk.integration.pipeline.yml
  .buildkite/pipeline.elastic-agent-helm-charts.yml
  .buildkite/pipeline.integration-test-matrix.yml
Labels: skip-changelog, backport-active-all

#8211 ci: reproducible builds using pinned VM images
  .buildkite/bk.integration.pipeline.yml
  .buildkite/pipeline.yml
  .ci/updatecli/updatecli-bump-vm-images.yml
  .github/workflows/bump-vm-images.yml
Labels: skip-changelog, backport-active-all

#8312 github-actions: pin mage action and use fixed version
  .github/workflows/bump-agent-versions.yml
  .github/workflows/bump-beats-version.yml
  .github/workflows/post-dependabot.yml
Labels: skip-changelog, backport-active-9

#8339 fix: proper time constraints in TestWatcher_PIDChangeSuccess unit test
  internal/pkg/agent/application/upgrade/watcher_test.go
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog, backport-active-all

#8374 fix: increase context timeout to accommodate for slower machines in Test_checkForUnprivilegedVault
  internal/pkg/agent/install/uninstall_test.go
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog, backport-active-all

#8035 Add Pipeline to deploy custom agent image for FIPS testing
  .buildkite/bk.integration-fips.pipeline.yml
  .buildkite/hooks/pre-command
  .buildkite/integration.pipeline.yml
  .buildkite/scripts/buildkite-integration-tests.sh
  .ci/updatecli/updatecli-bump-vm-images.yml
  .tool-versions
  magefile.go
  testing/integration/fleetserver_fips_test.go
Labels: enhancement, Team:Elastic-Agent-Control-Plane, skip-changelog, backport-8.19

#8418 Fix pre-command to support extended testing
  .buildkite/hooks/pre-command
Labels: skip-changelog, ci, backport-8.19

#8421 `TestFIPSAgentConnectingToFIPSFleetServerInECHFRH `: Use `require.Eventually` to try and address flakiness
  testing/integration/fleetserver_fips_test.go
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog, backport-8.19

#8365 buildkite(scripts): refactor common scripts
  .buildkite/scripts/common.sh
  .buildkite/scripts/common2.sh
  .buildkite/scripts/steps/ess_down.sh
  .buildkite/scripts/steps/ess_start.sh
  .buildkite/scripts/steps/integration_tests_tf.sh
Labels: skip-changelog, backport-active-all

#8254 Lock upgrade marker
  changelog/fragments/1749470526-lock-update-marker.yaml
  internal/pkg/agent/application/filelock/app_locker.go
  internal/pkg/agent/application/filelock/app_locker_test.go
  internal/pkg/agent/application/filelock/file_locker.go
  internal/pkg/agent/application/filelock/file_locker_test.go
  internal/pkg/agent/application/filelock/testlocker/.gitignore
  internal/pkg/agent/application/filelock/testlocker/main.go
  internal/pkg/agent/application/upgrade/marker_access_other.go
  internal/pkg/agent/application/upgrade/marker_access_windows.go
  internal/pkg/agent/application/upgrade/step_mark.go
  internal/pkg/agent/application/upgrade/step_mark_test.go
  magefile.go
Labels: enhancement, Team:Elastic-Agent-Control-Plane, backport-skip

#8448 fix(ci): add missing install Mage step
  .github/workflows/bump-otel-version.yml
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog, ci, backport-8.19

#8359 updatecli: create PRs per active branch and refactor slack notifications
  .ci/updatecli/updatecli-bump-vm-images.yml
  .github/workflows/bump-vm-images.yml
  .mergify.yml
Labels: backport-skip, skip-changelog

#8338 Add filebeat_input to beat receiver agent monitoring integration test
  internal/pkg/agent/application/monitoring/testdata/monitoring_config_full.yaml
  internal/pkg/agent/application/monitoring/v1_monitor.go
  internal/pkg/agent/application/monitoring/v1_monitor_test.go
  testing/integration/beat_receivers_test.go
  testing/integration/otel_test.go
Labels: Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent-Data-Plane, skip-changelog, backport-8.19

#7995 Enable Filebeat's Journald input in some docker image variants
  changelog/fragments/1745609163-journalctl-on-all-docker-variants.yaml
  dev-tools/packaging/settings.go
  dev-tools/packaging/templates/docker/Dockerfile.elastic-agent.tmpl
  magefile.go
  testing/integration/journald_test.go
  testing/integration/kubernetes_agent_standalone_test.go
  testing/integration/testdata/journald-input.yml
  testing/integration/testdata/journald-otel.yml
Labels: Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent-Data-Plane, backport-8.18

#8468 mergify: support auto-merge for bk.integration-fips.pipeline.yml
  .mergify.yml
Labels: backport-skip, skip-changelog

#8466 github-actions: updatecli bump for specific branches
  .github/workflows/bump-vm-images.yml
Labels: backport-skip, skip-changelog

#8479 Uncomment status verfication for FIPS test
  testing/integration/fleetserver_fips_test.go
Labels: skip-changelog, Testing, backport-8.19

#7804 [Integration Test] Ensure that upgrading a FIPS-capable Agent results in a FIPS-capable Agent
  internal/pkg/agent/application/upgrade/artifact/artifact_test.go
  internal/pkg/agent/application/upgrade/step_unpack.go
  internal/pkg/agent/application/upgrade/step_unpack_test.go
  internal/pkg/agent/application/upgrade/upgrade.go
  internal/pkg/agent/cmd/enroll_cmd.go
  pkg/control/v2/client/client.go
  pkg/testing/define/define.go
  pkg/testing/fetcher_local.go
  pkg/testing/fetcher_local_test.go
  pkg/testing/fixture.go
  pkg/version/version_parser.go
  pkg/version/version_parser_test.go
  testing/integration/beats_serverless_test.go
  testing/integration/upgrade_fleet_test.go
  testing/integration/upgrade_standalone_test.go
  testing/upgradetest/upgrader.go
  testing/upgradetest/versions.go
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog, Testing, backport-8.19

#8474 [otel] Update EDOT SDK k8s auto-instrumentation images to their latest versions
  deploy/helm/edot-collector/kube-stack/managed_otlp/values.yaml
  deploy/helm/edot-collector/kube-stack/values.yaml
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog, backport-active-9, backport-active-8

#8497 Explicitly crossbuild linux/arm with debian11.
  changelog/fragments/1749844873-Use-Debian-11-for-linux-arm-to-match-linux-amd64.yaml
  dev-tools/mage/crossbuild.go
Labels: Team:Elastic-Agent-Control-Plane, backport-active-all

#8263 ci(serverless): use OIDC for running the serverless ITs
  .buildkite/bk.integration.pipeline.yml
  .buildkite/integration.pipeline.yml
  .github/workflows/serverless-project.yml
  docs/test-framework-dev-guide.md
Labels: skip-changelog, backport-active-all

#8542 [CI] Add exclusions for release branches
  .ci/updatecli/updatecli-bump-stack-version.yml
  .github/workflows/bump-stable-snapshot.yml
Labels: enhancement, backport-skip, skip-changelog

#8451 [8.19][Synthetics] Revert base image rename from ubuntu to ubi
  dev-tools/packaging/templates/docker/Dockerfile.elastic-agent.tmpl
Labels: bug, backport-skip, skip-changelog, Team:obs-ds-hosted-services

#8559 `TestGetArtifactName`: Add test case + cleanup unused fields
  internal/pkg/agent/application/upgrade/artifact/artifact_test.go
Labels: Team:Elastic-Agent-Control-Plane, Cleanup, skip-changelog, Testing, backport-8.19

#8450 [Synthetics] Revert base image rename from ubuntu to ubi
  dev-tools/packaging/templates/docker/Dockerfile.elastic-agent.tmpl
Labels: bug, Team:Elastic-Agent-Control-Plane, backport-skip, skip-changelog, Team:obs-ds-hosted-services

#8435 Fix non-otel component status being incorrectly deleted
  internal/pkg/agent/application/coordinator/coordinator.go
  internal/pkg/agent/application/coordinator/coordinator_unit_test.go
  internal/pkg/otel/translate/status.go
  internal/pkg/otel/translate/status_test.go
Labels: bug, Team:Elastic-Agent-Control-Plane, skip-changelog, backport-8.19

#8583 Set force in update-beats scm configuration.
  .ci/updatecli/update-beats.yml
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog, backport-8.19

#6907 Enhancement/6394 allow deb rpm to upgrade with endpoint tamper protection
  changelog/fragments/1740166208-allow-deb-rpm-upgrade-with-tamper-protected-endpoint.yaml
  dev-tools/packaging/templates/linux/postinstall.sh.tmpl
  dev-tools/packaging/templates/linux/preinstall.sh.tmpl
  pkg/testing/fixture.go
  pkg/testing/fixture_install.go
  pkg/testing/tools/tools.go
  testing/integration/endpoint_security_test.go
Labels: Team:Elastic-Agent-Control-Plane, backport-8.18, backport-9.0, backport-8.19

#8625 [ci] otel k8s integration tests
  testing/integration/k8s/kubernetes_agent_standalone_test.go
Labels: Team:Elastic-Agent-Control-Plane, backport-skip, skip-changelog

#8638 [9.0] Revert "Enhancement/6394 allow deb rpm to upgrade with endpoint tamper protection"
  changelog/fragments/1740166208-allow-deb-rpm-upgrade-with-tamper-protected-endpoint.yaml
  dev-tools/packaging/templates/linux/postinstall.sh.tmpl
  dev-tools/packaging/templates/linux/preinstall.sh.tmpl
  pkg/testing/fixture.go
  pkg/testing/fixture_install.go
  pkg/testing/tools/tools.go
  testing/integration/endpoint_security_test.go
Labels: skip-changelog

#8637 [deb/rpm] restart endpoint with tamper protection after elastic-agent
  dev-tools/packaging/templates/linux/postinstall.sh.tmpl
  testing/integration/endpoint_security_test.go
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog, backport-8.19

#8422 Attempt to make test more reliable by querying ES directly
  testing/integration/ess/fleetserver_fips_test.go
Labels: Team:Elastic-Agent-Control-Plane, flaky-test, skip-changelog, backport-8.19

#8648 Changelog for 8.18.3
  changelog/8.18.3.asciidoc
  changelog/8.18.3.yaml
  changelog/fragments/1745609163-journalctl-on-all-docker-variants.yaml
  changelog/fragments/1747938268-fix-diag-race-condition.yaml
  changelog/fragments/1749176965-add-cumulativetodeltaprocessor.yaml
  changelog/fragments/1749742685-Use-paths.TempDir-for-diagnostics-actions.yaml
  changelog/fragments/1749844873-Use-Debian-11-for-linux-arm-to-match-linux-amd64.yaml
  changelog/fragments/1749923633-Windows-relax-file-ownership-check-for-re-enrollment.yaml
Labels: skip-changelog

#8647 Changelog for 8.17.8
  changelog/8.17.8.asciidoc
  changelog/8.17.8.yaml
  changelog/fragments/1747938268-fix-diag-race-condition.yaml
  changelog/fragments/1749176965-add-cumulativetodeltaprocessor.yaml
  changelog/fragments/1749742685-Use-paths.TempDir-for-diagnostics-actions.yaml
  changelog/fragments/1749844873-Use-Debian-11-for-linux-arm-to-match-linux-amd64.yaml
  changelog/fragments/1749923633-Windows-relax-file-ownership-check-for-re-enrollment.yaml
Labels: skip-changelog

#8585 [Release] Bump version to 9.0.4
  deploy/helm/edot-collector/kube-stack/managed_otlp/values.yaml
  deploy/helm/edot-collector/kube-stack/values.yaml
  deploy/helm/elastic-agent/Chart.yaml
  deploy/helm/elastic-agent/examples/eck/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/fleet-managed-certificates/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/fleet-managed-ksm-sharding/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/fleet-managed/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/kubernetes-custom-output/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/kubernetes-default/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/kubernetes-hints-autodiscover/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/kubernetes-ksm-sharding/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/kubernetes-only-logs/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/multiple-integrations/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/netflow-service/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/nginx-custom-integration/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/priority-class/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/system-custom-auth-paths/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/user-cluster-role/rendered/manifest.yaml
  deploy/helm/elastic-agent/examples/user-service-account/rendered/manifest.yaml
  deploy/helm/elastic-agent/values.yaml
  deploy/kubernetes/elastic-agent-kustomize/default/elastic-agent-managed/base/elastic-agent-managed-daemonset.yaml
  deploy/kubernetes/elastic-agent-kustomize/default/elastic-agent-standalone/base/elastic-agent-standalone-daemonset.yaml
  deploy/kubernetes/elastic-agent-kustomize/ksm-autosharding/elastic-agent-managed/base/elastic-agent-managed-daemonset.yaml
  deploy/kubernetes/elastic-agent-kustomize/ksm-autosharding/elastic-agent-managed/extra/elastic-agent-managed-statefulset.yaml
  deploy/kubernetes/elastic-agent-kustomize/ksm-autosharding/elastic-agent-standalone/base/elastic-agent-standalone-daemonset.yaml
  deploy/kubernetes/elastic-agent-kustomize/ksm-autosharding/elastic-agent-standalone/extra/elastic-agent-standalone-statefulset.yaml
  deploy/kubernetes/elastic-agent-kustomize/ksm-hints/elastic-agent-standalone/kustomization.yaml
  deploy/kubernetes/elastic-agent-managed-kubernetes.yaml
  deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml
  version/version.go
Labels: Team:Elastic-Agent-Control-Plane, release, skip-changelog

#8710 [CI][FIPS] Remove unnecessary env vars from FIPS build pipeline steps
  .buildkite/bk.integration-fips.pipeline.yml
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog, backport-8.19

#8417 Integration Test: upgrade Integrations Server in ECH
  .buildkite/bk.integration-fips.pipeline.yml
  .ci/updatecli/updatecli-bump-stack-version.yml
  .github/workflows/bump-agent-versions.sh
  .mergify.yml
  pkg/testing/common/stack.go
  pkg/testing/ess/client.go
  pkg/testing/ess/deployment.go
  pkg/testing/ess/deployment_csp_configuration.yaml
  pkg/testing/ess/deployment_test.go
  pkg/testing/ess/serverless_provisioner.go
  pkg/testing/ess/statful_provisioner.go
  pkg/testing/ess/upgrade_deployment_request.tmpl.json
  pkg/testing/runner/runner_test.go
  test_infra/ess/deployment.tf
  test_infra/ess/readme.md
  testing/integration/ess/upgrade_fleet_test.go
  testing/integration/ess/upgrade_integrations_server_test.go
  testing/integration/groups.go
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog, backport-8.19, Testing:run:TestUpgradeIntegrationsServer

#8746 ci: revert deployment_csp_configuration.yaml to create_deployment_csp_configuration.yaml
  .ci/updatecli/updatecli-bump-stack-version.yml
  .mergify.yml
  pkg/testing/ess/create_deployment_csp_configuration.yaml
  pkg/testing/ess/deployment.go
  test_infra/ess/deployment.tf
  test_infra/ess/readme.md
Labels: Team:Elastic-Agent-Control-Plane, skip-changelog, backport-8.19, backport-9.1
